// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package server

import (
	"context"
	"sync"

	hookCore "github.com/oxynote/oxynote/server/core/internal/document/hook"
	"github.com/oxynote/oxynote/server/core/internal/document/hook/manager"
	"github.com/rs/xid"
)

// Ensure, that HookManagerMock does implement HookManager.
// If this is not the case, regenerate this file with moq.
var _ HookManager = &HookManagerMock{}

// HookManagerMock is a mock implementation of HookManager.
//
//	func TestSomethingThatUsesHookManager(t *testing.T) {
//
//		// make and configure a mocked HookManager
//		mockedHookManager := &HookManagerMock{
//			CopyHooksFunc: func(ctx context.Context, tx manager.CopyTx, fromBranchID xid.ID, toBranchID xid.ID, documentID xid.ID, organizationID string, uids map[string]string) error {
//				panic("mock out the CopyHooks method")
//			},
//			CreateHookFunc: func(ctx context.Context, ci hookCore.CreateInput, documentID xid.ID, organizationID string, updatedBy string) (*hookCore.Hook, error) {
//				panic("mock out the CreateHook method")
//			},
//			DeleteHookFunc: func(ctx context.Context, id xid.ID, organizationID string, updatedBy string) error {
//				panic("mock out the DeleteHook method")
//			},
//			OnHookChangeFunc: func(fn func(hookCore.Hook)) func() {
//				panic("mock out the OnHookChange method")
//			},
//			ProcessBranchFunc: func(branchID xid.ID, organizationID string)  {
//				panic("mock out the ProcessBranch method")
//			},
//			ResetHookFunc: func(ctx context.Context, id xid.ID, organizationID string) (*hookCore.Hook, error) {
//				panic("mock out the ResetHook method")
//			},
//			UpdateHookFunc: func(ctx context.Context, id xid.ID, organizationID string, ui hookCore.UpdateInput, updatedBy string) (*hookCore.Hook, error) {
//				panic("mock out the UpdateHook method")
//			},
//		}
//
//		// use mockedHookManager in code that requires HookManager
//		// and then make assertions.
//
//	}
type HookManagerMock struct {
	// CopyHooksFunc mocks the CopyHooks method.
	CopyHooksFunc func(ctx context.Context, tx manager.CopyTx, fromBranchID xid.ID, toBranchID xid.ID, documentID xid.ID, organizationID string, uids map[string]string) error

	// CreateHookFunc mocks the CreateHook method.
	CreateHookFunc func(ctx context.Context, ci hookCore.CreateInput, documentID xid.ID, organizationID string, updatedBy string) (*hookCore.Hook, error)

	// DeleteHookFunc mocks the DeleteHook method.
	DeleteHookFunc func(ctx context.Context, id xid.ID, organizationID string, updatedBy string) error

	// OnHookChangeFunc mocks the OnHookChange method.
	OnHookChangeFunc func(fn func(hookCore.Hook)) func()

	// ProcessBranchFunc mocks the ProcessBranch method.
	ProcessBranchFunc func(branchID xid.ID, organizationID string)

	// ResetHookFunc mocks the ResetHook method.
	ResetHookFunc func(ctx context.Context, id xid.ID, organizationID string) (*hookCore.Hook, error)

	// UpdateHookFunc mocks the UpdateHook method.
	UpdateHookFunc func(ctx context.Context, id xid.ID, organizationID string, ui hookCore.UpdateInput, updatedBy string) (*hookCore.Hook, error)

	// calls tracks calls to the methods.
	calls struct {
		// CopyHooks holds details about calls to the CopyHooks method.
		CopyHooks []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Tx is the tx argument value.
			Tx manager.CopyTx
			// FromBranchID is the fromBranchID argument value.
			FromBranchID xid.ID
			// ToBranchID is the toBranchID argument value.
			ToBranchID xid.ID
			// DocumentID is the documentID argument value.
			DocumentID xid.ID
			// OrganizationID is the organizationID argument value.
			OrganizationID string
			// Uids is the uids argument value.
			Uids map[string]string
		}
		// CreateHook holds details about calls to the CreateHook method.
		CreateHook []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Ci is the ci argument value.
			Ci hookCore.CreateInput
			// DocumentID is the documentID argument value.
			DocumentID xid.ID
			// OrganizationID is the organizationID argument value.
			OrganizationID string
			// UpdatedBy is the updatedBy argument value.
			UpdatedBy string
		}
		// DeleteHook holds details about calls to the DeleteHook method.
		DeleteHook []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID xid.ID
			// OrganizationID is the organizationID argument value.
			OrganizationID string
			// UpdatedBy is the updatedBy argument value.
			UpdatedBy string
		}
		// OnHookChange holds details about calls to the OnHookChange method.
		OnHookChange []struct {
			// Fn is the fn argument value.
			Fn func(hookCore.Hook)
		}
		// ProcessBranch holds details about calls to the ProcessBranch method.
		ProcessBranch []struct {
			// BranchID is the branchID argument value.
			BranchID xid.ID
			// OrganizationID is the organizationID argument value.
			OrganizationID string
		}
		// ResetHook holds details about calls to the ResetHook method.
		ResetHook []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID xid.ID
			// OrganizationID is the organizationID argument value.
			OrganizationID string
		}
		// UpdateHook holds details about calls to the UpdateHook method.
		UpdateHook []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID xid.ID
			// OrganizationID is the organizationID argument value.
			OrganizationID string
			// UI is the ui argument value.
			UI hookCore.UpdateInput
			// UpdatedBy is the updatedBy argument value.
			UpdatedBy string
		}
	}
	lockCopyHooks     sync.RWMutex
	lockCreateHook    sync.RWMutex
	lockDeleteHook    sync.RWMutex
	lockOnHookChange  sync.RWMutex
	lockProcessBranch sync.RWMutex
	lockResetHook     sync.RWMutex
	lockUpdateHook    sync.RWMutex
}

// CopyHooks calls CopyHooksFunc.
func (mock *HookManagerMock) CopyHooks(ctx context.Context, tx manager.CopyTx, fromBranchID xid.ID, toBranchID xid.ID, documentID xid.ID, organizationID string, uids map[string]string) error {
	callInfo := struct {
		Ctx            context.Context
		Tx             manager.CopyTx
		FromBranchID   xid.ID
		ToBranchID     xid.ID
		DocumentID     xid.ID
		OrganizationID string
		Uids           map[string]string
	}{
		Ctx:            ctx,
		Tx:             tx,
		FromBranchID:   fromBranchID,
		ToBranchID:     toBranchID,
		DocumentID:     documentID,
		OrganizationID: organizationID,
		Uids:           uids,
	}
	mock.lockCopyHooks.Lock()
	mock.calls.CopyHooks = append(mock.calls.CopyHooks, callInfo)
	mock.lockCopyHooks.Unlock()
	if mock.CopyHooksFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.CopyHooksFunc(ctx, tx, fromBranchID, toBranchID, documentID, organizationID, uids)
}

// CopyHooksCalls gets all the calls that were made to CopyHooks.
// Check the length with:
//
//	len(mockedHookManager.CopyHooksCalls())
func (mock *HookManagerMock) CopyHooksCalls() []struct {
	Ctx            context.Context
	Tx             manager.CopyTx
	FromBranchID   xid.ID
	ToBranchID     xid.ID
	DocumentID     xid.ID
	OrganizationID string
	Uids           map[string]string
} {
	var calls []struct {
		Ctx            context.Context
		Tx             manager.CopyTx
		FromBranchID   xid.ID
		ToBranchID     xid.ID
		DocumentID     xid.ID
		OrganizationID string
		Uids           map[string]string
	}
	mock.lockCopyHooks.RLock()
	calls = mock.calls.CopyHooks
	mock.lockCopyHooks.RUnlock()
	return calls
}

// CreateHook calls CreateHookFunc.
func (mock *HookManagerMock) CreateHook(ctx context.Context, ci hookCore.CreateInput, documentID xid.ID, organizationID string, updatedBy string) (*hookCore.Hook, error) {
	callInfo := struct {
		Ctx            context.Context
		Ci             hookCore.CreateInput
		DocumentID     xid.ID
		OrganizationID string
		UpdatedBy      string
	}{
		Ctx:            ctx,
		Ci:             ci,
		DocumentID:     documentID,
		OrganizationID: organizationID,
		UpdatedBy:      updatedBy,
	}
	mock.lockCreateHook.Lock()
	mock.calls.CreateHook = append(mock.calls.CreateHook, callInfo)
	mock.lockCreateHook.Unlock()
	if mock.CreateHookFunc == nil {
		var (
			hookOut *hookCore.Hook
			errOut  error
		)
		return hookOut, errOut
	}
	return mock.CreateHookFunc(ctx, ci, documentID, organizationID, updatedBy)
}

// CreateHookCalls gets all the calls that were made to CreateHook.
// Check the length with:
//
//	len(mockedHookManager.CreateHookCalls())
func (mock *HookManagerMock) CreateHookCalls() []struct {
	Ctx            context.Context
	Ci             hookCore.CreateInput
	DocumentID     xid.ID
	OrganizationID string
	UpdatedBy      string
} {
	var calls []struct {
		Ctx            context.Context
		Ci             hookCore.CreateInput
		DocumentID     xid.ID
		OrganizationID string
		UpdatedBy      string
	}
	mock.lockCreateHook.RLock()
	calls = mock.calls.CreateHook
	mock.lockCreateHook.RUnlock()
	return calls
}

// DeleteHook calls DeleteHookFunc.
func (mock *HookManagerMock) DeleteHook(ctx context.Context, id xid.ID, organizationID string, updatedBy string) error {
	callInfo := struct {
		Ctx            context.Context
		ID             xid.ID
		OrganizationID string
		UpdatedBy      string
	}{
		Ctx:            ctx,
		ID:             id,
		OrganizationID: organizationID,
		UpdatedBy:      updatedBy,
	}
	mock.lockDeleteHook.Lock()
	mock.calls.DeleteHook = append(mock.calls.DeleteHook, callInfo)
	mock.lockDeleteHook.Unlock()
	if mock.DeleteHookFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.DeleteHookFunc(ctx, id, organizationID, updatedBy)
}

// DeleteHookCalls gets all the calls that were made to DeleteHook.
// Check the length with:
//
//	len(mockedHookManager.DeleteHookCalls())
func (mock *HookManagerMock) DeleteHookCalls() []struct {
	Ctx            context.Context
	ID             xid.ID
	OrganizationID string
	UpdatedBy      string
} {
	var calls []struct {
		Ctx            context.Context
		ID             xid.ID
		OrganizationID string
		UpdatedBy      string
	}
	mock.lockDeleteHook.RLock()
	calls = mock.calls.DeleteHook
	mock.lockDeleteHook.RUnlock()
	return calls
}

// OnHookChange calls OnHookChangeFunc.
func (mock *HookManagerMock) OnHookChange(fn func(hookCore.Hook)) func() {
	callInfo := struct {
		Fn func(hookCore.Hook)
	}{
		Fn: fn,
	}
	mock.lockOnHookChange.Lock()
	mock.calls.OnHookChange = append(mock.calls.OnHookChange, callInfo)
	mock.lockOnHookChange.Unlock()
	if mock.OnHookChangeFunc == nil {
		var (
			fnOut func()
		)
		return fnOut
	}
	return mock.OnHookChangeFunc(fn)
}

// OnHookChangeCalls gets all the calls that were made to OnHookChange.
// Check the length with:
//
//	len(mockedHookManager.OnHookChangeCalls())
func (mock *HookManagerMock) OnHookChangeCalls() []struct {
	Fn func(hookCore.Hook)
} {
	var calls []struct {
		Fn func(hookCore.Hook)
	}
	mock.lockOnHookChange.RLock()
	calls = mock.calls.OnHookChange
	mock.lockOnHookChange.RUnlock()
	return calls
}

// ProcessBranch calls ProcessBranchFunc.
func (mock *HookManagerMock) ProcessBranch(branchID xid.ID, organizationID string) {
	callInfo := struct {
		BranchID       xid.ID
		OrganizationID string
	}{
		BranchID:       branchID,
		OrganizationID: organizationID,
	}
	mock.lockProcessBranch.Lock()
	mock.calls.ProcessBranch = append(mock.calls.ProcessBranch, callInfo)
	mock.lockProcessBranch.Unlock()
	if mock.ProcessBranchFunc == nil {
		return
	}
	mock.ProcessBranchFunc(branchID, organizationID)
}

// ProcessBranchCalls gets all the calls that were made to ProcessBranch.
// Check the length with:
//
//	len(mockedHookManager.ProcessBranchCalls())
func (mock *HookManagerMock) ProcessBranchCalls() []struct {
	BranchID       xid.ID
	OrganizationID string
} {
	var calls []struct {
		BranchID       xid.ID
		OrganizationID string
	}
	mock.lockProcessBranch.RLock()
	calls = mock.calls.ProcessBranch
	mock.lockProcessBranch.RUnlock()
	return calls
}

// ResetHook calls ResetHookFunc.
func (mock *HookManagerMock) ResetHook(ctx context.Context, id xid.ID, organizationID string) (*hookCore.Hook, error) {
	callInfo := struct {
		Ctx            context.Context
		ID             xid.ID
		OrganizationID string
	}{
		Ctx:            ctx,
		ID:             id,
		OrganizationID: organizationID,
	}
	mock.lockResetHook.Lock()
	mock.calls.ResetHook = append(mock.calls.ResetHook, callInfo)
	mock.lockResetHook.Unlock()
	if mock.ResetHookFunc == nil {
		var (
			hookOut *hookCore.Hook
			errOut  error
		)
		return hookOut, errOut
	}
	return mock.ResetHookFunc(ctx, id, organizationID)
}

// ResetHookCalls gets all the calls that were made to ResetHook.
// Check the length with:
//
//	len(mockedHookManager.ResetHookCalls())
func (mock *HookManagerMock) ResetHookCalls() []struct {
	Ctx            context.Context
	ID             xid.ID
	OrganizationID string
} {
	var calls []struct {
		Ctx            context.Context
		ID             xid.ID
		OrganizationID string
	}
	mock.lockResetHook.RLock()
	calls = mock.calls.ResetHook
	mock.lockResetHook.RUnlock()
	return calls
}

// UpdateHook calls UpdateHookFunc.
func (mock *HookManagerMock) UpdateHook(ctx context.Context, id xid.ID, organizationID string, ui hookCore.UpdateInput, updatedBy string) (*hookCore.Hook, error) {
	callInfo := struct {
		Ctx            context.Context
		ID             xid.ID
		OrganizationID string
		UI             hookCore.UpdateInput
		UpdatedBy      string
	}{
		Ctx:            ctx,
		ID:             id,
		OrganizationID: organizationID,
		UI:             ui,
		UpdatedBy:      updatedBy,
	}
	mock.lockUpdateHook.Lock()
	mock.calls.UpdateHook = append(mock.calls.UpdateHook, callInfo)
	mock.lockUpdateHook.Unlock()
	if mock.UpdateHookFunc == nil {
		var (
			hookOut *hookCore.Hook
			errOut  error
		)
		return hookOut, errOut
	}
	return mock.UpdateHookFunc(ctx, id, organizationID, ui, updatedBy)
}

// UpdateHookCalls gets all the calls that were made to UpdateHook.
// Check the length with:
//
//	len(mockedHookManager.UpdateHookCalls())
func (mock *HookManagerMock) UpdateHookCalls() []struct {
	Ctx            context.Context
	ID             xid.ID
	OrganizationID string
	UI             hookCore.UpdateInput
	UpdatedBy      string
} {
	var calls []struct {
		Ctx            context.Context
		ID             xid.ID
		OrganizationID string
		UI             hookCore.UpdateInput
		UpdatedBy      string
	}
	mock.lockUpdateHook.RLock()
	calls = mock.calls.UpdateHook
	mock.lockUpdateHook.RUnlock()
	return calls
}
