// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package server

import (
	"context"
	"sync"

	hookCore "github.com/oxynote/oxynote/server/core/internal/document/hook"
	"github.com/rs/xid"
)

// Ensure, that HookManagerMock does implement HookManager.
// If this is not the case, regenerate this file with moq.
var _ HookManager = &HookManagerMock{}

// HookManagerMock is a mock implementation of HookManager.
//
//	func TestSomethingThatUsesHookManager(t *testing.T) {
//
//		// make and configure a mocked HookManager
//		mockedHookManager := &HookManagerMock{
//			BindHookChangeFunc: func(fn func(hookCore.Hook))  {
//				panic("mock out the BindHookChange method")
//			},
//			CreateHookFunc: func(ctx context.Context, ci hookCore.CreateInput, documentID xid.ID, organizationID string, updatedBy string) (*hookCore.Hook, error) {
//				panic("mock out the CreateHook method")
//			},
//			DeleteHookFunc: func(ctx context.Context, id xid.ID, organizationID string, updatedBy string) error {
//				panic("mock out the DeleteHook method")
//			},
//			QueueBranchFunc: func(branchID xid.ID, organizationID string)  {
//				panic("mock out the QueueBranch method")
//			},
//			ResetHookFunc: func(ctx context.Context, id xid.ID, organizationID string) (*hookCore.Hook, error) {
//				panic("mock out the ResetHook method")
//			},
//			UpdateHookFunc: func(ctx context.Context, id xid.ID, organizationID string, ui hookCore.UpdateInput, updatedBy string) (*hookCore.Hook, error) {
//				panic("mock out the UpdateHook method")
//			},
//		}
//
//		// use mockedHookManager in code that requires HookManager
//		// and then make assertions.
//
//	}
type HookManagerMock struct {
	// BindHookChangeFunc mocks the BindHookChange method.
	BindHookChangeFunc func(fn func(hookCore.Hook))

	// CreateHookFunc mocks the CreateHook method.
	CreateHookFunc func(ctx context.Context, ci hookCore.CreateInput, documentID xid.ID, organizationID string, updatedBy string) (*hookCore.Hook, error)

	// DeleteHookFunc mocks the DeleteHook method.
	DeleteHookFunc func(ctx context.Context, id xid.ID, organizationID string, updatedBy string) error

	// QueueBranchFunc mocks the QueueBranch method.
	QueueBranchFunc func(branchID xid.ID, organizationID string)

	// ResetHookFunc mocks the ResetHook method.
	ResetHookFunc func(ctx context.Context, id xid.ID, organizationID string) (*hookCore.Hook, error)

	// UpdateHookFunc mocks the UpdateHook method.
	UpdateHookFunc func(ctx context.Context, id xid.ID, organizationID string, ui hookCore.UpdateInput, updatedBy string) (*hookCore.Hook, error)

	// calls tracks calls to the methods.
	calls struct {
		// BindHookChange holds details about calls to the BindHookChange method.
		BindHookChange []struct {
			// Fn is the fn argument value.
			Fn func(hookCore.Hook)
		}
		// CreateHook holds details about calls to the CreateHook method.
		CreateHook []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Ci is the ci argument value.
			Ci hookCore.CreateInput
			// DocumentID is the documentID argument value.
			DocumentID xid.ID
			// OrganizationID is the organizationID argument value.
			OrganizationID string
			// UpdatedBy is the updatedBy argument value.
			UpdatedBy string
		}
		// DeleteHook holds details about calls to the DeleteHook method.
		DeleteHook []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID xid.ID
			// OrganizationID is the organizationID argument value.
			OrganizationID string
			// UpdatedBy is the updatedBy argument value.
			UpdatedBy string
		}
		// QueueBranch holds details about calls to the QueueBranch method.
		QueueBranch []struct {
			// BranchID is the branchID argument value.
			BranchID xid.ID
			// OrganizationID is the organizationID argument value.
			OrganizationID string
		}
		// ResetHook holds details about calls to the ResetHook method.
		ResetHook []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID xid.ID
			// OrganizationID is the organizationID argument value.
			OrganizationID string
		}
		// UpdateHook holds details about calls to the UpdateHook method.
		UpdateHook []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID xid.ID
			// OrganizationID is the organizationID argument value.
			OrganizationID string
			// UI is the ui argument value.
			UI hookCore.UpdateInput
			// UpdatedBy is the updatedBy argument value.
			UpdatedBy string
		}
	}
	lockBindHookChange sync.RWMutex
	lockCreateHook     sync.RWMutex
	lockDeleteHook     sync.RWMutex
	lockQueueBranch    sync.RWMutex
	lockResetHook      sync.RWMutex
	lockUpdateHook     sync.RWMutex
}

// BindHookChange calls BindHookChangeFunc.
func (mock *HookManagerMock) BindHookChange(fn func(hookCore.Hook)) {
	callInfo := struct {
		Fn func(hookCore.Hook)
	}{
		Fn: fn,
	}
	mock.lockBindHookChange.Lock()
	mock.calls.BindHookChange = append(mock.calls.BindHookChange, callInfo)
	mock.lockBindHookChange.Unlock()
	if mock.BindHookChangeFunc == nil {
		return
	}
	mock.BindHookChangeFunc(fn)
}

// BindHookChangeCalls gets all the calls that were made to BindHookChange.
// Check the length with:
//
//	len(mockedHookManager.BindHookChangeCalls())
func (mock *HookManagerMock) BindHookChangeCalls() []struct {
	Fn func(hookCore.Hook)
} {
	var calls []struct {
		Fn func(hookCore.Hook)
	}
	mock.lockBindHookChange.RLock()
	calls = mock.calls.BindHookChange
	mock.lockBindHookChange.RUnlock()
	return calls
}

// CreateHook calls CreateHookFunc.
func (mock *HookManagerMock) CreateHook(ctx context.Context, ci hookCore.CreateInput, documentID xid.ID, organizationID string, updatedBy string) (*hookCore.Hook, error) {
	callInfo := struct {
		Ctx            context.Context
		Ci             hookCore.CreateInput
		DocumentID     xid.ID
		OrganizationID string
		UpdatedBy      string
	}{
		Ctx:            ctx,
		Ci:             ci,
		DocumentID:     documentID,
		OrganizationID: organizationID,
		UpdatedBy:      updatedBy,
	}
	mock.lockCreateHook.Lock()
	mock.calls.CreateHook = append(mock.calls.CreateHook, callInfo)
	mock.lockCreateHook.Unlock()
	if mock.CreateHookFunc == nil {
		var (
			hookOut *hookCore.Hook
			errOut  error
		)
		return hookOut, errOut
	}
	return mock.CreateHookFunc(ctx, ci, documentID, organizationID, updatedBy)
}

// CreateHookCalls gets all the calls that were made to CreateHook.
// Check the length with:
//
//	len(mockedHookManager.CreateHookCalls())
func (mock *HookManagerMock) CreateHookCalls() []struct {
	Ctx            context.Context
	Ci             hookCore.CreateInput
	DocumentID     xid.ID
	OrganizationID string
	UpdatedBy      string
} {
	var calls []struct {
		Ctx            context.Context
		Ci             hookCore.CreateInput
		DocumentID     xid.ID
		OrganizationID string
		UpdatedBy      string
	}
	mock.lockCreateHook.RLock()
	calls = mock.calls.CreateHook
	mock.lockCreateHook.RUnlock()
	return calls
}

// DeleteHook calls DeleteHookFunc.
func (mock *HookManagerMock) DeleteHook(ctx context.Context, id xid.ID, organizationID string, updatedBy string) error {
	callInfo := struct {
		Ctx            context.Context
		ID             xid.ID
		OrganizationID string
		UpdatedBy      string
	}{
		Ctx:            ctx,
		ID:             id,
		OrganizationID: organizationID,
		UpdatedBy:      updatedBy,
	}
	mock.lockDeleteHook.Lock()
	mock.calls.DeleteHook = append(mock.calls.DeleteHook, callInfo)
	mock.lockDeleteHook.Unlock()
	if mock.DeleteHookFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.DeleteHookFunc(ctx, id, organizationID, updatedBy)
}

// DeleteHookCalls gets all the calls that were made to DeleteHook.
// Check the length with:
//
//	len(mockedHookManager.DeleteHookCalls())
func (mock *HookManagerMock) DeleteHookCalls() []struct {
	Ctx            context.Context
	ID             xid.ID
	OrganizationID string
	UpdatedBy      string
} {
	var calls []struct {
		Ctx            context.Context
		ID             xid.ID
		OrganizationID string
		UpdatedBy      string
	}
	mock.lockDeleteHook.RLock()
	calls = mock.calls.DeleteHook
	mock.lockDeleteHook.RUnlock()
	return calls
}

// QueueBranch calls QueueBranchFunc.
func (mock *HookManagerMock) QueueBranch(branchID xid.ID, organizationID string) {
	callInfo := struct {
		BranchID       xid.ID
		OrganizationID string
	}{
		BranchID:       branchID,
		OrganizationID: organizationID,
	}
	mock.lockQueueBranch.Lock()
	mock.calls.QueueBranch = append(mock.calls.QueueBranch, callInfo)
	mock.lockQueueBranch.Unlock()
	if mock.QueueBranchFunc == nil {
		return
	}
	mock.QueueBranchFunc(branchID, organizationID)
}

// QueueBranchCalls gets all the calls that were made to QueueBranch.
// Check the length with:
//
//	len(mockedHookManager.QueueBranchCalls())
func (mock *HookManagerMock) QueueBranchCalls() []struct {
	BranchID       xid.ID
	OrganizationID string
} {
	var calls []struct {
		BranchID       xid.ID
		OrganizationID string
	}
	mock.lockQueueBranch.RLock()
	calls = mock.calls.QueueBranch
	mock.lockQueueBranch.RUnlock()
	return calls
}

// ResetHook calls ResetHookFunc.
func (mock *HookManagerMock) ResetHook(ctx context.Context, id xid.ID, organizationID string) (*hookCore.Hook, error) {
	callInfo := struct {
		Ctx            context.Context
		ID             xid.ID
		OrganizationID string
	}{
		Ctx:            ctx,
		ID:             id,
		OrganizationID: organizationID,
	}
	mock.lockResetHook.Lock()
	mock.calls.ResetHook = append(mock.calls.ResetHook, callInfo)
	mock.lockResetHook.Unlock()
	if mock.ResetHookFunc == nil {
		var (
			hookOut *hookCore.Hook
			errOut  error
		)
		return hookOut, errOut
	}
	return mock.ResetHookFunc(ctx, id, organizationID)
}

// ResetHookCalls gets all the calls that were made to ResetHook.
// Check the length with:
//
//	len(mockedHookManager.ResetHookCalls())
func (mock *HookManagerMock) ResetHookCalls() []struct {
	Ctx            context.Context
	ID             xid.ID
	OrganizationID string
} {
	var calls []struct {
		Ctx            context.Context
		ID             xid.ID
		OrganizationID string
	}
	mock.lockResetHook.RLock()
	calls = mock.calls.ResetHook
	mock.lockResetHook.RUnlock()
	return calls
}

// UpdateHook calls UpdateHookFunc.
func (mock *HookManagerMock) UpdateHook(ctx context.Context, id xid.ID, organizationID string, ui hookCore.UpdateInput, updatedBy string) (*hookCore.Hook, error) {
	callInfo := struct {
		Ctx            context.Context
		ID             xid.ID
		OrganizationID string
		UI             hookCore.UpdateInput
		UpdatedBy      string
	}{
		Ctx:            ctx,
		ID:             id,
		OrganizationID: organizationID,
		UI:             ui,
		UpdatedBy:      updatedBy,
	}
	mock.lockUpdateHook.Lock()
	mock.calls.UpdateHook = append(mock.calls.UpdateHook, callInfo)
	mock.lockUpdateHook.Unlock()
	if mock.UpdateHookFunc == nil {
		var (
			hookOut *hookCore.Hook
			errOut  error
		)
		return hookOut, errOut
	}
	return mock.UpdateHookFunc(ctx, id, organizationID, ui, updatedBy)
}

// UpdateHookCalls gets all the calls that were made to UpdateHook.
// Check the length with:
//
//	len(mockedHookManager.UpdateHookCalls())
func (mock *HookManagerMock) UpdateHookCalls() []struct {
	Ctx            context.Context
	ID             xid.ID
	OrganizationID string
	UI             hookCore.UpdateInput
	UpdatedBy      string
} {
	var calls []struct {
		Ctx            context.Context
		ID             xid.ID
		OrganizationID string
		UI             hookCore.UpdateInput
		UpdatedBy      string
	}
	mock.lockUpdateHook.RLock()
	calls = mock.calls.UpdateHook
	mock.lockUpdateHook.RUnlock()
	return calls
}
