// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package server

import (
	"context"
	"sync"

	notificationCore "github.com/oxynote/oxynote/server/core/internal/notification"
)

// Ensure, that NotifierMock does implement Notifier.
// If this is not the case, regenerate this file with moq.
var _ Notifier = &NotifierMock{}

// NotifierMock is a mock implementation of Notifier.
//
//	func TestSomethingThatUsesNotifier(t *testing.T) {
//
//		// make and configure a mocked Notifier
//		mockedNotifier := &NotifierMock{
//			OnNotificationFunc: func(fn func(context.Context, notificationCore.Notification)) notificationCore.Unsubscribe {
//				panic("mock out the OnNotification method")
//			},
//			PublishNotificationsFunc: func(organizationID string, be notificationCore.Core, userIDs ...string)  {
//				panic("mock out the PublishNotifications method")
//			},
//		}
//
//		// use mockedNotifier in code that requires Notifier
//		// and then make assertions.
//
//	}
type NotifierMock struct {
	// OnNotificationFunc mocks the OnNotification method.
	OnNotificationFunc func(fn func(context.Context, notificationCore.Notification)) notificationCore.Unsubscribe

	// PublishNotificationsFunc mocks the PublishNotifications method.
	PublishNotificationsFunc func(organizationID string, be notificationCore.Core, userIDs ...string)

	// calls tracks calls to the methods.
	calls struct {
		// OnNotification holds details about calls to the OnNotification method.
		OnNotification []struct {
			// Fn is the fn argument value.
			Fn func(context.Context, notificationCore.Notification)
		}
		// PublishNotifications holds details about calls to the PublishNotifications method.
		PublishNotifications []struct {
			// OrganizationID is the organizationID argument value.
			OrganizationID string
			// Be is the be argument value.
			Be notificationCore.Core
			// UserIDs is the userIDs argument value.
			UserIDs []string
		}
	}
	lockOnNotification       sync.RWMutex
	lockPublishNotifications sync.RWMutex
}

// OnNotification calls OnNotificationFunc.
func (mock *NotifierMock) OnNotification(fn func(context.Context, notificationCore.Notification)) notificationCore.Unsubscribe {
	callInfo := struct {
		Fn func(context.Context, notificationCore.Notification)
	}{
		Fn: fn,
	}
	mock.lockOnNotification.Lock()
	mock.calls.OnNotification = append(mock.calls.OnNotification, callInfo)
	mock.lockOnNotification.Unlock()
	if mock.OnNotificationFunc == nil {
		var (
			unsubscribeOut notificationCore.Unsubscribe
		)
		return unsubscribeOut
	}
	return mock.OnNotificationFunc(fn)
}

// OnNotificationCalls gets all the calls that were made to OnNotification.
// Check the length with:
//
//	len(mockedNotifier.OnNotificationCalls())
func (mock *NotifierMock) OnNotificationCalls() []struct {
	Fn func(context.Context, notificationCore.Notification)
} {
	var calls []struct {
		Fn func(context.Context, notificationCore.Notification)
	}
	mock.lockOnNotification.RLock()
	calls = mock.calls.OnNotification
	mock.lockOnNotification.RUnlock()
	return calls
}

// PublishNotifications calls PublishNotificationsFunc.
func (mock *NotifierMock) PublishNotifications(organizationID string, be notificationCore.Core, userIDs ...string) {
	callInfo := struct {
		OrganizationID string
		Be             notificationCore.Core
		UserIDs        []string
	}{
		OrganizationID: organizationID,
		Be:             be,
		UserIDs:        userIDs,
	}
	mock.lockPublishNotifications.Lock()
	mock.calls.PublishNotifications = append(mock.calls.PublishNotifications, callInfo)
	mock.lockPublishNotifications.Unlock()
	if mock.PublishNotificationsFunc == nil {
		return
	}
	mock.PublishNotificationsFunc(organizationID, be, userIDs...)
}

// PublishNotificationsCalls gets all the calls that were made to PublishNotifications.
// Check the length with:
//
//	len(mockedNotifier.PublishNotificationsCalls())
func (mock *NotifierMock) PublishNotificationsCalls() []struct {
	OrganizationID string
	Be             notificationCore.Core
	UserIDs        []string
} {
	var calls []struct {
		OrganizationID string
		Be             notificationCore.Core
		UserIDs        []string
	}
	mock.lockPublishNotifications.RLock()
	calls = mock.calls.PublishNotifications
	mock.lockPublishNotifications.RUnlock()
	return calls
}
