// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"sync"

	"github.com/oxynote/oxynote/server/core/internal/assistant/protocol"
)

// Ensure, that SessionConn does implement protocol.SessionConn.
// If this is not the case, regenerate this file with moq.
var _ protocol.SessionConn = &SessionConn{}

// SessionConn is a mock implementation of protocol.SessionConn.
//
//	func TestSomethingThatUsesSessionConn(t *testing.T) {
//
//		// make and configure a mocked protocol.SessionConn
//		mockedSessionConn := &SessionConn{
//			ReadFunc: func(ctx context.Context) ([]byte, error) {
//				panic("mock out the Read method")
//			},
//			WriteJSONFunc: func(ctx context.Context, msg any)  {
//				panic("mock out the WriteJSON method")
//			},
//		}
//
//		// use mockedSessionConn in code that requires protocol.SessionConn
//		// and then make assertions.
//
//	}
type SessionConn struct {
	// ReadFunc mocks the Read method.
	ReadFunc func(ctx context.Context) ([]byte, error)

	// WriteJSONFunc mocks the WriteJSON method.
	WriteJSONFunc func(ctx context.Context, msg any)

	// calls tracks calls to the methods.
	calls struct {
		// Read holds details about calls to the Read method.
		Read []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// WriteJSON holds details about calls to the WriteJSON method.
		WriteJSON []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Msg is the msg argument value.
			Msg any
		}
	}
	lockRead      sync.RWMutex
	lockWriteJSON sync.RWMutex
}

// Read calls ReadFunc.
func (mock *SessionConn) Read(ctx context.Context) ([]byte, error) {
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockRead.Lock()
	mock.calls.Read = append(mock.calls.Read, callInfo)
	mock.lockRead.Unlock()
	if mock.ReadFunc == nil {
		var (
			bytesOut []byte
			errOut   error
		)
		return bytesOut, errOut
	}
	return mock.ReadFunc(ctx)
}

// ReadCalls gets all the calls that were made to Read.
// Check the length with:
//
//	len(mockedSessionConn.ReadCalls())
func (mock *SessionConn) ReadCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockRead.RLock()
	calls = mock.calls.Read
	mock.lockRead.RUnlock()
	return calls
}

// WriteJSON calls WriteJSONFunc.
func (mock *SessionConn) WriteJSON(ctx context.Context, msg any) {
	callInfo := struct {
		Ctx context.Context
		Msg any
	}{
		Ctx: ctx,
		Msg: msg,
	}
	mock.lockWriteJSON.Lock()
	mock.calls.WriteJSON = append(mock.calls.WriteJSON, callInfo)
	mock.lockWriteJSON.Unlock()
	if mock.WriteJSONFunc == nil {
		return
	}
	mock.WriteJSONFunc(ctx, msg)
}

// WriteJSONCalls gets all the calls that were made to WriteJSON.
// Check the length with:
//
//	len(mockedSessionConn.WriteJSONCalls())
func (mock *SessionConn) WriteJSONCalls() []struct {
	Ctx context.Context
	Msg any
} {
	var calls []struct {
		Ctx context.Context
		Msg any
	}
	mock.lockWriteJSON.RLock()
	calls = mock.calls.WriteJSON
	mock.lockWriteJSON.RUnlock()
	return calls
}
