// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"sync"

	"github.com/cloudwego/eino/components/model"
	"github.com/cloudwego/eino/schema"
)

// Ensure, that ChatModel does implement model.ToolCallingChatModel.
// If this is not the case, regenerate this file with moq.
var _ model.ToolCallingChatModel = &ChatModel{}

// ChatModel is a mock implementation of model.ToolCallingChatModel.
//
//	func TestSomethingThatUsesToolCallingChatModel(t *testing.T) {
//
//		// make and configure a mocked model.ToolCallingChatModel
//		mockedToolCallingChatModel := &ChatModel{
//			GenerateFunc: func(ctx context.Context, input []*schema.Message, opts ...model.Option) (*schema.Message, error) {
//				panic("mock out the Generate method")
//			},
//			StreamFunc: func(ctx context.Context, input []*schema.Message, opts ...model.Option) (*schema.StreamReader[*schema.Message], error) {
//				panic("mock out the Stream method")
//			},
//			WithToolsFunc: func(tools []*schema.ToolInfo) (model.ToolCallingChatModel, error) {
//				panic("mock out the WithTools method")
//			},
//		}
//
//		// use mockedToolCallingChatModel in code that requires model.ToolCallingChatModel
//		// and then make assertions.
//
//	}
type ChatModel struct {
	// GenerateFunc mocks the Generate method.
	GenerateFunc func(ctx context.Context, input []*schema.Message, opts ...model.Option) (*schema.Message, error)

	// StreamFunc mocks the Stream method.
	StreamFunc func(ctx context.Context, input []*schema.Message, opts ...model.Option) (*schema.StreamReader[*schema.Message], error)

	// WithToolsFunc mocks the WithTools method.
	WithToolsFunc func(tools []*schema.ToolInfo) (model.ToolCallingChatModel, error)

	// calls tracks calls to the methods.
	calls struct {
		// Generate holds details about calls to the Generate method.
		Generate []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Input is the input argument value.
			Input []*schema.Message
			// Opts is the opts argument value.
			Opts []model.Option
		}
		// Stream holds details about calls to the Stream method.
		Stream []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Input is the input argument value.
			Input []*schema.Message
			// Opts is the opts argument value.
			Opts []model.Option
		}
		// WithTools holds details about calls to the WithTools method.
		WithTools []struct {
			// Tools is the tools argument value.
			Tools []*schema.ToolInfo
		}
	}
	lockGenerate  sync.RWMutex
	lockStream    sync.RWMutex
	lockWithTools sync.RWMutex
}

// Generate calls GenerateFunc.
func (mock *ChatModel) Generate(ctx context.Context, input []*schema.Message, opts ...model.Option) (*schema.Message, error) {
	callInfo := struct {
		Ctx   context.Context
		Input []*schema.Message
		Opts  []model.Option
	}{
		Ctx:   ctx,
		Input: input,
		Opts:  opts,
	}
	mock.lockGenerate.Lock()
	mock.calls.Generate = append(mock.calls.Generate, callInfo)
	mock.lockGenerate.Unlock()
	if mock.GenerateFunc == nil {
		var (
			messageOut *schema.Message
			errOut     error
		)
		return messageOut, errOut
	}
	return mock.GenerateFunc(ctx, input, opts...)
}

// GenerateCalls gets all the calls that were made to Generate.
// Check the length with:
//
//	len(mockedToolCallingChatModel.GenerateCalls())
func (mock *ChatModel) GenerateCalls() []struct {
	Ctx   context.Context
	Input []*schema.Message
	Opts  []model.Option
} {
	var calls []struct {
		Ctx   context.Context
		Input []*schema.Message
		Opts  []model.Option
	}
	mock.lockGenerate.RLock()
	calls = mock.calls.Generate
	mock.lockGenerate.RUnlock()
	return calls
}

// Stream calls StreamFunc.
func (mock *ChatModel) Stream(ctx context.Context, input []*schema.Message, opts ...model.Option) (*schema.StreamReader[*schema.Message], error) {
	callInfo := struct {
		Ctx   context.Context
		Input []*schema.Message
		Opts  []model.Option
	}{
		Ctx:   ctx,
		Input: input,
		Opts:  opts,
	}
	mock.lockStream.Lock()
	mock.calls.Stream = append(mock.calls.Stream, callInfo)
	mock.lockStream.Unlock()
	if mock.StreamFunc == nil {
		var (
			streamReaderOut *schema.StreamReader[*schema.Message]
			errOut          error
		)
		return streamReaderOut, errOut
	}
	return mock.StreamFunc(ctx, input, opts...)
}

// StreamCalls gets all the calls that were made to Stream.
// Check the length with:
//
//	len(mockedToolCallingChatModel.StreamCalls())
func (mock *ChatModel) StreamCalls() []struct {
	Ctx   context.Context
	Input []*schema.Message
	Opts  []model.Option
} {
	var calls []struct {
		Ctx   context.Context
		Input []*schema.Message
		Opts  []model.Option
	}
	mock.lockStream.RLock()
	calls = mock.calls.Stream
	mock.lockStream.RUnlock()
	return calls
}

// WithTools calls WithToolsFunc.
func (mock *ChatModel) WithTools(tools []*schema.ToolInfo) (model.ToolCallingChatModel, error) {
	callInfo := struct {
		Tools []*schema.ToolInfo
	}{
		Tools: tools,
	}
	mock.lockWithTools.Lock()
	mock.calls.WithTools = append(mock.calls.WithTools, callInfo)
	mock.lockWithTools.Unlock()
	if mock.WithToolsFunc == nil {
		var (
			toolCallingChatModelOut model.ToolCallingChatModel
			errOut                  error
		)
		return toolCallingChatModelOut, errOut
	}
	return mock.WithToolsFunc(tools)
}

// WithToolsCalls gets all the calls that were made to WithTools.
// Check the length with:
//
//	len(mockedToolCallingChatModel.WithToolsCalls())
func (mock *ChatModel) WithToolsCalls() []struct {
	Tools []*schema.ToolInfo
} {
	var calls []struct {
		Tools []*schema.ToolInfo
	}
	mock.lockWithTools.RLock()
	calls = mock.calls.WithTools
	mock.lockWithTools.RUnlock()
	return calls
}
