// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"sync"

	"github.com/oxynote/oxynote/server/core/pkg/metricutil"
)

// Ensure, that Counter does implement metricutil.Counter.
// If this is not the case, regenerate this file with moq.
var _ metricutil.Counter = &Counter{}

// Counter is a mock implementation of metricutil.Counter.
//
//	func TestSomethingThatUsesCounter(t *testing.T) {
//
//		// make and configure a mocked metricutil.Counter
//		mockedCounter := &Counter{
//			AddFunc: func(f float64)  {
//				panic("mock out the Add method")
//			},
//			IncFunc: func()  {
//				panic("mock out the Inc method")
//			},
//		}
//
//		// use mockedCounter in code that requires metricutil.Counter
//		// and then make assertions.
//
//	}
type Counter struct {
	// AddFunc mocks the Add method.
	AddFunc func(f float64)

	// IncFunc mocks the Inc method.
	IncFunc func()

	// calls tracks calls to the methods.
	calls struct {
		// Add holds details about calls to the Add method.
		Add []struct {
			// F is the f argument value.
			F float64
		}
		// Inc holds details about calls to the Inc method.
		Inc []struct {
		}
	}
	lockAdd sync.RWMutex
	lockInc sync.RWMutex
}

// Add calls AddFunc.
func (mock *Counter) Add(f float64) {
	callInfo := struct {
		F float64
	}{
		F: f,
	}
	mock.lockAdd.Lock()
	mock.calls.Add = append(mock.calls.Add, callInfo)
	mock.lockAdd.Unlock()
	if mock.AddFunc == nil {
		return
	}
	mock.AddFunc(f)
}

// AddCalls gets all the calls that were made to Add.
// Check the length with:
//
//	len(mockedCounter.AddCalls())
func (mock *Counter) AddCalls() []struct {
	F float64
} {
	var calls []struct {
		F float64
	}
	mock.lockAdd.RLock()
	calls = mock.calls.Add
	mock.lockAdd.RUnlock()
	return calls
}

// Inc calls IncFunc.
func (mock *Counter) Inc() {
	callInfo := struct {
	}{}
	mock.lockInc.Lock()
	mock.calls.Inc = append(mock.calls.Inc, callInfo)
	mock.lockInc.Unlock()
	if mock.IncFunc == nil {
		return
	}
	mock.IncFunc()
}

// IncCalls gets all the calls that were made to Inc.
// Check the length with:
//
//	len(mockedCounter.IncCalls())
func (mock *Counter) IncCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockInc.RLock()
	calls = mock.calls.Inc
	mock.lockInc.RUnlock()
	return calls
}
