// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"sync"

	"github.com/oxynote/oxynote/server/core/pkg/metricutil"
)

// Ensure, that Observer does implement metricutil.Observer.
// If this is not the case, regenerate this file with moq.
var _ metricutil.Observer = &Observer{}

// Observer is a mock implementation of metricutil.Observer.
//
//	func TestSomethingThatUsesObserver(t *testing.T) {
//
//		// make and configure a mocked metricutil.Observer
//		mockedObserver := &Observer{
//			ObserveFunc: func(f float64)  {
//				panic("mock out the Observe method")
//			},
//		}
//
//		// use mockedObserver in code that requires metricutil.Observer
//		// and then make assertions.
//
//	}
type Observer struct {
	// ObserveFunc mocks the Observe method.
	ObserveFunc func(f float64)

	// calls tracks calls to the methods.
	calls struct {
		// Observe holds details about calls to the Observe method.
		Observe []struct {
			// F is the f argument value.
			F float64
		}
	}
	lockObserve sync.RWMutex
}

// Observe calls ObserveFunc.
func (mock *Observer) Observe(f float64) {
	callInfo := struct {
		F float64
	}{
		F: f,
	}
	mock.lockObserve.Lock()
	mock.calls.Observe = append(mock.calls.Observe, callInfo)
	mock.lockObserve.Unlock()
	if mock.ObserveFunc == nil {
		return
	}
	mock.ObserveFunc(f)
}

// ObserveCalls gets all the calls that were made to Observe.
// Check the length with:
//
//	len(mockedObserver.ObserveCalls())
func (mock *Observer) ObserveCalls() []struct {
	F float64
} {
	var calls []struct {
		F float64
	}
	mock.lockObserve.RLock()
	calls = mock.calls.Observe
	mock.lockObserve.RUnlock()
	return calls
}
