// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package datasource

import (
	"context"
	"sync"

	"github.com/oxynote/oxynote/server/core/internal/datasource/processor"
	"github.com/rs/xid"
)

// Ensure, that StatusStoreMock does implement StatusStore.
// If this is not the case, regenerate this file with moq.
var _ StatusStore = &StatusStoreMock{}

// StatusStoreMock is a mock implementation of StatusStore.
//
//	func TestSomethingThatUsesStatusStore(t *testing.T) {
//
//		// make and configure a mocked StatusStore
//		mockedStatusStore := &StatusStoreMock{
//			UpdateDataSourceStatusFunc: func(ctx context.Context, id xid.ID, organizationID string, status processor.ConnectionStatus) error {
//				panic("mock out the UpdateDataSourceStatus method")
//			},
//		}
//
//		// use mockedStatusStore in code that requires StatusStore
//		// and then make assertions.
//
//	}
type StatusStoreMock struct {
	// UpdateDataSourceStatusFunc mocks the UpdateDataSourceStatus method.
	UpdateDataSourceStatusFunc func(ctx context.Context, id xid.ID, organizationID string, status processor.ConnectionStatus) error

	// calls tracks calls to the methods.
	calls struct {
		// UpdateDataSourceStatus holds details about calls to the UpdateDataSourceStatus method.
		UpdateDataSourceStatus []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Id is the id argument value.
			Id xid.ID
			// OrganizationID is the organizationID argument value.
			OrganizationID string
			// Status is the status argument value.
			Status processor.ConnectionStatus
		}
	}
	lockUpdateDataSourceStatus sync.RWMutex
}

// UpdateDataSourceStatus calls UpdateDataSourceStatusFunc.
func (mock *StatusStoreMock) UpdateDataSourceStatus(ctx context.Context, id xid.ID, organizationID string, status processor.ConnectionStatus) error {
	callInfo := struct {
		Ctx            context.Context
		Id             xid.ID
		OrganizationID string
		Status         processor.ConnectionStatus
	}{
		Ctx:            ctx,
		Id:             id,
		OrganizationID: organizationID,
		Status:         status,
	}
	mock.lockUpdateDataSourceStatus.Lock()
	mock.calls.UpdateDataSourceStatus = append(mock.calls.UpdateDataSourceStatus, callInfo)
	mock.lockUpdateDataSourceStatus.Unlock()
	if mock.UpdateDataSourceStatusFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.UpdateDataSourceStatusFunc(ctx, id, organizationID, status)
}

// UpdateDataSourceStatusCalls gets all the calls that were made to UpdateDataSourceStatus.
// Check the length with:
//
//	len(mockedStatusStore.UpdateDataSourceStatusCalls())
func (mock *StatusStoreMock) UpdateDataSourceStatusCalls() []struct {
	Ctx            context.Context
	Id             xid.ID
	OrganizationID string
	Status         processor.ConnectionStatus
} {
	var calls []struct {
		Ctx            context.Context
		Id             xid.ID
		OrganizationID string
		Status         processor.ConnectionStatus
	}
	mock.lockUpdateDataSourceStatus.RLock()
	calls = mock.calls.UpdateDataSourceStatus
	mock.lockUpdateDataSourceStatus.RUnlock()
	return calls
}
