// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package files

import (
	"context"
	"sync"

	"github.com/oxynote/oxynote/server/core/internal/document"
	"github.com/rs/xid"
)

// Ensure, that DBMock does implement DB.
// If this is not the case, regenerate this file with moq.
var _ DB = &DBMock{}

// DBMock is a mock implementation of DB.
//
//	func TestSomethingThatUsesDB(t *testing.T) {
//
//		// make and configure a mocked DB
//		mockedDB := &DBMock{
//			CheckDocumentExistsFunc: func(ctx context.Context, id xid.ID, organizationID string) error {
//				panic("mock out the CheckDocumentExists method")
//			},
//			FetchDocumentFileFunc: func(ctx context.Context, blockID string, organizationID string) (*document.File, error) {
//				panic("mock out the FetchDocumentFile method")
//			},
//			InsertDocumentFileFunc: func(ctx context.Context, f document.File) error {
//				panic("mock out the InsertDocumentFile method")
//			},
//		}
//
//		// use mockedDB in code that requires DB
//		// and then make assertions.
//
//	}
type DBMock struct {
	// CheckDocumentExistsFunc mocks the CheckDocumentExists method.
	CheckDocumentExistsFunc func(ctx context.Context, id xid.ID, organizationID string) error

	// FetchDocumentFileFunc mocks the FetchDocumentFile method.
	FetchDocumentFileFunc func(ctx context.Context, blockID string, organizationID string) (*document.File, error)

	// InsertDocumentFileFunc mocks the InsertDocumentFile method.
	InsertDocumentFileFunc func(ctx context.Context, f document.File) error

	// calls tracks calls to the methods.
	calls struct {
		// CheckDocumentExists holds details about calls to the CheckDocumentExists method.
		CheckDocumentExists []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID xid.ID
			// OrganizationID is the organizationID argument value.
			OrganizationID string
		}
		// FetchDocumentFile holds details about calls to the FetchDocumentFile method.
		FetchDocumentFile []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// BlockID is the blockID argument value.
			BlockID string
			// OrganizationID is the organizationID argument value.
			OrganizationID string
		}
		// InsertDocumentFile holds details about calls to the InsertDocumentFile method.
		InsertDocumentFile []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// F is the f argument value.
			F document.File
		}
	}
	lockCheckDocumentExists sync.RWMutex
	lockFetchDocumentFile   sync.RWMutex
	lockInsertDocumentFile  sync.RWMutex
}

// CheckDocumentExists calls CheckDocumentExistsFunc.
func (mock *DBMock) CheckDocumentExists(ctx context.Context, id xid.ID, organizationID string) error {
	callInfo := struct {
		Ctx            context.Context
		ID             xid.ID
		OrganizationID string
	}{
		Ctx:            ctx,
		ID:             id,
		OrganizationID: organizationID,
	}
	mock.lockCheckDocumentExists.Lock()
	mock.calls.CheckDocumentExists = append(mock.calls.CheckDocumentExists, callInfo)
	mock.lockCheckDocumentExists.Unlock()
	if mock.CheckDocumentExistsFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.CheckDocumentExistsFunc(ctx, id, organizationID)
}

// CheckDocumentExistsCalls gets all the calls that were made to CheckDocumentExists.
// Check the length with:
//
//	len(mockedDB.CheckDocumentExistsCalls())
func (mock *DBMock) CheckDocumentExistsCalls() []struct {
	Ctx            context.Context
	ID             xid.ID
	OrganizationID string
} {
	var calls []struct {
		Ctx            context.Context
		ID             xid.ID
		OrganizationID string
	}
	mock.lockCheckDocumentExists.RLock()
	calls = mock.calls.CheckDocumentExists
	mock.lockCheckDocumentExists.RUnlock()
	return calls
}

// FetchDocumentFile calls FetchDocumentFileFunc.
func (mock *DBMock) FetchDocumentFile(ctx context.Context, blockID string, organizationID string) (*document.File, error) {
	callInfo := struct {
		Ctx            context.Context
		BlockID        string
		OrganizationID string
	}{
		Ctx:            ctx,
		BlockID:        blockID,
		OrganizationID: organizationID,
	}
	mock.lockFetchDocumentFile.Lock()
	mock.calls.FetchDocumentFile = append(mock.calls.FetchDocumentFile, callInfo)
	mock.lockFetchDocumentFile.Unlock()
	if mock.FetchDocumentFileFunc == nil {
		var (
			fileOut *document.File
			errOut  error
		)
		return fileOut, errOut
	}
	return mock.FetchDocumentFileFunc(ctx, blockID, organizationID)
}

// FetchDocumentFileCalls gets all the calls that were made to FetchDocumentFile.
// Check the length with:
//
//	len(mockedDB.FetchDocumentFileCalls())
func (mock *DBMock) FetchDocumentFileCalls() []struct {
	Ctx            context.Context
	BlockID        string
	OrganizationID string
} {
	var calls []struct {
		Ctx            context.Context
		BlockID        string
		OrganizationID string
	}
	mock.lockFetchDocumentFile.RLock()
	calls = mock.calls.FetchDocumentFile
	mock.lockFetchDocumentFile.RUnlock()
	return calls
}

// InsertDocumentFile calls InsertDocumentFileFunc.
func (mock *DBMock) InsertDocumentFile(ctx context.Context, f document.File) error {
	callInfo := struct {
		Ctx context.Context
		F   document.File
	}{
		Ctx: ctx,
		F:   f,
	}
	mock.lockInsertDocumentFile.Lock()
	mock.calls.InsertDocumentFile = append(mock.calls.InsertDocumentFile, callInfo)
	mock.lockInsertDocumentFile.Unlock()
	if mock.InsertDocumentFileFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.InsertDocumentFileFunc(ctx, f)
}

// InsertDocumentFileCalls gets all the calls that were made to InsertDocumentFile.
// Check the length with:
//
//	len(mockedDB.InsertDocumentFileCalls())
func (mock *DBMock) InsertDocumentFileCalls() []struct {
	Ctx context.Context
	F   document.File
} {
	var calls []struct {
		Ctx context.Context
		F   document.File
	}
	mock.lockInsertDocumentFile.RLock()
	calls = mock.calls.InsertDocumentFile
	mock.lockInsertDocumentFile.RUnlock()
	return calls
}
