// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package datasource

import (
	"context"
	"sync"

	datasourceCore "github.com/oxynote/oxynote/server/core/internal/datasource"
	"github.com/oxynote/oxynote/server/core/internal/datasource/processor"
)

// Ensure, that ExecutorMock does implement Executor.
// If this is not the case, regenerate this file with moq.
var _ Executor = &ExecutorMock{}

// ExecutorMock is a mock implementation of Executor.
//
//	func TestSomethingThatUsesExecutor(t *testing.T) {
//
//		// make and configure a mocked Executor
//		mockedExecutor := &ExecutorMock{
//			MySQLQueryFunc: func(ctx context.Context, ds datasourceCore.DataSource, query string, tr processor.TimeRange) (processor.ConnectionStatus, *processor.MySQLQueryResult, error) {
//				panic("mock out the MySQLQuery method")
//			},
//			PostgreSQLQueryFunc: func(ctx context.Context, ds datasourceCore.DataSource, query string, tr processor.TimeRange) (processor.ConnectionStatus, *processor.PostgreSQLQueryResult, error) {
//				panic("mock out the PostgreSQLQuery method")
//			},
//			PrometheusLabelNamesFunc: func(ctx context.Context, ds datasourceCore.DataSource, matchers []string, tr processor.TimeRange) (processor.ConnectionStatus, *processor.PrometheusLabelNamesResult, error) {
//				panic("mock out the PrometheusLabelNames method")
//			},
//			PrometheusLabelValuesFunc: func(ctx context.Context, ds datasourceCore.DataSource, label string, matchers []string, tr processor.TimeRange) (processor.ConnectionStatus, *processor.PrometheusLabelValuesResult, error) {
//				panic("mock out the PrometheusLabelValues method")
//			},
//			PrometheusMetadataFunc: func(ctx context.Context, ds datasourceCore.DataSource) (processor.ConnectionStatus, *processor.PrometheusMetadataResult, error) {
//				panic("mock out the PrometheusMetadata method")
//			},
//			PrometheusQueryFunc: func(ctx context.Context, ds datasourceCore.DataSource, query string, tr processor.TimeRange) (processor.ConnectionStatus, *processor.PrometheusQueryResult, error) {
//				panic("mock out the PrometheusQuery method")
//			},
//			PrometheusSeriesFunc: func(ctx context.Context, ds datasourceCore.DataSource, matchers []string, tr processor.TimeRange) (processor.ConnectionStatus, *processor.PrometheusSeriesResult, error) {
//				panic("mock out the PrometheusSeries method")
//			},
//			SQLMetadataFunc: func(ctx context.Context, ds datasourceCore.DataSource) (processor.ConnectionStatus, *processor.SQLMetadataResult, error) {
//				panic("mock out the SQLMetadata method")
//			},
//			SQLQueryLabelsFunc: func(ctx context.Context, ds datasourceCore.DataSource, query string, tr processor.TimeRange) (processor.ConnectionStatus, map[string]string, error) {
//				panic("mock out the SQLQueryLabels method")
//			},
//			TestConnectionFunc: func(ctx context.Context, ds datasourceCore.DataSource) (processor.ConnectionStatus, error) {
//				panic("mock out the TestConnection method")
//			},
//		}
//
//		// use mockedExecutor in code that requires Executor
//		// and then make assertions.
//
//	}
type ExecutorMock struct {
	// MySQLQueryFunc mocks the MySQLQuery method.
	MySQLQueryFunc func(ctx context.Context, ds datasourceCore.DataSource, query string, tr processor.TimeRange) (processor.ConnectionStatus, *processor.MySQLQueryResult, error)

	// PostgreSQLQueryFunc mocks the PostgreSQLQuery method.
	PostgreSQLQueryFunc func(ctx context.Context, ds datasourceCore.DataSource, query string, tr processor.TimeRange) (processor.ConnectionStatus, *processor.PostgreSQLQueryResult, error)

	// PrometheusLabelNamesFunc mocks the PrometheusLabelNames method.
	PrometheusLabelNamesFunc func(ctx context.Context, ds datasourceCore.DataSource, matchers []string, tr processor.TimeRange) (processor.ConnectionStatus, *processor.PrometheusLabelNamesResult, error)

	// PrometheusLabelValuesFunc mocks the PrometheusLabelValues method.
	PrometheusLabelValuesFunc func(ctx context.Context, ds datasourceCore.DataSource, label string, matchers []string, tr processor.TimeRange) (processor.ConnectionStatus, *processor.PrometheusLabelValuesResult, error)

	// PrometheusMetadataFunc mocks the PrometheusMetadata method.
	PrometheusMetadataFunc func(ctx context.Context, ds datasourceCore.DataSource) (processor.ConnectionStatus, *processor.PrometheusMetadataResult, error)

	// PrometheusQueryFunc mocks the PrometheusQuery method.
	PrometheusQueryFunc func(ctx context.Context, ds datasourceCore.DataSource, query string, tr processor.TimeRange) (processor.ConnectionStatus, *processor.PrometheusQueryResult, error)

	// PrometheusSeriesFunc mocks the PrometheusSeries method.
	PrometheusSeriesFunc func(ctx context.Context, ds datasourceCore.DataSource, matchers []string, tr processor.TimeRange) (processor.ConnectionStatus, *processor.PrometheusSeriesResult, error)

	// SQLMetadataFunc mocks the SQLMetadata method.
	SQLMetadataFunc func(ctx context.Context, ds datasourceCore.DataSource) (processor.ConnectionStatus, *processor.SQLMetadataResult, error)

	// SQLQueryLabelsFunc mocks the SQLQueryLabels method.
	SQLQueryLabelsFunc func(ctx context.Context, ds datasourceCore.DataSource, query string, tr processor.TimeRange) (processor.ConnectionStatus, map[string]string, error)

	// TestConnectionFunc mocks the TestConnection method.
	TestConnectionFunc func(ctx context.Context, ds datasourceCore.DataSource) (processor.ConnectionStatus, error)

	// calls tracks calls to the methods.
	calls struct {
		// MySQLQuery holds details about calls to the MySQLQuery method.
		MySQLQuery []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Ds is the ds argument value.
			Ds datasourceCore.DataSource
			// Query is the query argument value.
			Query string
			// Tr is the tr argument value.
			Tr processor.TimeRange
		}
		// PostgreSQLQuery holds details about calls to the PostgreSQLQuery method.
		PostgreSQLQuery []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Ds is the ds argument value.
			Ds datasourceCore.DataSource
			// Query is the query argument value.
			Query string
			// Tr is the tr argument value.
			Tr processor.TimeRange
		}
		// PrometheusLabelNames holds details about calls to the PrometheusLabelNames method.
		PrometheusLabelNames []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Ds is the ds argument value.
			Ds datasourceCore.DataSource
			// Matchers is the matchers argument value.
			Matchers []string
			// Tr is the tr argument value.
			Tr processor.TimeRange
		}
		// PrometheusLabelValues holds details about calls to the PrometheusLabelValues method.
		PrometheusLabelValues []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Ds is the ds argument value.
			Ds datasourceCore.DataSource
			// Label is the label argument value.
			Label string
			// Matchers is the matchers argument value.
			Matchers []string
			// Tr is the tr argument value.
			Tr processor.TimeRange
		}
		// PrometheusMetadata holds details about calls to the PrometheusMetadata method.
		PrometheusMetadata []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Ds is the ds argument value.
			Ds datasourceCore.DataSource
		}
		// PrometheusQuery holds details about calls to the PrometheusQuery method.
		PrometheusQuery []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Ds is the ds argument value.
			Ds datasourceCore.DataSource
			// Query is the query argument value.
			Query string
			// Tr is the tr argument value.
			Tr processor.TimeRange
		}
		// PrometheusSeries holds details about calls to the PrometheusSeries method.
		PrometheusSeries []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Ds is the ds argument value.
			Ds datasourceCore.DataSource
			// Matchers is the matchers argument value.
			Matchers []string
			// Tr is the tr argument value.
			Tr processor.TimeRange
		}
		// SQLMetadata holds details about calls to the SQLMetadata method.
		SQLMetadata []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Ds is the ds argument value.
			Ds datasourceCore.DataSource
		}
		// SQLQueryLabels holds details about calls to the SQLQueryLabels method.
		SQLQueryLabels []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Ds is the ds argument value.
			Ds datasourceCore.DataSource
			// Query is the query argument value.
			Query string
			// Tr is the tr argument value.
			Tr processor.TimeRange
		}
		// TestConnection holds details about calls to the TestConnection method.
		TestConnection []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Ds is the ds argument value.
			Ds datasourceCore.DataSource
		}
	}
	lockMySQLQuery            sync.RWMutex
	lockPostgreSQLQuery       sync.RWMutex
	lockPrometheusLabelNames  sync.RWMutex
	lockPrometheusLabelValues sync.RWMutex
	lockPrometheusMetadata    sync.RWMutex
	lockPrometheusQuery       sync.RWMutex
	lockPrometheusSeries      sync.RWMutex
	lockSQLMetadata           sync.RWMutex
	lockSQLQueryLabels        sync.RWMutex
	lockTestConnection        sync.RWMutex
}

// MySQLQuery calls MySQLQueryFunc.
func (mock *ExecutorMock) MySQLQuery(ctx context.Context, ds datasourceCore.DataSource, query string, tr processor.TimeRange) (processor.ConnectionStatus, *processor.MySQLQueryResult, error) {
	callInfo := struct {
		Ctx   context.Context
		Ds    datasourceCore.DataSource
		Query string
		Tr    processor.TimeRange
	}{
		Ctx:   ctx,
		Ds:    ds,
		Query: query,
		Tr:    tr,
	}
	mock.lockMySQLQuery.Lock()
	mock.calls.MySQLQuery = append(mock.calls.MySQLQuery, callInfo)
	mock.lockMySQLQuery.Unlock()
	if mock.MySQLQueryFunc == nil {
		var (
			connectionStatusOut processor.ConnectionStatus
			mySQLQueryResultOut *processor.MySQLQueryResult
			errOut              error
		)
		return connectionStatusOut, mySQLQueryResultOut, errOut
	}
	return mock.MySQLQueryFunc(ctx, ds, query, tr)
}

// MySQLQueryCalls gets all the calls that were made to MySQLQuery.
// Check the length with:
//
//	len(mockedExecutor.MySQLQueryCalls())
func (mock *ExecutorMock) MySQLQueryCalls() []struct {
	Ctx   context.Context
	Ds    datasourceCore.DataSource
	Query string
	Tr    processor.TimeRange
} {
	var calls []struct {
		Ctx   context.Context
		Ds    datasourceCore.DataSource
		Query string
		Tr    processor.TimeRange
	}
	mock.lockMySQLQuery.RLock()
	calls = mock.calls.MySQLQuery
	mock.lockMySQLQuery.RUnlock()
	return calls
}

// PostgreSQLQuery calls PostgreSQLQueryFunc.
func (mock *ExecutorMock) PostgreSQLQuery(ctx context.Context, ds datasourceCore.DataSource, query string, tr processor.TimeRange) (processor.ConnectionStatus, *processor.PostgreSQLQueryResult, error) {
	callInfo := struct {
		Ctx   context.Context
		Ds    datasourceCore.DataSource
		Query string
		Tr    processor.TimeRange
	}{
		Ctx:   ctx,
		Ds:    ds,
		Query: query,
		Tr:    tr,
	}
	mock.lockPostgreSQLQuery.Lock()
	mock.calls.PostgreSQLQuery = append(mock.calls.PostgreSQLQuery, callInfo)
	mock.lockPostgreSQLQuery.Unlock()
	if mock.PostgreSQLQueryFunc == nil {
		var (
			connectionStatusOut      processor.ConnectionStatus
			postgreSQLQueryResultOut *processor.PostgreSQLQueryResult
			errOut                   error
		)
		return connectionStatusOut, postgreSQLQueryResultOut, errOut
	}
	return mock.PostgreSQLQueryFunc(ctx, ds, query, tr)
}

// PostgreSQLQueryCalls gets all the calls that were made to PostgreSQLQuery.
// Check the length with:
//
//	len(mockedExecutor.PostgreSQLQueryCalls())
func (mock *ExecutorMock) PostgreSQLQueryCalls() []struct {
	Ctx   context.Context
	Ds    datasourceCore.DataSource
	Query string
	Tr    processor.TimeRange
} {
	var calls []struct {
		Ctx   context.Context
		Ds    datasourceCore.DataSource
		Query string
		Tr    processor.TimeRange
	}
	mock.lockPostgreSQLQuery.RLock()
	calls = mock.calls.PostgreSQLQuery
	mock.lockPostgreSQLQuery.RUnlock()
	return calls
}

// PrometheusLabelNames calls PrometheusLabelNamesFunc.
func (mock *ExecutorMock) PrometheusLabelNames(ctx context.Context, ds datasourceCore.DataSource, matchers []string, tr processor.TimeRange) (processor.ConnectionStatus, *processor.PrometheusLabelNamesResult, error) {
	callInfo := struct {
		Ctx      context.Context
		Ds       datasourceCore.DataSource
		Matchers []string
		Tr       processor.TimeRange
	}{
		Ctx:      ctx,
		Ds:       ds,
		Matchers: matchers,
		Tr:       tr,
	}
	mock.lockPrometheusLabelNames.Lock()
	mock.calls.PrometheusLabelNames = append(mock.calls.PrometheusLabelNames, callInfo)
	mock.lockPrometheusLabelNames.Unlock()
	if mock.PrometheusLabelNamesFunc == nil {
		var (
			connectionStatusOut           processor.ConnectionStatus
			prometheusLabelNamesResultOut *processor.PrometheusLabelNamesResult
			errOut                        error
		)
		return connectionStatusOut, prometheusLabelNamesResultOut, errOut
	}
	return mock.PrometheusLabelNamesFunc(ctx, ds, matchers, tr)
}

// PrometheusLabelNamesCalls gets all the calls that were made to PrometheusLabelNames.
// Check the length with:
//
//	len(mockedExecutor.PrometheusLabelNamesCalls())
func (mock *ExecutorMock) PrometheusLabelNamesCalls() []struct {
	Ctx      context.Context
	Ds       datasourceCore.DataSource
	Matchers []string
	Tr       processor.TimeRange
} {
	var calls []struct {
		Ctx      context.Context
		Ds       datasourceCore.DataSource
		Matchers []string
		Tr       processor.TimeRange
	}
	mock.lockPrometheusLabelNames.RLock()
	calls = mock.calls.PrometheusLabelNames
	mock.lockPrometheusLabelNames.RUnlock()
	return calls
}

// PrometheusLabelValues calls PrometheusLabelValuesFunc.
func (mock *ExecutorMock) PrometheusLabelValues(ctx context.Context, ds datasourceCore.DataSource, label string, matchers []string, tr processor.TimeRange) (processor.ConnectionStatus, *processor.PrometheusLabelValuesResult, error) {
	callInfo := struct {
		Ctx      context.Context
		Ds       datasourceCore.DataSource
		Label    string
		Matchers []string
		Tr       processor.TimeRange
	}{
		Ctx:      ctx,
		Ds:       ds,
		Label:    label,
		Matchers: matchers,
		Tr:       tr,
	}
	mock.lockPrometheusLabelValues.Lock()
	mock.calls.PrometheusLabelValues = append(mock.calls.PrometheusLabelValues, callInfo)
	mock.lockPrometheusLabelValues.Unlock()
	if mock.PrometheusLabelValuesFunc == nil {
		var (
			connectionStatusOut            processor.ConnectionStatus
			prometheusLabelValuesResultOut *processor.PrometheusLabelValuesResult
			errOut                         error
		)
		return connectionStatusOut, prometheusLabelValuesResultOut, errOut
	}
	return mock.PrometheusLabelValuesFunc(ctx, ds, label, matchers, tr)
}

// PrometheusLabelValuesCalls gets all the calls that were made to PrometheusLabelValues.
// Check the length with:
//
//	len(mockedExecutor.PrometheusLabelValuesCalls())
func (mock *ExecutorMock) PrometheusLabelValuesCalls() []struct {
	Ctx      context.Context
	Ds       datasourceCore.DataSource
	Label    string
	Matchers []string
	Tr       processor.TimeRange
} {
	var calls []struct {
		Ctx      context.Context
		Ds       datasourceCore.DataSource
		Label    string
		Matchers []string
		Tr       processor.TimeRange
	}
	mock.lockPrometheusLabelValues.RLock()
	calls = mock.calls.PrometheusLabelValues
	mock.lockPrometheusLabelValues.RUnlock()
	return calls
}

// PrometheusMetadata calls PrometheusMetadataFunc.
func (mock *ExecutorMock) PrometheusMetadata(ctx context.Context, ds datasourceCore.DataSource) (processor.ConnectionStatus, *processor.PrometheusMetadataResult, error) {
	callInfo := struct {
		Ctx context.Context
		Ds  datasourceCore.DataSource
	}{
		Ctx: ctx,
		Ds:  ds,
	}
	mock.lockPrometheusMetadata.Lock()
	mock.calls.PrometheusMetadata = append(mock.calls.PrometheusMetadata, callInfo)
	mock.lockPrometheusMetadata.Unlock()
	if mock.PrometheusMetadataFunc == nil {
		var (
			connectionStatusOut         processor.ConnectionStatus
			prometheusMetadataResultOut *processor.PrometheusMetadataResult
			errOut                      error
		)
		return connectionStatusOut, prometheusMetadataResultOut, errOut
	}
	return mock.PrometheusMetadataFunc(ctx, ds)
}

// PrometheusMetadataCalls gets all the calls that were made to PrometheusMetadata.
// Check the length with:
//
//	len(mockedExecutor.PrometheusMetadataCalls())
func (mock *ExecutorMock) PrometheusMetadataCalls() []struct {
	Ctx context.Context
	Ds  datasourceCore.DataSource
} {
	var calls []struct {
		Ctx context.Context
		Ds  datasourceCore.DataSource
	}
	mock.lockPrometheusMetadata.RLock()
	calls = mock.calls.PrometheusMetadata
	mock.lockPrometheusMetadata.RUnlock()
	return calls
}

// PrometheusQuery calls PrometheusQueryFunc.
func (mock *ExecutorMock) PrometheusQuery(ctx context.Context, ds datasourceCore.DataSource, query string, tr processor.TimeRange) (processor.ConnectionStatus, *processor.PrometheusQueryResult, error) {
	callInfo := struct {
		Ctx   context.Context
		Ds    datasourceCore.DataSource
		Query string
		Tr    processor.TimeRange
	}{
		Ctx:   ctx,
		Ds:    ds,
		Query: query,
		Tr:    tr,
	}
	mock.lockPrometheusQuery.Lock()
	mock.calls.PrometheusQuery = append(mock.calls.PrometheusQuery, callInfo)
	mock.lockPrometheusQuery.Unlock()
	if mock.PrometheusQueryFunc == nil {
		var (
			connectionStatusOut      processor.ConnectionStatus
			prometheusQueryResultOut *processor.PrometheusQueryResult
			errOut                   error
		)
		return connectionStatusOut, prometheusQueryResultOut, errOut
	}
	return mock.PrometheusQueryFunc(ctx, ds, query, tr)
}

// PrometheusQueryCalls gets all the calls that were made to PrometheusQuery.
// Check the length with:
//
//	len(mockedExecutor.PrometheusQueryCalls())
func (mock *ExecutorMock) PrometheusQueryCalls() []struct {
	Ctx   context.Context
	Ds    datasourceCore.DataSource
	Query string
	Tr    processor.TimeRange
} {
	var calls []struct {
		Ctx   context.Context
		Ds    datasourceCore.DataSource
		Query string
		Tr    processor.TimeRange
	}
	mock.lockPrometheusQuery.RLock()
	calls = mock.calls.PrometheusQuery
	mock.lockPrometheusQuery.RUnlock()
	return calls
}

// PrometheusSeries calls PrometheusSeriesFunc.
func (mock *ExecutorMock) PrometheusSeries(ctx context.Context, ds datasourceCore.DataSource, matchers []string, tr processor.TimeRange) (processor.ConnectionStatus, *processor.PrometheusSeriesResult, error) {
	callInfo := struct {
		Ctx      context.Context
		Ds       datasourceCore.DataSource
		Matchers []string
		Tr       processor.TimeRange
	}{
		Ctx:      ctx,
		Ds:       ds,
		Matchers: matchers,
		Tr:       tr,
	}
	mock.lockPrometheusSeries.Lock()
	mock.calls.PrometheusSeries = append(mock.calls.PrometheusSeries, callInfo)
	mock.lockPrometheusSeries.Unlock()
	if mock.PrometheusSeriesFunc == nil {
		var (
			connectionStatusOut       processor.ConnectionStatus
			prometheusSeriesResultOut *processor.PrometheusSeriesResult
			errOut                    error
		)
		return connectionStatusOut, prometheusSeriesResultOut, errOut
	}
	return mock.PrometheusSeriesFunc(ctx, ds, matchers, tr)
}

// PrometheusSeriesCalls gets all the calls that were made to PrometheusSeries.
// Check the length with:
//
//	len(mockedExecutor.PrometheusSeriesCalls())
func (mock *ExecutorMock) PrometheusSeriesCalls() []struct {
	Ctx      context.Context
	Ds       datasourceCore.DataSource
	Matchers []string
	Tr       processor.TimeRange
} {
	var calls []struct {
		Ctx      context.Context
		Ds       datasourceCore.DataSource
		Matchers []string
		Tr       processor.TimeRange
	}
	mock.lockPrometheusSeries.RLock()
	calls = mock.calls.PrometheusSeries
	mock.lockPrometheusSeries.RUnlock()
	return calls
}

// SQLMetadata calls SQLMetadataFunc.
func (mock *ExecutorMock) SQLMetadata(ctx context.Context, ds datasourceCore.DataSource) (processor.ConnectionStatus, *processor.SQLMetadataResult, error) {
	callInfo := struct {
		Ctx context.Context
		Ds  datasourceCore.DataSource
	}{
		Ctx: ctx,
		Ds:  ds,
	}
	mock.lockSQLMetadata.Lock()
	mock.calls.SQLMetadata = append(mock.calls.SQLMetadata, callInfo)
	mock.lockSQLMetadata.Unlock()
	if mock.SQLMetadataFunc == nil {
		var (
			connectionStatusOut  processor.ConnectionStatus
			sQLMetadataResultOut *processor.SQLMetadataResult
			errOut               error
		)
		return connectionStatusOut, sQLMetadataResultOut, errOut
	}
	return mock.SQLMetadataFunc(ctx, ds)
}

// SQLMetadataCalls gets all the calls that were made to SQLMetadata.
// Check the length with:
//
//	len(mockedExecutor.SQLMetadataCalls())
func (mock *ExecutorMock) SQLMetadataCalls() []struct {
	Ctx context.Context
	Ds  datasourceCore.DataSource
} {
	var calls []struct {
		Ctx context.Context
		Ds  datasourceCore.DataSource
	}
	mock.lockSQLMetadata.RLock()
	calls = mock.calls.SQLMetadata
	mock.lockSQLMetadata.RUnlock()
	return calls
}

// SQLQueryLabels calls SQLQueryLabelsFunc.
func (mock *ExecutorMock) SQLQueryLabels(ctx context.Context, ds datasourceCore.DataSource, query string, tr processor.TimeRange) (processor.ConnectionStatus, map[string]string, error) {
	callInfo := struct {
		Ctx   context.Context
		Ds    datasourceCore.DataSource
		Query string
		Tr    processor.TimeRange
	}{
		Ctx:   ctx,
		Ds:    ds,
		Query: query,
		Tr:    tr,
	}
	mock.lockSQLQueryLabels.Lock()
	mock.calls.SQLQueryLabels = append(mock.calls.SQLQueryLabels, callInfo)
	mock.lockSQLQueryLabels.Unlock()
	if mock.SQLQueryLabelsFunc == nil {
		var (
			connectionStatusOut processor.ConnectionStatus
			stringToStringOut   map[string]string
			errOut              error
		)
		return connectionStatusOut, stringToStringOut, errOut
	}
	return mock.SQLQueryLabelsFunc(ctx, ds, query, tr)
}

// SQLQueryLabelsCalls gets all the calls that were made to SQLQueryLabels.
// Check the length with:
//
//	len(mockedExecutor.SQLQueryLabelsCalls())
func (mock *ExecutorMock) SQLQueryLabelsCalls() []struct {
	Ctx   context.Context
	Ds    datasourceCore.DataSource
	Query string
	Tr    processor.TimeRange
} {
	var calls []struct {
		Ctx   context.Context
		Ds    datasourceCore.DataSource
		Query string
		Tr    processor.TimeRange
	}
	mock.lockSQLQueryLabels.RLock()
	calls = mock.calls.SQLQueryLabels
	mock.lockSQLQueryLabels.RUnlock()
	return calls
}

// TestConnection calls TestConnectionFunc.
func (mock *ExecutorMock) TestConnection(ctx context.Context, ds datasourceCore.DataSource) (processor.ConnectionStatus, error) {
	callInfo := struct {
		Ctx context.Context
		Ds  datasourceCore.DataSource
	}{
		Ctx: ctx,
		Ds:  ds,
	}
	mock.lockTestConnection.Lock()
	mock.calls.TestConnection = append(mock.calls.TestConnection, callInfo)
	mock.lockTestConnection.Unlock()
	if mock.TestConnectionFunc == nil {
		var (
			connectionStatusOut processor.ConnectionStatus
			errOut              error
		)
		return connectionStatusOut, errOut
	}
	return mock.TestConnectionFunc(ctx, ds)
}

// TestConnectionCalls gets all the calls that were made to TestConnection.
// Check the length with:
//
//	len(mockedExecutor.TestConnectionCalls())
func (mock *ExecutorMock) TestConnectionCalls() []struct {
	Ctx context.Context
	Ds  datasourceCore.DataSource
} {
	var calls []struct {
		Ctx context.Context
		Ds  datasourceCore.DataSource
	}
	mock.lockTestConnection.RLock()
	calls = mock.calls.TestConnection
	mock.lockTestConnection.RUnlock()
	return calls
}
