// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package slack

import (
	"context"
	"sync"

	"github.com/oxynote/oxynote/server/core/internal/notification"
	"github.com/oxynote/oxynote/server/core/internal/notification/interpreter"
)

// Ensure, that InterpreterMock does implement Interpreter.
// If this is not the case, regenerate this file with moq.
var _ Interpreter = &InterpreterMock{}

// InterpreterMock is a mock implementation of Interpreter.
//
//	func TestSomethingThatUsesInterpreter(t *testing.T) {
//
//		// make and configure a mocked Interpreter
//		mockedInterpreter := &InterpreterMock{
//			InterpretNotificationFunc: func(ctx context.Context, n notification.Notification) (*interpreter.Message, error) {
//				panic("mock out the InterpretNotification method")
//			},
//		}
//
//		// use mockedInterpreter in code that requires Interpreter
//		// and then make assertions.
//
//	}
type InterpreterMock struct {
	// InterpretNotificationFunc mocks the InterpretNotification method.
	InterpretNotificationFunc func(ctx context.Context, n notification.Notification) (*interpreter.Message, error)

	// calls tracks calls to the methods.
	calls struct {
		// InterpretNotification holds details about calls to the InterpretNotification method.
		InterpretNotification []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// N is the n argument value.
			N notification.Notification
		}
	}
	lockInterpretNotification sync.RWMutex
}

// InterpretNotification calls InterpretNotificationFunc.
func (mock *InterpreterMock) InterpretNotification(ctx context.Context, n notification.Notification) (*interpreter.Message, error) {
	callInfo := struct {
		Ctx context.Context
		N   notification.Notification
	}{
		Ctx: ctx,
		N:   n,
	}
	mock.lockInterpretNotification.Lock()
	mock.calls.InterpretNotification = append(mock.calls.InterpretNotification, callInfo)
	mock.lockInterpretNotification.Unlock()
	if mock.InterpretNotificationFunc == nil {
		var (
			messageOut *interpreter.Message
			errOut     error
		)
		return messageOut, errOut
	}
	return mock.InterpretNotificationFunc(ctx, n)
}

// InterpretNotificationCalls gets all the calls that were made to InterpretNotification.
// Check the length with:
//
//	len(mockedInterpreter.InterpretNotificationCalls())
func (mock *InterpreterMock) InterpretNotificationCalls() []struct {
	Ctx context.Context
	N   notification.Notification
} {
	var calls []struct {
		Ctx context.Context
		N   notification.Notification
	}
	mock.lockInterpretNotification.RLock()
	calls = mock.calls.InterpretNotification
	mock.lockInterpretNotification.RUnlock()
	return calls
}
