// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package user

import (
	"context"
	"sync"
)

// Ensure, that DBMock does implement DB.
// If this is not the case, regenerate this file with moq.
var _ DB = &DBMock{}

// DBMock is a mock implementation of DB.
//
//	func TestSomethingThatUsesDB(t *testing.T) {
//
//		// make and configure a mocked DB
//		mockedDB := &DBMock{
//			BeginTxFunc: func(ctx context.Context, dest any) error {
//				panic("mock out the BeginTx method")
//			},
//			UpdateUserImageFunc: func(ctx context.Context, userID string, image string) error {
//				panic("mock out the UpdateUserImage method")
//			},
//		}
//
//		// use mockedDB in code that requires DB
//		// and then make assertions.
//
//	}
type DBMock struct {
	// BeginTxFunc mocks the BeginTx method.
	BeginTxFunc func(ctx context.Context, dest any) error

	// UpdateUserImageFunc mocks the UpdateUserImage method.
	UpdateUserImageFunc func(ctx context.Context, userID string, image string) error

	// calls tracks calls to the methods.
	calls struct {
		// BeginTx holds details about calls to the BeginTx method.
		BeginTx []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Dest is the dest argument value.
			Dest any
		}
		// UpdateUserImage holds details about calls to the UpdateUserImage method.
		UpdateUserImage []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID string
			// Image is the image argument value.
			Image string
		}
	}
	lockBeginTx         sync.RWMutex
	lockUpdateUserImage sync.RWMutex
}

// BeginTx calls BeginTxFunc.
func (mock *DBMock) BeginTx(ctx context.Context, dest any) error {
	callInfo := struct {
		Ctx  context.Context
		Dest any
	}{
		Ctx:  ctx,
		Dest: dest,
	}
	mock.lockBeginTx.Lock()
	mock.calls.BeginTx = append(mock.calls.BeginTx, callInfo)
	mock.lockBeginTx.Unlock()
	if mock.BeginTxFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.BeginTxFunc(ctx, dest)
}

// BeginTxCalls gets all the calls that were made to BeginTx.
// Check the length with:
//
//	len(mockedDB.BeginTxCalls())
func (mock *DBMock) BeginTxCalls() []struct {
	Ctx  context.Context
	Dest any
} {
	var calls []struct {
		Ctx  context.Context
		Dest any
	}
	mock.lockBeginTx.RLock()
	calls = mock.calls.BeginTx
	mock.lockBeginTx.RUnlock()
	return calls
}

// UpdateUserImage calls UpdateUserImageFunc.
func (mock *DBMock) UpdateUserImage(ctx context.Context, userID string, image string) error {
	callInfo := struct {
		Ctx    context.Context
		UserID string
		Image  string
	}{
		Ctx:    ctx,
		UserID: userID,
		Image:  image,
	}
	mock.lockUpdateUserImage.Lock()
	mock.calls.UpdateUserImage = append(mock.calls.UpdateUserImage, callInfo)
	mock.lockUpdateUserImage.Unlock()
	if mock.UpdateUserImageFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.UpdateUserImageFunc(ctx, userID, image)
}

// UpdateUserImageCalls gets all the calls that were made to UpdateUserImage.
// Check the length with:
//
//	len(mockedDB.UpdateUserImageCalls())
func (mock *DBMock) UpdateUserImageCalls() []struct {
	Ctx    context.Context
	UserID string
	Image  string
} {
	var calls []struct {
		Ctx    context.Context
		UserID string
		Image  string
	}
	mock.lockUpdateUserImage.RLock()
	calls = mock.calls.UpdateUserImage
	mock.lockUpdateUserImage.RUnlock()
	return calls
}
