// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package middleware

import (
	"context"
	"sync"
)

// Ensure, that WriterMock does implement Writer.
// If this is not the case, regenerate this file with moq.
var _ Writer = &WriterMock{}

// WriterMock is a mock implementation of Writer.
//
//	func TestSomethingThatUsesWriter(t *testing.T) {
//
//		// make and configure a mocked Writer
//		mockedWriter := &WriterMock{
//			WriteJSONFunc: func(ctx context.Context, msg any)  {
//				panic("mock out the WriteJSON method")
//			},
//		}
//
//		// use mockedWriter in code that requires Writer
//		// and then make assertions.
//
//	}
type WriterMock struct {
	// WriteJSONFunc mocks the WriteJSON method.
	WriteJSONFunc func(ctx context.Context, msg any)

	// calls tracks calls to the methods.
	calls struct {
		// WriteJSON holds details about calls to the WriteJSON method.
		WriteJSON []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Msg is the msg argument value.
			Msg any
		}
	}
	lockWriteJSON sync.RWMutex
}

// WriteJSON calls WriteJSONFunc.
func (mock *WriterMock) WriteJSON(ctx context.Context, msg any) {
	callInfo := struct {
		Ctx context.Context
		Msg any
	}{
		Ctx: ctx,
		Msg: msg,
	}
	mock.lockWriteJSON.Lock()
	mock.calls.WriteJSON = append(mock.calls.WriteJSON, callInfo)
	mock.lockWriteJSON.Unlock()
	if mock.WriteJSONFunc == nil {
		return
	}
	mock.WriteJSONFunc(ctx, msg)
}

// WriteJSONCalls gets all the calls that were made to WriteJSON.
// Check the length with:
//
//	len(mockedWriter.WriteJSONCalls())
func (mock *WriterMock) WriteJSONCalls() []struct {
	Ctx context.Context
	Msg any
} {
	var calls []struct {
		Ctx context.Context
		Msg any
	}
	mock.lockWriteJSON.RLock()
	calls = mock.calls.WriteJSON
	mock.lockWriteJSON.RUnlock()
	return calls
}
