// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package block

import (
	"context"
	"sync"

	"github.com/rs/xid"
)

// Ensure, that RunnerMock does implement Runner.
// If this is not the case, regenerate this file with moq.
var _ Runner = &RunnerMock{}

// RunnerMock is a mock implementation of Runner.
//
//	func TestSomethingThatUsesRunner(t *testing.T) {
//
//		// make and configure a mocked Runner
//		mockedRunner := &RunnerMock{
//			RunFunc: func(ctx context.Context, documentID xid.ID, branchID xid.ID, blockUID string, organizationID string) (any, error) {
//				panic("mock out the Run method")
//			},
//		}
//
//		// use mockedRunner in code that requires Runner
//		// and then make assertions.
//
//	}
type RunnerMock struct {
	// RunFunc mocks the Run method.
	RunFunc func(ctx context.Context, documentID xid.ID, branchID xid.ID, blockUID string, organizationID string) (any, error)

	// calls tracks calls to the methods.
	calls struct {
		// Run holds details about calls to the Run method.
		Run []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// DocumentID is the documentID argument value.
			DocumentID xid.ID
			// BranchID is the branchID argument value.
			BranchID xid.ID
			// BlockUID is the blockUID argument value.
			BlockUID string
			// OrganizationID is the organizationID argument value.
			OrganizationID string
		}
	}
	lockRun sync.RWMutex
}

// Run calls RunFunc.
func (mock *RunnerMock) Run(ctx context.Context, documentID xid.ID, branchID xid.ID, blockUID string, organizationID string) (any, error) {
	callInfo := struct {
		Ctx            context.Context
		DocumentID     xid.ID
		BranchID       xid.ID
		BlockUID       string
		OrganizationID string
	}{
		Ctx:            ctx,
		DocumentID:     documentID,
		BranchID:       branchID,
		BlockUID:       blockUID,
		OrganizationID: organizationID,
	}
	mock.lockRun.Lock()
	mock.calls.Run = append(mock.calls.Run, callInfo)
	mock.lockRun.Unlock()
	if mock.RunFunc == nil {
		var (
			ifaceValOut any
			errOut      error
		)
		return ifaceValOut, errOut
	}
	return mock.RunFunc(ctx, documentID, branchID, blockUID, organizationID)
}

// RunCalls gets all the calls that were made to Run.
// Check the length with:
//
//	len(mockedRunner.RunCalls())
func (mock *RunnerMock) RunCalls() []struct {
	Ctx            context.Context
	DocumentID     xid.ID
	BranchID       xid.ID
	BlockUID       string
	OrganizationID string
} {
	var calls []struct {
		Ctx            context.Context
		DocumentID     xid.ID
		BranchID       xid.ID
		BlockUID       string
		OrganizationID string
	}
	mock.lockRun.RLock()
	calls = mock.calls.Run
	mock.lockRun.RUnlock()
	return calls
}
