// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package tag

import (
	"context"
	"sync"

	tagCore "github.com/oxynote/oxynote/server/core/internal/tag"
	"github.com/rs/xid"
)

// Ensure, that DBMock does implement DB.
// If this is not the case, regenerate this file with moq.
var _ DB = &DBMock{}

// DBMock is a mock implementation of DB.
//
//	func TestSomethingThatUsesDB(t *testing.T) {
//
//		// make and configure a mocked DB
//		mockedDB := &DBMock{
//			FetchTagTreeFunc: func(ctx context.Context, organizationID string) (tagCore.Summaries, error) {
//				panic("mock out the FetchTagTree method")
//			},
//			UpdateTagTreeFunc: func(ctx context.Context, tree tagCore.Summaries, organizationID string) error {
//				panic("mock out the UpdateTagTree method")
//			},
//			InsertTagFunc: func(ctx context.Context, t tagCore.Tag) error {
//				panic("mock out the InsertTag method")
//			},
//			DeleteTagFunc: func(ctx context.Context, id xid.ID, organizationID string) error {
//				panic("mock out the DeleteTag method")
//			},
//			AssignDocumentTagFunc: func(ctx context.Context, organizationID string, documentID xid.ID, tagID xid.ID) error {
//				panic("mock out the AssignDocumentTag method")
//			},
//			UnassignDocumentTagFunc: func(ctx context.Context, organizationID string, documentID xid.ID, tagID xid.ID) error {
//				panic("mock out the UnassignDocumentTag method")
//			},
//		}
//
//		// use mockedDB in code that requires DB
//		// and then make assertions.
//
//	}
type DBMock struct {
	// FetchTagTreeFunc mocks the FetchTagTree method.
	FetchTagTreeFunc func(ctx context.Context, organizationID string, userID string) (tagCore.Summaries, error)

	// UpdateTagTreeFunc mocks the UpdateTagTree method.
	UpdateTagTreeFunc func(ctx context.Context, tree tagCore.Summaries, organizationID string) error

	// InsertTagFunc mocks the InsertTag method.
	InsertTagFunc func(ctx context.Context, t tagCore.Tag) error

	// SetTagVisibilityFunc mocks the SetTagVisibility method.
	SetTagVisibilityFunc func(ctx context.Context, organizationID string, userID string, id xid.ID, inp tagCore.VisibilityInput) error

	// DeleteTagFunc mocks the DeleteTag method.
	DeleteTagFunc func(ctx context.Context, id xid.ID, organizationID string) error

	// AssignDocumentTagFunc mocks the AssignDocumentTag method.
	AssignDocumentTagFunc func(ctx context.Context, organizationID string, documentID xid.ID, tagID xid.ID) error

	// UnassignDocumentTagFunc mocks the UnassignDocumentTag method.
	UnassignDocumentTagFunc func(ctx context.Context, organizationID string, documentID xid.ID, tagID xid.ID) error

	// calls tracks calls to the methods.
	calls struct {
		// FetchTagTree holds details about calls to the FetchTagTree method.
		FetchTagTree []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrganizationID is the organizationID argument value.
			OrganizationID string
			// UserID is the userID argument value.
			UserID string
		}
		// UpdateTagTree holds details about calls to the UpdateTagTree method.
		UpdateTagTree []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Tree is the tree argument value.
			Tree tagCore.Summaries
			// OrganizationID is the organizationID argument value.
			OrganizationID string
		}
		// InsertTag holds details about calls to the InsertTag method.
		InsertTag []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// T is the t argument value.
			T tagCore.Tag
		}
		// SetTagVisibility holds details about calls to the SetTagVisibility method.
		SetTagVisibility []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrganizationID is the organizationID argument value.
			OrganizationID string
			// UserID is the userID argument value.
			UserID string
			// ID is the id argument value.
			ID xid.ID
			// Inp is the inp argument value.
			Inp tagCore.VisibilityInput
		}
		// DeleteTag holds details about calls to the DeleteTag method.
		DeleteTag []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID xid.ID
			// OrganizationID is the organizationID argument value.
			OrganizationID string
		}
		// AssignDocumentTag holds details about calls to the AssignDocumentTag method.
		AssignDocumentTag []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrganizationID is the organizationID argument value.
			OrganizationID string
			// DocumentID is the documentID argument value.
			DocumentID xid.ID
			// TagID is the tagID argument value.
			TagID xid.ID
		}
		// UnassignDocumentTag holds details about calls to the UnassignDocumentTag method.
		UnassignDocumentTag []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrganizationID is the organizationID argument value.
			OrganizationID string
			// DocumentID is the documentID argument value.
			DocumentID xid.ID
			// TagID is the tagID argument value.
			TagID xid.ID
		}
	}
	lockFetchTagTree        sync.RWMutex
	lockUpdateTagTree       sync.RWMutex
	lockInsertTag           sync.RWMutex
	lockSetTagVisibility    sync.RWMutex
	lockDeleteTag           sync.RWMutex
	lockAssignDocumentTag   sync.RWMutex
	lockUnassignDocumentTag sync.RWMutex
}

// FetchTagTree calls FetchTagTreeFunc.
func (mock *DBMock) FetchTagTree(ctx context.Context, organizationID string, userID string) (tagCore.Summaries, error) {
	callInfo := struct {
		Ctx            context.Context
		OrganizationID string
		UserID         string
	}{
		Ctx:            ctx,
		OrganizationID: organizationID,
		UserID:         userID,
	}
	mock.lockFetchTagTree.Lock()
	mock.calls.FetchTagTree = append(mock.calls.FetchTagTree, callInfo)
	mock.lockFetchTagTree.Unlock()
	if mock.FetchTagTreeFunc == nil {
		var (
			summariesOut tagCore.Summaries
			errOut       error
		)
		return summariesOut, errOut
	}
	return mock.FetchTagTreeFunc(ctx, organizationID, userID)
}

// FetchTagTreeCalls gets all the calls that were made to FetchTagTree.
// Check the length with:
//
//	len(mockedDB.FetchTagTreeCalls())
func (mock *DBMock) FetchTagTreeCalls() []struct {
	Ctx            context.Context
	OrganizationID string
	UserID         string
} {
	var calls []struct {
		Ctx            context.Context
		OrganizationID string
		UserID         string
	}
	mock.lockFetchTagTree.RLock()
	calls = mock.calls.FetchTagTree
	mock.lockFetchTagTree.RUnlock()
	return calls
}

// UpdateTagTree calls UpdateTagTreeFunc.
func (mock *DBMock) UpdateTagTree(ctx context.Context, tree tagCore.Summaries, organizationID string) error {
	callInfo := struct {
		Ctx            context.Context
		Tree           tagCore.Summaries
		OrganizationID string
	}{
		Ctx:            ctx,
		Tree:           tree,
		OrganizationID: organizationID,
	}
	mock.lockUpdateTagTree.Lock()
	mock.calls.UpdateTagTree = append(mock.calls.UpdateTagTree, callInfo)
	mock.lockUpdateTagTree.Unlock()
	if mock.UpdateTagTreeFunc == nil {
		var errOut error
		return errOut
	}
	return mock.UpdateTagTreeFunc(ctx, tree, organizationID)
}

// UpdateTagTreeCalls gets all the calls that were made to UpdateTagTree.
// Check the length with:
//
//	len(mockedDB.UpdateTagTreeCalls())
func (mock *DBMock) UpdateTagTreeCalls() []struct {
	Ctx            context.Context
	Tree           tagCore.Summaries
	OrganizationID string
} {
	var calls []struct {
		Ctx            context.Context
		Tree           tagCore.Summaries
		OrganizationID string
	}
	mock.lockUpdateTagTree.RLock()
	calls = mock.calls.UpdateTagTree
	mock.lockUpdateTagTree.RUnlock()
	return calls
}

// InsertTag calls InsertTagFunc.
func (mock *DBMock) InsertTag(ctx context.Context, t tagCore.Tag) error {
	callInfo := struct {
		Ctx context.Context
		T   tagCore.Tag
	}{
		Ctx: ctx,
		T:   t,
	}
	mock.lockInsertTag.Lock()
	mock.calls.InsertTag = append(mock.calls.InsertTag, callInfo)
	mock.lockInsertTag.Unlock()
	if mock.InsertTagFunc == nil {
		var errOut error
		return errOut
	}
	return mock.InsertTagFunc(ctx, t)
}

// InsertTagCalls gets all the calls that were made to InsertTag.
// Check the length with:
//
//	len(mockedDB.InsertTagCalls())
func (mock *DBMock) InsertTagCalls() []struct {
	Ctx context.Context
	T   tagCore.Tag
} {
	var calls []struct {
		Ctx context.Context
		T   tagCore.Tag
	}
	mock.lockInsertTag.RLock()
	calls = mock.calls.InsertTag
	mock.lockInsertTag.RUnlock()
	return calls
}

// SetTagVisibility calls SetTagVisibilityFunc.
func (mock *DBMock) SetTagVisibility(ctx context.Context, organizationID string, userID string, id xid.ID, inp tagCore.VisibilityInput) error {
	callInfo := struct {
		Ctx            context.Context
		OrganizationID string
		UserID         string
		ID             xid.ID
		Inp            tagCore.VisibilityInput
	}{
		Ctx:            ctx,
		OrganizationID: organizationID,
		UserID:         userID,
		ID:             id,
		Inp:            inp,
	}
	mock.lockSetTagVisibility.Lock()
	mock.calls.SetTagVisibility = append(mock.calls.SetTagVisibility, callInfo)
	mock.lockSetTagVisibility.Unlock()
	if mock.SetTagVisibilityFunc == nil {
		var errOut error
		return errOut
	}
	return mock.SetTagVisibilityFunc(ctx, organizationID, userID, id, inp)
}

// SetTagVisibilityCalls gets all the calls that were made to SetTagVisibility.
// Check the length with:
//
//	len(mockedDB.SetTagVisibilityCalls())
func (mock *DBMock) SetTagVisibilityCalls() []struct {
	Ctx            context.Context
	OrganizationID string
	UserID         string
	ID             xid.ID
	Inp            tagCore.VisibilityInput
} {
	var calls []struct {
		Ctx            context.Context
		OrganizationID string
		UserID         string
		ID             xid.ID
		Inp            tagCore.VisibilityInput
	}
	mock.lockSetTagVisibility.RLock()
	calls = mock.calls.SetTagVisibility
	mock.lockSetTagVisibility.RUnlock()
	return calls
}

// DeleteTag calls DeleteTagFunc.
func (mock *DBMock) DeleteTag(ctx context.Context, id xid.ID, organizationID string) error {
	callInfo := struct {
		Ctx            context.Context
		ID             xid.ID
		OrganizationID string
	}{
		Ctx:            ctx,
		ID:             id,
		OrganizationID: organizationID,
	}
	mock.lockDeleteTag.Lock()
	mock.calls.DeleteTag = append(mock.calls.DeleteTag, callInfo)
	mock.lockDeleteTag.Unlock()
	if mock.DeleteTagFunc == nil {
		var errOut error
		return errOut
	}
	return mock.DeleteTagFunc(ctx, id, organizationID)
}

// DeleteTagCalls gets all the calls that were made to DeleteTag.
// Check the length with:
//
//	len(mockedDB.DeleteTagCalls())
func (mock *DBMock) DeleteTagCalls() []struct {
	Ctx            context.Context
	ID             xid.ID
	OrganizationID string
} {
	var calls []struct {
		Ctx            context.Context
		ID             xid.ID
		OrganizationID string
	}
	mock.lockDeleteTag.RLock()
	calls = mock.calls.DeleteTag
	mock.lockDeleteTag.RUnlock()
	return calls
}

// AssignDocumentTag calls AssignDocumentTagFunc.
func (mock *DBMock) AssignDocumentTag(ctx context.Context, organizationID string, documentID xid.ID, tagID xid.ID) error {
	callInfo := struct {
		Ctx            context.Context
		OrganizationID string
		DocumentID     xid.ID
		TagID          xid.ID
	}{
		Ctx:            ctx,
		OrganizationID: organizationID,
		DocumentID:     documentID,
		TagID:          tagID,
	}
	mock.lockAssignDocumentTag.Lock()
	mock.calls.AssignDocumentTag = append(mock.calls.AssignDocumentTag, callInfo)
	mock.lockAssignDocumentTag.Unlock()
	if mock.AssignDocumentTagFunc == nil {
		var errOut error
		return errOut
	}
	return mock.AssignDocumentTagFunc(ctx, organizationID, documentID, tagID)
}

// AssignDocumentTagCalls gets all the calls that were made to AssignDocumentTag.
// Check the length with:
//
//	len(mockedDB.AssignDocumentTagCalls())
func (mock *DBMock) AssignDocumentTagCalls() []struct {
	Ctx            context.Context
	OrganizationID string
	DocumentID     xid.ID
	TagID          xid.ID
} {
	var calls []struct {
		Ctx            context.Context
		OrganizationID string
		DocumentID     xid.ID
		TagID          xid.ID
	}
	mock.lockAssignDocumentTag.RLock()
	calls = mock.calls.AssignDocumentTag
	mock.lockAssignDocumentTag.RUnlock()
	return calls
}

// UnassignDocumentTag calls UnassignDocumentTagFunc.
func (mock *DBMock) UnassignDocumentTag(ctx context.Context, organizationID string, documentID xid.ID, tagID xid.ID) error {
	callInfo := struct {
		Ctx            context.Context
		OrganizationID string
		DocumentID     xid.ID
		TagID          xid.ID
	}{
		Ctx:            ctx,
		OrganizationID: organizationID,
		DocumentID:     documentID,
		TagID:          tagID,
	}
	mock.lockUnassignDocumentTag.Lock()
	mock.calls.UnassignDocumentTag = append(mock.calls.UnassignDocumentTag, callInfo)
	mock.lockUnassignDocumentTag.Unlock()
	if mock.UnassignDocumentTagFunc == nil {
		var errOut error
		return errOut
	}
	return mock.UnassignDocumentTagFunc(ctx, organizationID, documentID, tagID)
}

// UnassignDocumentTagCalls gets all the calls that were made to UnassignDocumentTag.
// Check the length with:
//
//	len(mockedDB.UnassignDocumentTagCalls())
func (mock *DBMock) UnassignDocumentTagCalls() []struct {
	Ctx            context.Context
	OrganizationID string
	DocumentID     xid.ID
	TagID          xid.ID
} {
	var calls []struct {
		Ctx            context.Context
		OrganizationID string
		DocumentID     xid.ID
		TagID          xid.ID
	}
	mock.lockUnassignDocumentTag.RLock()
	calls = mock.calls.UnassignDocumentTag
	mock.lockUnassignDocumentTag.RUnlock()
	return calls
}
