// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package tag

import (
	"context"
	"sync"

	tagCore "github.com/oxynote/oxynote/server/core/internal/tag"
	"github.com/rs/xid"
)

// Ensure, that DBMock does implement DB.
// If this is not the case, regenerate this file with moq.
var _ DB = &DBMock{}

// DBMock is a mock implementation of DB.
//
//	func TestSomethingThatUsesDB(t *testing.T) {
//
//		// make and configure a mocked DB
//		mockedDB := &DBMock{
//			AssignBranchTagFunc: func(ctx context.Context, organizationID string, documentID xid.ID, branchID xid.ID, tagID xid.ID) error {
//				panic("mock out the AssignBranchTag method")
//			},
//			DeleteTagFunc: func(ctx context.Context, id xid.ID, organizationID string) error {
//				panic("mock out the DeleteTag method")
//			},
//			FetchBranchTagIDsFunc: func(ctx context.Context, organizationID string, documentID xid.ID, branchID xid.ID) ([]xid.ID, error) {
//				panic("mock out the FetchBranchTagIDs method")
//			},
//			FetchTagTreeFunc: func(ctx context.Context, organizationID string, userID string) (tagCore.Summaries, error) {
//				panic("mock out the FetchTagTree method")
//			},
//			InsertTagFunc: func(ctx context.Context, t tagCore.Tag) error {
//				panic("mock out the InsertTag method")
//			},
//			SetTagVisibilityFunc: func(ctx context.Context, organizationID string, userID string, id xid.ID, inp tagCore.VisibilityInput) error {
//				panic("mock out the SetTagVisibility method")
//			},
//			UnassignBranchTagFunc: func(ctx context.Context, organizationID string, documentID xid.ID, branchID xid.ID, tagID xid.ID) error {
//				panic("mock out the UnassignBranchTag method")
//			},
//			UpdateTagTreeFunc: func(ctx context.Context, tree tagCore.Summaries, organizationID string) error {
//				panic("mock out the UpdateTagTree method")
//			},
//		}
//
//		// use mockedDB in code that requires DB
//		// and then make assertions.
//
//	}
type DBMock struct {
	// AssignBranchTagFunc mocks the AssignBranchTag method.
	AssignBranchTagFunc func(ctx context.Context, organizationID string, documentID xid.ID, branchID xid.ID, tagID xid.ID) error

	// DeleteTagFunc mocks the DeleteTag method.
	DeleteTagFunc func(ctx context.Context, id xid.ID, organizationID string) error

	// FetchBranchTagIDsFunc mocks the FetchBranchTagIDs method.
	FetchBranchTagIDsFunc func(ctx context.Context, organizationID string, documentID xid.ID, branchID xid.ID) ([]xid.ID, error)

	// FetchTagTreeFunc mocks the FetchTagTree method.
	FetchTagTreeFunc func(ctx context.Context, organizationID string, userID string) (tagCore.Summaries, error)

	// InsertTagFunc mocks the InsertTag method.
	InsertTagFunc func(ctx context.Context, t tagCore.Tag) error

	// SetTagVisibilityFunc mocks the SetTagVisibility method.
	SetTagVisibilityFunc func(ctx context.Context, organizationID string, userID string, id xid.ID, inp tagCore.VisibilityInput) error

	// UnassignBranchTagFunc mocks the UnassignBranchTag method.
	UnassignBranchTagFunc func(ctx context.Context, organizationID string, documentID xid.ID, branchID xid.ID, tagID xid.ID) error

	// UpdateTagTreeFunc mocks the UpdateTagTree method.
	UpdateTagTreeFunc func(ctx context.Context, tree tagCore.Summaries, organizationID string) error

	// calls tracks calls to the methods.
	calls struct {
		// AssignBranchTag holds details about calls to the AssignBranchTag method.
		AssignBranchTag []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrganizationID is the organizationID argument value.
			OrganizationID string
			// DocumentID is the documentID argument value.
			DocumentID xid.ID
			// BranchID is the branchID argument value.
			BranchID xid.ID
			// TagID is the tagID argument value.
			TagID xid.ID
		}
		// DeleteTag holds details about calls to the DeleteTag method.
		DeleteTag []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID xid.ID
			// OrganizationID is the organizationID argument value.
			OrganizationID string
		}
		// FetchBranchTagIDs holds details about calls to the FetchBranchTagIDs method.
		FetchBranchTagIDs []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrganizationID is the organizationID argument value.
			OrganizationID string
			// DocumentID is the documentID argument value.
			DocumentID xid.ID
			// BranchID is the branchID argument value.
			BranchID xid.ID
		}
		// FetchTagTree holds details about calls to the FetchTagTree method.
		FetchTagTree []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrganizationID is the organizationID argument value.
			OrganizationID string
			// UserID is the userID argument value.
			UserID string
		}
		// InsertTag holds details about calls to the InsertTag method.
		InsertTag []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// T is the t argument value.
			T tagCore.Tag
		}
		// SetTagVisibility holds details about calls to the SetTagVisibility method.
		SetTagVisibility []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrganizationID is the organizationID argument value.
			OrganizationID string
			// UserID is the userID argument value.
			UserID string
			// ID is the id argument value.
			ID xid.ID
			// Inp is the inp argument value.
			Inp tagCore.VisibilityInput
		}
		// UnassignBranchTag holds details about calls to the UnassignBranchTag method.
		UnassignBranchTag []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrganizationID is the organizationID argument value.
			OrganizationID string
			// DocumentID is the documentID argument value.
			DocumentID xid.ID
			// BranchID is the branchID argument value.
			BranchID xid.ID
			// TagID is the tagID argument value.
			TagID xid.ID
		}
		// UpdateTagTree holds details about calls to the UpdateTagTree method.
		UpdateTagTree []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Tree is the tree argument value.
			Tree tagCore.Summaries
			// OrganizationID is the organizationID argument value.
			OrganizationID string
		}
	}
	lockAssignBranchTag   sync.RWMutex
	lockDeleteTag         sync.RWMutex
	lockFetchBranchTagIDs sync.RWMutex
	lockFetchTagTree      sync.RWMutex
	lockInsertTag         sync.RWMutex
	lockSetTagVisibility  sync.RWMutex
	lockUnassignBranchTag sync.RWMutex
	lockUpdateTagTree     sync.RWMutex
}

// AssignBranchTag calls AssignBranchTagFunc.
func (mock *DBMock) AssignBranchTag(ctx context.Context, organizationID string, documentID xid.ID, branchID xid.ID, tagID xid.ID) error {
	callInfo := struct {
		Ctx            context.Context
		OrganizationID string
		DocumentID     xid.ID
		BranchID       xid.ID
		TagID          xid.ID
	}{
		Ctx:            ctx,
		OrganizationID: organizationID,
		DocumentID:     documentID,
		BranchID:       branchID,
		TagID:          tagID,
	}
	mock.lockAssignBranchTag.Lock()
	mock.calls.AssignBranchTag = append(mock.calls.AssignBranchTag, callInfo)
	mock.lockAssignBranchTag.Unlock()
	if mock.AssignBranchTagFunc == nil {
		var errOut error
		return errOut
	}
	return mock.AssignBranchTagFunc(ctx, organizationID, documentID, branchID, tagID)
}

// AssignBranchTagCalls gets all the calls that were made to AssignBranchTag.
// Check the length with:
//
//	len(mockedDB.AssignBranchTagCalls())
func (mock *DBMock) AssignBranchTagCalls() []struct {
	Ctx            context.Context
	OrganizationID string
	DocumentID     xid.ID
	BranchID       xid.ID
	TagID          xid.ID
} {
	var calls []struct {
		Ctx            context.Context
		OrganizationID string
		DocumentID     xid.ID
		BranchID       xid.ID
		TagID          xid.ID
	}
	mock.lockAssignBranchTag.RLock()
	calls = mock.calls.AssignBranchTag
	mock.lockAssignBranchTag.RUnlock()
	return calls
}

// DeleteTag calls DeleteTagFunc.
func (mock *DBMock) DeleteTag(ctx context.Context, id xid.ID, organizationID string) error {
	callInfo := struct {
		Ctx            context.Context
		ID             xid.ID
		OrganizationID string
	}{
		Ctx:            ctx,
		ID:             id,
		OrganizationID: organizationID,
	}
	mock.lockDeleteTag.Lock()
	mock.calls.DeleteTag = append(mock.calls.DeleteTag, callInfo)
	mock.lockDeleteTag.Unlock()
	if mock.DeleteTagFunc == nil {
		var errOut error
		return errOut
	}
	return mock.DeleteTagFunc(ctx, id, organizationID)
}

// DeleteTagCalls gets all the calls that were made to DeleteTag.
// Check the length with:
//
//	len(mockedDB.DeleteTagCalls())
func (mock *DBMock) DeleteTagCalls() []struct {
	Ctx            context.Context
	ID             xid.ID
	OrganizationID string
} {
	var calls []struct {
		Ctx            context.Context
		ID             xid.ID
		OrganizationID string
	}
	mock.lockDeleteTag.RLock()
	calls = mock.calls.DeleteTag
	mock.lockDeleteTag.RUnlock()
	return calls
}

// FetchBranchTagIDs calls FetchBranchTagIDsFunc.
func (mock *DBMock) FetchBranchTagIDs(ctx context.Context, organizationID string, documentID xid.ID, branchID xid.ID) ([]xid.ID, error) {
	callInfo := struct {
		Ctx            context.Context
		OrganizationID string
		DocumentID     xid.ID
		BranchID       xid.ID
	}{
		Ctx:            ctx,
		OrganizationID: organizationID,
		DocumentID:     documentID,
		BranchID:       branchID,
	}
	mock.lockFetchBranchTagIDs.Lock()
	mock.calls.FetchBranchTagIDs = append(mock.calls.FetchBranchTagIDs, callInfo)
	mock.lockFetchBranchTagIDs.Unlock()
	if mock.FetchBranchTagIDsFunc == nil {
		var (
			idsOut []xid.ID
			errOut error
		)
		return idsOut, errOut
	}
	return mock.FetchBranchTagIDsFunc(ctx, organizationID, documentID, branchID)
}

// FetchBranchTagIDsCalls gets all the calls that were made to FetchBranchTagIDs.
// Check the length with:
//
//	len(mockedDB.FetchBranchTagIDsCalls())
func (mock *DBMock) FetchBranchTagIDsCalls() []struct {
	Ctx            context.Context
	OrganizationID string
	DocumentID     xid.ID
	BranchID       xid.ID
} {
	var calls []struct {
		Ctx            context.Context
		OrganizationID string
		DocumentID     xid.ID
		BranchID       xid.ID
	}
	mock.lockFetchBranchTagIDs.RLock()
	calls = mock.calls.FetchBranchTagIDs
	mock.lockFetchBranchTagIDs.RUnlock()
	return calls
}

// FetchTagTree calls FetchTagTreeFunc.
func (mock *DBMock) FetchTagTree(ctx context.Context, organizationID string, userID string) (tagCore.Summaries, error) {
	callInfo := struct {
		Ctx            context.Context
		OrganizationID string
		UserID         string
	}{
		Ctx:            ctx,
		OrganizationID: organizationID,
		UserID:         userID,
	}
	mock.lockFetchTagTree.Lock()
	mock.calls.FetchTagTree = append(mock.calls.FetchTagTree, callInfo)
	mock.lockFetchTagTree.Unlock()
	if mock.FetchTagTreeFunc == nil {
		var (
			summariesOut tagCore.Summaries
			errOut       error
		)
		return summariesOut, errOut
	}
	return mock.FetchTagTreeFunc(ctx, organizationID, userID)
}

// FetchTagTreeCalls gets all the calls that were made to FetchTagTree.
// Check the length with:
//
//	len(mockedDB.FetchTagTreeCalls())
func (mock *DBMock) FetchTagTreeCalls() []struct {
	Ctx            context.Context
	OrganizationID string
	UserID         string
} {
	var calls []struct {
		Ctx            context.Context
		OrganizationID string
		UserID         string
	}
	mock.lockFetchTagTree.RLock()
	calls = mock.calls.FetchTagTree
	mock.lockFetchTagTree.RUnlock()
	return calls
}

// InsertTag calls InsertTagFunc.
func (mock *DBMock) InsertTag(ctx context.Context, t tagCore.Tag) error {
	callInfo := struct {
		Ctx context.Context
		T   tagCore.Tag
	}{
		Ctx: ctx,
		T:   t,
	}
	mock.lockInsertTag.Lock()
	mock.calls.InsertTag = append(mock.calls.InsertTag, callInfo)
	mock.lockInsertTag.Unlock()
	if mock.InsertTagFunc == nil {
		var errOut error
		return errOut
	}
	return mock.InsertTagFunc(ctx, t)
}

// InsertTagCalls gets all the calls that were made to InsertTag.
// Check the length with:
//
//	len(mockedDB.InsertTagCalls())
func (mock *DBMock) InsertTagCalls() []struct {
	Ctx context.Context
	T   tagCore.Tag
} {
	var calls []struct {
		Ctx context.Context
		T   tagCore.Tag
	}
	mock.lockInsertTag.RLock()
	calls = mock.calls.InsertTag
	mock.lockInsertTag.RUnlock()
	return calls
}

// SetTagVisibility calls SetTagVisibilityFunc.
func (mock *DBMock) SetTagVisibility(ctx context.Context, organizationID string, userID string, id xid.ID, inp tagCore.VisibilityInput) error {
	callInfo := struct {
		Ctx            context.Context
		OrganizationID string
		UserID         string
		ID             xid.ID
		Inp            tagCore.VisibilityInput
	}{
		Ctx:            ctx,
		OrganizationID: organizationID,
		UserID:         userID,
		ID:             id,
		Inp:            inp,
	}
	mock.lockSetTagVisibility.Lock()
	mock.calls.SetTagVisibility = append(mock.calls.SetTagVisibility, callInfo)
	mock.lockSetTagVisibility.Unlock()
	if mock.SetTagVisibilityFunc == nil {
		var errOut error
		return errOut
	}
	return mock.SetTagVisibilityFunc(ctx, organizationID, userID, id, inp)
}

// SetTagVisibilityCalls gets all the calls that were made to SetTagVisibility.
// Check the length with:
//
//	len(mockedDB.SetTagVisibilityCalls())
func (mock *DBMock) SetTagVisibilityCalls() []struct {
	Ctx            context.Context
	OrganizationID string
	UserID         string
	ID             xid.ID
	Inp            tagCore.VisibilityInput
} {
	var calls []struct {
		Ctx            context.Context
		OrganizationID string
		UserID         string
		ID             xid.ID
		Inp            tagCore.VisibilityInput
	}
	mock.lockSetTagVisibility.RLock()
	calls = mock.calls.SetTagVisibility
	mock.lockSetTagVisibility.RUnlock()
	return calls
}

// UnassignBranchTag calls UnassignBranchTagFunc.
func (mock *DBMock) UnassignBranchTag(ctx context.Context, organizationID string, documentID xid.ID, branchID xid.ID, tagID xid.ID) error {
	callInfo := struct {
		Ctx            context.Context
		OrganizationID string
		DocumentID     xid.ID
		BranchID       xid.ID
		TagID          xid.ID
	}{
		Ctx:            ctx,
		OrganizationID: organizationID,
		DocumentID:     documentID,
		BranchID:       branchID,
		TagID:          tagID,
	}
	mock.lockUnassignBranchTag.Lock()
	mock.calls.UnassignBranchTag = append(mock.calls.UnassignBranchTag, callInfo)
	mock.lockUnassignBranchTag.Unlock()
	if mock.UnassignBranchTagFunc == nil {
		var errOut error
		return errOut
	}
	return mock.UnassignBranchTagFunc(ctx, organizationID, documentID, branchID, tagID)
}

// UnassignBranchTagCalls gets all the calls that were made to UnassignBranchTag.
// Check the length with:
//
//	len(mockedDB.UnassignBranchTagCalls())
func (mock *DBMock) UnassignBranchTagCalls() []struct {
	Ctx            context.Context
	OrganizationID string
	DocumentID     xid.ID
	BranchID       xid.ID
	TagID          xid.ID
} {
	var calls []struct {
		Ctx            context.Context
		OrganizationID string
		DocumentID     xid.ID
		BranchID       xid.ID
		TagID          xid.ID
	}
	mock.lockUnassignBranchTag.RLock()
	calls = mock.calls.UnassignBranchTag
	mock.lockUnassignBranchTag.RUnlock()
	return calls
}

// UpdateTagTree calls UpdateTagTreeFunc.
func (mock *DBMock) UpdateTagTree(ctx context.Context, tree tagCore.Summaries, organizationID string) error {
	callInfo := struct {
		Ctx            context.Context
		Tree           tagCore.Summaries
		OrganizationID string
	}{
		Ctx:            ctx,
		Tree:           tree,
		OrganizationID: organizationID,
	}
	mock.lockUpdateTagTree.Lock()
	mock.calls.UpdateTagTree = append(mock.calls.UpdateTagTree, callInfo)
	mock.lockUpdateTagTree.Unlock()
	if mock.UpdateTagTreeFunc == nil {
		var errOut error
		return errOut
	}
	return mock.UpdateTagTreeFunc(ctx, tree, organizationID)
}

// UpdateTagTreeCalls gets all the calls that were made to UpdateTagTree.
// Check the length with:
//
//	len(mockedDB.UpdateTagTreeCalls())
func (mock *DBMock) UpdateTagTreeCalls() []struct {
	Ctx            context.Context
	Tree           tagCore.Summaries
	OrganizationID string
} {
	var calls []struct {
		Ctx            context.Context
		Tree           tagCore.Summaries
		OrganizationID string
	}
	mock.lockUpdateTagTree.RLock()
	calls = mock.calls.UpdateTagTree
	mock.lockUpdateTagTree.RUnlock()
	return calls
}
