// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package processor

import (
	"sync"
)

// Ensure, that InputMock does implement Input.
// If this is not the case, regenerate this file with moq.
var _ Input = &InputMock{}

// InputMock is a mock implementation of Input.
//
//	func TestSomethingThatUsesInput(t *testing.T) {
//
//		// make and configure a mocked Input
//		mockedInput := &InputMock{
//			CredentialsFunc: func() Credentials {
//				panic("mock out the Credentials method")
//			},
//			URLFunc: func() string {
//				panic("mock out the URL method")
//			},
//		}
//
//		// use mockedInput in code that requires Input
//		// and then make assertions.
//
//	}
type InputMock struct {
	// CredentialsFunc mocks the Credentials method.
	CredentialsFunc func() Credentials

	// URLFunc mocks the URL method.
	URLFunc func() string

	// calls tracks calls to the methods.
	calls struct {
		// Credentials holds details about calls to the Credentials method.
		Credentials []struct {
		}
		// URL holds details about calls to the URL method.
		URL []struct {
		}
	}
	lockCredentials sync.RWMutex
	lockURL         sync.RWMutex
}

// Credentials calls CredentialsFunc.
func (mock *InputMock) Credentials() Credentials {
	callInfo := struct {
	}{}
	mock.lockCredentials.Lock()
	mock.calls.Credentials = append(mock.calls.Credentials, callInfo)
	mock.lockCredentials.Unlock()
	if mock.CredentialsFunc == nil {
		var (
			credentialsOut Credentials
		)
		return credentialsOut
	}
	return mock.CredentialsFunc()
}

// CredentialsCalls gets all the calls that were made to Credentials.
// Check the length with:
//
//	len(mockedInput.CredentialsCalls())
func (mock *InputMock) CredentialsCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockCredentials.RLock()
	calls = mock.calls.Credentials
	mock.lockCredentials.RUnlock()
	return calls
}

// URL calls URLFunc.
func (mock *InputMock) URL() string {
	callInfo := struct {
	}{}
	mock.lockURL.Lock()
	mock.calls.URL = append(mock.calls.URL, callInfo)
	mock.lockURL.Unlock()
	if mock.URLFunc == nil {
		var (
			sOut string
		)
		return sOut
	}
	return mock.URLFunc()
}

// URLCalls gets all the calls that were made to URL.
// Check the length with:
//
//	len(mockedInput.URLCalls())
func (mock *InputMock) URLCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockURL.RLock()
	calls = mock.calls.URL
	mock.lockURL.RUnlock()
	return calls
}
