// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"sync"

	"github.com/oxynote/oxynote/server/core/internal/datasource"
	"github.com/oxynote/oxynote/server/core/internal/datasource/processor"
)

// Ensure, that Runner does implement datasource.Runner.
// If this is not the case, regenerate this file with moq.
var _ datasource.Runner = &Runner{}

// Runner is a mock implementation of datasource.Runner.
//
//	func TestSomethingThatUsesdatasource.Runner(t *testing.T) {
//
//		// make and configure a mocked datasource.Runner
//		mockeddatasource.Runner := &Runner{
//			TypeFunc: func() datasource.Type {
//				panic("mock out the Type method")
//			},
//			TestConnectionFunc: func(ctx context.Context) (processor.ConnectionStatus, error) {
//				panic("mock out the TestConnection method")
//			},
//			PrometheusFunc: func(ctx context.Context) (datasource.Prometheus, error) {
//				panic("mock out the Prometheus method")
//			},
//			PostgreSQLFunc: func(ctx context.Context) (datasource.PostgreSQL, error) {
//				panic("mock out the PostgreSQL method")
//			},
//			MySQLFunc: func(ctx context.Context) (datasource.MySQL, error) {
//				panic("mock out the MySQL method")
//			},
//			SQLFunc: func(ctx context.Context) (datasource.SQL, error) {
//				panic("mock out the SQL method")
//			},
//		}
//
//		// use mockeddatasource.Runner in code that requires datasource.Runner
//		// and then make assertions.
//
//	}
type Runner struct {
	// TypeFunc mocks the Type method.
	TypeFunc func() datasource.Type

	// TestConnectionFunc mocks the TestConnection method.
	TestConnectionFunc func(ctx context.Context) (processor.ConnectionStatus, error)

	// PrometheusFunc mocks the Prometheus method.
	PrometheusFunc func(ctx context.Context) (datasource.Prometheus, error)

	// PostgreSQLFunc mocks the PostgreSQL method.
	PostgreSQLFunc func(ctx context.Context) (datasource.PostgreSQL, error)

	// MySQLFunc mocks the MySQL method.
	MySQLFunc func(ctx context.Context) (datasource.MySQL, error)

	// SQLFunc mocks the SQL method.
	SQLFunc func(ctx context.Context) (datasource.SQL, error)

	// calls tracks calls to the methods.
	calls struct {
		// Type holds details about calls to the Type method.
		Type []struct {
		}
		// TestConnection holds details about calls to the TestConnection method.
		TestConnection []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// Prometheus holds details about calls to the Prometheus method.
		Prometheus []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// PostgreSQL holds details about calls to the PostgreSQL method.
		PostgreSQL []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// MySQL holds details about calls to the MySQL method.
		MySQL []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// SQL holds details about calls to the SQL method.
		SQL []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
	}
	lockType           sync.RWMutex
	lockTestConnection sync.RWMutex
	lockPrometheus     sync.RWMutex
	lockPostgreSQL     sync.RWMutex
	lockMySQL          sync.RWMutex
	lockSQL            sync.RWMutex
}

// Type calls TypeFunc.
func (mock *Runner) Type() datasource.Type {
	callInfo := struct {
	}{}
	mock.lockType.Lock()
	mock.calls.Type = append(mock.calls.Type, callInfo)
	mock.lockType.Unlock()
	if mock.TypeFunc == nil {
		var (
			typeOut datasource.Type
		)
		return typeOut
	}
	return mock.TypeFunc()
}

// TypeCalls gets all the calls that were made to Type.
// Check the length with:
//
//	len(mockeddatasource.Runner.TypeCalls())
func (mock *Runner) TypeCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockType.RLock()
	calls = mock.calls.Type
	mock.lockType.RUnlock()
	return calls
}

// TestConnection calls TestConnectionFunc.
func (mock *Runner) TestConnection(ctx context.Context) (processor.ConnectionStatus, error) {
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockTestConnection.Lock()
	mock.calls.TestConnection = append(mock.calls.TestConnection, callInfo)
	mock.lockTestConnection.Unlock()
	if mock.TestConnectionFunc == nil {
		var (
			connectionStatusOut processor.ConnectionStatus
			errOut              error
		)
		return connectionStatusOut, errOut
	}
	return mock.TestConnectionFunc(ctx)
}

// TestConnectionCalls gets all the calls that were made to TestConnection.
// Check the length with:
//
//	len(mockeddatasource.Runner.TestConnectionCalls())
func (mock *Runner) TestConnectionCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockTestConnection.RLock()
	calls = mock.calls.TestConnection
	mock.lockTestConnection.RUnlock()
	return calls
}

// Prometheus calls PrometheusFunc.
func (mock *Runner) Prometheus(ctx context.Context) (datasource.Prometheus, error) {
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockPrometheus.Lock()
	mock.calls.Prometheus = append(mock.calls.Prometheus, callInfo)
	mock.lockPrometheus.Unlock()
	if mock.PrometheusFunc == nil {
		var (
			prometheusOut datasource.Prometheus
			errOut        error
		)
		return prometheusOut, errOut
	}
	return mock.PrometheusFunc(ctx)
}

// PrometheusCalls gets all the calls that were made to Prometheus.
// Check the length with:
//
//	len(mockeddatasource.Runner.PrometheusCalls())
func (mock *Runner) PrometheusCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockPrometheus.RLock()
	calls = mock.calls.Prometheus
	mock.lockPrometheus.RUnlock()
	return calls
}

// PostgreSQL calls PostgreSQLFunc.
func (mock *Runner) PostgreSQL(ctx context.Context) (datasource.PostgreSQL, error) {
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockPostgreSQL.Lock()
	mock.calls.PostgreSQL = append(mock.calls.PostgreSQL, callInfo)
	mock.lockPostgreSQL.Unlock()
	if mock.PostgreSQLFunc == nil {
		var (
			postgreSQLOut datasource.PostgreSQL
			errOut        error
		)
		return postgreSQLOut, errOut
	}
	return mock.PostgreSQLFunc(ctx)
}

// PostgreSQLCalls gets all the calls that were made to PostgreSQL.
// Check the length with:
//
//	len(mockeddatasource.Runner.PostgreSQLCalls())
func (mock *Runner) PostgreSQLCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockPostgreSQL.RLock()
	calls = mock.calls.PostgreSQL
	mock.lockPostgreSQL.RUnlock()
	return calls
}

// MySQL calls MySQLFunc.
func (mock *Runner) MySQL(ctx context.Context) (datasource.MySQL, error) {
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockMySQL.Lock()
	mock.calls.MySQL = append(mock.calls.MySQL, callInfo)
	mock.lockMySQL.Unlock()
	if mock.MySQLFunc == nil {
		var (
			mySQLOut datasource.MySQL
			errOut   error
		)
		return mySQLOut, errOut
	}
	return mock.MySQLFunc(ctx)
}

// MySQLCalls gets all the calls that were made to MySQL.
// Check the length with:
//
//	len(mockeddatasource.Runner.MySQLCalls())
func (mock *Runner) MySQLCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockMySQL.RLock()
	calls = mock.calls.MySQL
	mock.lockMySQL.RUnlock()
	return calls
}

// SQL calls SQLFunc.
func (mock *Runner) SQL(ctx context.Context) (datasource.SQL, error) {
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockSQL.Lock()
	mock.calls.SQL = append(mock.calls.SQL, callInfo)
	mock.lockSQL.Unlock()
	if mock.SQLFunc == nil {
		var (
			sQLOut datasource.SQL
			errOut error
		)
		return sQLOut, errOut
	}
	return mock.SQLFunc(ctx)
}

// SQLCalls gets all the calls that were made to SQL.
// Check the length with:
//
//	len(mockeddatasource.Runner.SQLCalls())
func (mock *Runner) SQLCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockSQL.RLock()
	calls = mock.calls.SQL
	mock.lockSQL.RUnlock()
	return calls
}
