// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"sync"

	"github.com/oxynote/oxynote/server/core/internal/datasource"
	"github.com/oxynote/oxynote/server/core/internal/datasource/processor"
)

// Ensure, that SQL does implement datasource.SQL.
// If this is not the case, regenerate this file with moq.
var _ datasource.SQL = &SQL{}

// SQL is a mock implementation of datasource.SQL.
//
//	func TestSomethingThatUsesdatasource.SQL(t *testing.T) {
//
//		// make and configure a mocked datasource.SQL
//		mockeddatasource.SQL := &SQL{
//			TestConnectionFunc: func(ctx context.Context) (processor.ConnectionStatus, error) {
//				panic("mock out the TestConnection method")
//			},
//			MetadataFunc: func(ctx context.Context) (*processor.SQLMetadataResult, error) {
//				panic("mock out the Metadata method")
//			},
//			QueryLabelsFunc: func(ctx context.Context, q string, tr processor.TimeRange) (map[string]string, error) {
//				panic("mock out the QueryLabels method")
//			},
//		}
//
//		// use mockeddatasource.SQL in code that requires datasource.SQL
//		// and then make assertions.
//
//	}
type SQL struct {
	// TestConnectionFunc mocks the TestConnection method.
	TestConnectionFunc func(ctx context.Context) (processor.ConnectionStatus, error)

	// MetadataFunc mocks the Metadata method.
	MetadataFunc func(ctx context.Context) (*processor.SQLMetadataResult, error)

	// QueryLabelsFunc mocks the QueryLabels method.
	QueryLabelsFunc func(ctx context.Context, q string, tr processor.TimeRange) (map[string]string, error)

	// calls tracks calls to the methods.
	calls struct {
		// TestConnection holds details about calls to the TestConnection method.
		TestConnection []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// Metadata holds details about calls to the Metadata method.
		Metadata []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// QueryLabels holds details about calls to the QueryLabels method.
		QueryLabels []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Q is the q argument value.
			Q string
			// Tr is the tr argument value.
			Tr processor.TimeRange
		}
	}
	lockTestConnection sync.RWMutex
	lockMetadata       sync.RWMutex
	lockQueryLabels    sync.RWMutex
}

// TestConnection calls TestConnectionFunc.
func (mock *SQL) TestConnection(ctx context.Context) (processor.ConnectionStatus, error) {
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockTestConnection.Lock()
	mock.calls.TestConnection = append(mock.calls.TestConnection, callInfo)
	mock.lockTestConnection.Unlock()
	if mock.TestConnectionFunc == nil {
		var (
			connectionStatusOut processor.ConnectionStatus
			errOut              error
		)
		return connectionStatusOut, errOut
	}
	return mock.TestConnectionFunc(ctx)
}

// TestConnectionCalls gets all the calls that were made to TestConnection.
// Check the length with:
//
//	len(mockeddatasource.SQL.TestConnectionCalls())
func (mock *SQL) TestConnectionCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockTestConnection.RLock()
	calls = mock.calls.TestConnection
	mock.lockTestConnection.RUnlock()
	return calls
}

// Metadata calls MetadataFunc.
func (mock *SQL) Metadata(ctx context.Context) (*processor.SQLMetadataResult, error) {
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockMetadata.Lock()
	mock.calls.Metadata = append(mock.calls.Metadata, callInfo)
	mock.lockMetadata.Unlock()
	if mock.MetadataFunc == nil {
		var (
			sQLMetadataResultOut *processor.SQLMetadataResult
			errOut               error
		)
		return sQLMetadataResultOut, errOut
	}
	return mock.MetadataFunc(ctx)
}

// MetadataCalls gets all the calls that were made to Metadata.
// Check the length with:
//
//	len(mockeddatasource.SQL.MetadataCalls())
func (mock *SQL) MetadataCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockMetadata.RLock()
	calls = mock.calls.Metadata
	mock.lockMetadata.RUnlock()
	return calls
}

// QueryLabels calls QueryLabelsFunc.
func (mock *SQL) QueryLabels(ctx context.Context, q string, tr processor.TimeRange) (map[string]string, error) {
	callInfo := struct {
		Ctx context.Context
		Q   string
		Tr  processor.TimeRange
	}{
		Ctx: ctx,
		Q:   q,
		Tr:  tr,
	}
	mock.lockQueryLabels.Lock()
	mock.calls.QueryLabels = append(mock.calls.QueryLabels, callInfo)
	mock.lockQueryLabels.Unlock()
	if mock.QueryLabelsFunc == nil {
		var (
			stringToStringOut map[string]string
			errOut            error
		)
		return stringToStringOut, errOut
	}
	return mock.QueryLabelsFunc(ctx, q, tr)
}

// QueryLabelsCalls gets all the calls that were made to QueryLabels.
// Check the length with:
//
//	len(mockeddatasource.SQL.QueryLabelsCalls())
func (mock *SQL) QueryLabelsCalls() []struct {
	Ctx context.Context
	Q   string
	Tr  processor.TimeRange
} {
	var calls []struct {
		Ctx context.Context
		Q   string
		Tr  processor.TimeRange
	}
	mock.lockQueryLabels.RLock()
	calls = mock.calls.QueryLabels
	mock.lockQueryLabels.RUnlock()
	return calls
}
