// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mcp

import (
	"sync"

	"github.com/oxynote/oxynote/server/core/internal/assistant/tools"
)

// Ensure, that ManagerMock does implement Manager.
// If this is not the case, regenerate this file with moq.
var _ Manager = &ManagerMock{}

// ManagerMock is a mock implementation of Manager.
//
//	func TestSomethingThatUsesManager(t *testing.T) {
//
//		// make and configure a mocked Manager
//		mockedManager := &ManagerMock{
//			ToolSetFunc: func(orgID string, userID string) *tools.Set {
//				panic("mock out the ToolSet method")
//			},
//		}
//
//		// use mockedManager in code that requires Manager
//		// and then make assertions.
//
//	}
type ManagerMock struct {
	// ToolSetFunc mocks the ToolSet method.
	ToolSetFunc func(orgID string, userID string) *tools.Set

	// calls tracks calls to the methods.
	calls struct {
		// ToolSet holds details about calls to the ToolSet method.
		ToolSet []struct {
			// OrgID is the orgID argument value.
			OrgID string
			// UserID is the userID argument value.
			UserID string
		}
	}
	lockToolSet sync.RWMutex
}

// ToolSet calls ToolSetFunc.
func (mock *ManagerMock) ToolSet(orgID string, userID string) *tools.Set {
	callInfo := struct {
		OrgID  string
		UserID string
	}{
		OrgID:  orgID,
		UserID: userID,
	}
	mock.lockToolSet.Lock()
	mock.calls.ToolSet = append(mock.calls.ToolSet, callInfo)
	mock.lockToolSet.Unlock()
	if mock.ToolSetFunc == nil {
		var (
			setOut *tools.Set
		)
		return setOut
	}
	return mock.ToolSetFunc(orgID, userID)
}

// ToolSetCalls gets all the calls that were made to ToolSet.
// Check the length with:
//
//	len(mockedManager.ToolSetCalls())
func (mock *ManagerMock) ToolSetCalls() []struct {
	OrgID  string
	UserID string
} {
	var calls []struct {
		OrgID  string
		UserID string
	}
	mock.lockToolSet.RLock()
	calls = mock.calls.ToolSet
	mock.lockToolSet.RUnlock()
	return calls
}
