// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package document

import (
	"context"
	"sync"
)

// Ensure, that SearchGatewayMock does implement SearchGateway.
// If this is not the case, regenerate this file with moq.
var _ SearchGateway = &SearchGatewayMock{}

// SearchGatewayMock is a mock implementation of SearchGateway.
//
//	func TestSomethingThatUsesSearchGateway(t *testing.T) {
//
//		// make and configure a mocked SearchGateway
//		mockedSearchGateway := &SearchGatewayMock{
//			SearchDocumentsFunc: func(ctx context.Context, organizationID string, query string) ([]byte, error) {
//				panic("mock out the SearchDocuments method")
//			},
//		}
//
//		// use mockedSearchGateway in code that requires SearchGateway
//		// and then make assertions.
//
//	}
type SearchGatewayMock struct {
	// SearchDocumentsFunc mocks the SearchDocuments method.
	SearchDocumentsFunc func(ctx context.Context, organizationID string, query string) ([]byte, error)

	// calls tracks calls to the methods.
	calls struct {
		// SearchDocuments holds details about calls to the SearchDocuments method.
		SearchDocuments []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrganizationID is the organizationID argument value.
			OrganizationID string
			// Query is the query argument value.
			Query string
		}
	}
	lockSearchDocuments sync.RWMutex
}

// SearchDocuments calls SearchDocumentsFunc.
func (mock *SearchGatewayMock) SearchDocuments(ctx context.Context, organizationID string, query string) ([]byte, error) {
	callInfo := struct {
		Ctx            context.Context
		OrganizationID string
		Query          string
	}{
		Ctx:            ctx,
		OrganizationID: organizationID,
		Query:          query,
	}
	mock.lockSearchDocuments.Lock()
	mock.calls.SearchDocuments = append(mock.calls.SearchDocuments, callInfo)
	mock.lockSearchDocuments.Unlock()
	if mock.SearchDocumentsFunc == nil {
		var (
			bytesOut []byte
			errOut   error
		)
		return bytesOut, errOut
	}
	return mock.SearchDocumentsFunc(ctx, organizationID, query)
}

// SearchDocumentsCalls gets all the calls that were made to SearchDocuments.
// Check the length with:
//
//	len(mockedSearchGateway.SearchDocumentsCalls())
func (mock *SearchGatewayMock) SearchDocumentsCalls() []struct {
	Ctx            context.Context
	OrganizationID string
	Query          string
} {
	var calls []struct {
		Ctx            context.Context
		OrganizationID string
		Query          string
	}
	mock.lockSearchDocuments.RLock()
	calls = mock.calls.SearchDocuments
	mock.lockSearchDocuments.RUnlock()
	return calls
}
