// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package document

import (
	"context"
	"sync"

	"github.com/rs/xid"
)

// Ensure, that HookManagerMock does implement HookManager.
// If this is not the case, regenerate this file with moq.
var _ HookManager = &HookManagerMock{}

// HookManagerMock is a mock implementation of HookManager.
//
//	func TestSomethingThatUsesHookManager(t *testing.T) {
//
//		// make and configure a mocked HookManager
//		mockedHookManager := &HookManagerMock{
//			SetUpBranchFunc: func(ctx context.Context, branchID xid.ID, organizationID string)  {
//				panic("mock out the SetUpBranch method")
//			},
//		}
//
//		// use mockedHookManager in code that requires HookManager
//		// and then make assertions.
//
//	}
type HookManagerMock struct {
	// SetUpBranchFunc mocks the SetUpBranch method.
	SetUpBranchFunc func(ctx context.Context, branchID xid.ID, organizationID string)

	// calls tracks calls to the methods.
	calls struct {
		// SetUpBranch holds details about calls to the SetUpBranch method.
		SetUpBranch []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// BranchID is the branchID argument value.
			BranchID xid.ID
			// OrganizationID is the organizationID argument value.
			OrganizationID string
		}
	}
	lockSetUpBranch sync.RWMutex
}

// SetUpBranch calls SetUpBranchFunc.
func (mock *HookManagerMock) SetUpBranch(ctx context.Context, branchID xid.ID, organizationID string) {
	callInfo := struct {
		Ctx            context.Context
		BranchID       xid.ID
		OrganizationID string
	}{
		Ctx:            ctx,
		BranchID:       branchID,
		OrganizationID: organizationID,
	}
	mock.lockSetUpBranch.Lock()
	mock.calls.SetUpBranch = append(mock.calls.SetUpBranch, callInfo)
	mock.lockSetUpBranch.Unlock()
	if mock.SetUpBranchFunc == nil {
		return
	}
	mock.SetUpBranchFunc(ctx, branchID, organizationID)
}

// SetUpBranchCalls gets all the calls that were made to SetUpBranch.
// Check the length with:
//
//	len(mockedHookManager.SetUpBranchCalls())
func (mock *HookManagerMock) SetUpBranchCalls() []struct {
	Ctx            context.Context
	BranchID       xid.ID
	OrganizationID string
} {
	var calls []struct {
		Ctx            context.Context
		BranchID       xid.ID
		OrganizationID string
	}
	mock.lockSetUpBranch.RLock()
	calls = mock.calls.SetUpBranch
	mock.lockSetUpBranch.RUnlock()
	return calls
}
