// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package document

import (
	"context"
	"sync"

	"github.com/oxynote/oxynote/server/core/internal/document/hook/manager"
	"github.com/rs/xid"
)

// Ensure, that HookManagerMock does implement HookManager.
// If this is not the case, regenerate this file with moq.
var _ HookManager = &HookManagerMock{}

// HookManagerMock is a mock implementation of HookManager.
//
//	func TestSomethingThatUsesHookManager(t *testing.T) {
//
//		// make and configure a mocked HookManager
//		mockedHookManager := &HookManagerMock{
//			CopyHooksFunc: func(ctx context.Context, tx manager.CopyTx, fromBranchID xid.ID, toBranchID xid.ID, documentID xid.ID, organizationID string, uids map[string]string) error {
//				panic("mock out the CopyHooks method")
//			},
//			ProcessBranchFunc: func(branchID xid.ID, organizationID string)  {
//				panic("mock out the ProcessBranch method")
//			},
//		}
//
//		// use mockedHookManager in code that requires HookManager
//		// and then make assertions.
//
//	}
type HookManagerMock struct {
	// CopyHooksFunc mocks the CopyHooks method.
	CopyHooksFunc func(ctx context.Context, tx manager.CopyTx, fromBranchID xid.ID, toBranchID xid.ID, documentID xid.ID, organizationID string, uids map[string]string) error

	// ProcessBranchFunc mocks the ProcessBranch method.
	ProcessBranchFunc func(branchID xid.ID, organizationID string)

	// calls tracks calls to the methods.
	calls struct {
		// CopyHooks holds details about calls to the CopyHooks method.
		CopyHooks []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Tx is the tx argument value.
			Tx manager.CopyTx
			// FromBranchID is the fromBranchID argument value.
			FromBranchID xid.ID
			// ToBranchID is the toBranchID argument value.
			ToBranchID xid.ID
			// DocumentID is the documentID argument value.
			DocumentID xid.ID
			// OrganizationID is the organizationID argument value.
			OrganizationID string
			// Uids is the uids argument value.
			Uids map[string]string
		}
		// ProcessBranch holds details about calls to the ProcessBranch method.
		ProcessBranch []struct {
			// BranchID is the branchID argument value.
			BranchID xid.ID
			// OrganizationID is the organizationID argument value.
			OrganizationID string
		}
	}
	lockCopyHooks     sync.RWMutex
	lockProcessBranch sync.RWMutex
}

// CopyHooks calls CopyHooksFunc.
func (mock *HookManagerMock) CopyHooks(ctx context.Context, tx manager.CopyTx, fromBranchID xid.ID, toBranchID xid.ID, documentID xid.ID, organizationID string, uids map[string]string) error {
	callInfo := struct {
		Ctx            context.Context
		Tx             manager.CopyTx
		FromBranchID   xid.ID
		ToBranchID     xid.ID
		DocumentID     xid.ID
		OrganizationID string
		Uids           map[string]string
	}{
		Ctx:            ctx,
		Tx:             tx,
		FromBranchID:   fromBranchID,
		ToBranchID:     toBranchID,
		DocumentID:     documentID,
		OrganizationID: organizationID,
		Uids:           uids,
	}
	mock.lockCopyHooks.Lock()
	mock.calls.CopyHooks = append(mock.calls.CopyHooks, callInfo)
	mock.lockCopyHooks.Unlock()
	if mock.CopyHooksFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.CopyHooksFunc(ctx, tx, fromBranchID, toBranchID, documentID, organizationID, uids)
}

// CopyHooksCalls gets all the calls that were made to CopyHooks.
// Check the length with:
//
//	len(mockedHookManager.CopyHooksCalls())
func (mock *HookManagerMock) CopyHooksCalls() []struct {
	Ctx            context.Context
	Tx             manager.CopyTx
	FromBranchID   xid.ID
	ToBranchID     xid.ID
	DocumentID     xid.ID
	OrganizationID string
	Uids           map[string]string
} {
	var calls []struct {
		Ctx            context.Context
		Tx             manager.CopyTx
		FromBranchID   xid.ID
		ToBranchID     xid.ID
		DocumentID     xid.ID
		OrganizationID string
		Uids           map[string]string
	}
	mock.lockCopyHooks.RLock()
	calls = mock.calls.CopyHooks
	mock.lockCopyHooks.RUnlock()
	return calls
}

// ProcessBranch calls ProcessBranchFunc.
func (mock *HookManagerMock) ProcessBranch(branchID xid.ID, organizationID string) {
	callInfo := struct {
		BranchID       xid.ID
		OrganizationID string
	}{
		BranchID:       branchID,
		OrganizationID: organizationID,
	}
	mock.lockProcessBranch.Lock()
	mock.calls.ProcessBranch = append(mock.calls.ProcessBranch, callInfo)
	mock.lockProcessBranch.Unlock()
	if mock.ProcessBranchFunc == nil {
		return
	}
	mock.ProcessBranchFunc(branchID, organizationID)
}

// ProcessBranchCalls gets all the calls that were made to ProcessBranch.
// Check the length with:
//
//	len(mockedHookManager.ProcessBranchCalls())
func (mock *HookManagerMock) ProcessBranchCalls() []struct {
	BranchID       xid.ID
	OrganizationID string
} {
	var calls []struct {
		BranchID       xid.ID
		OrganizationID string
	}
	mock.lockProcessBranch.RLock()
	calls = mock.calls.ProcessBranch
	mock.lockProcessBranch.RUnlock()
	return calls
}
