// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package document

import (
	"context"
	"sync"
)

// Ensure, that StorerMock does implement Storer.
// If this is not the case, regenerate this file with moq.
var _ Storer = &StorerMock{}

// StorerMock is a mock implementation of Storer.
//
//	func TestSomethingThatUsesStorer(t *testing.T) {
//
//		// make and configure a mocked Storer
//		mockedStorer := &StorerMock{
//			CopyFunc: func(ctx context.Context, srcFolder string, srcID string, dstFolder string, dstID string) error {
//				panic("mock out the Copy method")
//			},
//		}
//
//		// use mockedStorer in code that requires Storer
//		// and then make assertions.
//
//	}
type StorerMock struct {
	// CopyFunc mocks the Copy method.
	CopyFunc func(ctx context.Context, srcFolder string, srcID string, dstFolder string, dstID string) error

	// calls tracks calls to the methods.
	calls struct {
		// Copy holds details about calls to the Copy method.
		Copy []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// SrcFolder is the srcFolder argument value.
			SrcFolder string
			// SrcID is the srcID argument value.
			SrcID string
			// DstFolder is the dstFolder argument value.
			DstFolder string
			// DstID is the dstID argument value.
			DstID string
		}
	}
	lockCopy sync.RWMutex
}

// Copy calls CopyFunc.
func (mock *StorerMock) Copy(ctx context.Context, srcFolder string, srcID string, dstFolder string, dstID string) error {
	callInfo := struct {
		Ctx       context.Context
		SrcFolder string
		SrcID     string
		DstFolder string
		DstID     string
	}{
		Ctx:       ctx,
		SrcFolder: srcFolder,
		SrcID:     srcID,
		DstFolder: dstFolder,
		DstID:     dstID,
	}
	mock.lockCopy.Lock()
	mock.calls.Copy = append(mock.calls.Copy, callInfo)
	mock.lockCopy.Unlock()
	if mock.CopyFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.CopyFunc(ctx, srcFolder, srcID, dstFolder, dstID)
}

// CopyCalls gets all the calls that were made to Copy.
// Check the length with:
//
//	len(mockedStorer.CopyCalls())
func (mock *StorerMock) CopyCalls() []struct {
	Ctx       context.Context
	SrcFolder string
	SrcID     string
	DstFolder string
	DstID     string
} {
	var calls []struct {
		Ctx       context.Context
		SrcFolder string
		SrcID     string
		DstFolder string
		DstID     string
	}
	mock.lockCopy.RLock()
	calls = mock.calls.Copy
	mock.lockCopy.RUnlock()
	return calls
}
