// names a single-organization deployment can start with. Each is the real
// name of a place in space. Each passes the workspace name rule of the web
// forms. None is longer than 20 characters, which is where the web app
// cuts a name it puts in a link.
export const organizationNames = [
	// the Moon's seas, lakes and bays, by the English form of their names
	"Sea of Tranquility",
	"Sea of Serenity",
	"Sea of Clouds",
	"Sea of Nectar",
	"Sea of Islands",
	"Sea of Waves",
	"Lake of Dreams",
	"Lake of Time",
	"Lake of Spring",
	"Lake of Summer",
	"Lake of Autumn",
	"Wintry Lake",
	"Lake of Hope",
	"Lake of Joy",
	"Lake of Perseverance",
	"Bay of Dew",
	"Bay of Harmony",
	"Bay of Trust",
	// landing sites and landmarks on the Moon
	"Tranquility Base",
	"Hadley Base",
	"Hadley Rille",
	"Hadley Delta",
	"Descartes Highlands",
	"Fra Mauro Highlands",
	"Marius Hills",
	"Reiner Gamma",
	"Alpine Valley",
	"Serpentine Ridge",
	"Lunar Alps",
	"Cape Fresnel",
	"Sculptured Hills",
	"North Massif",
	"South Massif",
	"Family Mountain",
	"Silver Spur",
	"Apollo Basin",
	"Lunar South Pole",
	"Shackleton Crater",
	"Tycho Crater",
	"Copernicus Crater",
	"Clavius Crater",
	"Camelot Crater",
	"North Ray Crater",
	"South Ray Crater",
	"Plum Crater",
	"Cone Crater",
	"Surveyor Crater",
	"Babbage Crater",
	"Boole Crater",
	"Lovelace Crater",
	"Hilbert Crater",
	"Euler Crater",
	"Gauss Crater",
	"Hypatia Crater",
	"Kepler Crater",
	"Archimedes Crater",
	"Pythagoras Crater",
	// Mars
	"Bradbury Landing",
	"Green Valley",
	"Eagle Crater",
	"Endurance Crater",
	"Victoria Crater",
	"Endeavour Crater",
	"Bonneville Crater",
	"Gusev Crater",
	"Gale Crater",
	"Jezero Crater",
	"Meridiani Planum",
	"Oxia Planum",
	"Planum Boreum",
	"Planum Australe",
	"Utopia Planitia",
	"Elysium Planitia",
	"Arcadia Planitia",
	"Olympus Mons",
	"Pavonis Mons",
	"Elysium Mons",
	"Tharsis Montes",
	"Valles Marineris",
	"Candor Chasma",
	"Ophir Chasma",
	"Ares Vallis",
	"Kasei Valles",
	"Syrtis Major",
	"Lake of the Sun",
	"Meridian Bay",
	"Bay of the Dawn",
	"Golden Plain",
	"Labyrinth of Night",
	"Mariner Valley",
	"Mount Sharp",
	"Yellowknife Bay",
	"Glen Torridon",
	"Bagnold Dunes",
	"Vera Rubin Ridge",
	"Marathon Valley",
	"Perseverance Valley",
	"Cape York",
	"Solander Point",
	"Greeley Haven",
	"Murray Ridge",
	"Bright Angel",
	"Rock Garden",
	"Mermaid Dune",
	// other planets, moons, rings and asteroids
	"Caloris Basin",
	"Caloris Montes",
	"Borealis Planitia",
	"Maxwell Montes",
	"Artemis Chasma",
	"Tara Regio",
	"Galileo Regio",
	"Ontario Lacus",
	"Tiger Stripes",
	"Ithaca Chasma",
	"Odysseus Crater",
	"Herschel Crater",
	"Cassini Regio",
	"Cassini Division",
	"Roche Division",
	"Encke Gap",
	"Keeler Gap",
	"Huygens Gap",
	"Maxwell Gap",
	"Colombo Gap",
	"Phoebe Ring",
	"Gossamer Rings",
	"Adams Ring",
	"Verona Rupes",
	"Tenzing Montes",
	"Wright Mons",
	"Piccard Mons",
	"Voyager Terra",
	"Pioneer Terra",
	"Viking Terra",
	"Hayabusa Terra",
	"Lowell Regio",
	"Burney Crater",
	"Argo Chasma",
	"Kubrick Mons",
	"Butler Mons",
	"Ahuna Mons",
	"Hanami Planum",
	"Muses Sea",
	// orbits, belts and landmarks of the sky
	"Low Earth Orbit",
	"Geostationary Orbit",
	"Halo Orbit",
	"Lagrange Point",
	"Van Allen Belt",
	"Asteroid Belt",
	"Kirkwood Gap",
	"Kuiper Belt",
	"Oort Cloud",
	"Hill Sphere",
	"Planet Nine",
	"Goldilocks Zone",
	"Habitable Zone",
	"Pale Blue Dot",
	"Blue Marble",
	"Proxima Centauri",
	"Tau Ceti",
	"Solar Neighborhood",
	"Gould Belt",
	"Radcliffe Wave",
	"Orion Arm",
	"Orion Spur",
	"Perseus Arm",
	"Sagittarius Arm",
	"Galactic Center",
	"Fermi Bubbles",
	"Milky Way",
	"Great Attractor",
	"Cosmic Web",
	"Summer Triangle",
	"Winter Hexagon",
	"Big Dipper",
	"Jewel Box",
	"Cosmic Cliffs",
	"Cosmic Reef",
	"Mystic Mountain",
	"Cygnus Loop",
	"Orion Nebula",
	"Carina Nebula",
	"Lagoon Nebula",
	"Waterfall Nebula",
	"Eagle Nebula",
	"Helix Nebula",
	"Ring Nebula",
	"Rosette Nebula",
	"Veil Nebula",
	"Crab Nebula",
	"Horsehead Nebula",
	"Trifid Nebula",
	"Butterfly Nebula",
	"Pelican Nebula",
	"Flame Nebula",
	"Owl Nebula",
	"Bubble Nebula",
	"Heart Nebula",
	"Cone Nebula",
	"Andromeda Galaxy",
	"Whirlpool Galaxy",
	"Pinwheel Galaxy",
	"Sunflower Galaxy",
	"Cartwheel Galaxy",
	"Triangulum Galaxy",
	"Fireworks Galaxy",
	"Tadpole Galaxy",
	"Antennae Galaxies",
	"Hubble Deep Field",
	"Sunburst Arc",
	"Cosmic Horseshoe",
	"Einstein Ring",
	"Photon Ring",
	"Photon Sphere",
]

// pickOrganization picks the name and the slug of a new organization. The
// random number is at least zero and below one, as Math.random answers.
export function pickOrganization(random: () => number): {
	name: string
	slug: string
} {
	const name =
		organizationNames[
			Math.floor(random() * organizationNames.length)
		]
	if (name === undefined) {
		throw new Error("the random number is not between zero and one")
	}

	return { name, slug: name.toLowerCase().replaceAll(" ", "-") }
}
