// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package datasourcehandler

import (
	"context"
	"sync"

	"github.com/oxynote/oxynote/server/core/internal/datasource"
	"github.com/rs/xid"
)

// Ensure, that DBMock does implement DB.
// If this is not the case, regenerate this file with moq.
var _ DB = &DBMock{}

// DBMock is a mock implementation of DB.
//
//	func TestSomethingThatUsesDB(t *testing.T) {
//
//		// make and configure a mocked DB
//		mockedDB := &DBMock{
//			DeleteDataSourceFunc: func(ctx context.Context, id xid.ID, organizationID string) error {
//				panic("mock out the DeleteDataSource method")
//			},
//			FetchDataSourceFunc: func(ctx context.Context, id xid.ID, organizationID string) (*datasource.DataSource, error) {
//				panic("mock out the FetchDataSource method")
//			},
//			FetchDataSourcesFunc: func(ctx context.Context, organizationID string) ([]datasource.DataSource, error) {
//				panic("mock out the FetchDataSources method")
//			},
//			InsertDataSourceFunc: func(ctx context.Context, ds *datasource.DataSource) error {
//				panic("mock out the InsertDataSource method")
//			},
//			UpdateDataSourceFunc: func(ctx context.Context, ds *datasource.DataSource) error {
//				panic("mock out the UpdateDataSource method")
//			},
//		}
//
//		// use mockedDB in code that requires DB
//		// and then make assertions.
//
//	}
type DBMock struct {
	// DeleteDataSourceFunc mocks the DeleteDataSource method.
	DeleteDataSourceFunc func(ctx context.Context, id xid.ID, organizationID string) error

	// FetchDataSourceFunc mocks the FetchDataSource method.
	FetchDataSourceFunc func(ctx context.Context, id xid.ID, organizationID string) (*datasource.DataSource, error)

	// FetchDataSourcesFunc mocks the FetchDataSources method.
	FetchDataSourcesFunc func(ctx context.Context, organizationID string) ([]datasource.DataSource, error)

	// InsertDataSourceFunc mocks the InsertDataSource method.
	InsertDataSourceFunc func(ctx context.Context, ds *datasource.DataSource) error

	// UpdateDataSourceFunc mocks the UpdateDataSource method.
	UpdateDataSourceFunc func(ctx context.Context, ds *datasource.DataSource) error

	// calls tracks calls to the methods.
	calls struct {
		// DeleteDataSource holds details about calls to the DeleteDataSource method.
		DeleteDataSource []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID xid.ID
			// OrganizationID is the organizationID argument value.
			OrganizationID string
		}
		// FetchDataSource holds details about calls to the FetchDataSource method.
		FetchDataSource []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID xid.ID
			// OrganizationID is the organizationID argument value.
			OrganizationID string
		}
		// FetchDataSources holds details about calls to the FetchDataSources method.
		FetchDataSources []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrganizationID is the organizationID argument value.
			OrganizationID string
		}
		// InsertDataSource holds details about calls to the InsertDataSource method.
		InsertDataSource []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Ds is the ds argument value.
			Ds *datasource.DataSource
		}
		// UpdateDataSource holds details about calls to the UpdateDataSource method.
		UpdateDataSource []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Ds is the ds argument value.
			Ds *datasource.DataSource
		}
	}
	lockDeleteDataSource sync.RWMutex
	lockFetchDataSource  sync.RWMutex
	lockFetchDataSources sync.RWMutex
	lockInsertDataSource sync.RWMutex
	lockUpdateDataSource sync.RWMutex
}

// DeleteDataSource calls DeleteDataSourceFunc.
func (mock *DBMock) DeleteDataSource(ctx context.Context, id xid.ID, organizationID string) error {
	callInfo := struct {
		Ctx            context.Context
		ID             xid.ID
		OrganizationID string
	}{
		Ctx:            ctx,
		ID:             id,
		OrganizationID: organizationID,
	}
	mock.lockDeleteDataSource.Lock()
	mock.calls.DeleteDataSource = append(mock.calls.DeleteDataSource, callInfo)
	mock.lockDeleteDataSource.Unlock()
	if mock.DeleteDataSourceFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.DeleteDataSourceFunc(ctx, id, organizationID)
}

// DeleteDataSourceCalls gets all the calls that were made to DeleteDataSource.
// Check the length with:
//
//	len(mockedDB.DeleteDataSourceCalls())
func (mock *DBMock) DeleteDataSourceCalls() []struct {
	Ctx            context.Context
	ID             xid.ID
	OrganizationID string
} {
	var calls []struct {
		Ctx            context.Context
		ID             xid.ID
		OrganizationID string
	}
	mock.lockDeleteDataSource.RLock()
	calls = mock.calls.DeleteDataSource
	mock.lockDeleteDataSource.RUnlock()
	return calls
}

// FetchDataSource calls FetchDataSourceFunc.
func (mock *DBMock) FetchDataSource(ctx context.Context, id xid.ID, organizationID string) (*datasource.DataSource, error) {
	callInfo := struct {
		Ctx            context.Context
		ID             xid.ID
		OrganizationID string
	}{
		Ctx:            ctx,
		ID:             id,
		OrganizationID: organizationID,
	}
	mock.lockFetchDataSource.Lock()
	mock.calls.FetchDataSource = append(mock.calls.FetchDataSource, callInfo)
	mock.lockFetchDataSource.Unlock()
	if mock.FetchDataSourceFunc == nil {
		var (
			dataSourceOut *datasource.DataSource
			errOut        error
		)
		return dataSourceOut, errOut
	}
	return mock.FetchDataSourceFunc(ctx, id, organizationID)
}

// FetchDataSourceCalls gets all the calls that were made to FetchDataSource.
// Check the length with:
//
//	len(mockedDB.FetchDataSourceCalls())
func (mock *DBMock) FetchDataSourceCalls() []struct {
	Ctx            context.Context
	ID             xid.ID
	OrganizationID string
} {
	var calls []struct {
		Ctx            context.Context
		ID             xid.ID
		OrganizationID string
	}
	mock.lockFetchDataSource.RLock()
	calls = mock.calls.FetchDataSource
	mock.lockFetchDataSource.RUnlock()
	return calls
}

// FetchDataSources calls FetchDataSourcesFunc.
func (mock *DBMock) FetchDataSources(ctx context.Context, organizationID string) ([]datasource.DataSource, error) {
	callInfo := struct {
		Ctx            context.Context
		OrganizationID string
	}{
		Ctx:            ctx,
		OrganizationID: organizationID,
	}
	mock.lockFetchDataSources.Lock()
	mock.calls.FetchDataSources = append(mock.calls.FetchDataSources, callInfo)
	mock.lockFetchDataSources.Unlock()
	if mock.FetchDataSourcesFunc == nil {
		var (
			dataSourcesOut []datasource.DataSource
			errOut         error
		)
		return dataSourcesOut, errOut
	}
	return mock.FetchDataSourcesFunc(ctx, organizationID)
}

// FetchDataSourcesCalls gets all the calls that were made to FetchDataSources.
// Check the length with:
//
//	len(mockedDB.FetchDataSourcesCalls())
func (mock *DBMock) FetchDataSourcesCalls() []struct {
	Ctx            context.Context
	OrganizationID string
} {
	var calls []struct {
		Ctx            context.Context
		OrganizationID string
	}
	mock.lockFetchDataSources.RLock()
	calls = mock.calls.FetchDataSources
	mock.lockFetchDataSources.RUnlock()
	return calls
}

// InsertDataSource calls InsertDataSourceFunc.
func (mock *DBMock) InsertDataSource(ctx context.Context, ds *datasource.DataSource) error {
	callInfo := struct {
		Ctx context.Context
		Ds  *datasource.DataSource
	}{
		Ctx: ctx,
		Ds:  ds,
	}
	mock.lockInsertDataSource.Lock()
	mock.calls.InsertDataSource = append(mock.calls.InsertDataSource, callInfo)
	mock.lockInsertDataSource.Unlock()
	if mock.InsertDataSourceFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.InsertDataSourceFunc(ctx, ds)
}

// InsertDataSourceCalls gets all the calls that were made to InsertDataSource.
// Check the length with:
//
//	len(mockedDB.InsertDataSourceCalls())
func (mock *DBMock) InsertDataSourceCalls() []struct {
	Ctx context.Context
	Ds  *datasource.DataSource
} {
	var calls []struct {
		Ctx context.Context
		Ds  *datasource.DataSource
	}
	mock.lockInsertDataSource.RLock()
	calls = mock.calls.InsertDataSource
	mock.lockInsertDataSource.RUnlock()
	return calls
}

// UpdateDataSource calls UpdateDataSourceFunc.
func (mock *DBMock) UpdateDataSource(ctx context.Context, ds *datasource.DataSource) error {
	callInfo := struct {
		Ctx context.Context
		Ds  *datasource.DataSource
	}{
		Ctx: ctx,
		Ds:  ds,
	}
	mock.lockUpdateDataSource.Lock()
	mock.calls.UpdateDataSource = append(mock.calls.UpdateDataSource, callInfo)
	mock.lockUpdateDataSource.Unlock()
	if mock.UpdateDataSourceFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.UpdateDataSourceFunc(ctx, ds)
}

// UpdateDataSourceCalls gets all the calls that were made to UpdateDataSource.
// Check the length with:
//
//	len(mockedDB.UpdateDataSourceCalls())
func (mock *DBMock) UpdateDataSourceCalls() []struct {
	Ctx context.Context
	Ds  *datasource.DataSource
} {
	var calls []struct {
		Ctx context.Context
		Ds  *datasource.DataSource
	}
	mock.lockUpdateDataSource.RLock()
	calls = mock.calls.UpdateDataSource
	mock.lockUpdateDataSource.RUnlock()
	return calls
}
