// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package email

import (
	"context"
	"sync"

	"github.com/wneessen/go-mail"
)

// Ensure, that clientMock does implement client.
// If this is not the case, regenerate this file with moq.
var _ client = &clientMock{}

// clientMock is a mock implementation of client.
//
//	func TestSomethingThatUsesclient(t *testing.T) {
//
//		// make and configure a mocked client
//		mockedclient := &clientMock{
//			DialAndSendWithContextFunc: func(ctx context.Context, msgs ...*mail.Msg) error {
//				panic("mock out the DialAndSendWithContext method")
//			},
//		}
//
//		// use mockedclient in code that requires client
//		// and then make assertions.
//
//	}
type clientMock struct {
	// DialAndSendWithContextFunc mocks the DialAndSendWithContext method.
	DialAndSendWithContextFunc func(ctx context.Context, msgs ...*mail.Msg) error

	// calls tracks calls to the methods.
	calls struct {
		// DialAndSendWithContext holds details about calls to the DialAndSendWithContext method.
		DialAndSendWithContext []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Msgs is the msgs argument value.
			Msgs []*mail.Msg
		}
	}
	lockDialAndSendWithContext sync.RWMutex
}

// DialAndSendWithContext calls DialAndSendWithContextFunc.
func (mock *clientMock) DialAndSendWithContext(ctx context.Context, msgs ...*mail.Msg) error {
	callInfo := struct {
		Ctx  context.Context
		Msgs []*mail.Msg
	}{
		Ctx:  ctx,
		Msgs: msgs,
	}
	mock.lockDialAndSendWithContext.Lock()
	mock.calls.DialAndSendWithContext = append(mock.calls.DialAndSendWithContext, callInfo)
	mock.lockDialAndSendWithContext.Unlock()
	if mock.DialAndSendWithContextFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.DialAndSendWithContextFunc(ctx, msgs...)
}

// DialAndSendWithContextCalls gets all the calls that were made to DialAndSendWithContext.
// Check the length with:
//
//	len(mockedclient.DialAndSendWithContextCalls())
func (mock *clientMock) DialAndSendWithContextCalls() []struct {
	Ctx  context.Context
	Msgs []*mail.Msg
} {
	var calls []struct {
		Ctx  context.Context
		Msgs []*mail.Msg
	}
	mock.lockDialAndSendWithContext.RLock()
	calls = mock.calls.DialAndSendWithContext
	mock.lockDialAndSendWithContext.RUnlock()
	return calls
}
