// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package github

import (
	"context"
	"sync"

	"github.com/guregu/null/v5"
)

// Ensure, that DBMock does implement DB.
// If this is not the case, regenerate this file with moq.
var _ DB = &DBMock{}

// DBMock is a mock implementation of DB.
//
//	func TestSomethingThatUsesDB(t *testing.T) {
//
//		// make and configure a mocked DB
//		mockedDB := &DBMock{
//			DeleteGithubInstallationFunc: func(ctx context.Context, installationID int64) error {
//				panic("mock out the DeleteGithubInstallation method")
//			},
//			FetchGithubInstallationByOrganizationIDFunc: func(ctx context.Context, organizationID string) (int64, error) {
//				panic("mock out the FetchGithubInstallationByOrganizationID method")
//			},
//			FetchGithubInstallationOrganizationIDFunc: func(ctx context.Context, installationID int64) (null.String, error) {
//				panic("mock out the FetchGithubInstallationOrganizationID method")
//			},
//			InsertGithubInstallationFunc: func(ctx context.Context, installationID int64) error {
//				panic("mock out the InsertGithubInstallation method")
//			},
//			UnassignGithubInstallationOrganizationFunc: func(ctx context.Context, organizationID string) error {
//				panic("mock out the UnassignGithubInstallationOrganization method")
//			},
//			UpdateGithubInstallationOrganizationIDFunc: func(ctx context.Context, installationID int64, organizationID string) error {
//				panic("mock out the UpdateGithubInstallationOrganizationID method")
//			},
//		}
//
//		// use mockedDB in code that requires DB
//		// and then make assertions.
//
//	}
type DBMock struct {
	// DeleteGithubInstallationFunc mocks the DeleteGithubInstallation method.
	DeleteGithubInstallationFunc func(ctx context.Context, installationID int64) error

	// FetchGithubInstallationByOrganizationIDFunc mocks the FetchGithubInstallationByOrganizationID method.
	FetchGithubInstallationByOrganizationIDFunc func(ctx context.Context, organizationID string) (int64, error)

	// FetchGithubInstallationOrganizationIDFunc mocks the FetchGithubInstallationOrganizationID method.
	FetchGithubInstallationOrganizationIDFunc func(ctx context.Context, installationID int64) (null.String, error)

	// InsertGithubInstallationFunc mocks the InsertGithubInstallation method.
	InsertGithubInstallationFunc func(ctx context.Context, installationID int64) error

	// UnassignGithubInstallationOrganizationFunc mocks the UnassignGithubInstallationOrganization method.
	UnassignGithubInstallationOrganizationFunc func(ctx context.Context, organizationID string) error

	// UpdateGithubInstallationOrganizationIDFunc mocks the UpdateGithubInstallationOrganizationID method.
	UpdateGithubInstallationOrganizationIDFunc func(ctx context.Context, installationID int64, organizationID string) error

	// calls tracks calls to the methods.
	calls struct {
		// DeleteGithubInstallation holds details about calls to the DeleteGithubInstallation method.
		DeleteGithubInstallation []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// InstallationID is the installationID argument value.
			InstallationID int64
		}
		// FetchGithubInstallationByOrganizationID holds details about calls to the FetchGithubInstallationByOrganizationID method.
		FetchGithubInstallationByOrganizationID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrganizationID is the organizationID argument value.
			OrganizationID string
		}
		// FetchGithubInstallationOrganizationID holds details about calls to the FetchGithubInstallationOrganizationID method.
		FetchGithubInstallationOrganizationID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// InstallationID is the installationID argument value.
			InstallationID int64
		}
		// InsertGithubInstallation holds details about calls to the InsertGithubInstallation method.
		InsertGithubInstallation []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// InstallationID is the installationID argument value.
			InstallationID int64
		}
		// UnassignGithubInstallationOrganization holds details about calls to the UnassignGithubInstallationOrganization method.
		UnassignGithubInstallationOrganization []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrganizationID is the organizationID argument value.
			OrganizationID string
		}
		// UpdateGithubInstallationOrganizationID holds details about calls to the UpdateGithubInstallationOrganizationID method.
		UpdateGithubInstallationOrganizationID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// InstallationID is the installationID argument value.
			InstallationID int64
			// OrganizationID is the organizationID argument value.
			OrganizationID string
		}
	}
	lockDeleteGithubInstallation                sync.RWMutex
	lockFetchGithubInstallationByOrganizationID sync.RWMutex
	lockFetchGithubInstallationOrganizationID   sync.RWMutex
	lockInsertGithubInstallation                sync.RWMutex
	lockUnassignGithubInstallationOrganization  sync.RWMutex
	lockUpdateGithubInstallationOrganizationID  sync.RWMutex
}

// DeleteGithubInstallation calls DeleteGithubInstallationFunc.
func (mock *DBMock) DeleteGithubInstallation(ctx context.Context, installationID int64) error {
	callInfo := struct {
		Ctx            context.Context
		InstallationID int64
	}{
		Ctx:            ctx,
		InstallationID: installationID,
	}
	mock.lockDeleteGithubInstallation.Lock()
	mock.calls.DeleteGithubInstallation = append(mock.calls.DeleteGithubInstallation, callInfo)
	mock.lockDeleteGithubInstallation.Unlock()
	if mock.DeleteGithubInstallationFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.DeleteGithubInstallationFunc(ctx, installationID)
}

// DeleteGithubInstallationCalls gets all the calls that were made to DeleteGithubInstallation.
// Check the length with:
//
//	len(mockedDB.DeleteGithubInstallationCalls())
func (mock *DBMock) DeleteGithubInstallationCalls() []struct {
	Ctx            context.Context
	InstallationID int64
} {
	var calls []struct {
		Ctx            context.Context
		InstallationID int64
	}
	mock.lockDeleteGithubInstallation.RLock()
	calls = mock.calls.DeleteGithubInstallation
	mock.lockDeleteGithubInstallation.RUnlock()
	return calls
}

// FetchGithubInstallationByOrganizationID calls FetchGithubInstallationByOrganizationIDFunc.
func (mock *DBMock) FetchGithubInstallationByOrganizationID(ctx context.Context, organizationID string) (int64, error) {
	callInfo := struct {
		Ctx            context.Context
		OrganizationID string
	}{
		Ctx:            ctx,
		OrganizationID: organizationID,
	}
	mock.lockFetchGithubInstallationByOrganizationID.Lock()
	mock.calls.FetchGithubInstallationByOrganizationID = append(mock.calls.FetchGithubInstallationByOrganizationID, callInfo)
	mock.lockFetchGithubInstallationByOrganizationID.Unlock()
	if mock.FetchGithubInstallationByOrganizationIDFunc == nil {
		var (
			nOut   int64
			errOut error
		)
		return nOut, errOut
	}
	return mock.FetchGithubInstallationByOrganizationIDFunc(ctx, organizationID)
}

// FetchGithubInstallationByOrganizationIDCalls gets all the calls that were made to FetchGithubInstallationByOrganizationID.
// Check the length with:
//
//	len(mockedDB.FetchGithubInstallationByOrganizationIDCalls())
func (mock *DBMock) FetchGithubInstallationByOrganizationIDCalls() []struct {
	Ctx            context.Context
	OrganizationID string
} {
	var calls []struct {
		Ctx            context.Context
		OrganizationID string
	}
	mock.lockFetchGithubInstallationByOrganizationID.RLock()
	calls = mock.calls.FetchGithubInstallationByOrganizationID
	mock.lockFetchGithubInstallationByOrganizationID.RUnlock()
	return calls
}

// FetchGithubInstallationOrganizationID calls FetchGithubInstallationOrganizationIDFunc.
func (mock *DBMock) FetchGithubInstallationOrganizationID(ctx context.Context, installationID int64) (null.String, error) {
	callInfo := struct {
		Ctx            context.Context
		InstallationID int64
	}{
		Ctx:            ctx,
		InstallationID: installationID,
	}
	mock.lockFetchGithubInstallationOrganizationID.Lock()
	mock.calls.FetchGithubInstallationOrganizationID = append(mock.calls.FetchGithubInstallationOrganizationID, callInfo)
	mock.lockFetchGithubInstallationOrganizationID.Unlock()
	if mock.FetchGithubInstallationOrganizationIDFunc == nil {
		var (
			stringOut null.String
			errOut    error
		)
		return stringOut, errOut
	}
	return mock.FetchGithubInstallationOrganizationIDFunc(ctx, installationID)
}

// FetchGithubInstallationOrganizationIDCalls gets all the calls that were made to FetchGithubInstallationOrganizationID.
// Check the length with:
//
//	len(mockedDB.FetchGithubInstallationOrganizationIDCalls())
func (mock *DBMock) FetchGithubInstallationOrganizationIDCalls() []struct {
	Ctx            context.Context
	InstallationID int64
} {
	var calls []struct {
		Ctx            context.Context
		InstallationID int64
	}
	mock.lockFetchGithubInstallationOrganizationID.RLock()
	calls = mock.calls.FetchGithubInstallationOrganizationID
	mock.lockFetchGithubInstallationOrganizationID.RUnlock()
	return calls
}

// InsertGithubInstallation calls InsertGithubInstallationFunc.
func (mock *DBMock) InsertGithubInstallation(ctx context.Context, installationID int64) error {
	callInfo := struct {
		Ctx            context.Context
		InstallationID int64
	}{
		Ctx:            ctx,
		InstallationID: installationID,
	}
	mock.lockInsertGithubInstallation.Lock()
	mock.calls.InsertGithubInstallation = append(mock.calls.InsertGithubInstallation, callInfo)
	mock.lockInsertGithubInstallation.Unlock()
	if mock.InsertGithubInstallationFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.InsertGithubInstallationFunc(ctx, installationID)
}

// InsertGithubInstallationCalls gets all the calls that were made to InsertGithubInstallation.
// Check the length with:
//
//	len(mockedDB.InsertGithubInstallationCalls())
func (mock *DBMock) InsertGithubInstallationCalls() []struct {
	Ctx            context.Context
	InstallationID int64
} {
	var calls []struct {
		Ctx            context.Context
		InstallationID int64
	}
	mock.lockInsertGithubInstallation.RLock()
	calls = mock.calls.InsertGithubInstallation
	mock.lockInsertGithubInstallation.RUnlock()
	return calls
}

// UnassignGithubInstallationOrganization calls UnassignGithubInstallationOrganizationFunc.
func (mock *DBMock) UnassignGithubInstallationOrganization(ctx context.Context, organizationID string) error {
	callInfo := struct {
		Ctx            context.Context
		OrganizationID string
	}{
		Ctx:            ctx,
		OrganizationID: organizationID,
	}
	mock.lockUnassignGithubInstallationOrganization.Lock()
	mock.calls.UnassignGithubInstallationOrganization = append(mock.calls.UnassignGithubInstallationOrganization, callInfo)
	mock.lockUnassignGithubInstallationOrganization.Unlock()
	if mock.UnassignGithubInstallationOrganizationFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.UnassignGithubInstallationOrganizationFunc(ctx, organizationID)
}

// UnassignGithubInstallationOrganizationCalls gets all the calls that were made to UnassignGithubInstallationOrganization.
// Check the length with:
//
//	len(mockedDB.UnassignGithubInstallationOrganizationCalls())
func (mock *DBMock) UnassignGithubInstallationOrganizationCalls() []struct {
	Ctx            context.Context
	OrganizationID string
} {
	var calls []struct {
		Ctx            context.Context
		OrganizationID string
	}
	mock.lockUnassignGithubInstallationOrganization.RLock()
	calls = mock.calls.UnassignGithubInstallationOrganization
	mock.lockUnassignGithubInstallationOrganization.RUnlock()
	return calls
}

// UpdateGithubInstallationOrganizationID calls UpdateGithubInstallationOrganizationIDFunc.
func (mock *DBMock) UpdateGithubInstallationOrganizationID(ctx context.Context, installationID int64, organizationID string) error {
	callInfo := struct {
		Ctx            context.Context
		InstallationID int64
		OrganizationID string
	}{
		Ctx:            ctx,
		InstallationID: installationID,
		OrganizationID: organizationID,
	}
	mock.lockUpdateGithubInstallationOrganizationID.Lock()
	mock.calls.UpdateGithubInstallationOrganizationID = append(mock.calls.UpdateGithubInstallationOrganizationID, callInfo)
	mock.lockUpdateGithubInstallationOrganizationID.Unlock()
	if mock.UpdateGithubInstallationOrganizationIDFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.UpdateGithubInstallationOrganizationIDFunc(ctx, installationID, organizationID)
}

// UpdateGithubInstallationOrganizationIDCalls gets all the calls that were made to UpdateGithubInstallationOrganizationID.
// Check the length with:
//
//	len(mockedDB.UpdateGithubInstallationOrganizationIDCalls())
func (mock *DBMock) UpdateGithubInstallationOrganizationIDCalls() []struct {
	Ctx            context.Context
	InstallationID int64
	OrganizationID string
} {
	var calls []struct {
		Ctx            context.Context
		InstallationID int64
		OrganizationID string
	}
	mock.lockUpdateGithubInstallationOrganizationID.RLock()
	calls = mock.calls.UpdateGithubInstallationOrganizationID
	mock.lockUpdateGithubInstallationOrganizationID.RUnlock()
	return calls
}
