// icons a document can carry in its title, in the order the picker shows
// them.
const icons: (string | [id: string, name: string])[] = [
	// documents & knowledge
	"mingcute:document-2-fill",
	"mingcute:document-3-fill",
	"mingcute:documents-fill",
	"mingcute:doc-fill",
	"mingcute:file-code-fill",
	"mingcute:file-certificate-fill",
	"mingcute:file-check-fill",
	"mingcute:file-info-fill",
	"mingcute:file-locked-fill",
	"mingcute:file-search-fill",
	"mingcute:file-warning-fill",
	"mingcute:file-zip-fill",
	"mingcute:pdf-fill",
	"mingcute:markdown-fill",
	"mingcute:xls-fill",
	"mingcute:folder-fill",
	"mingcute:folder-open-fill",
	"mingcute:folders-fill",
	"mingcute:folder-locked-fill",
	"mingcute:book-fill",
	"mingcute:book-2-fill",
	"mingcute:book-3-fill",
	"mingcute:book-6-fill",
	"mingcute:notebook-fill",
	"mingcute:notebook-2-fill",
	"mingcute:diary-fill",
	"mingcute:news-fill",
	"mingcute:paper-fill",
	"fluent:script-24-filled",
	"mingcute:clipboard-fill",
	"mingcute:list-check-fill",
	"mingcute:list-ordered-fill",
	"ph:kanban-fill",
	"fluent:steps-24-filled",
	"mingcute:task-fill",
	"mingcute:task-2-fill",
	"mingcute:to-do-fill",
	"mingcute:report-fill",
	"mingcute:report-forms-fill",
	"mingcute:presentation-1-fill",
	"mingcute:presentation-2-fill",
	"mingcute:whiteboard-fill",
	"mingcute:black-board-fill",
	"mingcute:mind-map-fill",
	"mingcute:sitemap-fill",
	"mingcute:timeline-fill",
	"mingcute:version-fill",
	"mingcute:quill-pen-fill",
	"mingcute:pen-fill",
	"mingcute:pencil-fill",
	"mingcute:edit-fill",
	"mingcute:mark-pen-fill",
	"mingcute:signature-fill",
	"mingcute:certificate-fill",
	"mingcute:seal-fill",
	"mingcute:quote-left-fill",
	"mingcute:translate-fill",
	"mingcute:pin-fill",
	"mingcute:inbox-fill",
	"mingcute:archive-fill",
	"mingcute:package-fill",
	"mingcute:package-2-fill",
	"mingcute:box-2-fill",
	"mingcute:box-3-fill",
	"mingcute:question-fill",
	"mingcute:information-fill",
	"mingcute:bulb-fill",
	"mingcute:brain-fill",
	"mingcute:thought-fill",
	"mingcute:mortarboard-fill",
	"mingcute:school-fill",
	"mingcute:telescope-fill",
	"mingcute:microscope-fill",
	"mingcute:flask-fill",
	"mingcute:test-tube-fill",
	"mingcute:science-fill",
	"mingcute:formula-fill",
	"ph:sigma-fill",
	"ph:math-operations-fill",
	"ri:calculator-fill",
	"ri:atom-fill",
	"ri:dna-fill",
	"mingcute:omega-fill",
	"mingcute:asterisk-fill",

	// code
	"mingcute:code-fill",
	"mingcute:braces-fill",
	["fluent:braces-variable-24-filled", "variable"],
	"ph:function-fill",
	"ph:binary-fill",
	"mingcute:brackets-fill",
	"mingcute:brackets-angle-fill",
	"mingcute:markup-fill",
	"mingcute:terminal-fill",
	"mingcute:terminal-box-fill",
	["fluent:window-dev-tools-24-filled", "dev tools"],
	"mingcute:command-fill",
	"mingcute:hotkey-fill",
	"mingcute:keyboard-fill",
	"mingcute:bug-fill",
	"mingcute:git-branch-fill",
	"mingcute:git-commit-fill",
	"mingcute:git-compare-fill",
	"mingcute:git-merge-fill",
	"mingcute:git-pull-request-fill",
	"mingcute:git-pull-request-close-fill",
	"ri:git-repository-fill",
	"ri:git-repository-private-fill",
	"mingcute:plugin-fill",
	"mingcute:plugin-2-fill",
	"ph:plugs-connected-fill",
	"mingcute:components-fill",
	"mingcute:layers-fill",
	"ph:stack-fill",
	"mingcute:layer-fill",
	"mingcute:cube-fill",
	"mingcute:cube-3d-fill",
	"mingcute:hexagon-fill",
	"mingcute:hexagons-fill",
	"mingcute:process-fill",
	"fluent:pipeline-24-filled",
	"fluent:flowchart-24-filled",
	"ph:queue-fill",
	"ri:infinity-fill",
	"mingcute:transformation-fill",
	"mingcute:random-fill",
	"mingcute:repeat-fill",
	"mingcute:shuffle-fill",
	"mingcute:switch-fill",
	"mingcute:toggle-right-fill",
	"mingcute:cursor-fill",
	"mingcute:mouse-fill",
	"mingcute:inspect-fill",
	"mingcute:search-fill",
	"mingcute:filter-fill",
	"mingcute:filter-2-fill",
	"mingcute:sort-ascending-fill",
	"mingcute:sort-descending-fill",
	"mingcute:target-fill",
	"mingcute:aiming-fill",
	"mingcute:magic-1-fill",
	"mingcute:sparkles-fill",
	"mingcute:ai-fill",
	"mingcute:robot-fill",
	"mingcute:webhook-fill",
	"mingcute:mqtt-fill",
	"mingcute:rss-fill",
	"mingcute:web-fill",
	"mingcute:world-fill",
	"mingcute:earth-fill",
	"mingcute:globe-fill",
	"mingcute:link-fill",
	"mingcute:unlink-fill",
	"mingcute:external-link-fill",
	"mingcute:qrcode-fill",
	"mingcute:barcode-fill",
	"mingcute:scan-fill",

	// infrastructure
	"mingcute:server-fill",
	"mingcute:server-2-fill",
	"ri:instance-fill",
	["ph:shipping-container-fill", "container"],
	"mingcute:storage-fill",
	"ri:database-2-fill",
	"ri:hard-drive-2-fill",
	"mingcute:drive-fill",
	"mingcute:cylinder-fill",
	"mingcute:cylinder-2-fill",
	"mingcute:safe-box-fill",
	"mingcute:usb-fill",
	"mingcute:usb-flash-disk-fill",
	"mingcute:router-modem-fill",
	"mingcute:base-station-fill",
	"ph:network-fill",
	"ph:broadcast-fill",
	"mingcute:wifi-fill",
	"mingcute:signal-fill",
	"mingcute:bluetooth-fill",
	"mingcute:nfc-fill",
	"mingcute:cloud-fill",
	"mingcute:cloud-2-fill",
	"mingcute:clouds-fill",
	"mingcute:cloud-lightning-fill",
	"fluent:cloud-sync-24-filled",
	"mingcute:monitor-fill",
	"mingcute:display-fill",
	"mingcute:computer-fill",
	"mingcute:laptop-fill",
	"mingcute:imac-fill",
	"mingcute:device-fill",
	"mingcute:chip-fill",
	"ph:cpu-fill",
	"ph:memory-fill",
	"ri:ram-fill",
	"ph:circuitry-fill",
	"mingcute:cellphone-fill",
	"mingcute:pad-fill",
	"mingcute:watch-fill",
	"mingcute:tv-1-fill",
	"mingcute:projector-fill",
	"mingcute:print-fill",
	"mingcute:remote-fill",
	"mingcute:power-fill",
	"mingcute:flash-fill",
	"mingcute:lightning-fill",
	"mingcute:battery-fill",
	"mingcute:battery-charging-fill",
	"mingcute:charging-pile-fill",
	"mingcute:solar-panel-fill",
	"mingcute:high-voltage-power-fill",
	"mingcute:engine-fill",
	"mingcute:fan-fill",
	"mingcute:thermometer-fill",
	"mingcute:fire-fill",
	"mingcute:flame-fill",
	"mingcute:drop-fill",
	"mingcute:wind-fill",
	"mingcute:tornado-fill",
	"mingcute:thunderstorm-fill",
	"mingcute:sun-fill",
	"mingcute:moon-fill",
	"mingcute:moon-stars-fill",
	"mingcute:planet-fill",
	"mingcute:rocket-fill",
	"mingcute:rocket-2-fill",
	"mingcute:ufo-fill",
	"mingcute:drone-fill",
	"mingcute:radar-fill",
	"mingcute:radar-2-fill",
	"mingcute:compass-fill",
	"mingcute:navigation-fill",
	"mingcute:map-fill",
	"mingcute:map-pin-fill",
	"mingcute:location-fill",
	"mingcute:route-fill",
	"mingcute:directions-fill",
	"mingcute:road-fill",
	"mingcute:bridge-fill",
	"mingcute:tunnel-fill",
	"mingcute:tower-fill",
	"mingcute:tv-tower-fill",
	"mingcute:lighthouse-fill",
	"mingcute:anchor-fill",
	"mingcute:ship-fill",
	"mingcute:sailboat-fill",
	"mingcute:truck-fill",
	"mingcute:train-fill",
	"mingcute:bus-fill",
	"mingcute:car-fill",
	"mingcute:airplane-fill",
	"mingcute:flight-takeoff-fill",
	"mingcute:flight-land-fill",
	"mingcute:parachute-fill",
	"mingcute:lifebuoy-fill",
	"mingcute:traffic-cone-fill",
	"mingcute:traffic-lights-fill",
	"mingcute:home-1-fill",
	"mingcute:house-fill",
	"mingcute:door-fill",
	"mingcute:enter-door-fill",
	"mingcute:exit-door-fill",
	"mingcute:building-1-fill",
	"mingcute:building-2-fill",
	"mingcute:factory-fill",
	"mingcute:bank-fill",
	"mingcute:government-fill",
	"mingcute:store-fill",
	"mingcute:inventory-fill",
	"mingcute:trunk-fill",
	"mingcute:tower-crane-fill",
	"mingcute:ladder-fill",
	"mingcute:hammer-fill",
	"mingcute:screwdriver-fill",
	"mingcute:tool-fill",
	"ph:toolbox-fill",
	"mingcute:settings-1-fill",
	"mingcute:settings-3-fill",
	"mingcute:settings-6-fill",
	"mingcute:pickax-fill",
	"mingcute:axe-fill",
	"mingcute:shovel-fill",
	"mingcute:magnet-fill",
	"mingcute:broom-fill",
	"mingcute:recycle-fill",
	"mingcute:wastebasket-fill",
	"mingcute:delete-2-fill",

	// metrics & data
	"mingcute:chart-bar-fill",
	"mingcute:chart-bar-2-fill",
	"mingcute:chart-line-fill",
	"mingcute:chart-pie-fill",
	"mingcute:chart-pie-2-fill",
	"mingcute:chart-vertical-fill",
	"mingcute:chart-horizontal-fill",
	"mingcute:chart-decrease-fill",
	["fluent:data-scatter-24-filled", "scatter chart"],
	["fluent:data-treemap-24-filled", "treemap"],
	"ph:graph-fill",
	"mingcute:trending-up-fill",
	"mingcute:trending-down-fill",
	"mingcute:stock-fill",
	"mingcute:performance-fill",
	"mingcute:dashboard-fill",
	"mingcute:dashboard-2-fill",
	"mingcute:dashboard-3-fill",
	"mingcute:dashboard-4-fill",
	"ph:gauge-fill",
	"mingcute:counter-fill",
	"mingcute:percentage-fill",
	"mingcute:wave-fill",
	"mingcute:sound-line-fill",
	"mingcute:heartbeat-fill",
	"mingcute:heartbeat-2-fill",
	"mingcute:table-fill",
	"mingcute:table-2-fill",
	"mingcute:grid-fill",
	"mingcute:layout-fill",
	"mingcute:balance-fill",
	"mingcute:scale-fill",
	"mingcute:ruler-fill",
	"mingcute:pencil-ruler-fill",
	"mingcute:gradienter-fill",
	"mingcute:time-fill",
	"mingcute:clock-fill",
	"mingcute:stopwatch-fill",
	"mingcute:sandglass-fill",
	"mingcute:hours-fill",
	"mingcute:history-fill",
	"mingcute:schedule-fill",
	"mingcute:calendar-fill",
	"mingcute:calendar-month-fill",
	"mingcute:calendar-week-fill",
	"mingcute:alarm-1-fill",

	// security
	"mingcute:key-1-fill",
	"mingcute:key-2-fill",
	"mingcute:keyhole-fill",
	"fluent:password-24-filled",
	"mingcute:lock-fill",
	"mingcute:unlock-fill",
	"mingcute:shield-fill",
	"mingcute:shield-shape-fill",
	"mingcute:safe-shield-fill",
	"mingcute:safety-certificate-fill",
	"mingcute:safe-lock-fill",
	"mingcute:safe-alert-fill",
	"mingcute:fingerprint-fill",
	"mingcute:faceid-fill",
	"mingcute:incognito-mode-fill",
	"mingcute:eye-fill",
	"mingcute:eye-close-fill",
	"mingcute:virus-fill",
	"mingcute:bomb-fill",
	"mingcute:skull-fill",
	"mingcute:ghost-fill",
	"mingcute:sword-fill",

	// status & incidents
	"mingcute:notification-fill",
	"mingcute:bell-ringing-fill",
	"mingcute:announcement-fill",
	"mingcute:horn-fill",
	"mingcute:flag-1-fill",
	"mingcute:flag-2-fill",
	"mingcute:flag-3-fill",
	"mingcute:flag-4-fill",
	"mingcute:check-circle-fill",
	"mingcute:close-circle-fill",
	"mingcute:forbid-circle-fill",
	"mingcute:minus-circle-fill",
	"mingcute:add-circle-fill",
	"mingcute:alert-fill",
	"mingcute:alert-octagon-fill",
	"mingcute:alert-diamond-fill",
	"mingcute:warning-fill",
	"mingcute:fault-fill",
	"mingcute:stethoscope-fill",
	"mingcute:first-aid-kit-fill",
	"mingcute:capsule-fill",
	"mingcute:hospital-fill",
	"mingcute:medal-fill",
	"mingcute:trophy-fill",
	"mingcute:award-fill",
	"mingcute:star-fill",
	"mingcute:heart-fill",
	"mingcute:thumb-up-fill",
	"mingcute:thumb-down-fill",

	// people & communication
	"mingcute:user-1-fill",
	"mingcute:user-3-fill",
	"mingcute:user-add-fill",
	"mingcute:user-setting-fill",
	"mingcute:user-security-fill",
	"mingcute:user-lock-fill",
	"mingcute:user-star-fill",
	"mingcute:user-search-fill",
	"mingcute:group-fill",
	"mingcute:group-2-fill",
	"mingcute:contacts-fill",
	"mingcute:department-fill",
	"mingcute:idcard-fill",
	"mingcute:profile-fill",
	"mingcute:invite-fill",
	"mingcute:briefcase-fill",
	"mingcute:suitcase-fill",
	"mingcute:mail-fill",
	"mingcute:mail-send-fill",
	"mingcute:mail-open-fill",
	"mingcute:chat-1-fill",
	"mingcute:chat-2-fill",
	"mingcute:chat-4-fill",
	"mingcute:message-1-fill",
	"mingcute:message-3-fill",
	"mingcute:comment-fill",
	"mingcute:phone-fill",
	"mingcute:phone-call-fill",
	"mingcute:video-fill",
	"mingcute:video-camera-fill",
	"mingcute:mic-fill",
	"mingcute:headphone-fill",
	"mingcute:speaker-fill",
	"mingcute:volume-fill",
	"mingcute:live-fill",
	"mingcute:hands-clapping-fill",
	"mingcute:wave-hand-fill",
	"mingcute:hand-heart-fill",
	"ph:handshake-fill",
	"mingcute:celebrate-fill",
	"mingcute:firework-fill",
	"mingcute:gift-fill",
	"mingcute:cake-fill",
	"mingcute:teacup-fill",
	"mingcute:game-1-fill",
	"mingcute:chess-fill",
	"mingcute:leaf-fill",
	"mingcute:tree-2-fill",

	// money
	"mingcute:wallet-fill",
	"mingcute:coin-fill",
	"mingcute:cash-fill",
	"mingcute:bank-card-fill",
	"mingcute:bill-fill",
	"mingcute:pig-money-fill",
	"mingcute:currency-dollar-fill",
	"mingcute:currency-euro-fill",
	"mingcute:receive-money-fill",
	"mingcute:exchange-dollar-fill",
	"mingcute:sale-fill",
	"mingcute:coupon-fill",
	"mingcute:ticket-fill",
	"mingcute:auction-fill",

	// brands MingCute draws in its own style
	"mingcute:github-fill",
	"mingcute:git-lab-fill",
	"mingcute:linux-fill",
	"mingcute:ubuntu-fill",
	"mingcute:windows-fill",
	"mingcute:apple-fill",
	"mingcute:android-fill",
	"mingcute:chrome-fill",
	"mingcute:firefox-fill",
	"mingcute:safari-fill",
	"mingcute:edge-fill",
	"mingcute:vscode-fill",
	"mingcute:react-fill",
	"mingcute:vue-fill",
	"mingcute:figma-fill",
	"mingcute:notion-fill",
	"mingcute:discord-fill",
	"mingcute:telegram-fill",
	"mingcute:dropbox-fill",
	"mingcute:stripe-fill",
	"mingcute:paypal-fill",
	"mingcute:youtube-fill",
	"mingcute:reddit-fill",
	"mingcute:mastodon-fill",
	"mingcute:openai-fill",
	"mingcute:claude-fill",
	"mingcute:copilot-fill",
	"mingcute:mcp-fill",
	"mingcute:deepseek-fill",
	"mingcute:gemini-fill",
	"mingcute:grok-fill",
	"mingcute:perplexity-fill",
	"mingcute:vibe-coding-fill",

	// containers & clusters
	"simple-icons:kubernetes",
	"simple-icons:docker",
	"simple-icons:containerd",
	"simple-icons:helm",
	"simple-icons:rancher",
	"simple-icons:k3s",
	"simple-icons:talos",
	["simple-icons:redhatopenshift", "openshift"],
	"simple-icons:istio",
	"simple-icons:linkerd",
	["simple-icons:envoyproxy", "envoy"],
	"simple-icons:argo",
	"simple-icons:openstack",
	"simple-icons:proxmox",
	"file-icons:vmware",
	"simple-icons:virtualbox",
	"simple-icons:qemu",
	"simple-icons:portainer",

	// infrastructure as code
	"simple-icons:terraform",
	"simple-icons:ansible",
	"simple-icons:puppet",
	"simple-icons:chef",
	"simple-icons:pulumi",
	"simple-icons:hashicorp",
	"simple-icons:vault",
	"simple-icons:consul",
	"simple-icons:nomad",
	"simple-icons:backstage",

	// observability
	"simple-icons:prometheus",
	"simple-icons:grafana",
	"simple-icons:opentelemetry",
	"simple-icons:jaeger",
	"simple-icons:thanos",
	"simple-icons:victoriametrics",
	"simple-icons:influxdb",
	"simple-icons:elasticsearch",
	"simple-icons:kibana",
	"simple-icons:opensearch",
	"simple-icons:sentry",
	"simple-icons:datadog",
	["simple-icons:newrelic", "new relic"],
	"simple-icons:pagerduty",
	["simple-icons:uptimekuma", "uptime kuma"],

	// data stores & pipelines
	"devicon-plain:postgresql",
	"devicon-plain:mysql",
	"simple-icons:mariadb",
	"simple-icons:sqlite",
	"simple-icons:mongodb",
	"simple-icons:redis",
	"simple-icons:clickhouse",
	["simple-icons:cockroachlabs", "cockroachdb"],
	"simple-icons:etcd",
	"simple-icons:meilisearch",
	"simple-icons:minio",
	"simple-icons:rabbitmq",
	["simple-icons:apachekafka", "kafka"],
	"cib:cassandra",
	["cib:apache-spark", "spark"],
	["simple-icons:snowflake", "snowflake (data cloud)"],
	"simple-icons:databricks",
	"simple-icons:supabase",
	"ri:firebase-fill",
	"simple-icons:prisma",
	"simple-icons:metabase",
	"simple-icons:posthog",
	["simple-icons:googleanalytics", "google analytics"],

	// networking & edge
	"simple-icons:nginx",
	"file-icons:caddy",
	"simple-icons:kong",
	"simple-icons:cloudflare",
	["simple-icons:letsencrypt", "let's encrypt"],
	"simple-icons:wireguard",
	"simple-icons:openvpn",
	"simple-icons:tailscale",

	// source control & delivery
	"simple-icons:git",
	"simple-icons:gitea",
	"simple-icons:bitbucket",
	"devicon-plain:jenkins",
	"simple-icons:circleci",
	"simple-icons:dependabot",
	"simple-icons:codecov",
	"simple-icons:snyk",
	"simple-icons:trivy",
	"simple-icons:owasp",

	// cloud
	["simple-icons:amazonwebservices", "aws"],
	["simple-icons:googlecloud", "google cloud"],
	["simple-icons:googlebigquery", "bigquery"],
	["simple-icons:microsoftazure", "azure"],
	["simple-icons:azuredevops", "azure devops"],
	"simple-icons:digitalocean",
	"simple-icons:hetzner",
	"simple-icons:vercel",
	"cib:netlify",
	"simple-icons:heroku",
	["simple-icons:flydotio", "fly.io"],
	"simple-icons:railway",

	// operating systems & devices
	"simple-icons:fedora",
	"mdi:debian",
	["simple-icons:archlinux", "arch linux"],
	["simple-icons:alpinelinux", "alpine linux"],
	"simple-icons:nixos",
	["simple-icons:rockylinux", "rocky linux"],
	"ri:centos-fill",
	["simple-icons:redhat", "red hat"],
	"simple-icons:freebsd",
	["simple-icons:raspberrypi", "raspberry pi"],
	["simple-icons:homeassistant", "home assistant"],
	["simple-icons:eclipsemosquitto", "mosquitto"],
	"simple-icons:zapier",

	// languages & shells
	"devicon-plain:go",
	"simple-icons:rust",
	"simple-icons:python",
	"simple-icons:typescript",
	"simple-icons:javascript",
	["devicon-plain:nodejs", "node.js"],
	"simple-icons:bun",
	"simple-icons:deno",
	"ri:php-fill",
	"simple-icons:ruby",
	"simple-icons:kotlin",
	"simple-icons:swift",
	["devicon-plain:dot-net", ".net"],
	["simple-icons:csharp", "c#"],
	["simple-icons:cplusplus", "c++"],
	"simple-icons:c",
	"simple-icons:zig",
	"simple-icons:elixir",
	"simple-icons:erlang",
	"simple-icons:haskell",
	"simple-icons:scala",
	"simple-icons:lua",
	"devicon-plain:perl",
	"simple-icons:r",
	"simple-icons:julia",
	"simple-icons:webassembly",
	"simple-icons:powershell",
	"mdi:bash",

	// frameworks & tooling
	["simple-icons:vuedotjs", "vue.js"],
	"simple-icons:nuxt",
	["simple-icons:nextdotjs", "next.js"],
	"simple-icons:svelte",
	"simple-icons:angular",
	"simple-icons:astro",
	"simple-icons:hono",
	"simple-icons:nestjs",
	"simple-icons:fastapi",
	"simple-icons:django",
	["simple-icons:flask", "flask (python)"],
	"simple-icons:spring",
	"devicon-plain:laravel",
	["devicon-plain:rails", "ruby on rails"],
	["simple-icons:tailwindcss", "tailwind css"],
	"simple-icons:vite",
	"simple-icons:webpack",
	"simple-icons:eslint",
	"simple-icons:prettier",
	"simple-icons:vitest",
	"simple-icons:jest",
	"simple-icons:playwright",
	"simple-icons:cypress",
	"simple-icons:storybook",
	"simple-icons:graphql",
	["simple-icons:openapiinitiative", "openapi"],
	"simple-icons:swagger",
	"simple-icons:postman",
	"simple-icons:npm",
	"simple-icons:pnpm",
	"simple-icons:yarn",
	["simple-icons:d3dotjs", "d3.js"],
	"simple-icons:mermaid",
	"simple-icons:excalidraw",
	["simple-icons:diagramsdotnet", "diagrams.net"],
	"simple-icons:json",
	"simple-icons:yaml",

	// ai
	"simple-icons:anthropic",
	["simple-icons:huggingface", "hugging face"],
	"simple-icons:pytorch",
	"simple-icons:tensorflow",
	"simple-icons:ollama",
	"simple-icons:langchain",
	["simple-icons:mistralai", "mistral"],
	["simple-icons:cursor", "cursor (editor)"],

	// collaboration & docs
	"simple-icons:slack",
	"simple-icons:jira",
	"simple-icons:confluence",
	"simple-icons:trello",
	"simple-icons:linear",
	"simple-icons:clickup",
	"simple-icons:asana",
	"simple-icons:miro",
	"simple-icons:mattermost",
	["simple-icons:googlemeet", "google meet"],
	["simple-icons:microsoftteams", "microsoft teams"],
	["ph:matrix-logo-fill", "matrix"],
	"simple-icons:obsidian",
	["simple-icons:readthedocs", "read the docs"],
	"simple-icons:docusaurus",
	"simple-icons:gitbook",
	["simple-icons:stackoverflow", "stack overflow"],

	// editors & terminals
	"simple-icons:jetbrains",
	"simple-icons:neovim",
	"simple-icons:vim",
	"simple-icons:tmux",

	// identity & security tooling
	"simple-icons:1password",
	"simple-icons:bitwarden",
	"simple-icons:keycloak",
	"simple-icons:auth0",
	"simple-icons:okta",
	"simple-icons:authelia",
	"simple-icons:authentik",
	"simple-icons:wireshark",
	"simple-icons:metasploit",
	["simple-icons:burpsuite", "burp suite"],

	// storage & self-hosting
	"simple-icons:rclone",
	"simple-icons:truenas",

	// third-party services
	"simple-icons:twilio",
	"simple-icons:sendgrid",
]

// the icon's own name without its collection's style suffix. A trailing
// index is a collection's disambiguator between variants of one concept;
// the glyph tells them apart, so the name does not
function displayName(id: string) {
	return id
		.slice(id.indexOf(":") + 1)
		.replace(/-24-filled$|-fill$/, "")
		.replace(/-\d+$/, "")
		.replaceAll("-", " ")
}

export const selectableIcons: {
	id: string
	name: string // displayed and searched
}[] = icons.map((entry) =>
	typeof entry === "string"
		? { id: entry, name: displayName(entry) }
		: { id: entry[0], name: entry[1] },
)

export function selectableIconList() {
	return selectableIcons.map((v) => {
		return v.id
	})
}
