// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package github

import (
	"context"
	"sync"
)

// Ensure, that DBMock does implement DB.
// If this is not the case, regenerate this file with moq.
var _ DB = &DBMock{}

// DBMock is a mock implementation of DB.
//
//	func TestSomethingThatUsesDB(t *testing.T) {
//
//		// make and configure a mocked DB
//		mockedDB := &DBMock{
//			FetchGithubInstallationByOrganizationIDFunc: func(ctx context.Context, organizationID string) (int64, error) {
//				panic("mock out the FetchGithubInstallationByOrganizationID method")
//			},
//		}
//
//		// use mockedDB in code that requires DB
//		// and then make assertions.
//
//	}
type DBMock struct {
	// FetchGithubInstallationByOrganizationIDFunc mocks the FetchGithubInstallationByOrganizationID method.
	FetchGithubInstallationByOrganizationIDFunc func(ctx context.Context, organizationID string) (int64, error)

	// calls tracks calls to the methods.
	calls struct {
		// FetchGithubInstallationByOrganizationID holds details about calls to the FetchGithubInstallationByOrganizationID method.
		FetchGithubInstallationByOrganizationID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrganizationID is the organizationID argument value.
			OrganizationID string
		}
	}
	lockFetchGithubInstallationByOrganizationID sync.RWMutex
}

// FetchGithubInstallationByOrganizationID calls FetchGithubInstallationByOrganizationIDFunc.
func (mock *DBMock) FetchGithubInstallationByOrganizationID(ctx context.Context, organizationID string) (int64, error) {
	callInfo := struct {
		Ctx            context.Context
		OrganizationID string
	}{
		Ctx:            ctx,
		OrganizationID: organizationID,
	}
	mock.lockFetchGithubInstallationByOrganizationID.Lock()
	mock.calls.FetchGithubInstallationByOrganizationID = append(mock.calls.FetchGithubInstallationByOrganizationID, callInfo)
	mock.lockFetchGithubInstallationByOrganizationID.Unlock()
	if mock.FetchGithubInstallationByOrganizationIDFunc == nil {
		var (
			nOut   int64
			errOut error
		)
		return nOut, errOut
	}
	return mock.FetchGithubInstallationByOrganizationIDFunc(ctx, organizationID)
}

// FetchGithubInstallationByOrganizationIDCalls gets all the calls that were made to FetchGithubInstallationByOrganizationID.
// Check the length with:
//
//	len(mockedDB.FetchGithubInstallationByOrganizationIDCalls())
func (mock *DBMock) FetchGithubInstallationByOrganizationIDCalls() []struct {
	Ctx            context.Context
	OrganizationID string
} {
	var calls []struct {
		Ctx            context.Context
		OrganizationID string
	}
	mock.lockFetchGithubInstallationByOrganizationID.RLock()
	calls = mock.calls.FetchGithubInstallationByOrganizationID
	mock.lockFetchGithubInstallationByOrganizationID.RUnlock()
	return calls
}
