version: 2
project_name: oxynote
dist: bin
snapshot:
  version_template: dev
builds:
  - id: core
    main: ./cmd/core
    binary: "{{ .ProjectName }}-core"
    mod_timestamp: "{{ .CommitTimestamp }}"
    no_unique_dist_dir: true
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    tags:
      - "{{if not .IsSnapshot}} prod {{end}}"
    flags:
      - "-trimpath"
    ldflags:
      - "-s -w"
      - "-X github.com/oxynote/oxynote/server/core/internal/buildinfo._name={{ .ProjectName }}_core"
      - "-X github.com/oxynote/oxynote/server/core/internal/buildinfo._version={{ .Version }}"
      - "-X github.com/oxynote/oxynote/server/core/internal/buildinfo._commit={{ .ShortCommit }}"
      - "-X github.com/oxynote/oxynote/server/core/internal/buildinfo._timestampString={{ .CommitDate }}"
  - id: connector
    main: ./cmd/connector
    binary: "{{ .ProjectName }}-connector"
    mod_timestamp: "{{ .CommitTimestamp }}"
    no_unique_dist_dir: true
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    tags:
      - "{{if not .IsSnapshot}} prod {{end}}"
    flags:
      - "-trimpath"
    ldflags:
      - "-s -w"
      - "-X github.com/oxynote/oxynote/server/core/internal/buildinfo._name={{ .ProjectName }}_connector"
      - "-X github.com/oxynote/oxynote/server/core/internal/buildinfo._version={{ .Version }}"
      - "-X github.com/oxynote/oxynote/server/core/internal/buildinfo._commit={{ .ShortCommit }}"
      - "-X github.com/oxynote/oxynote/server/core/internal/buildinfo._timestampString={{ .CommitDate }}"
dockers:
  - ids:
      - core
    goos: linux
    goarch: amd64
    image_templates:
      - "ghcr.io/oxynote/core:{{ .Version }}"
      - "ghcr.io/oxynote/core:latest"
    dockerfile: ./Dockerfile.dev
    build_flag_templates:
      - "--pull"
      - "--platform=linux/amd64"
      - "--build-arg=BINARY={{ .ProjectName }}-core"
  - ids:
      - connector
    goos: linux
    goarch: amd64
    image_templates:
      - "ghcr.io/oxynote/connector:{{ .Version }}"
      - "ghcr.io/oxynote/connector:latest"
    dockerfile: ./Dockerfile.dev
    build_flag_templates:
      - "--pull"
      - "--platform=linux/amd64"
      - "--build-arg=BINARY={{ .ProjectName }}-connector"
checksum:
  disable: true
archives:
  - formats: ["binary"] # disable archives
release:
  disable: true # disable release uploading to github/gitlab
changelog:
  use: github
  filters:
    exclude:
      - "^workflow(s?):"
      - "^github:"
announce:
  skip: true
