// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package tools

import (
	"sync"

	"github.com/oxynote/oxynote/server/core/internal/datasource"
)

// Ensure, that DataSourceRunnersMock does implement DataSourceRunners.
// If this is not the case, regenerate this file with moq.
var _ DataSourceRunners = &DataSourceRunnersMock{}

// DataSourceRunnersMock is a mock implementation of DataSourceRunners.
//
//	func TestSomethingThatUsesDataSourceRunners(t *testing.T) {
//
//		// make and configure a mocked DataSourceRunners
//		mockedDataSourceRunners := &DataSourceRunnersMock{
//			RunnerFunc: func(ds datasource.DataSource) datasource.Runner {
//				panic("mock out the Runner method")
//			},
//		}
//
//		// use mockedDataSourceRunners in code that requires DataSourceRunners
//		// and then make assertions.
//
//	}
type DataSourceRunnersMock struct {
	// RunnerFunc mocks the Runner method.
	RunnerFunc func(ds datasource.DataSource) datasource.Runner

	// calls tracks calls to the methods.
	calls struct {
		// Runner holds details about calls to the Runner method.
		Runner []struct {
			// Ds is the ds argument value.
			Ds datasource.DataSource
		}
	}
	lockRunner sync.RWMutex
}

// Runner calls RunnerFunc.
func (mock *DataSourceRunnersMock) Runner(ds datasource.DataSource) datasource.Runner {
	callInfo := struct {
		Ds datasource.DataSource
	}{
		Ds: ds,
	}
	mock.lockRunner.Lock()
	mock.calls.Runner = append(mock.calls.Runner, callInfo)
	mock.lockRunner.Unlock()
	if mock.RunnerFunc == nil {
		var (
			runnerOut datasource.Runner
		)
		return runnerOut
	}
	return mock.RunnerFunc(ds)
}

// RunnerCalls gets all the calls that were made to Runner.
// Check the length with:
//
//	len(mockedDataSourceRunners.RunnerCalls())
func (mock *DataSourceRunnersMock) RunnerCalls() []struct {
	Ds datasource.DataSource
} {
	var calls []struct {
		Ds datasource.DataSource
	}
	mock.lockRunner.RLock()
	calls = mock.calls.Runner
	mock.lockRunner.RUnlock()
	return calls
}
