// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package tools

import (
	"sync"

	"github.com/guregu/null/v5"
	"github.com/rs/xid"
)

// Ensure, that TreeNotifierMock does implement TreeNotifier.
// If this is not the case, regenerate this file with moq.
var _ TreeNotifier = &TreeNotifierMock{}

// TreeNotifierMock is a mock implementation of TreeNotifier.
//
//	func TestSomethingThatUsesTreeNotifier(t *testing.T) {
//
//		// make and configure a mocked TreeNotifier
//		mockedTreeNotifier := &TreeNotifierMock{
//			NotifyTreeChangeFunc: func(organizationID string, parentID null.Value[xid.ID])  {
//				panic("mock out the NotifyTreeChange method")
//			},
//		}
//
//		// use mockedTreeNotifier in code that requires TreeNotifier
//		// and then make assertions.
//
//	}
type TreeNotifierMock struct {
	// NotifyTreeChangeFunc mocks the NotifyTreeChange method.
	NotifyTreeChangeFunc func(organizationID string, parentID null.Value[xid.ID])

	// calls tracks calls to the methods.
	calls struct {
		// NotifyTreeChange holds details about calls to the NotifyTreeChange method.
		NotifyTreeChange []struct {
			// OrganizationID is the organizationID argument value.
			OrganizationID string
			// ParentID is the parentID argument value.
			ParentID null.Value[xid.ID]
		}
	}
	lockNotifyTreeChange sync.RWMutex
}

// NotifyTreeChange calls NotifyTreeChangeFunc.
func (mock *TreeNotifierMock) NotifyTreeChange(organizationID string, parentID null.Value[xid.ID]) {
	callInfo := struct {
		OrganizationID string
		ParentID       null.Value[xid.ID]
	}{
		OrganizationID: organizationID,
		ParentID:       parentID,
	}
	mock.lockNotifyTreeChange.Lock()
	mock.calls.NotifyTreeChange = append(mock.calls.NotifyTreeChange, callInfo)
	mock.lockNotifyTreeChange.Unlock()
	if mock.NotifyTreeChangeFunc == nil {
		return
	}
	mock.NotifyTreeChangeFunc(organizationID, parentID)
}

// NotifyTreeChangeCalls gets all the calls that were made to NotifyTreeChange.
// Check the length with:
//
//	len(mockedTreeNotifier.NotifyTreeChangeCalls())
func (mock *TreeNotifierMock) NotifyTreeChangeCalls() []struct {
	OrganizationID string
	ParentID       null.Value[xid.ID]
} {
	var calls []struct {
		OrganizationID string
		ParentID       null.Value[xid.ID]
	}
	mock.lockNotifyTreeChange.RLock()
	calls = mock.calls.NotifyTreeChange
	mock.lockNotifyTreeChange.RUnlock()
	return calls
}
