// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package tools

import (
	"context"
	"sync"

	"github.com/oxynote/oxynote/server/core/internal/assistant/edit"
	"github.com/rs/xid"
)

// Ensure, that EditApplierMock does implement EditApplier.
// If this is not the case, regenerate this file with moq.
var _ EditApplier = &EditApplierMock{}

// EditApplierMock is a mock implementation of EditApplier.
//
//	func TestSomethingThatUsesEditApplier(t *testing.T) {
//
//		// make and configure a mocked EditApplier
//		mockedEditApplier := &EditApplierMock{
//			ApplyFunc: func(ctx context.Context, documentID xid.ID, branchID xid.ID, ops []edit.Operation) (edit.Result, error) {
//				panic("mock out the Apply method")
//			},
//		}
//
//		// use mockedEditApplier in code that requires EditApplier
//		// and then make assertions.
//
//	}
type EditApplierMock struct {
	// ApplyFunc mocks the Apply method.
	ApplyFunc func(ctx context.Context, documentID xid.ID, branchID xid.ID, ops []edit.Operation) (edit.Result, error)

	// calls tracks calls to the methods.
	calls struct {
		// Apply holds details about calls to the Apply method.
		Apply []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// DocumentID is the documentID argument value.
			DocumentID xid.ID
			// BranchID is the branchID argument value.
			BranchID xid.ID
			// Ops is the ops argument value.
			Ops []edit.Operation
		}
	}
	lockApply sync.RWMutex
}

// Apply calls ApplyFunc.
func (mock *EditApplierMock) Apply(ctx context.Context, documentID xid.ID, branchID xid.ID, ops []edit.Operation) (edit.Result, error) {
	callInfo := struct {
		Ctx        context.Context
		DocumentID xid.ID
		BranchID   xid.ID
		Ops        []edit.Operation
	}{
		Ctx:        ctx,
		DocumentID: documentID,
		BranchID:   branchID,
		Ops:        ops,
	}
	mock.lockApply.Lock()
	mock.calls.Apply = append(mock.calls.Apply, callInfo)
	mock.lockApply.Unlock()
	if mock.ApplyFunc == nil {
		var (
			resultOut edit.Result
			errOut    error
		)
		return resultOut, errOut
	}
	return mock.ApplyFunc(ctx, documentID, branchID, ops)
}

// ApplyCalls gets all the calls that were made to Apply.
// Check the length with:
//
//	len(mockedEditApplier.ApplyCalls())
func (mock *EditApplierMock) ApplyCalls() []struct {
	Ctx        context.Context
	DocumentID xid.ID
	BranchID   xid.ID
	Ops        []edit.Operation
} {
	var calls []struct {
		Ctx        context.Context
		DocumentID xid.ID
		BranchID   xid.ID
		Ops        []edit.Operation
	}
	mock.lockApply.RLock()
	calls = mock.calls.Apply
	mock.lockApply.RUnlock()
	return calls
}
