// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package tools

import (
	"context"
	"sync"

	"github.com/oxynote/oxynote/server/core/internal/document/searchgw"
)

// Ensure, that SearcherMock does implement Searcher.
// If this is not the case, regenerate this file with moq.
var _ Searcher = &SearcherMock{}

// SearcherMock is a mock implementation of Searcher.
//
//	func TestSomethingThatUsesSearcher(t *testing.T) {
//
//		// make and configure a mocked Searcher
//		mockedSearcher := &SearcherMock{
//			SearchDocumentBlocksFunc: func(ctx context.Context, organizationID string, query string, limit int) ([]searchgw.Block, error) {
//				panic("mock out the SearchDocumentBlocks method")
//			},
//		}
//
//		// use mockedSearcher in code that requires Searcher
//		// and then make assertions.
//
//	}
type SearcherMock struct {
	// SearchDocumentBlocksFunc mocks the SearchDocumentBlocks method.
	SearchDocumentBlocksFunc func(ctx context.Context, organizationID string, query string, limit int) ([]searchgw.Block, error)

	// calls tracks calls to the methods.
	calls struct {
		// SearchDocumentBlocks holds details about calls to the SearchDocumentBlocks method.
		SearchDocumentBlocks []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrganizationID is the organizationID argument value.
			OrganizationID string
			// Query is the query argument value.
			Query string
			// Limit is the limit argument value.
			Limit int
		}
	}
	lockSearchDocumentBlocks sync.RWMutex
}

// SearchDocumentBlocks calls SearchDocumentBlocksFunc.
func (mock *SearcherMock) SearchDocumentBlocks(ctx context.Context, organizationID string, query string, limit int) ([]searchgw.Block, error) {
	callInfo := struct {
		Ctx            context.Context
		OrganizationID string
		Query          string
		Limit          int
	}{
		Ctx:            ctx,
		OrganizationID: organizationID,
		Query:          query,
		Limit:          limit,
	}
	mock.lockSearchDocumentBlocks.Lock()
	mock.calls.SearchDocumentBlocks = append(mock.calls.SearchDocumentBlocks, callInfo)
	mock.lockSearchDocumentBlocks.Unlock()
	if mock.SearchDocumentBlocksFunc == nil {
		var (
			blocksOut []searchgw.Block
			errOut    error
		)
		return blocksOut, errOut
	}
	return mock.SearchDocumentBlocksFunc(ctx, organizationID, query, limit)
}

// SearchDocumentBlocksCalls gets all the calls that were made to SearchDocumentBlocks.
// Check the length with:
//
//	len(mockedSearcher.SearchDocumentBlocksCalls())
func (mock *SearcherMock) SearchDocumentBlocksCalls() []struct {
	Ctx            context.Context
	OrganizationID string
	Query          string
	Limit          int
} {
	var calls []struct {
		Ctx            context.Context
		OrganizationID string
		Query          string
		Limit          int
	}
	mock.lockSearchDocumentBlocks.RLock()
	calls = mock.calls.SearchDocumentBlocks
	mock.lockSearchDocumentBlocks.RUnlock()
	return calls
}
