// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package manager

import (
	"context"
	"sync"

	"github.com/rs/xid"
)

// Ensure, that FlusherMock does implement Flusher.
// If this is not the case, regenerate this file with moq.
var _ Flusher = &FlusherMock{}

// FlusherMock is a mock implementation of Flusher.
//
//	func TestSomethingThatUsesFlusher(t *testing.T) {
//
//		// make and configure a mocked Flusher
//		mockedFlusher := &FlusherMock{
//			FlushFunc: func(ctx context.Context, documentID xid.ID, branchID xid.ID) error {
//				panic("mock out the Flush method")
//			},
//		}
//
//		// use mockedFlusher in code that requires Flusher
//		// and then make assertions.
//
//	}
type FlusherMock struct {
	// FlushFunc mocks the Flush method.
	FlushFunc func(ctx context.Context, documentID xid.ID, branchID xid.ID) error

	// calls tracks calls to the methods.
	calls struct {
		// Flush holds details about calls to the Flush method.
		Flush []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// DocumentID is the documentID argument value.
			DocumentID xid.ID
			// BranchID is the branchID argument value.
			BranchID xid.ID
		}
	}
	lockFlush sync.RWMutex
}

// Flush calls FlushFunc.
func (mock *FlusherMock) Flush(ctx context.Context, documentID xid.ID, branchID xid.ID) error {
	callInfo := struct {
		Ctx        context.Context
		DocumentID xid.ID
		BranchID   xid.ID
	}{
		Ctx:        ctx,
		DocumentID: documentID,
		BranchID:   branchID,
	}
	mock.lockFlush.Lock()
	mock.calls.Flush = append(mock.calls.Flush, callInfo)
	mock.lockFlush.Unlock()
	if mock.FlushFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.FlushFunc(ctx, documentID, branchID)
}

// FlushCalls gets all the calls that were made to Flush.
// Check the length with:
//
//	len(mockedFlusher.FlushCalls())
func (mock *FlusherMock) FlushCalls() []struct {
	Ctx        context.Context
	DocumentID xid.ID
	BranchID   xid.ID
} {
	var calls []struct {
		Ctx        context.Context
		DocumentID xid.ID
		BranchID   xid.ID
	}
	mock.lockFlush.RLock()
	calls = mock.calls.Flush
	mock.lockFlush.RUnlock()
	return calls
}
