// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package manager

import (
	"context"
	"sync"

	"github.com/guregu/null/v5"
	"github.com/oxynote/oxynote/server/core/internal/document/hook"
	"github.com/rs/xid"
)

// Ensure, that TxMock does implement Tx.
// If this is not the case, regenerate this file with moq.
var _ Tx = &TxMock{}

// TxMock is a mock implementation of Tx.
//
//	func TestSomethingThatUsesTx(t *testing.T) {
//
//		// make and configure a mocked Tx
//		mockedTx := &TxMock{
//			CommitFunc: func() error {
//				panic("mock out the Commit method")
//			},
//			DeleteDocumentHookFunc: func(ctx context.Context, id xid.ID) error {
//				panic("mock out the DeleteDocumentHook method")
//			},
//			InsertDocumentHookFunc: func(ctx context.Context, hk hook.Hook) error {
//				panic("mock out the InsertDocumentHook method")
//			},
//			RecordDocumentBranchHistoryEntryFunc: func(ctx context.Context, branchID xid.ID, organizationID string, by null.String, boundary bool) (xid.ID, error) {
//				panic("mock out the RecordDocumentBranchHistoryEntry method")
//			},
//			RollbackFunc: func() error {
//				panic("mock out the Rollback method")
//			},
//			UpdateDocumentHookFunc: func(ctx context.Context, hk hook.Hook) error {
//				panic("mock out the UpdateDocumentHook method")
//			},
//		}
//
//		// use mockedTx in code that requires Tx
//		// and then make assertions.
//
//	}
type TxMock struct {
	// CommitFunc mocks the Commit method.
	CommitFunc func() error

	// DeleteDocumentHookFunc mocks the DeleteDocumentHook method.
	DeleteDocumentHookFunc func(ctx context.Context, id xid.ID) error

	// InsertDocumentHookFunc mocks the InsertDocumentHook method.
	InsertDocumentHookFunc func(ctx context.Context, hk hook.Hook) error

	// RecordDocumentBranchHistoryEntryFunc mocks the RecordDocumentBranchHistoryEntry method.
	RecordDocumentBranchHistoryEntryFunc func(ctx context.Context, branchID xid.ID, organizationID string, by null.String, boundary bool) (xid.ID, error)

	// RollbackFunc mocks the Rollback method.
	RollbackFunc func() error

	// UpdateDocumentHookFunc mocks the UpdateDocumentHook method.
	UpdateDocumentHookFunc func(ctx context.Context, hk hook.Hook) error

	// calls tracks calls to the methods.
	calls struct {
		// Commit holds details about calls to the Commit method.
		Commit []struct {
		}
		// DeleteDocumentHook holds details about calls to the DeleteDocumentHook method.
		DeleteDocumentHook []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID xid.ID
		}
		// InsertDocumentHook holds details about calls to the InsertDocumentHook method.
		InsertDocumentHook []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Hk is the hk argument value.
			Hk hook.Hook
		}
		// RecordDocumentBranchHistoryEntry holds details about calls to the RecordDocumentBranchHistoryEntry method.
		RecordDocumentBranchHistoryEntry []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// BranchID is the branchID argument value.
			BranchID xid.ID
			// OrganizationID is the organizationID argument value.
			OrganizationID string
			// By is the by argument value.
			By null.String
			// Boundary is the boundary argument value.
			Boundary bool
		}
		// Rollback holds details about calls to the Rollback method.
		Rollback []struct {
		}
		// UpdateDocumentHook holds details about calls to the UpdateDocumentHook method.
		UpdateDocumentHook []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Hk is the hk argument value.
			Hk hook.Hook
		}
	}
	lockCommit                           sync.RWMutex
	lockDeleteDocumentHook               sync.RWMutex
	lockInsertDocumentHook               sync.RWMutex
	lockRecordDocumentBranchHistoryEntry sync.RWMutex
	lockRollback                         sync.RWMutex
	lockUpdateDocumentHook               sync.RWMutex
}

// Commit calls CommitFunc.
func (mock *TxMock) Commit() error {
	callInfo := struct {
	}{}
	mock.lockCommit.Lock()
	mock.calls.Commit = append(mock.calls.Commit, callInfo)
	mock.lockCommit.Unlock()
	if mock.CommitFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.CommitFunc()
}

// CommitCalls gets all the calls that were made to Commit.
// Check the length with:
//
//	len(mockedTx.CommitCalls())
func (mock *TxMock) CommitCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockCommit.RLock()
	calls = mock.calls.Commit
	mock.lockCommit.RUnlock()
	return calls
}

// DeleteDocumentHook calls DeleteDocumentHookFunc.
func (mock *TxMock) DeleteDocumentHook(ctx context.Context, id xid.ID) error {
	callInfo := struct {
		Ctx context.Context
		ID  xid.ID
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockDeleteDocumentHook.Lock()
	mock.calls.DeleteDocumentHook = append(mock.calls.DeleteDocumentHook, callInfo)
	mock.lockDeleteDocumentHook.Unlock()
	if mock.DeleteDocumentHookFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.DeleteDocumentHookFunc(ctx, id)
}

// DeleteDocumentHookCalls gets all the calls that were made to DeleteDocumentHook.
// Check the length with:
//
//	len(mockedTx.DeleteDocumentHookCalls())
func (mock *TxMock) DeleteDocumentHookCalls() []struct {
	Ctx context.Context
	ID  xid.ID
} {
	var calls []struct {
		Ctx context.Context
		ID  xid.ID
	}
	mock.lockDeleteDocumentHook.RLock()
	calls = mock.calls.DeleteDocumentHook
	mock.lockDeleteDocumentHook.RUnlock()
	return calls
}

// InsertDocumentHook calls InsertDocumentHookFunc.
func (mock *TxMock) InsertDocumentHook(ctx context.Context, hk hook.Hook) error {
	callInfo := struct {
		Ctx context.Context
		Hk  hook.Hook
	}{
		Ctx: ctx,
		Hk:  hk,
	}
	mock.lockInsertDocumentHook.Lock()
	mock.calls.InsertDocumentHook = append(mock.calls.InsertDocumentHook, callInfo)
	mock.lockInsertDocumentHook.Unlock()
	if mock.InsertDocumentHookFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.InsertDocumentHookFunc(ctx, hk)
}

// InsertDocumentHookCalls gets all the calls that were made to InsertDocumentHook.
// Check the length with:
//
//	len(mockedTx.InsertDocumentHookCalls())
func (mock *TxMock) InsertDocumentHookCalls() []struct {
	Ctx context.Context
	Hk  hook.Hook
} {
	var calls []struct {
		Ctx context.Context
		Hk  hook.Hook
	}
	mock.lockInsertDocumentHook.RLock()
	calls = mock.calls.InsertDocumentHook
	mock.lockInsertDocumentHook.RUnlock()
	return calls
}

// RecordDocumentBranchHistoryEntry calls RecordDocumentBranchHistoryEntryFunc.
func (mock *TxMock) RecordDocumentBranchHistoryEntry(ctx context.Context, branchID xid.ID, organizationID string, by null.String, boundary bool) (xid.ID, error) {
	callInfo := struct {
		Ctx            context.Context
		BranchID       xid.ID
		OrganizationID string
		By             null.String
		Boundary       bool
	}{
		Ctx:            ctx,
		BranchID:       branchID,
		OrganizationID: organizationID,
		By:             by,
		Boundary:       boundary,
	}
	mock.lockRecordDocumentBranchHistoryEntry.Lock()
	mock.calls.RecordDocumentBranchHistoryEntry = append(mock.calls.RecordDocumentBranchHistoryEntry, callInfo)
	mock.lockRecordDocumentBranchHistoryEntry.Unlock()
	if mock.RecordDocumentBranchHistoryEntryFunc == nil {
		var (
			iDOut  xid.ID
			errOut error
		)
		return iDOut, errOut
	}
	return mock.RecordDocumentBranchHistoryEntryFunc(ctx, branchID, organizationID, by, boundary)
}

// RecordDocumentBranchHistoryEntryCalls gets all the calls that were made to RecordDocumentBranchHistoryEntry.
// Check the length with:
//
//	len(mockedTx.RecordDocumentBranchHistoryEntryCalls())
func (mock *TxMock) RecordDocumentBranchHistoryEntryCalls() []struct {
	Ctx            context.Context
	BranchID       xid.ID
	OrganizationID string
	By             null.String
	Boundary       bool
} {
	var calls []struct {
		Ctx            context.Context
		BranchID       xid.ID
		OrganizationID string
		By             null.String
		Boundary       bool
	}
	mock.lockRecordDocumentBranchHistoryEntry.RLock()
	calls = mock.calls.RecordDocumentBranchHistoryEntry
	mock.lockRecordDocumentBranchHistoryEntry.RUnlock()
	return calls
}

// Rollback calls RollbackFunc.
func (mock *TxMock) Rollback() error {
	callInfo := struct {
	}{}
	mock.lockRollback.Lock()
	mock.calls.Rollback = append(mock.calls.Rollback, callInfo)
	mock.lockRollback.Unlock()
	if mock.RollbackFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.RollbackFunc()
}

// RollbackCalls gets all the calls that were made to Rollback.
// Check the length with:
//
//	len(mockedTx.RollbackCalls())
func (mock *TxMock) RollbackCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockRollback.RLock()
	calls = mock.calls.Rollback
	mock.lockRollback.RUnlock()
	return calls
}

// UpdateDocumentHook calls UpdateDocumentHookFunc.
func (mock *TxMock) UpdateDocumentHook(ctx context.Context, hk hook.Hook) error {
	callInfo := struct {
		Ctx context.Context
		Hk  hook.Hook
	}{
		Ctx: ctx,
		Hk:  hk,
	}
	mock.lockUpdateDocumentHook.Lock()
	mock.calls.UpdateDocumentHook = append(mock.calls.UpdateDocumentHook, callInfo)
	mock.lockUpdateDocumentHook.Unlock()
	if mock.UpdateDocumentHookFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.UpdateDocumentHookFunc(ctx, hk)
}

// UpdateDocumentHookCalls gets all the calls that were made to UpdateDocumentHook.
// Check the length with:
//
//	len(mockedTx.UpdateDocumentHookCalls())
func (mock *TxMock) UpdateDocumentHookCalls() []struct {
	Ctx context.Context
	Hk  hook.Hook
} {
	var calls []struct {
		Ctx context.Context
		Hk  hook.Hook
	}
	mock.lockUpdateDocumentHook.RLock()
	calls = mock.calls.UpdateDocumentHook
	mock.lockUpdateDocumentHook.RUnlock()
	return calls
}
