// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package manager

import (
	"context"
	"sync"

	"github.com/oxynote/oxynote/server/core/internal/document/hook"
	"github.com/rs/xid"
)

// Ensure, that CopyTxMock does implement CopyTx.
// If this is not the case, regenerate this file with moq.
var _ CopyTx = &CopyTxMock{}

// CopyTxMock is a mock implementation of CopyTx.
//
//	func TestSomethingThatUsesCopyTx(t *testing.T) {
//
//		// make and configure a mocked CopyTx
//		mockedCopyTx := &CopyTxMock{
//			FetchDocumentHooksByBranchIDFunc: func(ctx context.Context, branchID xid.ID, organizationID string) ([]hook.Hook, error) {
//				panic("mock out the FetchDocumentHooksByBranchID method")
//			},
//			InsertDocumentHookFunc: func(ctx context.Context, hk hook.Hook) error {
//				panic("mock out the InsertDocumentHook method")
//			},
//		}
//
//		// use mockedCopyTx in code that requires CopyTx
//		// and then make assertions.
//
//	}
type CopyTxMock struct {
	// FetchDocumentHooksByBranchIDFunc mocks the FetchDocumentHooksByBranchID method.
	FetchDocumentHooksByBranchIDFunc func(ctx context.Context, branchID xid.ID, organizationID string) ([]hook.Hook, error)

	// InsertDocumentHookFunc mocks the InsertDocumentHook method.
	InsertDocumentHookFunc func(ctx context.Context, hk hook.Hook) error

	// calls tracks calls to the methods.
	calls struct {
		// FetchDocumentHooksByBranchID holds details about calls to the FetchDocumentHooksByBranchID method.
		FetchDocumentHooksByBranchID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// BranchID is the branchID argument value.
			BranchID xid.ID
			// OrganizationID is the organizationID argument value.
			OrganizationID string
		}
		// InsertDocumentHook holds details about calls to the InsertDocumentHook method.
		InsertDocumentHook []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Hk is the hk argument value.
			Hk hook.Hook
		}
	}
	lockFetchDocumentHooksByBranchID sync.RWMutex
	lockInsertDocumentHook           sync.RWMutex
}

// FetchDocumentHooksByBranchID calls FetchDocumentHooksByBranchIDFunc.
func (mock *CopyTxMock) FetchDocumentHooksByBranchID(ctx context.Context, branchID xid.ID, organizationID string) ([]hook.Hook, error) {
	callInfo := struct {
		Ctx            context.Context
		BranchID       xid.ID
		OrganizationID string
	}{
		Ctx:            ctx,
		BranchID:       branchID,
		OrganizationID: organizationID,
	}
	mock.lockFetchDocumentHooksByBranchID.Lock()
	mock.calls.FetchDocumentHooksByBranchID = append(mock.calls.FetchDocumentHooksByBranchID, callInfo)
	mock.lockFetchDocumentHooksByBranchID.Unlock()
	if mock.FetchDocumentHooksByBranchIDFunc == nil {
		var (
			hooksOut []hook.Hook
			errOut   error
		)
		return hooksOut, errOut
	}
	return mock.FetchDocumentHooksByBranchIDFunc(ctx, branchID, organizationID)
}

// FetchDocumentHooksByBranchIDCalls gets all the calls that were made to FetchDocumentHooksByBranchID.
// Check the length with:
//
//	len(mockedCopyTx.FetchDocumentHooksByBranchIDCalls())
func (mock *CopyTxMock) FetchDocumentHooksByBranchIDCalls() []struct {
	Ctx            context.Context
	BranchID       xid.ID
	OrganizationID string
} {
	var calls []struct {
		Ctx            context.Context
		BranchID       xid.ID
		OrganizationID string
	}
	mock.lockFetchDocumentHooksByBranchID.RLock()
	calls = mock.calls.FetchDocumentHooksByBranchID
	mock.lockFetchDocumentHooksByBranchID.RUnlock()
	return calls
}

// InsertDocumentHook calls InsertDocumentHookFunc.
func (mock *CopyTxMock) InsertDocumentHook(ctx context.Context, hk hook.Hook) error {
	callInfo := struct {
		Ctx context.Context
		Hk  hook.Hook
	}{
		Ctx: ctx,
		Hk:  hk,
	}
	mock.lockInsertDocumentHook.Lock()
	mock.calls.InsertDocumentHook = append(mock.calls.InsertDocumentHook, callInfo)
	mock.lockInsertDocumentHook.Unlock()
	if mock.InsertDocumentHookFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.InsertDocumentHookFunc(ctx, hk)
}

// InsertDocumentHookCalls gets all the calls that were made to InsertDocumentHook.
// Check the length with:
//
//	len(mockedCopyTx.InsertDocumentHookCalls())
func (mock *CopyTxMock) InsertDocumentHookCalls() []struct {
	Ctx context.Context
	Hk  hook.Hook
} {
	var calls []struct {
		Ctx context.Context
		Hk  hook.Hook
	}
	mock.lockInsertDocumentHook.RLock()
	calls = mock.calls.InsertDocumentHook
	mock.lockInsertDocumentHook.RUnlock()
	return calls
}
