global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'heimdall-gate'
    metrics_path: api/x/metrics
    static_configs:
      - targets: ['heimdall-gate:8080']
        labels:
          service: 'gate'
  - job_name: 'telegraf'
    static_configs:
      - targets: ['telegraf:9273']
        labels:
          service: 'telegraf'
