global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'core'
    metrics_path: api/x/metrics
    static_configs:
      - targets: ['core:8080']
        labels:
          service: 'core'
  - job_name: 'telegraf'
    static_configs:
      - targets: ['telegraf:9273']
        labels:
          service: 'telegraf'
