// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package org

import (
	"context"
	"sync"

	"github.com/oxynote/oxynote/server/core/internal/datasource"
	"github.com/oxynote/oxynote/server/core/internal/document"
	"github.com/oxynote/oxynote/server/core/internal/document/searchgw"
	"github.com/rs/xid"
)

// Ensure, that TxMock does implement Tx.
// If this is not the case, regenerate this file with moq.
var _ Tx = &TxMock{}

// TxMock is a mock implementation of Tx.
//
//	func TestSomethingThatUsesTx(t *testing.T) {
//
//		// make and configure a mocked Tx
//		mockedTx := &TxMock{
//			CommitFunc: func() error {
//				panic("mock out the Commit method")
//			},
//			FetchOrganizationMembersFunc: func(ctx context.Context, organizationID string) ([]string, error) {
//				panic("mock out the FetchOrganizationMembers method")
//			},
//			InsertDataSourceFunc: func(ctx context.Context, ds *datasource.DataSource) error {
//				panic("mock out the InsertDataSource method")
//			},
//			InsertDocumentFunc: func(ctx context.Context, doc document.Document) error {
//				panic("mock out the InsertDocument method")
//			},
//			InsertDocumentSearchJobFunc: func(ctx context.Context, diff searchgw.BlocksDifference) error {
//				panic("mock out the InsertDocumentSearchJob method")
//			},
//			RollbackFunc: func() error {
//				panic("mock out the Rollback method")
//			},
//			UpdateOrganizationLogoFunc: func(ctx context.Context, organizationID string, logo string) error {
//				panic("mock out the UpdateOrganizationLogo method")
//			},
//			UpsertDocumentMaintainersFunc: func(ctx context.Context, documentID xid.ID, organizationID string, maintainerIDs []string) error {
//				panic("mock out the UpsertDocumentMaintainers method")
//			},
//		}
//
//		// use mockedTx in code that requires Tx
//		// and then make assertions.
//
//	}
type TxMock struct {
	// CommitFunc mocks the Commit method.
	CommitFunc func() error

	// FetchOrganizationMembersFunc mocks the FetchOrganizationMembers method.
	FetchOrganizationMembersFunc func(ctx context.Context, organizationID string) ([]string, error)

	// InsertDataSourceFunc mocks the InsertDataSource method.
	InsertDataSourceFunc func(ctx context.Context, ds *datasource.DataSource) error

	// InsertDocumentFunc mocks the InsertDocument method.
	InsertDocumentFunc func(ctx context.Context, doc document.Document) error

	// InsertDocumentSearchJobFunc mocks the InsertDocumentSearchJob method.
	InsertDocumentSearchJobFunc func(ctx context.Context, diff searchgw.BlocksDifference) error

	// RollbackFunc mocks the Rollback method.
	RollbackFunc func() error

	// UpdateOrganizationLogoFunc mocks the UpdateOrganizationLogo method.
	UpdateOrganizationLogoFunc func(ctx context.Context, organizationID string, logo string) error

	// UpsertDocumentMaintainersFunc mocks the UpsertDocumentMaintainers method.
	UpsertDocumentMaintainersFunc func(ctx context.Context, documentID xid.ID, organizationID string, maintainerIDs []string) error

	// calls tracks calls to the methods.
	calls struct {
		// Commit holds details about calls to the Commit method.
		Commit []struct {
		}
		// FetchOrganizationMembers holds details about calls to the FetchOrganizationMembers method.
		FetchOrganizationMembers []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrganizationID is the organizationID argument value.
			OrganizationID string
		}
		// InsertDataSource holds details about calls to the InsertDataSource method.
		InsertDataSource []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Ds is the ds argument value.
			Ds *datasource.DataSource
		}
		// InsertDocument holds details about calls to the InsertDocument method.
		InsertDocument []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Doc is the doc argument value.
			Doc document.Document
		}
		// InsertDocumentSearchJob holds details about calls to the InsertDocumentSearchJob method.
		InsertDocumentSearchJob []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Diff is the diff argument value.
			Diff searchgw.BlocksDifference
		}
		// Rollback holds details about calls to the Rollback method.
		Rollback []struct {
		}
		// UpdateOrganizationLogo holds details about calls to the UpdateOrganizationLogo method.
		UpdateOrganizationLogo []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrganizationID is the organizationID argument value.
			OrganizationID string
			// Logo is the logo argument value.
			Logo string
		}
		// UpsertDocumentMaintainers holds details about calls to the UpsertDocumentMaintainers method.
		UpsertDocumentMaintainers []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// DocumentID is the documentID argument value.
			DocumentID xid.ID
			// OrganizationID is the organizationID argument value.
			OrganizationID string
			// MaintainerIDs is the maintainerIDs argument value.
			MaintainerIDs []string
		}
	}
	lockCommit                    sync.RWMutex
	lockFetchOrganizationMembers  sync.RWMutex
	lockInsertDataSource          sync.RWMutex
	lockInsertDocument            sync.RWMutex
	lockInsertDocumentSearchJob   sync.RWMutex
	lockRollback                  sync.RWMutex
	lockUpdateOrganizationLogo    sync.RWMutex
	lockUpsertDocumentMaintainers sync.RWMutex
}

// Commit calls CommitFunc.
func (mock *TxMock) Commit() error {
	callInfo := struct {
	}{}
	mock.lockCommit.Lock()
	mock.calls.Commit = append(mock.calls.Commit, callInfo)
	mock.lockCommit.Unlock()
	if mock.CommitFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.CommitFunc()
}

// CommitCalls gets all the calls that were made to Commit.
// Check the length with:
//
//	len(mockedTx.CommitCalls())
func (mock *TxMock) CommitCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockCommit.RLock()
	calls = mock.calls.Commit
	mock.lockCommit.RUnlock()
	return calls
}

// FetchOrganizationMembers calls FetchOrganizationMembersFunc.
func (mock *TxMock) FetchOrganizationMembers(ctx context.Context, organizationID string) ([]string, error) {
	callInfo := struct {
		Ctx            context.Context
		OrganizationID string
	}{
		Ctx:            ctx,
		OrganizationID: organizationID,
	}
	mock.lockFetchOrganizationMembers.Lock()
	mock.calls.FetchOrganizationMembers = append(mock.calls.FetchOrganizationMembers, callInfo)
	mock.lockFetchOrganizationMembers.Unlock()
	if mock.FetchOrganizationMembersFunc == nil {
		var (
			stringsOut []string
			errOut     error
		)
		return stringsOut, errOut
	}
	return mock.FetchOrganizationMembersFunc(ctx, organizationID)
}

// FetchOrganizationMembersCalls gets all the calls that were made to FetchOrganizationMembers.
// Check the length with:
//
//	len(mockedTx.FetchOrganizationMembersCalls())
func (mock *TxMock) FetchOrganizationMembersCalls() []struct {
	Ctx            context.Context
	OrganizationID string
} {
	var calls []struct {
		Ctx            context.Context
		OrganizationID string
	}
	mock.lockFetchOrganizationMembers.RLock()
	calls = mock.calls.FetchOrganizationMembers
	mock.lockFetchOrganizationMembers.RUnlock()
	return calls
}

// InsertDataSource calls InsertDataSourceFunc.
func (mock *TxMock) InsertDataSource(ctx context.Context, ds *datasource.DataSource) error {
	callInfo := struct {
		Ctx context.Context
		Ds  *datasource.DataSource
	}{
		Ctx: ctx,
		Ds:  ds,
	}
	mock.lockInsertDataSource.Lock()
	mock.calls.InsertDataSource = append(mock.calls.InsertDataSource, callInfo)
	mock.lockInsertDataSource.Unlock()
	if mock.InsertDataSourceFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.InsertDataSourceFunc(ctx, ds)
}

// InsertDataSourceCalls gets all the calls that were made to InsertDataSource.
// Check the length with:
//
//	len(mockedTx.InsertDataSourceCalls())
func (mock *TxMock) InsertDataSourceCalls() []struct {
	Ctx context.Context
	Ds  *datasource.DataSource
} {
	var calls []struct {
		Ctx context.Context
		Ds  *datasource.DataSource
	}
	mock.lockInsertDataSource.RLock()
	calls = mock.calls.InsertDataSource
	mock.lockInsertDataSource.RUnlock()
	return calls
}

// InsertDocument calls InsertDocumentFunc.
func (mock *TxMock) InsertDocument(ctx context.Context, doc document.Document) error {
	callInfo := struct {
		Ctx context.Context
		Doc document.Document
	}{
		Ctx: ctx,
		Doc: doc,
	}
	mock.lockInsertDocument.Lock()
	mock.calls.InsertDocument = append(mock.calls.InsertDocument, callInfo)
	mock.lockInsertDocument.Unlock()
	if mock.InsertDocumentFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.InsertDocumentFunc(ctx, doc)
}

// InsertDocumentCalls gets all the calls that were made to InsertDocument.
// Check the length with:
//
//	len(mockedTx.InsertDocumentCalls())
func (mock *TxMock) InsertDocumentCalls() []struct {
	Ctx context.Context
	Doc document.Document
} {
	var calls []struct {
		Ctx context.Context
		Doc document.Document
	}
	mock.lockInsertDocument.RLock()
	calls = mock.calls.InsertDocument
	mock.lockInsertDocument.RUnlock()
	return calls
}

// InsertDocumentSearchJob calls InsertDocumentSearchJobFunc.
func (mock *TxMock) InsertDocumentSearchJob(ctx context.Context, diff searchgw.BlocksDifference) error {
	callInfo := struct {
		Ctx  context.Context
		Diff searchgw.BlocksDifference
	}{
		Ctx:  ctx,
		Diff: diff,
	}
	mock.lockInsertDocumentSearchJob.Lock()
	mock.calls.InsertDocumentSearchJob = append(mock.calls.InsertDocumentSearchJob, callInfo)
	mock.lockInsertDocumentSearchJob.Unlock()
	if mock.InsertDocumentSearchJobFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.InsertDocumentSearchJobFunc(ctx, diff)
}

// InsertDocumentSearchJobCalls gets all the calls that were made to InsertDocumentSearchJob.
// Check the length with:
//
//	len(mockedTx.InsertDocumentSearchJobCalls())
func (mock *TxMock) InsertDocumentSearchJobCalls() []struct {
	Ctx  context.Context
	Diff searchgw.BlocksDifference
} {
	var calls []struct {
		Ctx  context.Context
		Diff searchgw.BlocksDifference
	}
	mock.lockInsertDocumentSearchJob.RLock()
	calls = mock.calls.InsertDocumentSearchJob
	mock.lockInsertDocumentSearchJob.RUnlock()
	return calls
}

// Rollback calls RollbackFunc.
func (mock *TxMock) Rollback() error {
	callInfo := struct {
	}{}
	mock.lockRollback.Lock()
	mock.calls.Rollback = append(mock.calls.Rollback, callInfo)
	mock.lockRollback.Unlock()
	if mock.RollbackFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.RollbackFunc()
}

// RollbackCalls gets all the calls that were made to Rollback.
// Check the length with:
//
//	len(mockedTx.RollbackCalls())
func (mock *TxMock) RollbackCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockRollback.RLock()
	calls = mock.calls.Rollback
	mock.lockRollback.RUnlock()
	return calls
}

// UpdateOrganizationLogo calls UpdateOrganizationLogoFunc.
func (mock *TxMock) UpdateOrganizationLogo(ctx context.Context, organizationID string, logo string) error {
	callInfo := struct {
		Ctx            context.Context
		OrganizationID string
		Logo           string
	}{
		Ctx:            ctx,
		OrganizationID: organizationID,
		Logo:           logo,
	}
	mock.lockUpdateOrganizationLogo.Lock()
	mock.calls.UpdateOrganizationLogo = append(mock.calls.UpdateOrganizationLogo, callInfo)
	mock.lockUpdateOrganizationLogo.Unlock()
	if mock.UpdateOrganizationLogoFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.UpdateOrganizationLogoFunc(ctx, organizationID, logo)
}

// UpdateOrganizationLogoCalls gets all the calls that were made to UpdateOrganizationLogo.
// Check the length with:
//
//	len(mockedTx.UpdateOrganizationLogoCalls())
func (mock *TxMock) UpdateOrganizationLogoCalls() []struct {
	Ctx            context.Context
	OrganizationID string
	Logo           string
} {
	var calls []struct {
		Ctx            context.Context
		OrganizationID string
		Logo           string
	}
	mock.lockUpdateOrganizationLogo.RLock()
	calls = mock.calls.UpdateOrganizationLogo
	mock.lockUpdateOrganizationLogo.RUnlock()
	return calls
}

// UpsertDocumentMaintainers calls UpsertDocumentMaintainersFunc.
func (mock *TxMock) UpsertDocumentMaintainers(ctx context.Context, documentID xid.ID, organizationID string, maintainerIDs []string) error {
	callInfo := struct {
		Ctx            context.Context
		DocumentID     xid.ID
		OrganizationID string
		MaintainerIDs  []string
	}{
		Ctx:            ctx,
		DocumentID:     documentID,
		OrganizationID: organizationID,
		MaintainerIDs:  maintainerIDs,
	}
	mock.lockUpsertDocumentMaintainers.Lock()
	mock.calls.UpsertDocumentMaintainers = append(mock.calls.UpsertDocumentMaintainers, callInfo)
	mock.lockUpsertDocumentMaintainers.Unlock()
	if mock.UpsertDocumentMaintainersFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.UpsertDocumentMaintainersFunc(ctx, documentID, organizationID, maintainerIDs)
}

// UpsertDocumentMaintainersCalls gets all the calls that were made to UpsertDocumentMaintainers.
// Check the length with:
//
//	len(mockedTx.UpsertDocumentMaintainersCalls())
func (mock *TxMock) UpsertDocumentMaintainersCalls() []struct {
	Ctx            context.Context
	DocumentID     xid.ID
	OrganizationID string
	MaintainerIDs  []string
} {
	var calls []struct {
		Ctx            context.Context
		DocumentID     xid.ID
		OrganizationID string
		MaintainerIDs  []string
	}
	mock.lockUpsertDocumentMaintainers.RLock()
	calls = mock.calls.UpsertDocumentMaintainers
	mock.lockUpsertDocumentMaintainers.RUnlock()
	return calls
}
