// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package org

import (
	"context"
	"sync"

	"github.com/oxynote/oxynote/server/core/internal/datasource"
	"github.com/oxynote/oxynote/server/core/internal/document"
	"github.com/oxynote/oxynote/server/core/internal/search"
	"github.com/rs/xid"
)

// Ensure, that DBMock does implement DB.
// If this is not the case, regenerate this file with moq.
var _ DB = &DBMock{}

// DBMock is a mock implementation of DB.
//
//	func TestSomethingThatUsesDB(t *testing.T) {
//
//		// make and configure a mocked DB
//		mockedDB := &DBMock{
//			BeginTxFunc: func(ctx context.Context, dest any) error {
//				panic("mock out the BeginTx method")
//			},
//			FetchOrganizationMembersFunc: func(ctx context.Context, organizationID string) ([]string, error) {
//				panic("mock out the FetchOrganizationMembers method")
//			},
//			InsertDataSourceFunc: func(ctx context.Context, ds *datasource.DataSource) error {
//				panic("mock out the InsertDataSource method")
//			},
//			InsertDocumentFunc: func(ctx context.Context, doc document.Document) error {
//				panic("mock out the InsertDocument method")
//			},
//			InsertDocumentSearchJobFunc: func(ctx context.Context, diff search.BlocksDifference) error {
//				panic("mock out the InsertDocumentSearchJob method")
//			},
//			UpdateOrganizationLogoFunc: func(ctx context.Context, organizationID string, logo string) error {
//				panic("mock out the UpdateOrganizationLogo method")
//			},
//			UpsertDocumentMaintainersFunc: func(ctx context.Context, documentID xid.ID, organizationID string, maintainerIDs []string) error {
//				panic("mock out the UpsertDocumentMaintainers method")
//			},
//		}
//
//		// use mockedDB in code that requires DB
//		// and then make assertions.
//
//	}
type DBMock struct {
	// BeginTxFunc mocks the BeginTx method.
	BeginTxFunc func(ctx context.Context, dest any) error

	// FetchOrganizationMembersFunc mocks the FetchOrganizationMembers method.
	FetchOrganizationMembersFunc func(ctx context.Context, organizationID string) ([]string, error)

	// InsertDataSourceFunc mocks the InsertDataSource method.
	InsertDataSourceFunc func(ctx context.Context, ds *datasource.DataSource) error

	// InsertDocumentFunc mocks the InsertDocument method.
	InsertDocumentFunc func(ctx context.Context, doc document.Document) error

	// InsertDocumentSearchJobFunc mocks the InsertDocumentSearchJob method.
	InsertDocumentSearchJobFunc func(ctx context.Context, diff search.BlocksDifference) error

	// UpdateOrganizationLogoFunc mocks the UpdateOrganizationLogo method.
	UpdateOrganizationLogoFunc func(ctx context.Context, organizationID string, logo string) error

	// UpsertDocumentMaintainersFunc mocks the UpsertDocumentMaintainers method.
	UpsertDocumentMaintainersFunc func(ctx context.Context, documentID xid.ID, organizationID string, maintainerIDs []string) error

	// calls tracks calls to the methods.
	calls struct {
		// BeginTx holds details about calls to the BeginTx method.
		BeginTx []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Dest is the dest argument value.
			Dest any
		}
		// FetchOrganizationMembers holds details about calls to the FetchOrganizationMembers method.
		FetchOrganizationMembers []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrganizationID is the organizationID argument value.
			OrganizationID string
		}
		// InsertDataSource holds details about calls to the InsertDataSource method.
		InsertDataSource []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Ds is the ds argument value.
			Ds *datasource.DataSource
		}
		// InsertDocument holds details about calls to the InsertDocument method.
		InsertDocument []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Doc is the doc argument value.
			Doc document.Document
		}
		// InsertDocumentSearchJob holds details about calls to the InsertDocumentSearchJob method.
		InsertDocumentSearchJob []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Diff is the diff argument value.
			Diff search.BlocksDifference
		}
		// UpdateOrganizationLogo holds details about calls to the UpdateOrganizationLogo method.
		UpdateOrganizationLogo []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrganizationID is the organizationID argument value.
			OrganizationID string
			// Logo is the logo argument value.
			Logo string
		}
		// UpsertDocumentMaintainers holds details about calls to the UpsertDocumentMaintainers method.
		UpsertDocumentMaintainers []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// DocumentID is the documentID argument value.
			DocumentID xid.ID
			// OrganizationID is the organizationID argument value.
			OrganizationID string
			// MaintainerIDs is the maintainerIDs argument value.
			MaintainerIDs []string
		}
	}
	lockBeginTx                   sync.RWMutex
	lockFetchOrganizationMembers  sync.RWMutex
	lockInsertDataSource          sync.RWMutex
	lockInsertDocument            sync.RWMutex
	lockInsertDocumentSearchJob   sync.RWMutex
	lockUpdateOrganizationLogo    sync.RWMutex
	lockUpsertDocumentMaintainers sync.RWMutex
}

// BeginTx calls BeginTxFunc.
func (mock *DBMock) BeginTx(ctx context.Context, dest any) error {
	callInfo := struct {
		Ctx  context.Context
		Dest any
	}{
		Ctx:  ctx,
		Dest: dest,
	}
	mock.lockBeginTx.Lock()
	mock.calls.BeginTx = append(mock.calls.BeginTx, callInfo)
	mock.lockBeginTx.Unlock()
	if mock.BeginTxFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.BeginTxFunc(ctx, dest)
}

// BeginTxCalls gets all the calls that were made to BeginTx.
// Check the length with:
//
//	len(mockedDB.BeginTxCalls())
func (mock *DBMock) BeginTxCalls() []struct {
	Ctx  context.Context
	Dest any
} {
	var calls []struct {
		Ctx  context.Context
		Dest any
	}
	mock.lockBeginTx.RLock()
	calls = mock.calls.BeginTx
	mock.lockBeginTx.RUnlock()
	return calls
}

// FetchOrganizationMembers calls FetchOrganizationMembersFunc.
func (mock *DBMock) FetchOrganizationMembers(ctx context.Context, organizationID string) ([]string, error) {
	callInfo := struct {
		Ctx            context.Context
		OrganizationID string
	}{
		Ctx:            ctx,
		OrganizationID: organizationID,
	}
	mock.lockFetchOrganizationMembers.Lock()
	mock.calls.FetchOrganizationMembers = append(mock.calls.FetchOrganizationMembers, callInfo)
	mock.lockFetchOrganizationMembers.Unlock()
	if mock.FetchOrganizationMembersFunc == nil {
		var (
			stringsOut []string
			errOut     error
		)
		return stringsOut, errOut
	}
	return mock.FetchOrganizationMembersFunc(ctx, organizationID)
}

// FetchOrganizationMembersCalls gets all the calls that were made to FetchOrganizationMembers.
// Check the length with:
//
//	len(mockedDB.FetchOrganizationMembersCalls())
func (mock *DBMock) FetchOrganizationMembersCalls() []struct {
	Ctx            context.Context
	OrganizationID string
} {
	var calls []struct {
		Ctx            context.Context
		OrganizationID string
	}
	mock.lockFetchOrganizationMembers.RLock()
	calls = mock.calls.FetchOrganizationMembers
	mock.lockFetchOrganizationMembers.RUnlock()
	return calls
}

// InsertDataSource calls InsertDataSourceFunc.
func (mock *DBMock) InsertDataSource(ctx context.Context, ds *datasource.DataSource) error {
	callInfo := struct {
		Ctx context.Context
		Ds  *datasource.DataSource
	}{
		Ctx: ctx,
		Ds:  ds,
	}
	mock.lockInsertDataSource.Lock()
	mock.calls.InsertDataSource = append(mock.calls.InsertDataSource, callInfo)
	mock.lockInsertDataSource.Unlock()
	if mock.InsertDataSourceFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.InsertDataSourceFunc(ctx, ds)
}

// InsertDataSourceCalls gets all the calls that were made to InsertDataSource.
// Check the length with:
//
//	len(mockedDB.InsertDataSourceCalls())
func (mock *DBMock) InsertDataSourceCalls() []struct {
	Ctx context.Context
	Ds  *datasource.DataSource
} {
	var calls []struct {
		Ctx context.Context
		Ds  *datasource.DataSource
	}
	mock.lockInsertDataSource.RLock()
	calls = mock.calls.InsertDataSource
	mock.lockInsertDataSource.RUnlock()
	return calls
}

// InsertDocument calls InsertDocumentFunc.
func (mock *DBMock) InsertDocument(ctx context.Context, doc document.Document) error {
	callInfo := struct {
		Ctx context.Context
		Doc document.Document
	}{
		Ctx: ctx,
		Doc: doc,
	}
	mock.lockInsertDocument.Lock()
	mock.calls.InsertDocument = append(mock.calls.InsertDocument, callInfo)
	mock.lockInsertDocument.Unlock()
	if mock.InsertDocumentFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.InsertDocumentFunc(ctx, doc)
}

// InsertDocumentCalls gets all the calls that were made to InsertDocument.
// Check the length with:
//
//	len(mockedDB.InsertDocumentCalls())
func (mock *DBMock) InsertDocumentCalls() []struct {
	Ctx context.Context
	Doc document.Document
} {
	var calls []struct {
		Ctx context.Context
		Doc document.Document
	}
	mock.lockInsertDocument.RLock()
	calls = mock.calls.InsertDocument
	mock.lockInsertDocument.RUnlock()
	return calls
}

// InsertDocumentSearchJob calls InsertDocumentSearchJobFunc.
func (mock *DBMock) InsertDocumentSearchJob(ctx context.Context, diff search.BlocksDifference) error {
	callInfo := struct {
		Ctx  context.Context
		Diff search.BlocksDifference
	}{
		Ctx:  ctx,
		Diff: diff,
	}
	mock.lockInsertDocumentSearchJob.Lock()
	mock.calls.InsertDocumentSearchJob = append(mock.calls.InsertDocumentSearchJob, callInfo)
	mock.lockInsertDocumentSearchJob.Unlock()
	if mock.InsertDocumentSearchJobFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.InsertDocumentSearchJobFunc(ctx, diff)
}

// InsertDocumentSearchJobCalls gets all the calls that were made to InsertDocumentSearchJob.
// Check the length with:
//
//	len(mockedDB.InsertDocumentSearchJobCalls())
func (mock *DBMock) InsertDocumentSearchJobCalls() []struct {
	Ctx  context.Context
	Diff search.BlocksDifference
} {
	var calls []struct {
		Ctx  context.Context
		Diff search.BlocksDifference
	}
	mock.lockInsertDocumentSearchJob.RLock()
	calls = mock.calls.InsertDocumentSearchJob
	mock.lockInsertDocumentSearchJob.RUnlock()
	return calls
}

// UpdateOrganizationLogo calls UpdateOrganizationLogoFunc.
func (mock *DBMock) UpdateOrganizationLogo(ctx context.Context, organizationID string, logo string) error {
	callInfo := struct {
		Ctx            context.Context
		OrganizationID string
		Logo           string
	}{
		Ctx:            ctx,
		OrganizationID: organizationID,
		Logo:           logo,
	}
	mock.lockUpdateOrganizationLogo.Lock()
	mock.calls.UpdateOrganizationLogo = append(mock.calls.UpdateOrganizationLogo, callInfo)
	mock.lockUpdateOrganizationLogo.Unlock()
	if mock.UpdateOrganizationLogoFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.UpdateOrganizationLogoFunc(ctx, organizationID, logo)
}

// UpdateOrganizationLogoCalls gets all the calls that were made to UpdateOrganizationLogo.
// Check the length with:
//
//	len(mockedDB.UpdateOrganizationLogoCalls())
func (mock *DBMock) UpdateOrganizationLogoCalls() []struct {
	Ctx            context.Context
	OrganizationID string
	Logo           string
} {
	var calls []struct {
		Ctx            context.Context
		OrganizationID string
		Logo           string
	}
	mock.lockUpdateOrganizationLogo.RLock()
	calls = mock.calls.UpdateOrganizationLogo
	mock.lockUpdateOrganizationLogo.RUnlock()
	return calls
}

// UpsertDocumentMaintainers calls UpsertDocumentMaintainersFunc.
func (mock *DBMock) UpsertDocumentMaintainers(ctx context.Context, documentID xid.ID, organizationID string, maintainerIDs []string) error {
	callInfo := struct {
		Ctx            context.Context
		DocumentID     xid.ID
		OrganizationID string
		MaintainerIDs  []string
	}{
		Ctx:            ctx,
		DocumentID:     documentID,
		OrganizationID: organizationID,
		MaintainerIDs:  maintainerIDs,
	}
	mock.lockUpsertDocumentMaintainers.Lock()
	mock.calls.UpsertDocumentMaintainers = append(mock.calls.UpsertDocumentMaintainers, callInfo)
	mock.lockUpsertDocumentMaintainers.Unlock()
	if mock.UpsertDocumentMaintainersFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.UpsertDocumentMaintainersFunc(ctx, documentID, organizationID, maintainerIDs)
}

// UpsertDocumentMaintainersCalls gets all the calls that were made to UpsertDocumentMaintainers.
// Check the length with:
//
//	len(mockedDB.UpsertDocumentMaintainersCalls())
func (mock *DBMock) UpsertDocumentMaintainersCalls() []struct {
	Ctx            context.Context
	DocumentID     xid.ID
	OrganizationID string
	MaintainerIDs  []string
} {
	var calls []struct {
		Ctx            context.Context
		DocumentID     xid.ID
		OrganizationID string
		MaintainerIDs  []string
	}
	mock.lockUpsertDocumentMaintainers.RLock()
	calls = mock.calls.UpsertDocumentMaintainers
	mock.lockUpsertDocumentMaintainers.RUnlock()
	return calls
}
