// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package comment

import (
	"context"
	"sync"

	"github.com/oxynote/oxynote/server/core/internal/document"
	commentCore "github.com/oxynote/oxynote/server/core/internal/document/comment"
	"github.com/rs/xid"
)

// Ensure, that TxMock does implement Tx.
// If this is not the case, regenerate this file with moq.
var _ Tx = &TxMock{}

// TxMock is a mock implementation of Tx.
//
//	func TestSomethingThatUsesTx(t *testing.T) {
//
//		// make and configure a mocked Tx
//		mockedTx := &TxMock{
//			CommitFunc: func() error {
//				panic("mock out the Commit method")
//			},
//			DeleteDocumentCommentFunc: func(ctx context.Context, id xid.ID, documentID xid.ID, organizationID string) error {
//				panic("mock out the DeleteDocumentComment method")
//			},
//			DeleteDocumentCommentReplyFunc: func(ctx context.Context, id xid.ID, commentID xid.ID, organizationID string) error {
//				panic("mock out the DeleteDocumentCommentReply method")
//			},
//			DeleteDocumentCommentsByBranchIDFunc: func(ctx context.Context, branchID xid.ID, organizationID string) error {
//				panic("mock out the DeleteDocumentCommentsByBranchID method")
//			},
//			FetchDocumentByBranchIDFunc: func(ctx context.Context, branchID xid.ID, organizationID string) (*document.Document, error) {
//				panic("mock out the FetchDocumentByBranchID method")
//			},
//			FetchDocumentCommentFunc: func(ctx context.Context, id xid.ID, documentID xid.ID, organizationID string) (*commentCore.Comment, error) {
//				panic("mock out the FetchDocumentComment method")
//			},
//			FetchDocumentCommentReplyFunc: func(ctx context.Context, id xid.ID, commentID xid.ID, organizationID string) (*commentCore.Reply, error) {
//				panic("mock out the FetchDocumentCommentReply method")
//			},
//			FetchDocumentCommentsByBranchIDFunc: func(ctx context.Context, branchID xid.ID, organizationID string) ([]commentCore.Comment, error) {
//				panic("mock out the FetchDocumentCommentsByBranchID method")
//			},
//			FetchDocumentMaintainersFunc: func(ctx context.Context, documentID xid.ID, organizationID string) ([]string, error) {
//				panic("mock out the FetchDocumentMaintainers method")
//			},
//			InsertDocumentCommentFunc: func(ctx context.Context, c commentCore.Comment) error {
//				panic("mock out the InsertDocumentComment method")
//			},
//			InsertDocumentCommentReplyFunc: func(ctx context.Context, r commentCore.Reply) error {
//				panic("mock out the InsertDocumentCommentReply method")
//			},
//			ReplaceDocumentCommentFunc: func(ctx context.Context, c commentCore.Comment) error {
//				panic("mock out the ReplaceDocumentComment method")
//			},
//			RollbackFunc: func() error {
//				panic("mock out the Rollback method")
//			},
//			UpdateDocumentCommentFunc: func(ctx context.Context, c commentCore.Comment) error {
//				panic("mock out the UpdateDocumentComment method")
//			},
//			UpdateDocumentCommentReplyFunc: func(ctx context.Context, r commentCore.Reply) error {
//				panic("mock out the UpdateDocumentCommentReply method")
//			},
//		}
//
//		// use mockedTx in code that requires Tx
//		// and then make assertions.
//
//	}
type TxMock struct {
	// CommitFunc mocks the Commit method.
	CommitFunc func() error

	// DeleteDocumentCommentFunc mocks the DeleteDocumentComment method.
	DeleteDocumentCommentFunc func(ctx context.Context, id xid.ID, documentID xid.ID, organizationID string) error

	// DeleteDocumentCommentReplyFunc mocks the DeleteDocumentCommentReply method.
	DeleteDocumentCommentReplyFunc func(ctx context.Context, id xid.ID, commentID xid.ID, organizationID string) error

	// DeleteDocumentCommentsByBranchIDFunc mocks the DeleteDocumentCommentsByBranchID method.
	DeleteDocumentCommentsByBranchIDFunc func(ctx context.Context, branchID xid.ID, organizationID string) error

	// FetchDocumentByBranchIDFunc mocks the FetchDocumentByBranchID method.
	FetchDocumentByBranchIDFunc func(ctx context.Context, branchID xid.ID, organizationID string) (*document.Document, error)

	// FetchDocumentCommentFunc mocks the FetchDocumentComment method.
	FetchDocumentCommentFunc func(ctx context.Context, id xid.ID, documentID xid.ID, organizationID string) (*commentCore.Comment, error)

	// FetchDocumentCommentReplyFunc mocks the FetchDocumentCommentReply method.
	FetchDocumentCommentReplyFunc func(ctx context.Context, id xid.ID, commentID xid.ID, organizationID string) (*commentCore.Reply, error)

	// FetchDocumentCommentsByBranchIDFunc mocks the FetchDocumentCommentsByBranchID method.
	FetchDocumentCommentsByBranchIDFunc func(ctx context.Context, branchID xid.ID, organizationID string) ([]commentCore.Comment, error)

	// FetchDocumentMaintainersFunc mocks the FetchDocumentMaintainers method.
	FetchDocumentMaintainersFunc func(ctx context.Context, documentID xid.ID, organizationID string) ([]string, error)

	// InsertDocumentCommentFunc mocks the InsertDocumentComment method.
	InsertDocumentCommentFunc func(ctx context.Context, c commentCore.Comment) error

	// InsertDocumentCommentReplyFunc mocks the InsertDocumentCommentReply method.
	InsertDocumentCommentReplyFunc func(ctx context.Context, r commentCore.Reply) error

	// ReplaceDocumentCommentFunc mocks the ReplaceDocumentComment method.
	ReplaceDocumentCommentFunc func(ctx context.Context, c commentCore.Comment) error

	// RollbackFunc mocks the Rollback method.
	RollbackFunc func() error

	// UpdateDocumentCommentFunc mocks the UpdateDocumentComment method.
	UpdateDocumentCommentFunc func(ctx context.Context, c commentCore.Comment) error

	// UpdateDocumentCommentReplyFunc mocks the UpdateDocumentCommentReply method.
	UpdateDocumentCommentReplyFunc func(ctx context.Context, r commentCore.Reply) error

	// calls tracks calls to the methods.
	calls struct {
		// Commit holds details about calls to the Commit method.
		Commit []struct {
		}
		// DeleteDocumentComment holds details about calls to the DeleteDocumentComment method.
		DeleteDocumentComment []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID xid.ID
			// DocumentID is the documentID argument value.
			DocumentID xid.ID
			// OrganizationID is the organizationID argument value.
			OrganizationID string
		}
		// DeleteDocumentCommentReply holds details about calls to the DeleteDocumentCommentReply method.
		DeleteDocumentCommentReply []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID xid.ID
			// CommentID is the commentID argument value.
			CommentID xid.ID
			// OrganizationID is the organizationID argument value.
			OrganizationID string
		}
		// DeleteDocumentCommentsByBranchID holds details about calls to the DeleteDocumentCommentsByBranchID method.
		DeleteDocumentCommentsByBranchID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// BranchID is the branchID argument value.
			BranchID xid.ID
			// OrganizationID is the organizationID argument value.
			OrganizationID string
		}
		// FetchDocumentByBranchID holds details about calls to the FetchDocumentByBranchID method.
		FetchDocumentByBranchID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// BranchID is the branchID argument value.
			BranchID xid.ID
			// OrganizationID is the organizationID argument value.
			OrganizationID string
		}
		// FetchDocumentComment holds details about calls to the FetchDocumentComment method.
		FetchDocumentComment []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID xid.ID
			// DocumentID is the documentID argument value.
			DocumentID xid.ID
			// OrganizationID is the organizationID argument value.
			OrganizationID string
		}
		// FetchDocumentCommentReply holds details about calls to the FetchDocumentCommentReply method.
		FetchDocumentCommentReply []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID xid.ID
			// CommentID is the commentID argument value.
			CommentID xid.ID
			// OrganizationID is the organizationID argument value.
			OrganizationID string
		}
		// FetchDocumentCommentsByBranchID holds details about calls to the FetchDocumentCommentsByBranchID method.
		FetchDocumentCommentsByBranchID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// BranchID is the branchID argument value.
			BranchID xid.ID
			// OrganizationID is the organizationID argument value.
			OrganizationID string
		}
		// FetchDocumentMaintainers holds details about calls to the FetchDocumentMaintainers method.
		FetchDocumentMaintainers []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// DocumentID is the documentID argument value.
			DocumentID xid.ID
			// OrganizationID is the organizationID argument value.
			OrganizationID string
		}
		// InsertDocumentComment holds details about calls to the InsertDocumentComment method.
		InsertDocumentComment []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// C is the c argument value.
			C commentCore.Comment
		}
		// InsertDocumentCommentReply holds details about calls to the InsertDocumentCommentReply method.
		InsertDocumentCommentReply []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// R is the r argument value.
			R commentCore.Reply
		}
		// ReplaceDocumentComment holds details about calls to the ReplaceDocumentComment method.
		ReplaceDocumentComment []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// C is the c argument value.
			C commentCore.Comment
		}
		// Rollback holds details about calls to the Rollback method.
		Rollback []struct {
		}
		// UpdateDocumentComment holds details about calls to the UpdateDocumentComment method.
		UpdateDocumentComment []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// C is the c argument value.
			C commentCore.Comment
		}
		// UpdateDocumentCommentReply holds details about calls to the UpdateDocumentCommentReply method.
		UpdateDocumentCommentReply []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// R is the r argument value.
			R commentCore.Reply
		}
	}
	lockCommit                           sync.RWMutex
	lockDeleteDocumentComment            sync.RWMutex
	lockDeleteDocumentCommentReply       sync.RWMutex
	lockDeleteDocumentCommentsByBranchID sync.RWMutex
	lockFetchDocumentByBranchID          sync.RWMutex
	lockFetchDocumentComment             sync.RWMutex
	lockFetchDocumentCommentReply        sync.RWMutex
	lockFetchDocumentCommentsByBranchID  sync.RWMutex
	lockFetchDocumentMaintainers         sync.RWMutex
	lockInsertDocumentComment            sync.RWMutex
	lockInsertDocumentCommentReply       sync.RWMutex
	lockReplaceDocumentComment           sync.RWMutex
	lockRollback                         sync.RWMutex
	lockUpdateDocumentComment            sync.RWMutex
	lockUpdateDocumentCommentReply       sync.RWMutex
}

// Commit calls CommitFunc.
func (mock *TxMock) Commit() error {
	callInfo := struct {
	}{}
	mock.lockCommit.Lock()
	mock.calls.Commit = append(mock.calls.Commit, callInfo)
	mock.lockCommit.Unlock()
	if mock.CommitFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.CommitFunc()
}

// CommitCalls gets all the calls that were made to Commit.
// Check the length with:
//
//	len(mockedTx.CommitCalls())
func (mock *TxMock) CommitCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockCommit.RLock()
	calls = mock.calls.Commit
	mock.lockCommit.RUnlock()
	return calls
}

// DeleteDocumentComment calls DeleteDocumentCommentFunc.
func (mock *TxMock) DeleteDocumentComment(ctx context.Context, id xid.ID, documentID xid.ID, organizationID string) error {
	callInfo := struct {
		Ctx            context.Context
		ID             xid.ID
		DocumentID     xid.ID
		OrganizationID string
	}{
		Ctx:            ctx,
		ID:             id,
		DocumentID:     documentID,
		OrganizationID: organizationID,
	}
	mock.lockDeleteDocumentComment.Lock()
	mock.calls.DeleteDocumentComment = append(mock.calls.DeleteDocumentComment, callInfo)
	mock.lockDeleteDocumentComment.Unlock()
	if mock.DeleteDocumentCommentFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.DeleteDocumentCommentFunc(ctx, id, documentID, organizationID)
}

// DeleteDocumentCommentCalls gets all the calls that were made to DeleteDocumentComment.
// Check the length with:
//
//	len(mockedTx.DeleteDocumentCommentCalls())
func (mock *TxMock) DeleteDocumentCommentCalls() []struct {
	Ctx            context.Context
	ID             xid.ID
	DocumentID     xid.ID
	OrganizationID string
} {
	var calls []struct {
		Ctx            context.Context
		ID             xid.ID
		DocumentID     xid.ID
		OrganizationID string
	}
	mock.lockDeleteDocumentComment.RLock()
	calls = mock.calls.DeleteDocumentComment
	mock.lockDeleteDocumentComment.RUnlock()
	return calls
}

// DeleteDocumentCommentReply calls DeleteDocumentCommentReplyFunc.
func (mock *TxMock) DeleteDocumentCommentReply(ctx context.Context, id xid.ID, commentID xid.ID, organizationID string) error {
	callInfo := struct {
		Ctx            context.Context
		ID             xid.ID
		CommentID      xid.ID
		OrganizationID string
	}{
		Ctx:            ctx,
		ID:             id,
		CommentID:      commentID,
		OrganizationID: organizationID,
	}
	mock.lockDeleteDocumentCommentReply.Lock()
	mock.calls.DeleteDocumentCommentReply = append(mock.calls.DeleteDocumentCommentReply, callInfo)
	mock.lockDeleteDocumentCommentReply.Unlock()
	if mock.DeleteDocumentCommentReplyFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.DeleteDocumentCommentReplyFunc(ctx, id, commentID, organizationID)
}

// DeleteDocumentCommentReplyCalls gets all the calls that were made to DeleteDocumentCommentReply.
// Check the length with:
//
//	len(mockedTx.DeleteDocumentCommentReplyCalls())
func (mock *TxMock) DeleteDocumentCommentReplyCalls() []struct {
	Ctx            context.Context
	ID             xid.ID
	CommentID      xid.ID
	OrganizationID string
} {
	var calls []struct {
		Ctx            context.Context
		ID             xid.ID
		CommentID      xid.ID
		OrganizationID string
	}
	mock.lockDeleteDocumentCommentReply.RLock()
	calls = mock.calls.DeleteDocumentCommentReply
	mock.lockDeleteDocumentCommentReply.RUnlock()
	return calls
}

// DeleteDocumentCommentsByBranchID calls DeleteDocumentCommentsByBranchIDFunc.
func (mock *TxMock) DeleteDocumentCommentsByBranchID(ctx context.Context, branchID xid.ID, organizationID string) error {
	callInfo := struct {
		Ctx            context.Context
		BranchID       xid.ID
		OrganizationID string
	}{
		Ctx:            ctx,
		BranchID:       branchID,
		OrganizationID: organizationID,
	}
	mock.lockDeleteDocumentCommentsByBranchID.Lock()
	mock.calls.DeleteDocumentCommentsByBranchID = append(mock.calls.DeleteDocumentCommentsByBranchID, callInfo)
	mock.lockDeleteDocumentCommentsByBranchID.Unlock()
	if mock.DeleteDocumentCommentsByBranchIDFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.DeleteDocumentCommentsByBranchIDFunc(ctx, branchID, organizationID)
}

// DeleteDocumentCommentsByBranchIDCalls gets all the calls that were made to DeleteDocumentCommentsByBranchID.
// Check the length with:
//
//	len(mockedTx.DeleteDocumentCommentsByBranchIDCalls())
func (mock *TxMock) DeleteDocumentCommentsByBranchIDCalls() []struct {
	Ctx            context.Context
	BranchID       xid.ID
	OrganizationID string
} {
	var calls []struct {
		Ctx            context.Context
		BranchID       xid.ID
		OrganizationID string
	}
	mock.lockDeleteDocumentCommentsByBranchID.RLock()
	calls = mock.calls.DeleteDocumentCommentsByBranchID
	mock.lockDeleteDocumentCommentsByBranchID.RUnlock()
	return calls
}

// FetchDocumentByBranchID calls FetchDocumentByBranchIDFunc.
func (mock *TxMock) FetchDocumentByBranchID(ctx context.Context, branchID xid.ID, organizationID string) (*document.Document, error) {
	callInfo := struct {
		Ctx            context.Context
		BranchID       xid.ID
		OrganizationID string
	}{
		Ctx:            ctx,
		BranchID:       branchID,
		OrganizationID: organizationID,
	}
	mock.lockFetchDocumentByBranchID.Lock()
	mock.calls.FetchDocumentByBranchID = append(mock.calls.FetchDocumentByBranchID, callInfo)
	mock.lockFetchDocumentByBranchID.Unlock()
	if mock.FetchDocumentByBranchIDFunc == nil {
		var (
			documentOut *document.Document
			errOut      error
		)
		return documentOut, errOut
	}
	return mock.FetchDocumentByBranchIDFunc(ctx, branchID, organizationID)
}

// FetchDocumentByBranchIDCalls gets all the calls that were made to FetchDocumentByBranchID.
// Check the length with:
//
//	len(mockedTx.FetchDocumentByBranchIDCalls())
func (mock *TxMock) FetchDocumentByBranchIDCalls() []struct {
	Ctx            context.Context
	BranchID       xid.ID
	OrganizationID string
} {
	var calls []struct {
		Ctx            context.Context
		BranchID       xid.ID
		OrganizationID string
	}
	mock.lockFetchDocumentByBranchID.RLock()
	calls = mock.calls.FetchDocumentByBranchID
	mock.lockFetchDocumentByBranchID.RUnlock()
	return calls
}

// FetchDocumentComment calls FetchDocumentCommentFunc.
func (mock *TxMock) FetchDocumentComment(ctx context.Context, id xid.ID, documentID xid.ID, organizationID string) (*commentCore.Comment, error) {
	callInfo := struct {
		Ctx            context.Context
		ID             xid.ID
		DocumentID     xid.ID
		OrganizationID string
	}{
		Ctx:            ctx,
		ID:             id,
		DocumentID:     documentID,
		OrganizationID: organizationID,
	}
	mock.lockFetchDocumentComment.Lock()
	mock.calls.FetchDocumentComment = append(mock.calls.FetchDocumentComment, callInfo)
	mock.lockFetchDocumentComment.Unlock()
	if mock.FetchDocumentCommentFunc == nil {
		var (
			commentOut *commentCore.Comment
			errOut     error
		)
		return commentOut, errOut
	}
	return mock.FetchDocumentCommentFunc(ctx, id, documentID, organizationID)
}

// FetchDocumentCommentCalls gets all the calls that were made to FetchDocumentComment.
// Check the length with:
//
//	len(mockedTx.FetchDocumentCommentCalls())
func (mock *TxMock) FetchDocumentCommentCalls() []struct {
	Ctx            context.Context
	ID             xid.ID
	DocumentID     xid.ID
	OrganizationID string
} {
	var calls []struct {
		Ctx            context.Context
		ID             xid.ID
		DocumentID     xid.ID
		OrganizationID string
	}
	mock.lockFetchDocumentComment.RLock()
	calls = mock.calls.FetchDocumentComment
	mock.lockFetchDocumentComment.RUnlock()
	return calls
}

// FetchDocumentCommentReply calls FetchDocumentCommentReplyFunc.
func (mock *TxMock) FetchDocumentCommentReply(ctx context.Context, id xid.ID, commentID xid.ID, organizationID string) (*commentCore.Reply, error) {
	callInfo := struct {
		Ctx            context.Context
		ID             xid.ID
		CommentID      xid.ID
		OrganizationID string
	}{
		Ctx:            ctx,
		ID:             id,
		CommentID:      commentID,
		OrganizationID: organizationID,
	}
	mock.lockFetchDocumentCommentReply.Lock()
	mock.calls.FetchDocumentCommentReply = append(mock.calls.FetchDocumentCommentReply, callInfo)
	mock.lockFetchDocumentCommentReply.Unlock()
	if mock.FetchDocumentCommentReplyFunc == nil {
		var (
			replyOut *commentCore.Reply
			errOut   error
		)
		return replyOut, errOut
	}
	return mock.FetchDocumentCommentReplyFunc(ctx, id, commentID, organizationID)
}

// FetchDocumentCommentReplyCalls gets all the calls that were made to FetchDocumentCommentReply.
// Check the length with:
//
//	len(mockedTx.FetchDocumentCommentReplyCalls())
func (mock *TxMock) FetchDocumentCommentReplyCalls() []struct {
	Ctx            context.Context
	ID             xid.ID
	CommentID      xid.ID
	OrganizationID string
} {
	var calls []struct {
		Ctx            context.Context
		ID             xid.ID
		CommentID      xid.ID
		OrganizationID string
	}
	mock.lockFetchDocumentCommentReply.RLock()
	calls = mock.calls.FetchDocumentCommentReply
	mock.lockFetchDocumentCommentReply.RUnlock()
	return calls
}

// FetchDocumentCommentsByBranchID calls FetchDocumentCommentsByBranchIDFunc.
func (mock *TxMock) FetchDocumentCommentsByBranchID(ctx context.Context, branchID xid.ID, organizationID string) ([]commentCore.Comment, error) {
	callInfo := struct {
		Ctx            context.Context
		BranchID       xid.ID
		OrganizationID string
	}{
		Ctx:            ctx,
		BranchID:       branchID,
		OrganizationID: organizationID,
	}
	mock.lockFetchDocumentCommentsByBranchID.Lock()
	mock.calls.FetchDocumentCommentsByBranchID = append(mock.calls.FetchDocumentCommentsByBranchID, callInfo)
	mock.lockFetchDocumentCommentsByBranchID.Unlock()
	if mock.FetchDocumentCommentsByBranchIDFunc == nil {
		var (
			commentsOut []commentCore.Comment
			errOut      error
		)
		return commentsOut, errOut
	}
	return mock.FetchDocumentCommentsByBranchIDFunc(ctx, branchID, organizationID)
}

// FetchDocumentCommentsByBranchIDCalls gets all the calls that were made to FetchDocumentCommentsByBranchID.
// Check the length with:
//
//	len(mockedTx.FetchDocumentCommentsByBranchIDCalls())
func (mock *TxMock) FetchDocumentCommentsByBranchIDCalls() []struct {
	Ctx            context.Context
	BranchID       xid.ID
	OrganizationID string
} {
	var calls []struct {
		Ctx            context.Context
		BranchID       xid.ID
		OrganizationID string
	}
	mock.lockFetchDocumentCommentsByBranchID.RLock()
	calls = mock.calls.FetchDocumentCommentsByBranchID
	mock.lockFetchDocumentCommentsByBranchID.RUnlock()
	return calls
}

// FetchDocumentMaintainers calls FetchDocumentMaintainersFunc.
func (mock *TxMock) FetchDocumentMaintainers(ctx context.Context, documentID xid.ID, organizationID string) ([]string, error) {
	callInfo := struct {
		Ctx            context.Context
		DocumentID     xid.ID
		OrganizationID string
	}{
		Ctx:            ctx,
		DocumentID:     documentID,
		OrganizationID: organizationID,
	}
	mock.lockFetchDocumentMaintainers.Lock()
	mock.calls.FetchDocumentMaintainers = append(mock.calls.FetchDocumentMaintainers, callInfo)
	mock.lockFetchDocumentMaintainers.Unlock()
	if mock.FetchDocumentMaintainersFunc == nil {
		var (
			stringsOut []string
			errOut     error
		)
		return stringsOut, errOut
	}
	return mock.FetchDocumentMaintainersFunc(ctx, documentID, organizationID)
}

// FetchDocumentMaintainersCalls gets all the calls that were made to FetchDocumentMaintainers.
// Check the length with:
//
//	len(mockedTx.FetchDocumentMaintainersCalls())
func (mock *TxMock) FetchDocumentMaintainersCalls() []struct {
	Ctx            context.Context
	DocumentID     xid.ID
	OrganizationID string
} {
	var calls []struct {
		Ctx            context.Context
		DocumentID     xid.ID
		OrganizationID string
	}
	mock.lockFetchDocumentMaintainers.RLock()
	calls = mock.calls.FetchDocumentMaintainers
	mock.lockFetchDocumentMaintainers.RUnlock()
	return calls
}

// InsertDocumentComment calls InsertDocumentCommentFunc.
func (mock *TxMock) InsertDocumentComment(ctx context.Context, c commentCore.Comment) error {
	callInfo := struct {
		Ctx context.Context
		C   commentCore.Comment
	}{
		Ctx: ctx,
		C:   c,
	}
	mock.lockInsertDocumentComment.Lock()
	mock.calls.InsertDocumentComment = append(mock.calls.InsertDocumentComment, callInfo)
	mock.lockInsertDocumentComment.Unlock()
	if mock.InsertDocumentCommentFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.InsertDocumentCommentFunc(ctx, c)
}

// InsertDocumentCommentCalls gets all the calls that were made to InsertDocumentComment.
// Check the length with:
//
//	len(mockedTx.InsertDocumentCommentCalls())
func (mock *TxMock) InsertDocumentCommentCalls() []struct {
	Ctx context.Context
	C   commentCore.Comment
} {
	var calls []struct {
		Ctx context.Context
		C   commentCore.Comment
	}
	mock.lockInsertDocumentComment.RLock()
	calls = mock.calls.InsertDocumentComment
	mock.lockInsertDocumentComment.RUnlock()
	return calls
}

// InsertDocumentCommentReply calls InsertDocumentCommentReplyFunc.
func (mock *TxMock) InsertDocumentCommentReply(ctx context.Context, r commentCore.Reply) error {
	callInfo := struct {
		Ctx context.Context
		R   commentCore.Reply
	}{
		Ctx: ctx,
		R:   r,
	}
	mock.lockInsertDocumentCommentReply.Lock()
	mock.calls.InsertDocumentCommentReply = append(mock.calls.InsertDocumentCommentReply, callInfo)
	mock.lockInsertDocumentCommentReply.Unlock()
	if mock.InsertDocumentCommentReplyFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.InsertDocumentCommentReplyFunc(ctx, r)
}

// InsertDocumentCommentReplyCalls gets all the calls that were made to InsertDocumentCommentReply.
// Check the length with:
//
//	len(mockedTx.InsertDocumentCommentReplyCalls())
func (mock *TxMock) InsertDocumentCommentReplyCalls() []struct {
	Ctx context.Context
	R   commentCore.Reply
} {
	var calls []struct {
		Ctx context.Context
		R   commentCore.Reply
	}
	mock.lockInsertDocumentCommentReply.RLock()
	calls = mock.calls.InsertDocumentCommentReply
	mock.lockInsertDocumentCommentReply.RUnlock()
	return calls
}

// ReplaceDocumentComment calls ReplaceDocumentCommentFunc.
func (mock *TxMock) ReplaceDocumentComment(ctx context.Context, c commentCore.Comment) error {
	callInfo := struct {
		Ctx context.Context
		C   commentCore.Comment
	}{
		Ctx: ctx,
		C:   c,
	}
	mock.lockReplaceDocumentComment.Lock()
	mock.calls.ReplaceDocumentComment = append(mock.calls.ReplaceDocumentComment, callInfo)
	mock.lockReplaceDocumentComment.Unlock()
	if mock.ReplaceDocumentCommentFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.ReplaceDocumentCommentFunc(ctx, c)
}

// ReplaceDocumentCommentCalls gets all the calls that were made to ReplaceDocumentComment.
// Check the length with:
//
//	len(mockedTx.ReplaceDocumentCommentCalls())
func (mock *TxMock) ReplaceDocumentCommentCalls() []struct {
	Ctx context.Context
	C   commentCore.Comment
} {
	var calls []struct {
		Ctx context.Context
		C   commentCore.Comment
	}
	mock.lockReplaceDocumentComment.RLock()
	calls = mock.calls.ReplaceDocumentComment
	mock.lockReplaceDocumentComment.RUnlock()
	return calls
}

// Rollback calls RollbackFunc.
func (mock *TxMock) Rollback() error {
	callInfo := struct {
	}{}
	mock.lockRollback.Lock()
	mock.calls.Rollback = append(mock.calls.Rollback, callInfo)
	mock.lockRollback.Unlock()
	if mock.RollbackFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.RollbackFunc()
}

// RollbackCalls gets all the calls that were made to Rollback.
// Check the length with:
//
//	len(mockedTx.RollbackCalls())
func (mock *TxMock) RollbackCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockRollback.RLock()
	calls = mock.calls.Rollback
	mock.lockRollback.RUnlock()
	return calls
}

// UpdateDocumentComment calls UpdateDocumentCommentFunc.
func (mock *TxMock) UpdateDocumentComment(ctx context.Context, c commentCore.Comment) error {
	callInfo := struct {
		Ctx context.Context
		C   commentCore.Comment
	}{
		Ctx: ctx,
		C:   c,
	}
	mock.lockUpdateDocumentComment.Lock()
	mock.calls.UpdateDocumentComment = append(mock.calls.UpdateDocumentComment, callInfo)
	mock.lockUpdateDocumentComment.Unlock()
	if mock.UpdateDocumentCommentFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.UpdateDocumentCommentFunc(ctx, c)
}

// UpdateDocumentCommentCalls gets all the calls that were made to UpdateDocumentComment.
// Check the length with:
//
//	len(mockedTx.UpdateDocumentCommentCalls())
func (mock *TxMock) UpdateDocumentCommentCalls() []struct {
	Ctx context.Context
	C   commentCore.Comment
} {
	var calls []struct {
		Ctx context.Context
		C   commentCore.Comment
	}
	mock.lockUpdateDocumentComment.RLock()
	calls = mock.calls.UpdateDocumentComment
	mock.lockUpdateDocumentComment.RUnlock()
	return calls
}

// UpdateDocumentCommentReply calls UpdateDocumentCommentReplyFunc.
func (mock *TxMock) UpdateDocumentCommentReply(ctx context.Context, r commentCore.Reply) error {
	callInfo := struct {
		Ctx context.Context
		R   commentCore.Reply
	}{
		Ctx: ctx,
		R:   r,
	}
	mock.lockUpdateDocumentCommentReply.Lock()
	mock.calls.UpdateDocumentCommentReply = append(mock.calls.UpdateDocumentCommentReply, callInfo)
	mock.lockUpdateDocumentCommentReply.Unlock()
	if mock.UpdateDocumentCommentReplyFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.UpdateDocumentCommentReplyFunc(ctx, r)
}

// UpdateDocumentCommentReplyCalls gets all the calls that were made to UpdateDocumentCommentReply.
// Check the length with:
//
//	len(mockedTx.UpdateDocumentCommentReplyCalls())
func (mock *TxMock) UpdateDocumentCommentReplyCalls() []struct {
	Ctx context.Context
	R   commentCore.Reply
} {
	var calls []struct {
		Ctx context.Context
		R   commentCore.Reply
	}
	mock.lockUpdateDocumentCommentReply.RLock()
	calls = mock.calls.UpdateDocumentCommentReply
	mock.lockUpdateDocumentCommentReply.RUnlock()
	return calls
}
