global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'core'
    metrics_path: api/x/metrics
    static_configs:
      - targets: ['core:8080']
  - job_name: 'datagen'
    metrics_path: api/metrics
    static_configs:
      - targets: ['datagen:8080']
