// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"sync"

	"github.com/guregu/null/v5"
	"github.com/oxynote/oxynote/server/core/internal/assistant/tools"
	"github.com/oxynote/oxynote/server/core/internal/document"
	"github.com/rs/xid"
)

// Ensure, that DB does implement tools.DB.
// If this is not the case, regenerate this file with moq.
var _ tools.DB = &DB{}

// DB is a mock implementation of tools.DB.
//
//	func TestSomethingThatUsesDB(t *testing.T) {
//
//		// make and configure a mocked tools.DB
//		mockedDB := &DB{
//			CheckDocumentExistsFunc: func(ctx context.Context, id xid.ID, organizationID string) error {
//				panic("mock out the CheckDocumentExists method")
//			},
//			DeleteDocumentFunc: func(ctx context.Context, id xid.ID, organizationID string) error {
//				panic("mock out the DeleteDocument method")
//			},
//			FetchDocumentFunc: func(ctx context.Context, id xid.ID, organizationID string, branchName string) (*document.Document, error) {
//				panic("mock out the FetchDocument method")
//			},
//			FetchDocumentTreeFunc: func(ctx context.Context, organizationID string) (document.Summaries, error) {
//				panic("mock out the FetchDocumentTree method")
//			},
//			FetchDocumentTreeByDocumentParentIDFunc: func(ctx context.Context, parentID null.Value[xid.ID], organizationID string) (document.Summaries, error) {
//				panic("mock out the FetchDocumentTreeByDocumentParentID method")
//			},
//			FetchMainBranchContentFunc: func(ctx context.Context, docID xid.ID, organizationID string) (document.Content, error) {
//				panic("mock out the FetchMainBranchContent method")
//			},
//			InsertDocumentFunc: func(ctx context.Context, doc document.Document) error {
//				panic("mock out the InsertDocument method")
//			},
//			UpdateDocumentParentIDFunc: func(ctx context.Context, id xid.ID, parentID null.Value[xid.ID], organizationID string) error {
//				panic("mock out the UpdateDocumentParentID method")
//			},
//			UpsertDocumentMaintainersFunc: func(ctx context.Context, documentID xid.ID, organizationID string, maintainerIDs []string) error {
//				panic("mock out the UpsertDocumentMaintainers method")
//			},
//		}
//
//		// use mockedDB in code that requires tools.DB
//		// and then make assertions.
//
//	}
type DB struct {
	// CheckDocumentExistsFunc mocks the CheckDocumentExists method.
	CheckDocumentExistsFunc func(ctx context.Context, id xid.ID, organizationID string) error

	// DeleteDocumentFunc mocks the DeleteDocument method.
	DeleteDocumentFunc func(ctx context.Context, id xid.ID, organizationID string) error

	// FetchDocumentFunc mocks the FetchDocument method.
	FetchDocumentFunc func(ctx context.Context, id xid.ID, organizationID string, branchName string) (*document.Document, error)

	// FetchDocumentTreeFunc mocks the FetchDocumentTree method.
	FetchDocumentTreeFunc func(ctx context.Context, organizationID string) (document.Summaries, error)

	// FetchDocumentTreeByDocumentParentIDFunc mocks the FetchDocumentTreeByDocumentParentID method.
	FetchDocumentTreeByDocumentParentIDFunc func(ctx context.Context, parentID null.Value[xid.ID], organizationID string) (document.Summaries, error)

	// FetchMainBranchContentFunc mocks the FetchMainBranchContent method.
	FetchMainBranchContentFunc func(ctx context.Context, docID xid.ID, organizationID string) (document.Content, error)

	// InsertDocumentFunc mocks the InsertDocument method.
	InsertDocumentFunc func(ctx context.Context, doc document.Document) error

	// UpdateDocumentParentIDFunc mocks the UpdateDocumentParentID method.
	UpdateDocumentParentIDFunc func(ctx context.Context, id xid.ID, parentID null.Value[xid.ID], organizationID string) error

	// UpsertDocumentMaintainersFunc mocks the UpsertDocumentMaintainers method.
	UpsertDocumentMaintainersFunc func(ctx context.Context, documentID xid.ID, organizationID string, maintainerIDs []string) error

	// calls tracks calls to the methods.
	calls struct {
		// CheckDocumentExists holds details about calls to the CheckDocumentExists method.
		CheckDocumentExists []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID xid.ID
			// OrganizationID is the organizationID argument value.
			OrganizationID string
		}
		// DeleteDocument holds details about calls to the DeleteDocument method.
		DeleteDocument []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID xid.ID
			// OrganizationID is the organizationID argument value.
			OrganizationID string
		}
		// FetchDocument holds details about calls to the FetchDocument method.
		FetchDocument []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID xid.ID
			// OrganizationID is the organizationID argument value.
			OrganizationID string
			// BranchName is the branchName argument value.
			BranchName string
		}
		// FetchDocumentTree holds details about calls to the FetchDocumentTree method.
		FetchDocumentTree []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrganizationID is the organizationID argument value.
			OrganizationID string
		}
		// FetchDocumentTreeByDocumentParentID holds details about calls to the FetchDocumentTreeByDocumentParentID method.
		FetchDocumentTreeByDocumentParentID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ParentID is the parentID argument value.
			ParentID null.Value[xid.ID]
			// OrganizationID is the organizationID argument value.
			OrganizationID string
		}
		// FetchMainBranchContent holds details about calls to the FetchMainBranchContent method.
		FetchMainBranchContent []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// DocID is the docID argument value.
			DocID xid.ID
			// OrganizationID is the organizationID argument value.
			OrganizationID string
		}
		// InsertDocument holds details about calls to the InsertDocument method.
		InsertDocument []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Doc is the doc argument value.
			Doc document.Document
		}
		// UpdateDocumentParentID holds details about calls to the UpdateDocumentParentID method.
		UpdateDocumentParentID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID xid.ID
			// ParentID is the parentID argument value.
			ParentID null.Value[xid.ID]
			// OrganizationID is the organizationID argument value.
			OrganizationID string
		}
		// UpsertDocumentMaintainers holds details about calls to the UpsertDocumentMaintainers method.
		UpsertDocumentMaintainers []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// DocumentID is the documentID argument value.
			DocumentID xid.ID
			// OrganizationID is the organizationID argument value.
			OrganizationID string
			// MaintainerIDs is the maintainerIDs argument value.
			MaintainerIDs []string
		}
	}
	lockCheckDocumentExists                 sync.RWMutex
	lockDeleteDocument                      sync.RWMutex
	lockFetchDocument                       sync.RWMutex
	lockFetchDocumentTree                   sync.RWMutex
	lockFetchDocumentTreeByDocumentParentID sync.RWMutex
	lockFetchMainBranchContent              sync.RWMutex
	lockInsertDocument                      sync.RWMutex
	lockUpdateDocumentParentID              sync.RWMutex
	lockUpsertDocumentMaintainers           sync.RWMutex
}

// CheckDocumentExists calls CheckDocumentExistsFunc.
func (mock *DB) CheckDocumentExists(ctx context.Context, id xid.ID, organizationID string) error {
	callInfo := struct {
		Ctx            context.Context
		ID             xid.ID
		OrganizationID string
	}{
		Ctx:            ctx,
		ID:             id,
		OrganizationID: organizationID,
	}
	mock.lockCheckDocumentExists.Lock()
	mock.calls.CheckDocumentExists = append(mock.calls.CheckDocumentExists, callInfo)
	mock.lockCheckDocumentExists.Unlock()
	if mock.CheckDocumentExistsFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.CheckDocumentExistsFunc(ctx, id, organizationID)
}

// CheckDocumentExistsCalls gets all the calls that were made to CheckDocumentExists.
// Check the length with:
//
//	len(mockedDB.CheckDocumentExistsCalls())
func (mock *DB) CheckDocumentExistsCalls() []struct {
	Ctx            context.Context
	ID             xid.ID
	OrganizationID string
} {
	var calls []struct {
		Ctx            context.Context
		ID             xid.ID
		OrganizationID string
	}
	mock.lockCheckDocumentExists.RLock()
	calls = mock.calls.CheckDocumentExists
	mock.lockCheckDocumentExists.RUnlock()
	return calls
}

// DeleteDocument calls DeleteDocumentFunc.
func (mock *DB) DeleteDocument(ctx context.Context, id xid.ID, organizationID string) error {
	callInfo := struct {
		Ctx            context.Context
		ID             xid.ID
		OrganizationID string
	}{
		Ctx:            ctx,
		ID:             id,
		OrganizationID: organizationID,
	}
	mock.lockDeleteDocument.Lock()
	mock.calls.DeleteDocument = append(mock.calls.DeleteDocument, callInfo)
	mock.lockDeleteDocument.Unlock()
	if mock.DeleteDocumentFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.DeleteDocumentFunc(ctx, id, organizationID)
}

// DeleteDocumentCalls gets all the calls that were made to DeleteDocument.
// Check the length with:
//
//	len(mockedDB.DeleteDocumentCalls())
func (mock *DB) DeleteDocumentCalls() []struct {
	Ctx            context.Context
	ID             xid.ID
	OrganizationID string
} {
	var calls []struct {
		Ctx            context.Context
		ID             xid.ID
		OrganizationID string
	}
	mock.lockDeleteDocument.RLock()
	calls = mock.calls.DeleteDocument
	mock.lockDeleteDocument.RUnlock()
	return calls
}

// FetchDocument calls FetchDocumentFunc.
func (mock *DB) FetchDocument(ctx context.Context, id xid.ID, organizationID string, branchName string) (*document.Document, error) {
	callInfo := struct {
		Ctx            context.Context
		ID             xid.ID
		OrganizationID string
		BranchName     string
	}{
		Ctx:            ctx,
		ID:             id,
		OrganizationID: organizationID,
		BranchName:     branchName,
	}
	mock.lockFetchDocument.Lock()
	mock.calls.FetchDocument = append(mock.calls.FetchDocument, callInfo)
	mock.lockFetchDocument.Unlock()
	if mock.FetchDocumentFunc == nil {
		var (
			documentOut *document.Document
			errOut      error
		)
		return documentOut, errOut
	}
	return mock.FetchDocumentFunc(ctx, id, organizationID, branchName)
}

// FetchDocumentCalls gets all the calls that were made to FetchDocument.
// Check the length with:
//
//	len(mockedDB.FetchDocumentCalls())
func (mock *DB) FetchDocumentCalls() []struct {
	Ctx            context.Context
	ID             xid.ID
	OrganizationID string
	BranchName     string
} {
	var calls []struct {
		Ctx            context.Context
		ID             xid.ID
		OrganizationID string
		BranchName     string
	}
	mock.lockFetchDocument.RLock()
	calls = mock.calls.FetchDocument
	mock.lockFetchDocument.RUnlock()
	return calls
}

// FetchDocumentTree calls FetchDocumentTreeFunc.
func (mock *DB) FetchDocumentTree(ctx context.Context, organizationID string) (document.Summaries, error) {
	callInfo := struct {
		Ctx            context.Context
		OrganizationID string
	}{
		Ctx:            ctx,
		OrganizationID: organizationID,
	}
	mock.lockFetchDocumentTree.Lock()
	mock.calls.FetchDocumentTree = append(mock.calls.FetchDocumentTree, callInfo)
	mock.lockFetchDocumentTree.Unlock()
	if mock.FetchDocumentTreeFunc == nil {
		var (
			summariesOut document.Summaries
			errOut       error
		)
		return summariesOut, errOut
	}
	return mock.FetchDocumentTreeFunc(ctx, organizationID)
}

// FetchDocumentTreeCalls gets all the calls that were made to FetchDocumentTree.
// Check the length with:
//
//	len(mockedDB.FetchDocumentTreeCalls())
func (mock *DB) FetchDocumentTreeCalls() []struct {
	Ctx            context.Context
	OrganizationID string
} {
	var calls []struct {
		Ctx            context.Context
		OrganizationID string
	}
	mock.lockFetchDocumentTree.RLock()
	calls = mock.calls.FetchDocumentTree
	mock.lockFetchDocumentTree.RUnlock()
	return calls
}

// FetchDocumentTreeByDocumentParentID calls FetchDocumentTreeByDocumentParentIDFunc.
func (mock *DB) FetchDocumentTreeByDocumentParentID(ctx context.Context, parentID null.Value[xid.ID], organizationID string) (document.Summaries, error) {
	callInfo := struct {
		Ctx            context.Context
		ParentID       null.Value[xid.ID]
		OrganizationID string
	}{
		Ctx:            ctx,
		ParentID:       parentID,
		OrganizationID: organizationID,
	}
	mock.lockFetchDocumentTreeByDocumentParentID.Lock()
	mock.calls.FetchDocumentTreeByDocumentParentID = append(mock.calls.FetchDocumentTreeByDocumentParentID, callInfo)
	mock.lockFetchDocumentTreeByDocumentParentID.Unlock()
	if mock.FetchDocumentTreeByDocumentParentIDFunc == nil {
		var (
			summariesOut document.Summaries
			errOut       error
		)
		return summariesOut, errOut
	}
	return mock.FetchDocumentTreeByDocumentParentIDFunc(ctx, parentID, organizationID)
}

// FetchDocumentTreeByDocumentParentIDCalls gets all the calls that were made to FetchDocumentTreeByDocumentParentID.
// Check the length with:
//
//	len(mockedDB.FetchDocumentTreeByDocumentParentIDCalls())
func (mock *DB) FetchDocumentTreeByDocumentParentIDCalls() []struct {
	Ctx            context.Context
	ParentID       null.Value[xid.ID]
	OrganizationID string
} {
	var calls []struct {
		Ctx            context.Context
		ParentID       null.Value[xid.ID]
		OrganizationID string
	}
	mock.lockFetchDocumentTreeByDocumentParentID.RLock()
	calls = mock.calls.FetchDocumentTreeByDocumentParentID
	mock.lockFetchDocumentTreeByDocumentParentID.RUnlock()
	return calls
}

// FetchMainBranchContent calls FetchMainBranchContentFunc.
func (mock *DB) FetchMainBranchContent(ctx context.Context, docID xid.ID, organizationID string) (document.Content, error) {
	callInfo := struct {
		Ctx            context.Context
		DocID          xid.ID
		OrganizationID string
	}{
		Ctx:            ctx,
		DocID:          docID,
		OrganizationID: organizationID,
	}
	mock.lockFetchMainBranchContent.Lock()
	mock.calls.FetchMainBranchContent = append(mock.calls.FetchMainBranchContent, callInfo)
	mock.lockFetchMainBranchContent.Unlock()
	if mock.FetchMainBranchContentFunc == nil {
		var (
			contentOut document.Content
			errOut     error
		)
		return contentOut, errOut
	}
	return mock.FetchMainBranchContentFunc(ctx, docID, organizationID)
}

// FetchMainBranchContentCalls gets all the calls that were made to FetchMainBranchContent.
// Check the length with:
//
//	len(mockedDB.FetchMainBranchContentCalls())
func (mock *DB) FetchMainBranchContentCalls() []struct {
	Ctx            context.Context
	DocID          xid.ID
	OrganizationID string
} {
	var calls []struct {
		Ctx            context.Context
		DocID          xid.ID
		OrganizationID string
	}
	mock.lockFetchMainBranchContent.RLock()
	calls = mock.calls.FetchMainBranchContent
	mock.lockFetchMainBranchContent.RUnlock()
	return calls
}

// InsertDocument calls InsertDocumentFunc.
func (mock *DB) InsertDocument(ctx context.Context, doc document.Document) error {
	callInfo := struct {
		Ctx context.Context
		Doc document.Document
	}{
		Ctx: ctx,
		Doc: doc,
	}
	mock.lockInsertDocument.Lock()
	mock.calls.InsertDocument = append(mock.calls.InsertDocument, callInfo)
	mock.lockInsertDocument.Unlock()
	if mock.InsertDocumentFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.InsertDocumentFunc(ctx, doc)
}

// InsertDocumentCalls gets all the calls that were made to InsertDocument.
// Check the length with:
//
//	len(mockedDB.InsertDocumentCalls())
func (mock *DB) InsertDocumentCalls() []struct {
	Ctx context.Context
	Doc document.Document
} {
	var calls []struct {
		Ctx context.Context
		Doc document.Document
	}
	mock.lockInsertDocument.RLock()
	calls = mock.calls.InsertDocument
	mock.lockInsertDocument.RUnlock()
	return calls
}

// UpdateDocumentParentID calls UpdateDocumentParentIDFunc.
func (mock *DB) UpdateDocumentParentID(ctx context.Context, id xid.ID, parentID null.Value[xid.ID], organizationID string) error {
	callInfo := struct {
		Ctx            context.Context
		ID             xid.ID
		ParentID       null.Value[xid.ID]
		OrganizationID string
	}{
		Ctx:            ctx,
		ID:             id,
		ParentID:       parentID,
		OrganizationID: organizationID,
	}
	mock.lockUpdateDocumentParentID.Lock()
	mock.calls.UpdateDocumentParentID = append(mock.calls.UpdateDocumentParentID, callInfo)
	mock.lockUpdateDocumentParentID.Unlock()
	if mock.UpdateDocumentParentIDFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.UpdateDocumentParentIDFunc(ctx, id, parentID, organizationID)
}

// UpdateDocumentParentIDCalls gets all the calls that were made to UpdateDocumentParentID.
// Check the length with:
//
//	len(mockedDB.UpdateDocumentParentIDCalls())
func (mock *DB) UpdateDocumentParentIDCalls() []struct {
	Ctx            context.Context
	ID             xid.ID
	ParentID       null.Value[xid.ID]
	OrganizationID string
} {
	var calls []struct {
		Ctx            context.Context
		ID             xid.ID
		ParentID       null.Value[xid.ID]
		OrganizationID string
	}
	mock.lockUpdateDocumentParentID.RLock()
	calls = mock.calls.UpdateDocumentParentID
	mock.lockUpdateDocumentParentID.RUnlock()
	return calls
}

// UpsertDocumentMaintainers calls UpsertDocumentMaintainersFunc.
func (mock *DB) UpsertDocumentMaintainers(ctx context.Context, documentID xid.ID, organizationID string, maintainerIDs []string) error {
	callInfo := struct {
		Ctx            context.Context
		DocumentID     xid.ID
		OrganizationID string
		MaintainerIDs  []string
	}{
		Ctx:            ctx,
		DocumentID:     documentID,
		OrganizationID: organizationID,
		MaintainerIDs:  maintainerIDs,
	}
	mock.lockUpsertDocumentMaintainers.Lock()
	mock.calls.UpsertDocumentMaintainers = append(mock.calls.UpsertDocumentMaintainers, callInfo)
	mock.lockUpsertDocumentMaintainers.Unlock()
	if mock.UpsertDocumentMaintainersFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.UpsertDocumentMaintainersFunc(ctx, documentID, organizationID, maintainerIDs)
}

// UpsertDocumentMaintainersCalls gets all the calls that were made to UpsertDocumentMaintainers.
// Check the length with:
//
//	len(mockedDB.UpsertDocumentMaintainersCalls())
func (mock *DB) UpsertDocumentMaintainersCalls() []struct {
	Ctx            context.Context
	DocumentID     xid.ID
	OrganizationID string
	MaintainerIDs  []string
} {
	var calls []struct {
		Ctx            context.Context
		DocumentID     xid.ID
		OrganizationID string
		MaintainerIDs  []string
	}
	mock.lockUpsertDocumentMaintainers.RLock()
	calls = mock.calls.UpsertDocumentMaintainers
	mock.lockUpsertDocumentMaintainers.RUnlock()
	return calls
}
