// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"sync"

	"github.com/guregu/null/v5"
	"github.com/oxynote/oxynote/server/core/internal/assistant/tools"
	"github.com/oxynote/oxynote/server/core/internal/datasource"
	"github.com/oxynote/oxynote/server/core/internal/document"
	hookCore "github.com/oxynote/oxynote/server/core/internal/document/hook"
	"github.com/oxynote/oxynote/server/core/internal/tag"
	"github.com/rs/xid"
)

// Ensure, that DB does implement tools.DB.
// If this is not the case, regenerate this file with moq.
var _ tools.DB = &DB{}

// DB is a mock implementation of tools.DB.
//
//	func TestSomethingThatUsesDB(t *testing.T) {
//
//		// make and configure a mocked tools.DB
//		mockedDB := &DB{
//			BeginTxFunc: func(ctx context.Context, dest any) error {
//				panic("mock out the BeginTx method")
//			},
//			CheckDocumentCycleFunc: func(ctx context.Context, id xid.ID, parentID xid.ID, organizationID string) (bool, error) {
//				panic("mock out the CheckDocumentCycle method")
//			},
//			CheckDocumentExistsFunc: func(ctx context.Context, id xid.ID, organizationID string) error {
//				panic("mock out the CheckDocumentExists method")
//			},
//			FetchDocumentFunc: func(ctx context.Context, id xid.ID, organizationID string, branchName string) (*document.Document, error) {
//				panic("mock out the FetchDocument method")
//			},
//			FetchDocumentTreeFunc: func(ctx context.Context, organizationID string) (document.Summaries, error) {
//				panic("mock out the FetchDocumentTree method")
//			},
//			FetchDocumentTreeByDocumentParentIDFunc: func(ctx context.Context, parentID null.Value[xid.ID], organizationID string) (document.Summaries, error) {
//				panic("mock out the FetchDocumentTreeByDocumentParentID method")
//			},
//			UpdateDocumentParentIDFunc: func(ctx context.Context, id xid.ID, parentID null.Value[xid.ID], organizationID string) error {
//				panic("mock out the UpdateDocumentParentID method")
//			},
//		}
//
//		// use mockedDB in code that requires tools.DB
//		// and then make assertions.
//
//	}
type DB struct {
	// BeginTxFunc mocks the BeginTx method.
	BeginTxFunc func(ctx context.Context, dest any) error

	// CheckDocumentCycleFunc mocks the CheckDocumentCycle method.
	CheckDocumentCycleFunc func(ctx context.Context, id xid.ID, parentID xid.ID, organizationID string) (bool, error)

	// CheckDocumentExistsFunc mocks the CheckDocumentExists method.
	CheckDocumentExistsFunc func(ctx context.Context, id xid.ID, organizationID string) error

	// FetchDocumentFunc mocks the FetchDocument method.
	FetchDocumentFunc func(ctx context.Context, id xid.ID, organizationID string, branchName string) (*document.Document, error)

	// FetchDocumentTreeFunc mocks the FetchDocumentTree method.
	FetchDocumentTreeFunc func(ctx context.Context, organizationID string) (document.Summaries, error)

	// FetchDocumentTreeByDocumentParentIDFunc mocks the FetchDocumentTreeByDocumentParentID method.
	FetchDocumentTreeByDocumentParentIDFunc func(ctx context.Context, parentID null.Value[xid.ID], organizationID string) (document.Summaries, error)

	// FetchDocumentBranchesFunc mocks the FetchDocumentBranches method.
	FetchDocumentBranchesFunc func(ctx context.Context, docID xid.ID, organizationID string) ([]document.BranchSummary, error)

	// FetchDocumentByBranchIDFunc mocks the FetchDocumentByBranchID method.
	FetchDocumentByBranchIDFunc func(ctx context.Context, branchID xid.ID, organizationID string) (*document.Document, error)

	// UpdateDocumentParentIDFunc mocks the UpdateDocumentParentID method.
	UpdateDocumentParentIDFunc func(ctx context.Context, id xid.ID, parentID null.Value[xid.ID], organizationID string) error

	// FetchDataSourceFunc mocks the FetchDataSource method.
	FetchDataSourceFunc func(ctx context.Context, id xid.ID, organizationID string) (*datasource.DataSource, error)

	// FetchDataSourcesFunc mocks the FetchDataSources method.
	FetchDataSourcesFunc func(ctx context.Context, organizationID string) ([]datasource.DataSource, error)

	// FetchTagTreeFunc mocks the FetchTagTree method.
	FetchTagTreeFunc func(ctx context.Context, organizationID string, userID string) (tag.Summaries, error)
	// FetchBranchTagsFunc mocks the FetchBranchTags method.
	FetchBranchTagsFunc func(ctx context.Context, organizationID string, documentID xid.ID, branchID xid.ID) ([]tag.Tag, error)
	// InsertTagFunc mocks the InsertTag method.
	InsertTagFunc func(ctx context.Context, t tag.Tag) error
	// UpdateTagFunc mocks the UpdateTag method.
	UpdateTagFunc func(ctx context.Context, organizationID string, id xid.ID, inp tag.UpdateInput) error
	// DeleteTagFunc mocks the DeleteTag method.
	DeleteTagFunc func(ctx context.Context, id xid.ID, organizationID string) error
	// AssignBranchTagFunc mocks the AssignBranchTag method.
	AssignBranchTagFunc func(ctx context.Context, organizationID string, documentID xid.ID, branchID xid.ID, tagID xid.ID) error
	// UnassignBranchTagFunc mocks the UnassignBranchTag method.
	UnassignBranchTagFunc func(ctx context.Context, organizationID string, documentID xid.ID, branchID xid.ID, tagID xid.ID) error
	// UpdateTagTreeFunc mocks the UpdateTagTree method.
	UpdateTagTreeFunc func(ctx context.Context, tree tag.Summaries, organizationID string) error
	// FetchDocumentHooksByBranchIDFunc mocks the FetchDocumentHooksByBranchID method.
	FetchDocumentHooksByBranchIDFunc func(ctx context.Context, branchID xid.ID, organizationID string) ([]hookCore.Hook, error)
	// FetchDocumentHookFunc mocks the FetchDocumentHook method.
	FetchDocumentHookFunc func(ctx context.Context, id xid.ID, organizationID string) (*hookCore.Hook, error)
	// InsertDocumentHookFunc mocks the InsertDocumentHook method.
	InsertDocumentHookFunc func(ctx context.Context, hk hookCore.Hook) error
	// UpdateDocumentHookFunc mocks the UpdateDocumentHook method.
	UpdateDocumentHookFunc func(ctx context.Context, hk hookCore.Hook) error
	// DeleteDocumentHookFunc mocks the DeleteDocumentHook method.
	DeleteDocumentHookFunc func(ctx context.Context, id xid.ID) error

	// calls tracks calls to the methods.
	calls struct {
		// BeginTx holds details about calls to the BeginTx method.
		BeginTx []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Dest is the dest argument value.
			Dest any
		}
		// CheckDocumentCycle holds details about calls to the CheckDocumentCycle method.
		CheckDocumentCycle []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID xid.ID
			// ParentID is the parentID argument value.
			ParentID xid.ID
			// OrganizationID is the organizationID argument value.
			OrganizationID string
		}
		// CheckDocumentExists holds details about calls to the CheckDocumentExists method.
		CheckDocumentExists []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID xid.ID
			// OrganizationID is the organizationID argument value.
			OrganizationID string
		}
		// FetchDocument holds details about calls to the FetchDocument method.
		FetchDocument []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID xid.ID
			// OrganizationID is the organizationID argument value.
			OrganizationID string
			// BranchName is the branchName argument value.
			BranchName string
		}
		// FetchDocumentBranches holds details about calls to the FetchDocumentBranches method.
		FetchDocumentBranches []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// DocID is the docID argument value.
			DocID xid.ID
			// OrganizationID is the organizationID argument value.
			OrganizationID string
		}
		// FetchDocumentByBranchID holds details about calls to the FetchDocumentByBranchID method.
		FetchDocumentByBranchID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// BranchID is the branchID argument value.
			BranchID xid.ID
			// OrganizationID is the organizationID argument value.
			OrganizationID string
		}
		// FetchDocumentTree holds details about calls to the FetchDocumentTree method.
		FetchDocumentTree []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrganizationID is the organizationID argument value.
			OrganizationID string
		}
		// FetchDocumentTreeByDocumentParentID holds details about calls to the FetchDocumentTreeByDocumentParentID method.
		FetchDocumentTreeByDocumentParentID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ParentID is the parentID argument value.
			ParentID null.Value[xid.ID]
			// OrganizationID is the organizationID argument value.
			OrganizationID string
		}
		// UpdateDocumentParentID holds details about calls to the UpdateDocumentParentID method.
		UpdateDocumentParentID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID xid.ID
			// ParentID is the parentID argument value.
			ParentID null.Value[xid.ID]
			// OrganizationID is the organizationID argument value.
			OrganizationID string
		}
		// FetchDataSource holds details about calls to the FetchDataSource method.
		FetchDataSource []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Id is the id argument value.
			Id xid.ID
			// OrganizationID is the organizationID argument value.
			OrganizationID string
		}
		// FetchDataSources holds details about calls to the FetchDataSources method.
		FetchDataSources []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrganizationID is the organizationID argument value.
			OrganizationID string
		}
		// FetchTagTree holds details about calls to the FetchTagTree method.
		FetchTagTree []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrganizationID is the organizationID argument value.
			OrganizationID string
			// UserID is the userID argument value.
			UserID string
		}
		// FetchBranchTags holds details about calls to the FetchBranchTags method.
		FetchBranchTags []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrganizationID is the organizationID argument value.
			OrganizationID string
			// DocumentID is the documentID argument value.
			DocumentID xid.ID
			// BranchID is the branchID argument value.
			BranchID xid.ID
		}
		// InsertTag holds details about calls to the InsertTag method.
		InsertTag []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// T is the t argument value.
			T tag.Tag
		}
		// UpdateTag holds details about calls to the UpdateTag method.
		UpdateTag []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrganizationID is the organizationID argument value.
			OrganizationID string
			// ID is the id argument value.
			ID xid.ID
			// Inp is the inp argument value.
			Inp tag.UpdateInput
		}
		// DeleteTag holds details about calls to the DeleteTag method.
		DeleteTag []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID xid.ID
			// OrganizationID is the organizationID argument value.
			OrganizationID string
		}
		// AssignBranchTag holds details about calls to the AssignBranchTag method.
		AssignBranchTag []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrganizationID is the organizationID argument value.
			OrganizationID string
			// DocumentID is the documentID argument value.
			DocumentID xid.ID
			// BranchID is the branchID argument value.
			BranchID xid.ID
			// TagID is the tagID argument value.
			TagID xid.ID
		}
		// UnassignBranchTag holds details about calls to the UnassignBranchTag method.
		UnassignBranchTag []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrganizationID is the organizationID argument value.
			OrganizationID string
			// DocumentID is the documentID argument value.
			DocumentID xid.ID
			// BranchID is the branchID argument value.
			BranchID xid.ID
			// TagID is the tagID argument value.
			TagID xid.ID
		}
		// UpdateTagTree holds details about calls to the UpdateTagTree method.
		UpdateTagTree []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Tree is the tree argument value.
			Tree tag.Summaries
			// OrganizationID is the organizationID argument value.
			OrganizationID string
		}
		// FetchDocumentHooksByBranchID holds details about calls to the FetchDocumentHooksByBranchID method.
		FetchDocumentHooksByBranchID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// BranchID is the branchID argument value.
			BranchID xid.ID
			// OrganizationID is the organizationID argument value.
			OrganizationID string
		}
		// FetchDocumentHook holds details about calls to the FetchDocumentHook method.
		FetchDocumentHook []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID xid.ID
			// OrganizationID is the organizationID argument value.
			OrganizationID string
		}
		// InsertDocumentHook holds details about calls to the InsertDocumentHook method.
		InsertDocumentHook []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Hk is the hk argument value.
			Hk hookCore.Hook
		}
		// UpdateDocumentHook holds details about calls to the UpdateDocumentHook method.
		UpdateDocumentHook []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Hk is the hk argument value.
			Hk hookCore.Hook
		}
		// DeleteDocumentHook holds details about calls to the DeleteDocumentHook method.
		DeleteDocumentHook []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID xid.ID
		}
	}
	lockBeginTx                             sync.RWMutex
	lockCheckDocumentCycle                  sync.RWMutex
	lockCheckDocumentExists                 sync.RWMutex
	lockFetchDocument                       sync.RWMutex
	lockFetchDocumentBranches               sync.RWMutex
	lockFetchDocumentByBranchID             sync.RWMutex
	lockFetchDocumentTree                   sync.RWMutex
	lockFetchDocumentTreeByDocumentParentID sync.RWMutex
	lockUpdateDocumentParentID              sync.RWMutex
	lockFetchDataSource                     sync.RWMutex
	lockFetchDataSources                    sync.RWMutex
	lockFetchTagTree                        sync.RWMutex
	lockFetchBranchTags                     sync.RWMutex
	lockInsertTag                           sync.RWMutex
	lockUpdateTag                           sync.RWMutex
	lockDeleteTag                           sync.RWMutex
	lockAssignBranchTag                     sync.RWMutex
	lockUnassignBranchTag                   sync.RWMutex
	lockUpdateTagTree                       sync.RWMutex
	lockFetchDocumentHooksByBranchID        sync.RWMutex
	lockFetchDocumentHook                   sync.RWMutex
	lockInsertDocumentHook                  sync.RWMutex
	lockUpdateDocumentHook                  sync.RWMutex
	lockDeleteDocumentHook                  sync.RWMutex
}

// BeginTx calls BeginTxFunc.
func (mock *DB) BeginTx(ctx context.Context, dest any) error {
	callInfo := struct {
		Ctx  context.Context
		Dest any
	}{
		Ctx:  ctx,
		Dest: dest,
	}
	mock.lockBeginTx.Lock()
	mock.calls.BeginTx = append(mock.calls.BeginTx, callInfo)
	mock.lockBeginTx.Unlock()
	if mock.BeginTxFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.BeginTxFunc(ctx, dest)
}

// BeginTxCalls gets all the calls that were made to BeginTx.
// Check the length with:
//
//	len(mockedDB.BeginTxCalls())
func (mock *DB) BeginTxCalls() []struct {
	Ctx  context.Context
	Dest any
} {
	var calls []struct {
		Ctx  context.Context
		Dest any
	}
	mock.lockBeginTx.RLock()
	calls = mock.calls.BeginTx
	mock.lockBeginTx.RUnlock()
	return calls
}

// CheckDocumentCycle calls CheckDocumentCycleFunc.
func (mock *DB) CheckDocumentCycle(ctx context.Context, id xid.ID, parentID xid.ID, organizationID string) (bool, error) {
	callInfo := struct {
		Ctx            context.Context
		ID             xid.ID
		ParentID       xid.ID
		OrganizationID string
	}{
		Ctx:            ctx,
		ID:             id,
		ParentID:       parentID,
		OrganizationID: organizationID,
	}
	mock.lockCheckDocumentCycle.Lock()
	mock.calls.CheckDocumentCycle = append(mock.calls.CheckDocumentCycle, callInfo)
	mock.lockCheckDocumentCycle.Unlock()
	if mock.CheckDocumentCycleFunc == nil {
		var (
			bOut   bool
			errOut error
		)
		return bOut, errOut
	}
	return mock.CheckDocumentCycleFunc(ctx, id, parentID, organizationID)
}

// CheckDocumentCycleCalls gets all the calls that were made to CheckDocumentCycle.
// Check the length with:
//
//	len(mockedDB.CheckDocumentCycleCalls())
func (mock *DB) CheckDocumentCycleCalls() []struct {
	Ctx            context.Context
	ID             xid.ID
	ParentID       xid.ID
	OrganizationID string
} {
	var calls []struct {
		Ctx            context.Context
		ID             xid.ID
		ParentID       xid.ID
		OrganizationID string
	}
	mock.lockCheckDocumentCycle.RLock()
	calls = mock.calls.CheckDocumentCycle
	mock.lockCheckDocumentCycle.RUnlock()
	return calls
}

// CheckDocumentExists calls CheckDocumentExistsFunc.
func (mock *DB) CheckDocumentExists(ctx context.Context, id xid.ID, organizationID string) error {
	callInfo := struct {
		Ctx            context.Context
		ID             xid.ID
		OrganizationID string
	}{
		Ctx:            ctx,
		ID:             id,
		OrganizationID: organizationID,
	}
	mock.lockCheckDocumentExists.Lock()
	mock.calls.CheckDocumentExists = append(mock.calls.CheckDocumentExists, callInfo)
	mock.lockCheckDocumentExists.Unlock()
	if mock.CheckDocumentExistsFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.CheckDocumentExistsFunc(ctx, id, organizationID)
}

// CheckDocumentExistsCalls gets all the calls that were made to CheckDocumentExists.
// Check the length with:
//
//	len(mockedDB.CheckDocumentExistsCalls())
func (mock *DB) CheckDocumentExistsCalls() []struct {
	Ctx            context.Context
	ID             xid.ID
	OrganizationID string
} {
	var calls []struct {
		Ctx            context.Context
		ID             xid.ID
		OrganizationID string
	}
	mock.lockCheckDocumentExists.RLock()
	calls = mock.calls.CheckDocumentExists
	mock.lockCheckDocumentExists.RUnlock()
	return calls
}

// FetchDocument calls FetchDocumentFunc.
func (mock *DB) FetchDocument(ctx context.Context, id xid.ID, organizationID string, branchName string) (*document.Document, error) {
	callInfo := struct {
		Ctx            context.Context
		ID             xid.ID
		OrganizationID string
		BranchName     string
	}{
		Ctx:            ctx,
		ID:             id,
		OrganizationID: organizationID,
		BranchName:     branchName,
	}
	mock.lockFetchDocument.Lock()
	mock.calls.FetchDocument = append(mock.calls.FetchDocument, callInfo)
	mock.lockFetchDocument.Unlock()
	if mock.FetchDocumentFunc == nil {
		var (
			documentOut *document.Document
			errOut      error
		)
		return documentOut, errOut
	}
	return mock.FetchDocumentFunc(ctx, id, organizationID, branchName)
}

// FetchDocumentCalls gets all the calls that were made to FetchDocument.
// Check the length with:
//
//	len(mockedDB.FetchDocumentCalls())
func (mock *DB) FetchDocumentCalls() []struct {
	Ctx            context.Context
	ID             xid.ID
	OrganizationID string
	BranchName     string
} {
	var calls []struct {
		Ctx            context.Context
		ID             xid.ID
		OrganizationID string
		BranchName     string
	}
	mock.lockFetchDocument.RLock()
	calls = mock.calls.FetchDocument
	mock.lockFetchDocument.RUnlock()
	return calls
}

// FetchDocumentBranches calls FetchDocumentBranchesFunc.
func (mock *DB) FetchDocumentBranches(ctx context.Context, docID xid.ID, organizationID string) ([]document.BranchSummary, error) {
	callInfo := struct {
		Ctx            context.Context
		DocID          xid.ID
		OrganizationID string
	}{
		Ctx:            ctx,
		DocID:          docID,
		OrganizationID: organizationID,
	}
	mock.lockFetchDocumentBranches.Lock()
	mock.calls.FetchDocumentBranches = append(mock.calls.FetchDocumentBranches, callInfo)
	mock.lockFetchDocumentBranches.Unlock()
	if mock.FetchDocumentBranchesFunc == nil {
		var (
			branchSummarysOut []document.BranchSummary
			errOut            error
		)
		return branchSummarysOut, errOut
	}
	return mock.FetchDocumentBranchesFunc(ctx, docID, organizationID)
}

// FetchDocumentBranchesCalls gets all the calls that were made to FetchDocumentBranches.
// Check the length with:
//
//	len(mockedDB.FetchDocumentBranchesCalls())
func (mock *DB) FetchDocumentBranchesCalls() []struct {
	Ctx            context.Context
	DocID          xid.ID
	OrganizationID string
} {
	var calls []struct {
		Ctx            context.Context
		DocID          xid.ID
		OrganizationID string
	}
	mock.lockFetchDocumentBranches.RLock()
	calls = mock.calls.FetchDocumentBranches
	mock.lockFetchDocumentBranches.RUnlock()
	return calls
}

// FetchDocumentByBranchID calls FetchDocumentByBranchIDFunc.
func (mock *DB) FetchDocumentByBranchID(ctx context.Context, branchID xid.ID, organizationID string) (*document.Document, error) {
	callInfo := struct {
		Ctx            context.Context
		BranchID       xid.ID
		OrganizationID string
	}{
		Ctx:            ctx,
		BranchID:       branchID,
		OrganizationID: organizationID,
	}
	mock.lockFetchDocumentByBranchID.Lock()
	mock.calls.FetchDocumentByBranchID = append(mock.calls.FetchDocumentByBranchID, callInfo)
	mock.lockFetchDocumentByBranchID.Unlock()
	if mock.FetchDocumentByBranchIDFunc == nil {
		var (
			documentOut *document.Document
			errOut      error
		)
		return documentOut, errOut
	}
	return mock.FetchDocumentByBranchIDFunc(ctx, branchID, organizationID)
}

// FetchDocumentByBranchIDCalls gets all the calls that were made to FetchDocumentByBranchID.
// Check the length with:
//
//	len(mockedDB.FetchDocumentByBranchIDCalls())
func (mock *DB) FetchDocumentByBranchIDCalls() []struct {
	Ctx            context.Context
	BranchID       xid.ID
	OrganizationID string
} {
	var calls []struct {
		Ctx            context.Context
		BranchID       xid.ID
		OrganizationID string
	}
	mock.lockFetchDocumentByBranchID.RLock()
	calls = mock.calls.FetchDocumentByBranchID
	mock.lockFetchDocumentByBranchID.RUnlock()
	return calls
}

// FetchDocumentTree calls FetchDocumentTreeFunc.
func (mock *DB) FetchDocumentTree(ctx context.Context, organizationID string) (document.Summaries, error) {
	callInfo := struct {
		Ctx            context.Context
		OrganizationID string
	}{
		Ctx:            ctx,
		OrganizationID: organizationID,
	}
	mock.lockFetchDocumentTree.Lock()
	mock.calls.FetchDocumentTree = append(mock.calls.FetchDocumentTree, callInfo)
	mock.lockFetchDocumentTree.Unlock()
	if mock.FetchDocumentTreeFunc == nil {
		var (
			summariesOut document.Summaries
			errOut       error
		)
		return summariesOut, errOut
	}
	return mock.FetchDocumentTreeFunc(ctx, organizationID)
}

// FetchDocumentTreeCalls gets all the calls that were made to FetchDocumentTree.
// Check the length with:
//
//	len(mockedDB.FetchDocumentTreeCalls())
func (mock *DB) FetchDocumentTreeCalls() []struct {
	Ctx            context.Context
	OrganizationID string
} {
	var calls []struct {
		Ctx            context.Context
		OrganizationID string
	}
	mock.lockFetchDocumentTree.RLock()
	calls = mock.calls.FetchDocumentTree
	mock.lockFetchDocumentTree.RUnlock()
	return calls
}

// FetchDocumentTreeByDocumentParentID calls FetchDocumentTreeByDocumentParentIDFunc.
func (mock *DB) FetchDocumentTreeByDocumentParentID(ctx context.Context, parentID null.Value[xid.ID], organizationID string) (document.Summaries, error) {
	callInfo := struct {
		Ctx            context.Context
		ParentID       null.Value[xid.ID]
		OrganizationID string
	}{
		Ctx:            ctx,
		ParentID:       parentID,
		OrganizationID: organizationID,
	}
	mock.lockFetchDocumentTreeByDocumentParentID.Lock()
	mock.calls.FetchDocumentTreeByDocumentParentID = append(mock.calls.FetchDocumentTreeByDocumentParentID, callInfo)
	mock.lockFetchDocumentTreeByDocumentParentID.Unlock()
	if mock.FetchDocumentTreeByDocumentParentIDFunc == nil {
		var (
			summariesOut document.Summaries
			errOut       error
		)
		return summariesOut, errOut
	}
	return mock.FetchDocumentTreeByDocumentParentIDFunc(ctx, parentID, organizationID)
}

// FetchDocumentTreeByDocumentParentIDCalls gets all the calls that were made to FetchDocumentTreeByDocumentParentID.
// Check the length with:
//
//	len(mockedDB.FetchDocumentTreeByDocumentParentIDCalls())
func (mock *DB) FetchDocumentTreeByDocumentParentIDCalls() []struct {
	Ctx            context.Context
	ParentID       null.Value[xid.ID]
	OrganizationID string
} {
	var calls []struct {
		Ctx            context.Context
		ParentID       null.Value[xid.ID]
		OrganizationID string
	}
	mock.lockFetchDocumentTreeByDocumentParentID.RLock()
	calls = mock.calls.FetchDocumentTreeByDocumentParentID
	mock.lockFetchDocumentTreeByDocumentParentID.RUnlock()
	return calls
}

// UpdateDocumentParentID calls UpdateDocumentParentIDFunc.
func (mock *DB) UpdateDocumentParentID(ctx context.Context, id xid.ID, parentID null.Value[xid.ID], organizationID string) error {
	callInfo := struct {
		Ctx            context.Context
		ID             xid.ID
		ParentID       null.Value[xid.ID]
		OrganizationID string
	}{
		Ctx:            ctx,
		ID:             id,
		ParentID:       parentID,
		OrganizationID: organizationID,
	}
	mock.lockUpdateDocumentParentID.Lock()
	mock.calls.UpdateDocumentParentID = append(mock.calls.UpdateDocumentParentID, callInfo)
	mock.lockUpdateDocumentParentID.Unlock()
	if mock.UpdateDocumentParentIDFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.UpdateDocumentParentIDFunc(ctx, id, parentID, organizationID)
}

// UpdateDocumentParentIDCalls gets all the calls that were made to UpdateDocumentParentID.
// Check the length with:
//
//	len(mockedDB.UpdateDocumentParentIDCalls())
func (mock *DB) UpdateDocumentParentIDCalls() []struct {
	Ctx            context.Context
	ID             xid.ID
	ParentID       null.Value[xid.ID]
	OrganizationID string
} {
	var calls []struct {
		Ctx            context.Context
		ID             xid.ID
		ParentID       null.Value[xid.ID]
		OrganizationID string
	}
	mock.lockUpdateDocumentParentID.RLock()
	calls = mock.calls.UpdateDocumentParentID
	mock.lockUpdateDocumentParentID.RUnlock()
	return calls
}

// FetchDataSource calls FetchDataSourceFunc.
func (mock *DB) FetchDataSource(ctx context.Context, id xid.ID, organizationID string) (*datasource.DataSource, error) {
	callInfo := struct {
		Ctx            context.Context
		Id             xid.ID
		OrganizationID string
	}{
		Ctx:            ctx,
		Id:             id,
		OrganizationID: organizationID,
	}
	mock.lockFetchDataSource.Lock()
	mock.calls.FetchDataSource = append(mock.calls.FetchDataSource, callInfo)
	mock.lockFetchDataSource.Unlock()
	if mock.FetchDataSourceFunc == nil {
		var (
			dataSourceOut *datasource.DataSource
			errOut        error
		)
		return dataSourceOut, errOut
	}
	return mock.FetchDataSourceFunc(ctx, id, organizationID)
}

// FetchDataSourceCalls gets all the calls that were made to FetchDataSource.
// Check the length with:
//
//	len(mockedDB.FetchDataSourceCalls())
func (mock *DB) FetchDataSourceCalls() []struct {
	Ctx            context.Context
	Id             xid.ID
	OrganizationID string
} {
	var calls []struct {
		Ctx            context.Context
		Id             xid.ID
		OrganizationID string
	}
	mock.lockFetchDataSource.RLock()
	calls = mock.calls.FetchDataSource
	mock.lockFetchDataSource.RUnlock()
	return calls
}

// FetchDataSources calls FetchDataSourcesFunc.
func (mock *DB) FetchDataSources(ctx context.Context, organizationID string) ([]datasource.DataSource, error) {
	callInfo := struct {
		Ctx            context.Context
		OrganizationID string
	}{
		Ctx:            ctx,
		OrganizationID: organizationID,
	}
	mock.lockFetchDataSources.Lock()
	mock.calls.FetchDataSources = append(mock.calls.FetchDataSources, callInfo)
	mock.lockFetchDataSources.Unlock()
	if mock.FetchDataSourcesFunc == nil {
		var (
			dataSourcesOut []datasource.DataSource
			errOut         error
		)
		return dataSourcesOut, errOut
	}
	return mock.FetchDataSourcesFunc(ctx, organizationID)
}

// FetchDataSourcesCalls gets all the calls that were made to FetchDataSources.
// Check the length with:
//
//	len(mockedDB.FetchDataSourcesCalls())
func (mock *DB) FetchDataSourcesCalls() []struct {
	Ctx            context.Context
	OrganizationID string
} {
	var calls []struct {
		Ctx            context.Context
		OrganizationID string
	}
	mock.lockFetchDataSources.RLock()
	calls = mock.calls.FetchDataSources
	mock.lockFetchDataSources.RUnlock()
	return calls
}

// FetchTagTree calls FetchTagTreeFunc.
func (mock *DB) FetchTagTree(ctx context.Context, organizationID string, userID string) (tag.Summaries, error) {
	callInfo := struct {
		Ctx            context.Context
		OrganizationID string
		UserID         string
	}{
		Ctx:            ctx,
		OrganizationID: organizationID,
		UserID:         userID,
	}
	mock.lockFetchTagTree.Lock()
	mock.calls.FetchTagTree = append(mock.calls.FetchTagTree, callInfo)
	mock.lockFetchTagTree.Unlock()
	if mock.FetchTagTreeFunc == nil {
		var (
			summariesOut tag.Summaries
			errOut       error
		)
		return summariesOut, errOut
	}
	return mock.FetchTagTreeFunc(ctx, organizationID, userID)
}

// FetchTagTreeCalls gets all the calls that were made to FetchTagTree.
// Check the length with:
//
//	len(mockedDB.FetchTagTreeCalls())
func (mock *DB) FetchTagTreeCalls() []struct {
	Ctx            context.Context
	OrganizationID string
	UserID         string
} {
	var calls []struct {
		Ctx            context.Context
		OrganizationID string
		UserID         string
	}
	mock.lockFetchTagTree.RLock()
	calls = mock.calls.FetchTagTree
	mock.lockFetchTagTree.RUnlock()
	return calls
}

// FetchBranchTags calls FetchBranchTagsFunc.
func (mock *DB) FetchBranchTags(ctx context.Context, organizationID string, documentID xid.ID, branchID xid.ID) ([]tag.Tag, error) {
	callInfo := struct {
		Ctx            context.Context
		OrganizationID string
		DocumentID     xid.ID
		BranchID       xid.ID
	}{
		Ctx:            ctx,
		OrganizationID: organizationID,
		DocumentID:     documentID,
		BranchID:       branchID,
	}
	mock.lockFetchBranchTags.Lock()
	mock.calls.FetchBranchTags = append(mock.calls.FetchBranchTags, callInfo)
	mock.lockFetchBranchTags.Unlock()
	if mock.FetchBranchTagsFunc == nil {
		var (
			tagsOut []tag.Tag
			errOut  error
		)
		return tagsOut, errOut
	}
	return mock.FetchBranchTagsFunc(ctx, organizationID, documentID, branchID)
}

// FetchBranchTagsCalls gets all the calls that were made to FetchBranchTags.
// Check the length with:
//
//	len(mockedDB.FetchBranchTagsCalls())
func (mock *DB) FetchBranchTagsCalls() []struct {
	Ctx            context.Context
	OrganizationID string
	DocumentID     xid.ID
	BranchID       xid.ID
} {
	var calls []struct {
		Ctx            context.Context
		OrganizationID string
		DocumentID     xid.ID
		BranchID       xid.ID
	}
	mock.lockFetchBranchTags.RLock()
	calls = mock.calls.FetchBranchTags
	mock.lockFetchBranchTags.RUnlock()
	return calls
}

// InsertTag calls InsertTagFunc.
func (mock *DB) InsertTag(ctx context.Context, t tag.Tag) error {
	callInfo := struct {
		Ctx context.Context
		T   tag.Tag
	}{
		Ctx: ctx,
		T:   t,
	}
	mock.lockInsertTag.Lock()
	mock.calls.InsertTag = append(mock.calls.InsertTag, callInfo)
	mock.lockInsertTag.Unlock()
	if mock.InsertTagFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.InsertTagFunc(ctx, t)
}

// InsertTagCalls gets all the calls that were made to InsertTag.
// Check the length with:
//
//	len(mockedDB.InsertTagCalls())
func (mock *DB) InsertTagCalls() []struct {
	Ctx context.Context
	T   tag.Tag
} {
	var calls []struct {
		Ctx context.Context
		T   tag.Tag
	}
	mock.lockInsertTag.RLock()
	calls = mock.calls.InsertTag
	mock.lockInsertTag.RUnlock()
	return calls
}

// UpdateTag calls UpdateTagFunc.
func (mock *DB) UpdateTag(ctx context.Context, organizationID string, id xid.ID, inp tag.UpdateInput) error {
	callInfo := struct {
		Ctx            context.Context
		OrganizationID string
		ID             xid.ID
		Inp            tag.UpdateInput
	}{
		Ctx:            ctx,
		OrganizationID: organizationID,
		ID:             id,
		Inp:            inp,
	}
	mock.lockUpdateTag.Lock()
	mock.calls.UpdateTag = append(mock.calls.UpdateTag, callInfo)
	mock.lockUpdateTag.Unlock()
	if mock.UpdateTagFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.UpdateTagFunc(ctx, organizationID, id, inp)
}

// UpdateTagCalls gets all the calls that were made to UpdateTag.
// Check the length with:
//
//	len(mockedDB.UpdateTagCalls())
func (mock *DB) UpdateTagCalls() []struct {
	Ctx            context.Context
	OrganizationID string
	ID             xid.ID
	Inp            tag.UpdateInput
} {
	var calls []struct {
		Ctx            context.Context
		OrganizationID string
		ID             xid.ID
		Inp            tag.UpdateInput
	}
	mock.lockUpdateTag.RLock()
	calls = mock.calls.UpdateTag
	mock.lockUpdateTag.RUnlock()
	return calls
}

// DeleteTag calls DeleteTagFunc.
func (mock *DB) DeleteTag(ctx context.Context, id xid.ID, organizationID string) error {
	callInfo := struct {
		Ctx            context.Context
		ID             xid.ID
		OrganizationID string
	}{
		Ctx:            ctx,
		ID:             id,
		OrganizationID: organizationID,
	}
	mock.lockDeleteTag.Lock()
	mock.calls.DeleteTag = append(mock.calls.DeleteTag, callInfo)
	mock.lockDeleteTag.Unlock()
	if mock.DeleteTagFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.DeleteTagFunc(ctx, id, organizationID)
}

// DeleteTagCalls gets all the calls that were made to DeleteTag.
// Check the length with:
//
//	len(mockedDB.DeleteTagCalls())
func (mock *DB) DeleteTagCalls() []struct {
	Ctx            context.Context
	ID             xid.ID
	OrganizationID string
} {
	var calls []struct {
		Ctx            context.Context
		ID             xid.ID
		OrganizationID string
	}
	mock.lockDeleteTag.RLock()
	calls = mock.calls.DeleteTag
	mock.lockDeleteTag.RUnlock()
	return calls
}

// AssignBranchTag calls AssignBranchTagFunc.
func (mock *DB) AssignBranchTag(ctx context.Context, organizationID string, documentID xid.ID, branchID xid.ID, tagID xid.ID) error {
	callInfo := struct {
		Ctx            context.Context
		OrganizationID string
		DocumentID     xid.ID
		BranchID       xid.ID
		TagID          xid.ID
	}{
		Ctx:            ctx,
		OrganizationID: organizationID,
		DocumentID:     documentID,
		BranchID:       branchID,
		TagID:          tagID,
	}
	mock.lockAssignBranchTag.Lock()
	mock.calls.AssignBranchTag = append(mock.calls.AssignBranchTag, callInfo)
	mock.lockAssignBranchTag.Unlock()
	if mock.AssignBranchTagFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.AssignBranchTagFunc(ctx, organizationID, documentID, branchID, tagID)
}

// AssignBranchTagCalls gets all the calls that were made to AssignBranchTag.
// Check the length with:
//
//	len(mockedDB.AssignBranchTagCalls())
func (mock *DB) AssignBranchTagCalls() []struct {
	Ctx            context.Context
	OrganizationID string
	DocumentID     xid.ID
	BranchID       xid.ID
	TagID          xid.ID
} {
	var calls []struct {
		Ctx            context.Context
		OrganizationID string
		DocumentID     xid.ID
		BranchID       xid.ID
		TagID          xid.ID
	}
	mock.lockAssignBranchTag.RLock()
	calls = mock.calls.AssignBranchTag
	mock.lockAssignBranchTag.RUnlock()
	return calls
}

// UnassignBranchTag calls UnassignBranchTagFunc.
func (mock *DB) UnassignBranchTag(ctx context.Context, organizationID string, documentID xid.ID, branchID xid.ID, tagID xid.ID) error {
	callInfo := struct {
		Ctx            context.Context
		OrganizationID string
		DocumentID     xid.ID
		BranchID       xid.ID
		TagID          xid.ID
	}{
		Ctx:            ctx,
		OrganizationID: organizationID,
		DocumentID:     documentID,
		BranchID:       branchID,
		TagID:          tagID,
	}
	mock.lockUnassignBranchTag.Lock()
	mock.calls.UnassignBranchTag = append(mock.calls.UnassignBranchTag, callInfo)
	mock.lockUnassignBranchTag.Unlock()
	if mock.UnassignBranchTagFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.UnassignBranchTagFunc(ctx, organizationID, documentID, branchID, tagID)
}

// UnassignBranchTagCalls gets all the calls that were made to UnassignBranchTag.
// Check the length with:
//
//	len(mockedDB.UnassignBranchTagCalls())
func (mock *DB) UnassignBranchTagCalls() []struct {
	Ctx            context.Context
	OrganizationID string
	DocumentID     xid.ID
	BranchID       xid.ID
	TagID          xid.ID
} {
	var calls []struct {
		Ctx            context.Context
		OrganizationID string
		DocumentID     xid.ID
		BranchID       xid.ID
		TagID          xid.ID
	}
	mock.lockUnassignBranchTag.RLock()
	calls = mock.calls.UnassignBranchTag
	mock.lockUnassignBranchTag.RUnlock()
	return calls
}

// UpdateTagTree calls UpdateTagTreeFunc.
func (mock *DB) UpdateTagTree(ctx context.Context, tree tag.Summaries, organizationID string) error {
	callInfo := struct {
		Ctx            context.Context
		Tree           tag.Summaries
		OrganizationID string
	}{
		Ctx:            ctx,
		Tree:           tree,
		OrganizationID: organizationID,
	}
	mock.lockUpdateTagTree.Lock()
	mock.calls.UpdateTagTree = append(mock.calls.UpdateTagTree, callInfo)
	mock.lockUpdateTagTree.Unlock()
	if mock.UpdateTagTreeFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.UpdateTagTreeFunc(ctx, tree, organizationID)
}

// UpdateTagTreeCalls gets all the calls that were made to UpdateTagTree.
// Check the length with:
//
//	len(mockedDB.UpdateTagTreeCalls())
func (mock *DB) UpdateTagTreeCalls() []struct {
	Ctx            context.Context
	Tree           tag.Summaries
	OrganizationID string
} {
	var calls []struct {
		Ctx            context.Context
		Tree           tag.Summaries
		OrganizationID string
	}
	mock.lockUpdateTagTree.RLock()
	calls = mock.calls.UpdateTagTree
	mock.lockUpdateTagTree.RUnlock()
	return calls
}

// FetchDocumentHooksByBranchID calls FetchDocumentHooksByBranchIDFunc.
func (mock *DB) FetchDocumentHooksByBranchID(ctx context.Context, branchID xid.ID, organizationID string) ([]hookCore.Hook, error) {
	callInfo := struct {
		Ctx            context.Context
		BranchID       xid.ID
		OrganizationID string
	}{
		Ctx:            ctx,
		BranchID:       branchID,
		OrganizationID: organizationID,
	}
	mock.lockFetchDocumentHooksByBranchID.Lock()
	mock.calls.FetchDocumentHooksByBranchID = append(mock.calls.FetchDocumentHooksByBranchID, callInfo)
	mock.lockFetchDocumentHooksByBranchID.Unlock()
	if mock.FetchDocumentHooksByBranchIDFunc == nil {
		var (
			hooksOut []hookCore.Hook
			errOut   error
		)
		return hooksOut, errOut
	}
	return mock.FetchDocumentHooksByBranchIDFunc(ctx, branchID, organizationID)
}

// FetchDocumentHooksByBranchIDCalls gets all the calls that were made to FetchDocumentHooksByBranchID.
// Check the length with:
//
//	len(mockedDB.FetchDocumentHooksByBranchIDCalls())
func (mock *DB) FetchDocumentHooksByBranchIDCalls() []struct {
	Ctx            context.Context
	BranchID       xid.ID
	OrganizationID string
} {
	var calls []struct {
		Ctx            context.Context
		BranchID       xid.ID
		OrganizationID string
	}
	mock.lockFetchDocumentHooksByBranchID.RLock()
	calls = mock.calls.FetchDocumentHooksByBranchID
	mock.lockFetchDocumentHooksByBranchID.RUnlock()
	return calls
}

// FetchDocumentHook calls FetchDocumentHookFunc.
func (mock *DB) FetchDocumentHook(ctx context.Context, id xid.ID, organizationID string) (*hookCore.Hook, error) {
	callInfo := struct {
		Ctx            context.Context
		ID             xid.ID
		OrganizationID string
	}{
		Ctx:            ctx,
		ID:             id,
		OrganizationID: organizationID,
	}
	mock.lockFetchDocumentHook.Lock()
	mock.calls.FetchDocumentHook = append(mock.calls.FetchDocumentHook, callInfo)
	mock.lockFetchDocumentHook.Unlock()
	if mock.FetchDocumentHookFunc == nil {
		var (
			hookOut *hookCore.Hook
			errOut  error
		)
		return hookOut, errOut
	}
	return mock.FetchDocumentHookFunc(ctx, id, organizationID)
}

// FetchDocumentHookCalls gets all the calls that were made to FetchDocumentHook.
// Check the length with:
//
//	len(mockedDB.FetchDocumentHookCalls())
func (mock *DB) FetchDocumentHookCalls() []struct {
	Ctx            context.Context
	ID             xid.ID
	OrganizationID string
} {
	var calls []struct {
		Ctx            context.Context
		ID             xid.ID
		OrganizationID string
	}
	mock.lockFetchDocumentHook.RLock()
	calls = mock.calls.FetchDocumentHook
	mock.lockFetchDocumentHook.RUnlock()
	return calls
}

// InsertDocumentHook calls InsertDocumentHookFunc.
func (mock *DB) InsertDocumentHook(ctx context.Context, hk hookCore.Hook) error {
	callInfo := struct {
		Ctx context.Context
		Hk  hookCore.Hook
	}{
		Ctx: ctx,
		Hk:  hk,
	}
	mock.lockInsertDocumentHook.Lock()
	mock.calls.InsertDocumentHook = append(mock.calls.InsertDocumentHook, callInfo)
	mock.lockInsertDocumentHook.Unlock()
	if mock.InsertDocumentHookFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.InsertDocumentHookFunc(ctx, hk)
}

// InsertDocumentHookCalls gets all the calls that were made to InsertDocumentHook.
// Check the length with:
//
//	len(mockedDB.InsertDocumentHookCalls())
func (mock *DB) InsertDocumentHookCalls() []struct {
	Ctx context.Context
	Hk  hookCore.Hook
} {
	var calls []struct {
		Ctx context.Context
		Hk  hookCore.Hook
	}
	mock.lockInsertDocumentHook.RLock()
	calls = mock.calls.InsertDocumentHook
	mock.lockInsertDocumentHook.RUnlock()
	return calls
}

// UpdateDocumentHook calls UpdateDocumentHookFunc.
func (mock *DB) UpdateDocumentHook(ctx context.Context, hk hookCore.Hook) error {
	callInfo := struct {
		Ctx context.Context
		Hk  hookCore.Hook
	}{
		Ctx: ctx,
		Hk:  hk,
	}
	mock.lockUpdateDocumentHook.Lock()
	mock.calls.UpdateDocumentHook = append(mock.calls.UpdateDocumentHook, callInfo)
	mock.lockUpdateDocumentHook.Unlock()
	if mock.UpdateDocumentHookFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.UpdateDocumentHookFunc(ctx, hk)
}

// UpdateDocumentHookCalls gets all the calls that were made to UpdateDocumentHook.
// Check the length with:
//
//	len(mockedDB.UpdateDocumentHookCalls())
func (mock *DB) UpdateDocumentHookCalls() []struct {
	Ctx context.Context
	Hk  hookCore.Hook
} {
	var calls []struct {
		Ctx context.Context
		Hk  hookCore.Hook
	}
	mock.lockUpdateDocumentHook.RLock()
	calls = mock.calls.UpdateDocumentHook
	mock.lockUpdateDocumentHook.RUnlock()
	return calls
}

// DeleteDocumentHook calls DeleteDocumentHookFunc.
func (mock *DB) DeleteDocumentHook(ctx context.Context, id xid.ID) error {
	callInfo := struct {
		Ctx context.Context
		ID  xid.ID
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockDeleteDocumentHook.Lock()
	mock.calls.DeleteDocumentHook = append(mock.calls.DeleteDocumentHook, callInfo)
	mock.lockDeleteDocumentHook.Unlock()
	if mock.DeleteDocumentHookFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.DeleteDocumentHookFunc(ctx, id)
}

// DeleteDocumentHookCalls gets all the calls that were made to DeleteDocumentHook.
// Check the length with:
//
//	len(mockedDB.DeleteDocumentHookCalls())
func (mock *DB) DeleteDocumentHookCalls() []struct {
	Ctx context.Context
	ID  xid.ID
} {
	var calls []struct {
		Ctx context.Context
		ID  xid.ID
	}
	mock.lockDeleteDocumentHook.RLock()
	calls = mock.calls.DeleteDocumentHook
	mock.lockDeleteDocumentHook.RUnlock()
	return calls
}
