// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"sync"

	"github.com/oxynote/oxynote/server/core/internal/assistant/edit"
	"github.com/oxynote/oxynote/server/core/internal/assistant/tools"
)

// Ensure, that EditApplier does implement tools.EditApplier.
// If this is not the case, regenerate this file with moq.
var _ tools.EditApplier = &EditApplier{}

// EditApplier is a mock implementation of tools.EditApplier.
//
//	func TestSomethingThatUsesEditApplier(t *testing.T) {
//
//		// make and configure a mocked tools.EditApplier
//		mockedEditApplier := &EditApplier{
//			ApplyFunc: func(ctx context.Context, documentID string, branchID string, ops []edit.Operation) (edit.Result, error) {
//				panic("mock out the Apply method")
//			},
//		}
//
//		// use mockedEditApplier in code that requires tools.EditApplier
//		// and then make assertions.
//
//	}
type EditApplier struct {
	// ApplyFunc mocks the Apply method.
	ApplyFunc func(ctx context.Context, documentID string, branchID string, ops []edit.Operation) (edit.Result, error)

	// calls tracks calls to the methods.
	calls struct {
		// Apply holds details about calls to the Apply method.
		Apply []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// DocumentID is the documentID argument value.
			DocumentID string
			// BranchID is the branchID argument value.
			BranchID string
			// Ops is the ops argument value.
			Ops []edit.Operation
		}
	}
	lockApply sync.RWMutex
}

// Apply calls ApplyFunc.
func (mock *EditApplier) Apply(ctx context.Context, documentID string, branchID string, ops []edit.Operation) (edit.Result, error) {
	callInfo := struct {
		Ctx        context.Context
		DocumentID string
		BranchID   string
		Ops        []edit.Operation
	}{
		Ctx:        ctx,
		DocumentID: documentID,
		BranchID:   branchID,
		Ops:        ops,
	}
	mock.lockApply.Lock()
	mock.calls.Apply = append(mock.calls.Apply, callInfo)
	mock.lockApply.Unlock()
	if mock.ApplyFunc == nil {
		var (
			resultOut edit.Result
			errOut    error
		)
		return resultOut, errOut
	}
	return mock.ApplyFunc(ctx, documentID, branchID, ops)
}

// ApplyCalls gets all the calls that were made to Apply.
// Check the length with:
//
//	len(mockedEditApplier.ApplyCalls())
func (mock *EditApplier) ApplyCalls() []struct {
	Ctx        context.Context
	DocumentID string
	BranchID   string
	Ops        []edit.Operation
} {
	var calls []struct {
		Ctx        context.Context
		DocumentID string
		BranchID   string
		Ops        []edit.Operation
	}
	mock.lockApply.RLock()
	calls = mock.calls.Apply
	mock.lockApply.RUnlock()
	return calls
}
