// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"sync"

	"github.com/oxynote/oxynote/server/core/internal/assistant/tools"
	"github.com/oxynote/oxynote/server/core/internal/search"
)

// Ensure, that Searcher does implement tools.Searcher.
// If this is not the case, regenerate this file with moq.
var _ tools.Searcher = &Searcher{}

// Searcher is a mock implementation of tools.Searcher.
//
//	func TestSomethingThatUsesSearcher(t *testing.T) {
//
//		// make and configure a mocked tools.Searcher
//		mockedSearcher := &Searcher{
//			SearchDocumentBlocksFunc: func(ctx context.Context, organizationID string, query string, limit int) ([]search.Block, error) {
//				panic("mock out the SearchDocumentBlocks method")
//			},
//		}
//
//		// use mockedSearcher in code that requires tools.Searcher
//		// and then make assertions.
//
//	}
type Searcher struct {
	// ConfiguredFunc mocks the Configured method.
	ConfiguredFunc func() bool

	// SearchDocumentBlocksFunc mocks the SearchDocumentBlocks method.
	SearchDocumentBlocksFunc func(ctx context.Context, organizationID string, query string, limit int) ([]search.Block, error)

	// calls tracks calls to the methods.
	calls struct {
		// Configured holds details about calls to the Configured method.
		Configured []struct {
		}
		// SearchDocumentBlocks holds details about calls to the SearchDocumentBlocks method.
		SearchDocumentBlocks []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrganizationID is the organizationID argument value.
			OrganizationID string
			// Query is the query argument value.
			Query string
			// Limit is the limit argument value.
			Limit int
		}
	}
	lockConfigured           sync.RWMutex
	lockSearchDocumentBlocks sync.RWMutex
}

// SearchDocumentBlocks calls SearchDocumentBlocksFunc.
func (mock *Searcher) SearchDocumentBlocks(ctx context.Context, organizationID string, query string, limit int) ([]search.Block, error) {
	callInfo := struct {
		Ctx            context.Context
		OrganizationID string
		Query          string
		Limit          int
	}{
		Ctx:            ctx,
		OrganizationID: organizationID,
		Query:          query,
		Limit:          limit,
	}
	mock.lockSearchDocumentBlocks.Lock()
	mock.calls.SearchDocumentBlocks = append(mock.calls.SearchDocumentBlocks, callInfo)
	mock.lockSearchDocumentBlocks.Unlock()
	if mock.SearchDocumentBlocksFunc == nil {
		var (
			blocksOut []search.Block
			errOut    error
		)
		return blocksOut, errOut
	}
	return mock.SearchDocumentBlocksFunc(ctx, organizationID, query, limit)
}

// SearchDocumentBlocksCalls gets all the calls that were made to SearchDocumentBlocks.
// Check the length with:
//
//	len(mockedSearcher.SearchDocumentBlocksCalls())
func (mock *Searcher) SearchDocumentBlocksCalls() []struct {
	Ctx            context.Context
	OrganizationID string
	Query          string
	Limit          int
} {
	var calls []struct {
		Ctx            context.Context
		OrganizationID string
		Query          string
		Limit          int
	}
	mock.lockSearchDocumentBlocks.RLock()
	calls = mock.calls.SearchDocumentBlocks
	mock.lockSearchDocumentBlocks.RUnlock()
	return calls
}

// Configured calls ConfiguredFunc.
func (mock *Searcher) Configured() bool {
	callInfo := struct {
	}{}
	mock.lockConfigured.Lock()
	mock.calls.Configured = append(mock.calls.Configured, callInfo)
	mock.lockConfigured.Unlock()
	if mock.ConfiguredFunc == nil {
		var (
			bOut bool
		)
		return bOut
	}
	return mock.ConfiguredFunc()
}

// ConfiguredCalls gets all the calls that were made to Configured.
// Check the length with:
//
//	len(mockedSearcher.ConfiguredCalls())
func (mock *Searcher) ConfiguredCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockConfigured.RLock()
	calls = mock.calls.Configured
	mock.lockConfigured.RUnlock()
	return calls
}
