// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package notification

import (
	"context"
	"sync"

	notificationCore "github.com/oxynote/oxynote/server/core/internal/notification"
	"github.com/oxynote/oxynote/server/core/pkg/httpserver"
	"github.com/rs/xid"
)

// Ensure, that DBMock does implement DB.
// If this is not the case, regenerate this file with moq.
var _ DB = &DBMock{}

// DBMock is a mock implementation of DB.
//
//	func TestSomethingThatUsesDB(t *testing.T) {
//
//		// make and configure a mocked DB
//		mockedDB := &DBMock{
//			FetchManyNotificationsFunc: func(ctx context.Context, organizationID string, userID string, qr httpserver.Query) ([]*notificationCore.Notification, uint64, error) {
//				panic("mock out the FetchManyNotifications method")
//			},
//			FetchNotificationCountFunc: func(ctx context.Context, organizationID string, userID string, read bool) (uint64, error) {
//				panic("mock out the FetchNotificationCount method")
//			},
//			MarkReadByNotificationsIDsFunc: func(ctx context.Context, organizationID string, userID string, ids []xid.ID) error {
//				panic("mock out the MarkReadByNotificationsIDs method")
//			},
//		}
//
//		// use mockedDB in code that requires DB
//		// and then make assertions.
//
//	}
type DBMock struct {
	// FetchManyNotificationsFunc mocks the FetchManyNotifications method.
	FetchManyNotificationsFunc func(ctx context.Context, organizationID string, userID string, qr httpserver.Query) ([]*notificationCore.Notification, uint64, error)

	// FetchNotificationCountFunc mocks the FetchNotificationCount method.
	FetchNotificationCountFunc func(ctx context.Context, organizationID string, userID string, read bool) (uint64, error)

	// MarkReadByNotificationsIDsFunc mocks the MarkReadByNotificationsIDs method.
	MarkReadByNotificationsIDsFunc func(ctx context.Context, organizationID string, userID string, ids []xid.ID) error

	// calls tracks calls to the methods.
	calls struct {
		// FetchManyNotifications holds details about calls to the FetchManyNotifications method.
		FetchManyNotifications []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrganizationID is the organizationID argument value.
			OrganizationID string
			// UserID is the userID argument value.
			UserID string
			// Qr is the qr argument value.
			Qr httpserver.Query
		}
		// FetchNotificationCount holds details about calls to the FetchNotificationCount method.
		FetchNotificationCount []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrganizationID is the organizationID argument value.
			OrganizationID string
			// UserID is the userID argument value.
			UserID string
			// Read is the read argument value.
			Read bool
		}
		// MarkReadByNotificationsIDs holds details about calls to the MarkReadByNotificationsIDs method.
		MarkReadByNotificationsIDs []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrganizationID is the organizationID argument value.
			OrganizationID string
			// UserID is the userID argument value.
			UserID string
			// Ids is the ids argument value.
			Ids []xid.ID
		}
	}
	lockFetchManyNotifications     sync.RWMutex
	lockFetchNotificationCount     sync.RWMutex
	lockMarkReadByNotificationsIDs sync.RWMutex
}

// FetchManyNotifications calls FetchManyNotificationsFunc.
func (mock *DBMock) FetchManyNotifications(ctx context.Context, organizationID string, userID string, qr httpserver.Query) ([]*notificationCore.Notification, uint64, error) {
	callInfo := struct {
		Ctx            context.Context
		OrganizationID string
		UserID         string
		Qr             httpserver.Query
	}{
		Ctx:            ctx,
		OrganizationID: organizationID,
		UserID:         userID,
		Qr:             qr,
	}
	mock.lockFetchManyNotifications.Lock()
	mock.calls.FetchManyNotifications = append(mock.calls.FetchManyNotifications, callInfo)
	mock.lockFetchManyNotifications.Unlock()
	if mock.FetchManyNotificationsFunc == nil {
		var (
			notificationsOut []*notificationCore.Notification
			vOut             uint64
			errOut           error
		)
		return notificationsOut, vOut, errOut
	}
	return mock.FetchManyNotificationsFunc(ctx, organizationID, userID, qr)
}

// FetchManyNotificationsCalls gets all the calls that were made to FetchManyNotifications.
// Check the length with:
//
//	len(mockedDB.FetchManyNotificationsCalls())
func (mock *DBMock) FetchManyNotificationsCalls() []struct {
	Ctx            context.Context
	OrganizationID string
	UserID         string
	Qr             httpserver.Query
} {
	var calls []struct {
		Ctx            context.Context
		OrganizationID string
		UserID         string
		Qr             httpserver.Query
	}
	mock.lockFetchManyNotifications.RLock()
	calls = mock.calls.FetchManyNotifications
	mock.lockFetchManyNotifications.RUnlock()
	return calls
}

// FetchNotificationCount calls FetchNotificationCountFunc.
func (mock *DBMock) FetchNotificationCount(ctx context.Context, organizationID string, userID string, read bool) (uint64, error) {
	callInfo := struct {
		Ctx            context.Context
		OrganizationID string
		UserID         string
		Read           bool
	}{
		Ctx:            ctx,
		OrganizationID: organizationID,
		UserID:         userID,
		Read:           read,
	}
	mock.lockFetchNotificationCount.Lock()
	mock.calls.FetchNotificationCount = append(mock.calls.FetchNotificationCount, callInfo)
	mock.lockFetchNotificationCount.Unlock()
	if mock.FetchNotificationCountFunc == nil {
		var (
			vOut   uint64
			errOut error
		)
		return vOut, errOut
	}
	return mock.FetchNotificationCountFunc(ctx, organizationID, userID, read)
}

// FetchNotificationCountCalls gets all the calls that were made to FetchNotificationCount.
// Check the length with:
//
//	len(mockedDB.FetchNotificationCountCalls())
func (mock *DBMock) FetchNotificationCountCalls() []struct {
	Ctx            context.Context
	OrganizationID string
	UserID         string
	Read           bool
} {
	var calls []struct {
		Ctx            context.Context
		OrganizationID string
		UserID         string
		Read           bool
	}
	mock.lockFetchNotificationCount.RLock()
	calls = mock.calls.FetchNotificationCount
	mock.lockFetchNotificationCount.RUnlock()
	return calls
}

// MarkReadByNotificationsIDs calls MarkReadByNotificationsIDsFunc.
func (mock *DBMock) MarkReadByNotificationsIDs(ctx context.Context, organizationID string, userID string, ids []xid.ID) error {
	callInfo := struct {
		Ctx            context.Context
		OrganizationID string
		UserID         string
		Ids            []xid.ID
	}{
		Ctx:            ctx,
		OrganizationID: organizationID,
		UserID:         userID,
		Ids:            ids,
	}
	mock.lockMarkReadByNotificationsIDs.Lock()
	mock.calls.MarkReadByNotificationsIDs = append(mock.calls.MarkReadByNotificationsIDs, callInfo)
	mock.lockMarkReadByNotificationsIDs.Unlock()
	if mock.MarkReadByNotificationsIDsFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.MarkReadByNotificationsIDsFunc(ctx, organizationID, userID, ids)
}

// MarkReadByNotificationsIDsCalls gets all the calls that were made to MarkReadByNotificationsIDs.
// Check the length with:
//
//	len(mockedDB.MarkReadByNotificationsIDsCalls())
func (mock *DBMock) MarkReadByNotificationsIDsCalls() []struct {
	Ctx            context.Context
	OrganizationID string
	UserID         string
	Ids            []xid.ID
} {
	var calls []struct {
		Ctx            context.Context
		OrganizationID string
		UserID         string
		Ids            []xid.ID
	}
	mock.lockMarkReadByNotificationsIDs.RLock()
	calls = mock.calls.MarkReadByNotificationsIDs
	mock.lockMarkReadByNotificationsIDs.RUnlock()
	return calls
}
