// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package assistant

import (
	"context"
	"sync"

	anthropic "github.com/anthropics/anthropic-sdk-go"
)

// Ensure, that SessionStoreMock does implement SessionStore.
// If this is not the case, regenerate this file with moq.
var _ SessionStore = &SessionStoreMock{}

// SessionStoreMock is a mock implementation of SessionStore.
//
//	func TestSomethingThatUsesSessionStore(t *testing.T) {
//
//		// make and configure a mocked SessionStore
//		mockedSessionStore := &SessionStoreMock{
//			DeleteFunc: func(ctx context.Context, key string) error {
//				panic("mock out the Delete method")
//			},
//			GetFunc: func(ctx context.Context, key string) (*[]anthropic.MessageParam, error) {
//				panic("mock out the Get method")
//			},
//			SetFunc: func(ctx context.Context, key string, value []anthropic.MessageParam) error {
//				panic("mock out the Set method")
//			},
//		}
//
//		// use mockedSessionStore in code that requires SessionStore
//		// and then make assertions.
//
//	}
type SessionStoreMock struct {
	// DeleteFunc mocks the Delete method.
	DeleteFunc func(ctx context.Context, key string) error

	// GetFunc mocks the Get method.
	GetFunc func(ctx context.Context, key string) (*[]anthropic.MessageParam, error)

	// SetFunc mocks the Set method.
	SetFunc func(ctx context.Context, key string, value []anthropic.MessageParam) error

	// calls tracks calls to the methods.
	calls struct {
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Key is the key argument value.
			Key string
		}
		// Get holds details about calls to the Get method.
		Get []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Key is the key argument value.
			Key string
		}
		// Set holds details about calls to the Set method.
		Set []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Key is the key argument value.
			Key string
			// Value is the value argument value.
			Value []anthropic.MessageParam
		}
	}
	lockDelete sync.RWMutex
	lockGet    sync.RWMutex
	lockSet    sync.RWMutex
}

// Delete calls DeleteFunc.
func (mock *SessionStoreMock) Delete(ctx context.Context, key string) error {
	callInfo := struct {
		Ctx context.Context
		Key string
	}{
		Ctx: ctx,
		Key: key,
	}
	mock.lockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	mock.lockDelete.Unlock()
	if mock.DeleteFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.DeleteFunc(ctx, key)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//
//	len(mockedSessionStore.DeleteCalls())
func (mock *SessionStoreMock) DeleteCalls() []struct {
	Ctx context.Context
	Key string
} {
	var calls []struct {
		Ctx context.Context
		Key string
	}
	mock.lockDelete.RLock()
	calls = mock.calls.Delete
	mock.lockDelete.RUnlock()
	return calls
}

// Get calls GetFunc.
func (mock *SessionStoreMock) Get(ctx context.Context, key string) (*[]anthropic.MessageParam, error) {
	callInfo := struct {
		Ctx context.Context
		Key string
	}{
		Ctx: ctx,
		Key: key,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	if mock.GetFunc == nil {
		var (
			messageParamsOut *[]anthropic.MessageParam
			errOut           error
		)
		return messageParamsOut, errOut
	}
	return mock.GetFunc(ctx, key)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//
//	len(mockedSessionStore.GetCalls())
func (mock *SessionStoreMock) GetCalls() []struct {
	Ctx context.Context
	Key string
} {
	var calls []struct {
		Ctx context.Context
		Key string
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}

// Set calls SetFunc.
func (mock *SessionStoreMock) Set(ctx context.Context, key string, value []anthropic.MessageParam) error {
	callInfo := struct {
		Ctx   context.Context
		Key   string
		Value []anthropic.MessageParam
	}{
		Ctx:   ctx,
		Key:   key,
		Value: value,
	}
	mock.lockSet.Lock()
	mock.calls.Set = append(mock.calls.Set, callInfo)
	mock.lockSet.Unlock()
	if mock.SetFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.SetFunc(ctx, key, value)
}

// SetCalls gets all the calls that were made to Set.
// Check the length with:
//
//	len(mockedSessionStore.SetCalls())
func (mock *SessionStoreMock) SetCalls() []struct {
	Ctx   context.Context
	Key   string
	Value []anthropic.MessageParam
} {
	var calls []struct {
		Ctx   context.Context
		Key   string
		Value []anthropic.MessageParam
	}
	mock.lockSet.RLock()
	calls = mock.calls.Set
	mock.lockSet.RUnlock()
	return calls
}
