// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package assistant

import (
	"context"
	"sync"
)

// Ensure, that PendingStoreMock does implement PendingStore.
// If this is not the case, regenerate this file with moq.
var _ PendingStore = &PendingStoreMock{}

// PendingStoreMock is a mock implementation of PendingStore.
//
//	func TestSomethingThatUsesPendingStore(t *testing.T) {
//
//		// make and configure a mocked PendingStore
//		mockedPendingStore := &PendingStoreMock{
//			DeleteFunc: func(ctx context.Context, key string) error {
//				panic("mock out the Delete method")
//			},
//			GetFunc: func(ctx context.Context, key string) (*pendingConfirm, error) {
//				panic("mock out the Get method")
//			},
//			SetFunc: func(ctx context.Context, key string, value pendingConfirm) error {
//				panic("mock out the Set method")
//			},
//		}
//
//		// use mockedPendingStore in code that requires PendingStore
//		// and then make assertions.
//
//	}
type PendingStoreMock struct {
	// DeleteFunc mocks the Delete method.
	DeleteFunc func(ctx context.Context, key string) error

	// GetFunc mocks the Get method.
	GetFunc func(ctx context.Context, key string) (*pendingConfirm, error)

	// SetFunc mocks the Set method.
	SetFunc func(ctx context.Context, key string, value pendingConfirm) error

	// calls tracks calls to the methods.
	calls struct {
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Key is the key argument value.
			Key string
		}
		// Get holds details about calls to the Get method.
		Get []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Key is the key argument value.
			Key string
		}
		// Set holds details about calls to the Set method.
		Set []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Key is the key argument value.
			Key string
			// Value is the value argument value.
			Value pendingConfirm
		}
	}
	lockDelete sync.RWMutex
	lockGet    sync.RWMutex
	lockSet    sync.RWMutex
}

// Delete calls DeleteFunc.
func (mock *PendingStoreMock) Delete(ctx context.Context, key string) error {
	callInfo := struct {
		Ctx context.Context
		Key string
	}{
		Ctx: ctx,
		Key: key,
	}
	mock.lockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	mock.lockDelete.Unlock()
	if mock.DeleteFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.DeleteFunc(ctx, key)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//
//	len(mockedPendingStore.DeleteCalls())
func (mock *PendingStoreMock) DeleteCalls() []struct {
	Ctx context.Context
	Key string
} {
	var calls []struct {
		Ctx context.Context
		Key string
	}
	mock.lockDelete.RLock()
	calls = mock.calls.Delete
	mock.lockDelete.RUnlock()
	return calls
}

// Get calls GetFunc.
func (mock *PendingStoreMock) Get(ctx context.Context, key string) (*pendingConfirm, error) {
	callInfo := struct {
		Ctx context.Context
		Key string
	}{
		Ctx: ctx,
		Key: key,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	if mock.GetFunc == nil {
		var (
			pendingConfirmMoqParamOut *pendingConfirm
			errOut                    error
		)
		return pendingConfirmMoqParamOut, errOut
	}
	return mock.GetFunc(ctx, key)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//
//	len(mockedPendingStore.GetCalls())
func (mock *PendingStoreMock) GetCalls() []struct {
	Ctx context.Context
	Key string
} {
	var calls []struct {
		Ctx context.Context
		Key string
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}

// Set calls SetFunc.
func (mock *PendingStoreMock) Set(ctx context.Context, key string, value pendingConfirm) error {
	callInfo := struct {
		Ctx   context.Context
		Key   string
		Value pendingConfirm
	}{
		Ctx:   ctx,
		Key:   key,
		Value: value,
	}
	mock.lockSet.Lock()
	mock.calls.Set = append(mock.calls.Set, callInfo)
	mock.lockSet.Unlock()
	if mock.SetFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.SetFunc(ctx, key, value)
}

// SetCalls gets all the calls that were made to Set.
// Check the length with:
//
//	len(mockedPendingStore.SetCalls())
func (mock *PendingStoreMock) SetCalls() []struct {
	Ctx   context.Context
	Key   string
	Value pendingConfirm
} {
	var calls []struct {
		Ctx   context.Context
		Key   string
		Value pendingConfirm
	}
	mock.lockSet.RLock()
	calls = mock.calls.Set
	mock.lockSet.RUnlock()
	return calls
}
