import type { KnipConfig } from "knip"
import { parse } from "vue/compiler-sfc"

// knip's nuxt plugin only knows the nuxt 3 layout, so the nuxt 4 app/
// conventions (and everything else referenced by convention rather than by
// import) are declared as entries here explicitly.
const config: KnipConfig = {
	// the vendored PromQL grammar fork is re-synced from upstream and must
	// not be reported against (see packages/README.lezer-promql.md)
	ignoreWorkspaces: ["packages/lezer-promql"],

	// project policy: the hoisted node_modules layout (required by
	// electron-forge) makes transitive packages importable, and relying on
	// that is deliberate — package.json declares top-level intent only, so
	// imports of undeclared packages are not an issue here
	rules: {
		unlisted: "off",
	},

	compilers: {
		// the SFC compiler recommended by knip's docs, extended to follow
		// tailwind v4 @reference/@plugin directives in <style> blocks
		vue: (text: string, filename: string) => {
			const { descriptor } = parse(text, { filename, sourceMap: false })

			const scripts = [descriptor.script, descriptor.scriptSetup]
				.filter((block) => block !== null)
				.map((block) => (block.src ? `import '${block.src}'` : block.content))

			const styles = descriptor.styles.flatMap((block) => [
				...[...block.content.matchAll(/(?<=@)import[^;]+/g)].map(String),
				...[
					...block.content.matchAll(/@(?:plugin|reference)\s+"([^"]+)"/g),
				].map((m) => `import "${m[1]}"`),
			])

			return [...scripts, ...styles].join("\n")
		},
		// follows @import chains and tailwind v4 @plugin directives in the
		// css entries nuxt loads (main.css)
		css: (text: string) =>
			[
				...[...text.matchAll(/(?<=@)import[^;]+/g)].map(String),
				...[...text.matchAll(/@plugin\s+"([^"]+)"/g)].map(
					(m) => `import "${m[1]}"`,
				),
			].join("\n"),
	},

	workspaces: {
		".": {
			entry: [
				// nuxt 4 app/ conventions: loaded by the framework, never
				// imported. Components are included because templates
				// reference them by tag through nuxt auto-registration,
				// which knip cannot resolve — a component no longer used by
				// any template is therefore NOT reported by knip.
				"app/pages/**/*.vue",
				"app/middleware/**/*.ts",
				"app/plugins/**/*.ts",
				"app/components/**/*.vue",
				// the whole auto-import surface: unimport makes everything
				// in these directories reachable without import statements,
				// so knip cannot trace their usage. The tradeoff: unused
				// exports inside these directories are NOT reported.
				"app/composables/**/*.ts",
				"app/stores/**/*.ts",
				"app/utils/**/*.ts",
				// module conventions loaded by name
				"colada.options.ts",
				// electron main/preload world, built by forge + vite
				"electron/main.ts",
				"electron/preload.ts",
				"forge.config.ts",
				"vite.electron.config.ts",
			],

			// auto-imported by unimport (no import statements at use
			// sites), so the files must count as project members even when
			// nothing imports them
			project: ["app/**/*.{ts,vue,css}", "electron/**/*.ts", "*.ts"],

			ignore: [
				// vendored shadcn-vue components: installed ahead of use and
				// regenerated by the CLI; unused spares and barrel exports
				// are expected there
				"app/components/shadcn/**",
			],

			ignoreDependencies: [
				// icon collections resolved by name at build time by
				// @nuxt/icon
				"@iconify-json/.*",
				// never imported directly — declared as the umbrella that
				// provides the individually-imported @tiptap/extension-*
				// packages (see rules.unlisted above)
				"@tiptap/starter-kit",
				// loaded by electron-forge at package time via the string
				// names in forge.config.ts
				"@electron-forge/maker-deb",
				"@electron-forge/maker-rpm",
				"@electron-forge/maker-squirrel",
				"@electron-forge/maker-zip",
				"@electron-forge/plugin-auto-unpack-natives",
				"@electron-forge/plugin-vite",
				// spawned by `nuxt typecheck` (check-types), not imported
				"vue-tsc",
			],
		},
	},
}

export default config
