import { fileURLToPath } from "node:url"
import { defineVitestProject } from "@nuxt/test-utils/config"
import vue from "@vitejs/plugin-vue"
import Unimport from "unimport/unplugin"
import {
	configDefaults,
	defineConfig,
	type TestUserConfig,
} from "vitest/config"

// every test runs concurrently, and no mock, stubbed global, or env
// stub may leak between tests. Spread into every project explicitly
// because vitest does not inherit all root test options into projects.
const sharedTestOptions = {
	sequence: {
		concurrent: true,
	},
	restoreMocks: true,
	unstubGlobals: true,
	unstubEnvs: true,
} satisfies TestUserConfig

export default defineConfig({
	test: {
		...sharedTestOptions,

		coverage: {
			provider: "v8" as const,
			// terminal summary only — no coverage/ artifact directory for
			// git, prettier, and eslint to trip over. Pass
			// --coverage.reporter=html ad hoc for the browsable report.
			reporter: ["text"],
			include: ["app/**/*.{ts,vue}", "electron/**/*.ts"],
			exclude: [
				// vendored, regenerated by the shadcn CLI
				"app/components/shadcn/**",
				"**/*.d.ts",
			],
			// set from the measured baseline and ratcheted up as suites
			// grow — never lowered. 100% is not the target: genuinely
			// untestable branches stay visible in the report, marked with
			// NOCOV comments in place
			thresholds: {
				statements: 10,
				branches: 3,
				functions: 4,
				lines: 9,
			},
		},

		// the suffix encodes the environment: .test.ts runs in plain node,
		// .nuxt.test.ts inside the nuxt runtime, and .browser.test.ts is
		// reserved for a future browser-mode project
		projects: [
			{
				// import graphs of app modules routinely pass through .vue
				// files (e.g. tiptap extensions registering node views), so
				// the node project must be able to compile them even though
				// it never renders one. App code also references app/utils
				// helpers through nuxt auto-imports — unimport resolves the
				// same real modules here without booting a nuxt runtime.
				plugins: [
					vue(),
					Unimport.vite({
						dirs: [fileURLToPath(new URL("./app/utils", import.meta.url))],
						dts: false,
					}),
				],
				define: {
					// build-time constants injected by vite.electron.config.ts
					// (electron) and nuxt.config.ts (app); tests get inert
					// stand-ins
					__API_BASE_URL__: JSON.stringify("http://test.local/core"),
					__APP_BASE_URL__: JSON.stringify("http://test.local"),
					__DESKTOP_BUILD__: "false",
				},
				resolve: {
					alias: {
						"~": fileURLToPath(new URL("./app", import.meta.url)),
						"@": fileURLToPath(new URL("./app", import.meta.url)),
					},
				},
				test: {
					...sharedTestOptions,
					name: "node",
					environment: "node",
					include: ["app/**/*.test.ts", "electron/**/*.test.ts"],
					exclude: [
						...configDefaults.exclude,
						"**/*.nuxt.test.ts",
						"**/*.browser.test.ts",
					],
				},
			},
			await defineVitestProject({
				test: {
					...sharedTestOptions,
					name: "nuxt",
					environment: "nuxt",
					// @nuxt/test-utils boots the whole nuxt runtime in a
					// beforeAll hook before the first .nuxt.test.ts file; on
					// cold CI runners that routinely exceeds the 10s default
					// and fails the suite before any test runs
					hookTimeout: 60_000,
					include: ["app/**/*.nuxt.test.ts"],
					environmentOptions: {
						nuxt: {
							overrides: {
								// deterministic base for anything url-building;
								// mocking useRuntimeConfig instead would starve
								// nuxt's own bootstrap, which consumes it too
								runtimeConfig: {
									public: {
										appBaseURL: "http://test.local",
									},
								},
							},
						},
					},
				},
			}),
		],
	},
})
