import { fileURLToPath } from "node:url"
import type { ModuleOptions as NuxtIconOptions } from "@nuxt/icon"
import { defineVitestProject } from "@nuxt/test-utils/config"
import { playwright } from "@vitest/browser-playwright"
import vue from "@vitejs/plugin-vue"
import type { NuxtConfig } from "nuxt/schema"
import Unimport from "unimport/unplugin"
import {
	configDefaults,
	defineConfig,
	type TestUserConfig,
} from "vitest/config"

// every test runs concurrently, and no mock, stubbed global, or env
// stub may leak between tests. Spread into every project explicitly
// because vitest does not inherit all root test options into projects.
const sharedTestOptions = {
	sequence: {
		concurrent: true,
	},
	restoreMocks: true,
	unstubGlobals: true,
	unstubEnvs: true,
	// @nuxt/test-utils mounts the test app inside <Suspense>, so vue's dev
	// build prints its experimental-feature notice once per nuxt test file
	// — pure noise in test output
	onConsoleLog(log: string) {
		if (log.includes("<Suspense> is an experimental feature")) {
			return false
		}

		// the nuxt overrides below point @nuxt/icon at no provider, so
		// every icon that is not already in the client bundle fails its
		// load and warns once per render. That is the intended trade for
		// keeping the iconify api off the network, not a test failure
		if (log.startsWith("[Icon] failed to load icon")) {
			return false
		}

		// temporary suppression. reka-ui warns once per dialog mount that
		// no DialogDescription answers the aria-describedby it points at,
		// and every modal in the app has that gap, so no individual suite
		// can act on it. Delete this branch once the dialogs describe
		// themselves
		if (log.startsWith("Warning: Missing `Description`")) {
			return false
		}
	},
} satisfies TestUserConfig

// import graphs of app modules routinely pass through .vue files (e.g.
// tiptap extensions registering node views), so the node and browser
// projects must be able to compile them even though they never render
// one. App code also references app/utils helpers and composable enums
// (e.g. HostOsType) through nuxt auto-imports — unimport resolves the
// same real modules here without booting a nuxt runtime. A factory
// because vite plugin instances cannot be shared between projects.
function appPlugins() {
	return [
		vue(),
		Unimport.vite({
			dirs: [
				fileURLToPath(new URL("./app/utils", import.meta.url)),
				fileURLToPath(new URL("./app/composables", import.meta.url)),
			],
			dts: false,
		}),
	]
}

// nuxt config the test app is booted with. A module's options only become
// known keys on NuxtConfig through the declarations nuxt generates into
// .nuxt, and only the nuxt.config tsconfig project loads those — this file
// sits outside it, so @nuxt/icon's key is spelled out here.
const nuxtOverrides: NuxtConfig & {
	icon: { provider: NuxtIconOptions["provider"] }
} = {
	// @nuxt/icon otherwise resolves any icon missing from the client bundle
	// over the public iconify api — real network io on every component mount
	// that renders one. "none" stubs its fetch out. Setting it through
	// appConfig instead does not work: the module overwrites that key with
	// its own resolved options.
	icon: {
		provider: "none",
	},
	// deterministic bases for anything url-building; mocking
	// useRuntimeConfig instead would starve nuxt's own bootstrap, which
	// consumes it too. The auth-realtime url must be absolute or the
	// 02.auth plugin fails app init on every nuxt test file (better-auth
	// rejects relative bases)
	runtimeConfig: {
		public: {
			appBaseURL: "http://test.local",
			authRealtimeAPIBaseHttpURL: "http://test.local/auth-realtime",
		},
	},
}

// vendored shadcn-vue components are regenerated by the shadcn CLI, so
// they are out of scope for this suite: no test file under here is
// collected by any project, and nothing here counts towards coverage
const shadcnExclude = "app/components/shadcn/**"

// build-time constants injected by vite.electron.config.ts (electron)
// and nuxt.config.ts (app); tests get inert stand-ins
const appDefine = {
	__API_BASE_URL__: JSON.stringify("http://test.local/core"),
	__APP_BASE_URL__: JSON.stringify("http://test.local"),
	__DESKTOP_BUILD__: "false",
}

const appAlias = {
	"~": fileURLToPath(new URL("./app", import.meta.url)),
	"@": fileURLToPath(new URL("./app", import.meta.url)),
}

export default defineConfig({
	test: {
		...sharedTestOptions,

		coverage: {
			provider: "v8" as const,
			// terminal summary only — no coverage/ artifact directory for
			// git, prettier, and eslint to trip over. Pass
			// --coverage.reporter=html ad hoc for the browsable report.
			reporter: ["text"],
			include: ["app/**/*.{ts,vue}", "electron/**/*.ts"],
			exclude: [
				shadcnExclude,
				"**/*.d.ts",
				// test-only helper modules colocated with the suites they
				// serve — test code, not app code
				"app/**/test-helpers.ts",
				"app/**/test-helpers/**",
			],
			// set from the measured baseline and ratcheted up as suites
			// grow. 100% is not the target: genuinely untestable branches
			// stay visible in the report, marked with NOCOV comments in place
			thresholds: {
				statements: 83.9,
				branches: 74,
				functions: 86.9,
				lines: 84.1,
			},
		},

		// the suffix encodes the environment: .test.ts runs in plain node,
		// .nuxt.test.ts inside the nuxt runtime, and .browser.test.ts in a
		// real headless chromium via playwright
		projects: [
			{
				plugins: appPlugins(),
				define: appDefine,
				resolve: {
					alias: appAlias,
				},
				test: {
					...sharedTestOptions,
					name: "node",
					environment: "node",
					include: ["app/**/*.test.ts", "electron/**/*.test.ts"],
					exclude: [
						...configDefaults.exclude,
						shadcnExclude,
						"**/*.nuxt.test.ts",
						"**/*.browser.test.ts",
					],
				},
			},
			{
				plugins: appPlugins(),
				define: appDefine,
				resolve: {
					alias: appAlias,
				},
				optimizeDeps: {
					// pre-bundle everything the browser tests pull in, so vite
					// never discovers a dependency mid-run and reloads the page
					// (which vitest warns makes runs flaky)
					include: [
						"vue",
						"slugify",
						"dompurify",
						"@tiptap/core",
						"@tiptap/pm/model",
						"@tiptap/pm/state",
						"@tiptap/extension-list",
						"safe-stable-stringify",
						"fast-deep-equal",
						"@tiptap/extension-document",
						"@tiptap/extension-paragraph",
						"@tiptap/extension-text",
						"@tiptap/y-tiptap",
						"@floating-ui/dom",
						"yjs",
					],
				},
				test: {
					...sharedTestOptions,
					name: "browser",
					include: ["app/**/*.browser.test.ts"],
					exclude: [...configDefaults.exclude, shadcnExclude],
					browser: {
						enabled: true,
						provider: playwright(),
						headless: true,
						// failure screenshots would pollute the source tree
						// with __screenshots__ directories
						screenshotFailures: false,
						instances: [{ browser: "chromium" }],
					},
				},
			},
			await defineVitestProject({
				test: {
					...sharedTestOptions,
					name: "nuxt",
					environment: "nuxt",
					// @nuxt/test-utils boots the whole nuxt runtime in a
					// beforeAll hook before the first .nuxt.test.ts file; on
					// cold CI runners that routinely exceeds the 10s default
					// and fails the suite before any test runs
					hookTimeout: 60_000,
					// component tests drive real request chains through the
					// test-time h3 app; under the full suite's parallelism the
					// slowest of them outgrows the 5s default
					testTimeout: 20_000,
					include: ["app/**/*.nuxt.test.ts"],
					exclude: [...configDefaults.exclude, shadcnExclude],
					setupFiles: ["./vitest.nuxt-setup.ts"],
					environmentOptions: {
						nuxt: {
							overrides: nuxtOverrides,
						},
					},
				},
			}),
		],
	},
})
