import { fileURLToPath } from "node:url"
import { defineVitestProject } from "@nuxt/test-utils/config"
import { playwright } from "@vitest/browser-playwright"
import vue from "@vitejs/plugin-vue"
import Unimport from "unimport/unplugin"
import {
	configDefaults,
	defineConfig,
	type TestUserConfig,
} from "vitest/config"

// every test runs concurrently, and no mock, stubbed global, or env
// stub may leak between tests. Spread into every project explicitly
// because vitest does not inherit all root test options into projects.
const sharedTestOptions = {
	sequence: {
		concurrent: true,
	},
	restoreMocks: true,
	unstubGlobals: true,
	unstubEnvs: true,
} satisfies TestUserConfig

// import graphs of app modules routinely pass through .vue files (e.g.
// tiptap extensions registering node views), so the node and browser
// projects must be able to compile them even though they never render
// one. App code also references app/utils helpers and composable enums
// (e.g. HostOsType) through nuxt auto-imports — unimport resolves the
// same real modules here without booting a nuxt runtime. A factory
// because vite plugin instances cannot be shared between projects.
function appPlugins() {
	return [
		vue(),
		Unimport.vite({
			dirs: [
				fileURLToPath(new URL("./app/utils", import.meta.url)),
				fileURLToPath(new URL("./app/composables", import.meta.url)),
			],
			dts: false,
		}),
	]
}

// build-time constants injected by vite.electron.config.ts (electron)
// and nuxt.config.ts (app); tests get inert stand-ins
const appDefine = {
	__API_BASE_URL__: JSON.stringify("http://test.local/core"),
	__APP_BASE_URL__: JSON.stringify("http://test.local"),
	__DESKTOP_BUILD__: "false",
}

const appAlias = {
	"~": fileURLToPath(new URL("./app", import.meta.url)),
	"@": fileURLToPath(new URL("./app", import.meta.url)),
	// same fork alias as nuxt.config.ts — without it these projects
	// would resolve the upstream package instead of the vendored grammar
	"@prometheus-io/lezer-promql": fileURLToPath(
		new URL("./packages/lezer-promql/dist/index.es.js", import.meta.url),
	),
}

export default defineConfig({
	test: {
		...sharedTestOptions,

		coverage: {
			provider: "v8" as const,
			// terminal summary only — no coverage/ artifact directory for
			// git, prettier, and eslint to trip over. Pass
			// --coverage.reporter=html ad hoc for the browsable report.
			reporter: ["text"],
			include: ["app/**/*.{ts,vue}", "electron/**/*.ts"],
			exclude: [
				// vendored, regenerated by the shadcn CLI
				"app/components/shadcn/**",
				"**/*.d.ts",
			],
			// set from the measured baseline and ratcheted up as suites
			// grow — never lowered. 100% is not the target: genuinely
			// untestable branches stay visible in the report, marked with
			// NOCOV comments in place
			thresholds: {
				statements: 19,
				branches: 11,
				functions: 14,
				lines: 19,
			},
		},

		// the suffix encodes the environment: .test.ts runs in plain node,
		// .nuxt.test.ts inside the nuxt runtime, and .browser.test.ts in a
		// real headless chromium via playwright
		projects: [
			{
				plugins: appPlugins(),
				define: appDefine,
				resolve: {
					alias: appAlias,
				},
				test: {
					...sharedTestOptions,
					name: "node",
					environment: "node",
					include: ["app/**/*.test.ts", "electron/**/*.test.ts"],
					exclude: [
						...configDefaults.exclude,
						"**/*.nuxt.test.ts",
						"**/*.browser.test.ts",
					],
				},
			},
			{
				plugins: appPlugins(),
				define: appDefine,
				resolve: {
					alias: appAlias,
				},
				optimizeDeps: {
					// pre-bundle everything the browser tests pull in, so vite
					// never discovers a dependency mid-run and reloads the page
					// (which vitest warns makes runs flaky)
					include: [
						"vue",
						"slugify",
						"dompurify",
						"@tiptap/core",
						"@tiptap/pm/model",
						"@tiptap/pm/state",
						"@tiptap/extension-list",
					],
				},
				test: {
					...sharedTestOptions,
					name: "browser",
					include: ["app/**/*.browser.test.ts"],
					browser: {
						enabled: true,
						provider: playwright(),
						headless: true,
						// failure screenshots would pollute the source tree
						// with __screenshots__ directories
						screenshotFailures: false,
						instances: [{ browser: "chromium" }],
					},
				},
			},
			await defineVitestProject({
				test: {
					...sharedTestOptions,
					name: "nuxt",
					environment: "nuxt",
					// @nuxt/test-utils boots the whole nuxt runtime in a
					// beforeAll hook before the first .nuxt.test.ts file; on
					// cold CI runners that routinely exceeds the 10s default
					// and fails the suite before any test runs
					hookTimeout: 60_000,
					include: ["app/**/*.nuxt.test.ts"],
					environmentOptions: {
						nuxt: {
							overrides: {
								// deterministic bases for anything url-building;
								// mocking useRuntimeConfig instead would starve
								// nuxt's own bootstrap, which consumes it too.
								// The auth-realtime url must be absolute or the
								// 02.auth plugin fails app init on every nuxt
								// test file (better-auth rejects relative bases)
								runtimeConfig: {
									public: {
										appBaseURL: "http://test.local",
										authRealtimeAPIBaseHttpURL:
											"http://test.local/auth-realtime",
									},
								},
							},
						},
					},
				},
			}),
		],
	},
})
